### ISSUE TITLE
Mobile publish flow

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1001]
Pragmatic design of new publish form in #928 was pretty much desktop-centric but we mostly made use of existing components and patterns so there shouldn't be any major visual design problems.

on mobile:

- bonus: publish on mobile
  - requires a WalletConnect → MetaMask or WalletConnect → Ledger Live wallet connection on mobile
  - in `v4` there also was some wallet connect update, but we might still run into #592

**Comment by EnzoVezzaro** [comment]
Blocked: Web3 mobile connection not working

Will be fixed on [Restore order #1068](https://github.com/oceanprotocol/market/pull/1068)

**Comment by mihaisc** [comment]
Not blocked, the first 3 steps are doable without a wallet connection.

**Comment by EnzoVezzaro** [comment]
Splitting this card.
