### ISSUE TITLE
Decimals with leading 0 can't be typed in Trade

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#1003]
**Describe the bug**
 I want to buy 1.0 datatokens for use later. In trying to do this, encountered two issues:
- I can't specify a "minimum datatokens to receive" in TRADE
- I can't specify decimals in amounts of OCEAN or datatoken, which would have been a workaround
- I did find a workaround, by fiddling with number of OCEAN. But it shouldn't be so hard

**To Reproduce**
Step 1. Go to https://market.oceanprotocol.com/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38, and connect wallet. See image below for what you see.

Step 2. I want to buy 1.0 datatokens for use later. If I go to "USE" button, it's for immediate usage, but I don't want to use the datatoken immediately. So I go to "TRADE" button. I can trade OCEAN for a datatoken (eg QUICRA-0). But it only gives me a "maximum to receive", not a "minimum to receive". For my use case, I want a "minimum to receive" of 1.0 datatokens.  (I know that this is possible in Balancer pools, via `function swapExactAmountOut` where `tokenAmountOut` gets set to 1.0 datatokens. I guess this functionality wasn't exposed to the market yet.)

Step 2. I specified the field "maximum to receive" of 1 QUICRA-0, it tells me that "Minimum received" is 0.95. OK, that's close. So I try to change it from "1" to "1.05", but it auto-changes it back to 1. It won't let me enter any decimals for the number of datatokens. That's frustrating; it seems like a bug to me.

Step 3. I thought maybe I can tweak the number of OCEAN. So go into the OCEAN field above, and change it from 212.24 to other numbers, fiddling until I arrive at 224.1 OCEAN. OK, that works, it doesn't kick out the number of decimals there. It gives me about 1.05 QUICRA. So this is the workaround for now. But that only works for datasets that are relatively expensive 

**Expected behavior**
- [ ] I should be able to specify decimal values in the field for the # datatokens that I want. This should be a quick win, since it's already supported for # OCEAN.
- [ ] I should be able to specify a _minimum_ number of datatokens to receive, where under the hood it uses `swapExactAmountOut`.  This will take a bit more UI work to do a good job on.

Wrt priorities, given V4 I see that this can happen after V4 is shipped. 

![screenshot](https://user-images.githubusercontent.com/5305452/149813161-3472b84a-578e-48bf-8ee5-baceacb5bd25.png)

**Comment by kremalicious** [comment]
> I should be able to specify decimal values in the field for the # datatokens that I want

totally agree on that but with fractions you are still able to get 1 datatoken so I'll just label this here as enhancement

**Comment by trentmc** [comment]
> you are still able to get 1 datatoken by tweaking the OCEAN input so I'll just label this here as enhancement

I could see how it's considered a bug, or a feature.

Bug view: people will try to enter a decimal in the datatoken side, and find that they can't, and see it as a bug, since you should be able to.

Enhancement view: there's a workaround.

**Comment by mihaisc** [comment]
I'm not sure what the problem is
![Animation](https://user-images.githubusercontent.com/26000280/151956730-3178265c-f5f7-4a0f-91d8-fc92218c7724.gif)
.

**Comment by kremalicious** [comment]
ok, so the actual issue is that decimals with a `0` after the dot can't be typed. So something like `1.05` doesn't work although it should. There is some auto formatting going on in the input fields where `1.0` gets transformed into `1`

**Comment by trentmc** [comment]
> I'm not sure what the problem is
If you enter 1.0 datatokens, after the fee the result is 0.95 datatokens

> something like 1.05 doesn't work although it should. 
correct

The description at the top of this issue elaborates.
