### ISSUE TITLE
Pool creator/publisher vs. NFT owner

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1010]
Just some double-checking for the pool tab data as I implement certain logic in #1009 which should be discussed. 

In v3 we made some assumptions to get the _Pool Creator Statistics_ populated, main one being that the publisher is assumed to be the pool creator. This was fine as long as the `owner` in the DDO was not changed, given our `transferOwnership()` in ocean.js never really worked, we can assume this rarely happened.

In v4 many things in UI switch from reacting to publisher to the NFT owner. And transferring a NFT is way easier. So we can't assume anymore the NFT owner is also the pool creator.

Current v4 implementation reacts to the NFT owner, and based on that populates _Pool Creator Statistics_.

Question is if we're fine with that and what's more valuable to know for users in this context, as we could also switch to base _Pool Creator Statistics_ on the actual pool creator which we would get from the initial setup event.

Along the same lines we are not fully transparent when using _Publisher_ in UI and base it on the NFT owner as the publisher and NFT owner can now more likely be different accounts.

**Comment by mihaisc** [comment]
Valid points. 
In the ui i suggest to replace publisher with owner. Maybe have another field somewhere at the end with publisher as well , for historical data
Regarding the pool , if owner != pool creator show both , easy fix

**Comment by kremalicious** [comment]
As for owner/publisher line, might be worth displaying both in case they are different. So always check NFT owner against actual publisher, and if different output bot like "Owned by 0xxx, published by 0xxx"
