### ISSUE TITLE
Show proper errors in submit step of form

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1025]
![image](https://user-images.githubusercontent.com/26000280/151020984-1386b045-e41c-4949-ad90-bbcec5974133.png)

We need a proper error message, not what we currently have.

**Comment by kremalicious** [comment]
now that we have errors shown suddenly they are too much 😀 I think we have to do some string manipulation here as that red block shown is the actual `error.message`

**Comment by mihaisc** [comment]
I'm not saying that it's a problem with the font/color or whatever but with the fact that we are just dumping the error. It means nothing for the common user, and we need some text wrapping

**Comment by EnzoVezzaro** [comment]
Guys, any of you have any idea how to replicate this issue? I can't figure out if this has been fixed.

**Comment by mihaisc** [comment]
It was not fixed, you can just go in the publish form and change some params to mess it up, then you will get an error

**Comment by EnzoVezzaro** [comment]
found it. If shows up when you reject the first transaction, but accept the second one.

**Comment by EnzoVezzaro** [comment]
now, it gets weirder. I don't have 2 transactions anymore. On the "Create Tokens & Pricing" step at the end of publish, it used to make 2 transactions, now makes only one transaction. is that ok @mihaisc ?
