### ISSUE TITLE
add liquidity: calculate minPoolAmountOut, calculate max

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1027]
Following up on #1017, calculating `minPoolAmountOut` passed to `joinswapExternAmountIn()` and calculating what we called "Max" before. For `minPoolAmountOut` fees should be taken in consideration as well

See `/AssetActions/Pool/Add/index.tsx`

**Comment by mihaisc** [comment]
Will be handled in https://github.com/oceanprotocol/ocean.js/pull/1306
