### ISSUE TITLE
Fetch own liquidity from graph in pool tab

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1037]
Currently in the pool tab your liquidity is calculated based on values from the price object.  These will be removed from there. 
``` 
  ocean?: number
  oceanSymbol?: string
  datatoken?: number
  datatokenSymbol?: string
```
In the big subgraph query that was added to fetch all the info we can also include data on own liquidity.

Reasons ;
- cleanup
- more efficient subgraph queries 
- stop mixing data with different concerns in same objects.

**Comment by kremalicious** [comment]
Trying that, but not sure this is possible with current subgraph. I would expect somewhere in this query under `poolDataUser.shares` to get only the user related values but seems not possible, always gives me whole pool info.

Isolated in [this query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=PoolData&query=query%20PoolData(%24pool%3A%20ID!%2C%20%24poolAsString%3A%20String!%2C%20%24owner%3A%20String!%2C%20%24user%3A%20String)%20%7B%0A%20%20poolDataUser%3A%20pool(id%3A%20%24pool)%20%7B%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%24user%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20%20%20baseTokenLiquidity%0A%20%20%20%20%20%20%20%20datatokenLiquidity%0A%20%20%20%20%20%20%20%20totalShares%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20user%20%7B%0A%20%20%20%20%20%20%20%20sharesOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20shares%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20tokensOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20supply%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20tokenBalancesOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20token%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22pool%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22poolAsString%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22user%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%2C%0A%20%20%22owner%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%0A%7D)

**Comment by mihaisc** [comment]
That is not possible, even in the past (v3) we were fetching the total liqudity and doing the math . `poolDataUser.shares.pool` is redundant , pool is already in your main query. So a quick translation the old `price.ocean` is `poolDataUser.baseTokenLiquidity` and `price.datatoken` is `poolDataUser.datatokenLiquidity` the rest of the math can stay as it is

**Comment by kremalicious** [comment]
yup, figured that and I think I made this work already, just need to double check the new numbers I get.

**Comment by mihaisc** [comment]
Also there is an issue in the [query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=PoolData&query=query%20PoolData(%24pool%3A%20ID!%2C%20%24poolAsString%3A%20String!%2C%20%24owner%3A%20String!%2C%20%24user%3A%20String)%20%7B%0A%20%20poolDataUser%3A%20pool(id%3A%20%24pool)%20%7B%0A%20%20%20%20baseTokenLiquidity%0A%20%20%20%20datatokenLiquidity%0A%20%20%20%20shares(where%3A%20%7Buser%3A%20%24user%7D)%20%7B%0A%20%20%20%20%20%20shares%0A%20%20%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20%20%20baseTokenLiquidity%0A%20%20%20%20%20%20%20%20datatokenLiquidity%0A%20%20%20%20%20%20%20%20totalShares%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20user%20%7B%0A%20%20%20%20%20%20%20%20sharesOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20shares%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20tokensOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20supply%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20tokenBalancesOwned%20%7B%0A%20%20%20%20%20%20%20%20%20%20token%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22pool%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22poolAsString%22%3A%20%220x871fa6f63b88c956977487090e3d7b79e5d58636%22%2C%0A%20%20%22user%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%2C%0A%20%20%22owner%22%3A%20%220x903322c7e45a60d7c8c3ea236c5bea9af86310c7%22%0A%7D)  The most nested sharesOwned doesn't make sense here, it will display all the shared the user has (i added pool ther so it's clearer)
