### ISSUE TITLE
Restore profile header

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1039]
It refers to this 
![image](https://user-images.githubusercontent.com/26000280/151957704-8642c123-bca0-4d07-84cc-6cee9d4b3777.png)

**Comment by claudiaHash** [comment]
Seems like bseides `Sales` metric header stats values are correct. I'll come back on this once we have #970 restored.
![Screenshot from 2022-02-10 14-28-21](https://user-images.githubusercontent.com/49017601/153410037-a1ad34e0-e2ac-4a3b-933e-0063ac6c7036.png)
