### ISSUE TITLE
Errors on Items with Compute access type

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1048]
**Describe the bug**
On all items with `Compute` access type, I get the following errors:

1. Query `const computeDatasets = await queryMetadata(query, cancelToken)` fails (see screenshot)
2. "Your Compute Jobs" dropdown breaks

**To Reproduce**

Steps to reproduce the behavior (First Issue):
1. Go to Publish
2. Create a publication with `Compute` access type
3. Go to the item's page

Steps to reproduce the behavior (Second Issue):
1. Go to a Computed Item
2. Go to the "Your Compute Jobs" dropdown
3. Click "Show"
4. See how it get stuck on loading 

**Expected behavior**

First Issue:
I expect to receive all the information from Acquarius or having a fallback in case there's not `computeDatasets.totalResults`.

Second Issue: 
I expect to receive the results from the query or having a fallback for it.

**Screenshots**

First Issue:
<img width="2560" alt="Screenshot 2022-02-01 at 09 35 53" src="https://user-images.githubusercontent.com/13741335/151971513-bb400851-77ce-45e9-ac81-831b0fe07783.png">

Second Issue:
<img width="2560" alt="Screenshot 2022-02-01 at 09 37 32" src="https://user-images.githubusercontent.com/13741335/151972549-027dfcd4-11da-4bc5-b434-ec942dc4ba70.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser: Brave, Chrome

**Comment by mihaisc** [comment]
This is normal, compute is not restored yet, https://github.com/oceanprotocol/market/issues/976
