### ISSUE TITLE
Buy button not working as expected 

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1049]
**Describe the bug**
On items with Download access type, I get the following error:

1. `Buy for X` button not being triggered

**To Reproduce**

First Issue:
1. Go to Published item (Download access type)
2. Click on `Buy for X`

**Expected behavior**

First Issue:
- I expect the action to be triggered in order to buy the dataset or having a clear error why I'm not able to. 

**Screenshots**

First Issue: 
File: `src/components/Asset/AssetActions/index.tsx`
This seems to be caused by the `datatokenInstance.balance` function in line 101. 

![dtbalance](https://user-images.githubusercontent.com/13741335/151977491-461661ca-61e4-478e-aa70-005f7cc16c32.png)

File: `src/components/Asset/AssetActions/Consume.tsx `
The action stops in line 153 

![dtbalance-consume](https://user-images.githubusercontent.com/13741335/151977594-eb38a486-3d3c-4bd4-996d-e9e31a09a726.png)

Desktop (please complete the following information):

OS: MacOS 12.0.1
Browser: Brave, Chrome

**Comment by mihaisc** [comment]
This was not restored yet, is handled in https://github.com/oceanprotocol/market/issues/970
