### ISSUE TITLE
Errors on Liquidity Functionality

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1050]
**Describe the bug**
On all items with Download access type, I get the following errors:

1. Sometimes the `add liquidity` operation doesn't work as expected. Although the operation goes through, the UI doesn't show the `success` animation, which gives me the impression that nothing happened. (see video)
2. `Your Pool Transactions` dropdown is not displaying all the liquidity transactions. This might be related to the issue n.1 as the missing transactions are actually those. 
3. On submit, we should block some operations like changing the value on the input
4. After submit, If you change the value on the input field, the button goes back to “approved X ocean” (see screen)
5. Removing liquidity fails without trowing an error. Also you can change the slider while the operation is ongoing. I think it should be blocked.

**Screenshots**

Issue N. 1:

https://user-images.githubusercontent.com/13741335/151983177-4edf6a05-3238-46ba-8b3c-15a1168e50b0.mp4

Issue N.2: 
none

Issue N.3: 
none

Issue N.4:

<img width="2558" alt="Screenshot 2022-02-01 at 14 58 19" src="https://user-images.githubusercontent.com/13741335/151983385-095cf2d5-e049-4c6c-8d04-0892ff98ff5b.png">

Issue N.5:

<img width="2560" alt="Screenshot 2022-02-01 at 14 40 55" src="https://user-images.githubusercontent.com/13741335/151983467-2aca8a8b-5786-4d1d-986c-f6567e68ee63.png">

Desktop (please complete the following information):

OS: MacOS 12.0.1
Browser: Brave, Chrome

**Comment by kremalicious** [comment]
> Sometimes the add liquidity operation doesn't work as expected. Although the operation goes through, the UI doesn't show the success animation, which gives me the impression that nothing happened.

Does the confusion come from the fact that we don't show a success state for the approve transaction? A way around this would be to initially use 2 buttons the uniswap way so as to communicate in the UI those are 2 actions. Then disappearing approve button communicates a success

<img width="545" alt="Screen Shot 2022-02-04 at 18 02 08" src="https://user-images.githubusercontent.com/90316/152579790-c5d9e13d-4503-45c7-9530-3e4726c68e22.png">

In general always have success in adding liquidity in my tests so far so if you get failing things, do report back.

For all the rest, excellent point with disabling inputs, this solves all the other issues described here, so did just that over in [#1062](https://github.com/oceanprotocol/market/pull/1062)
