### ISSUE TITLE
Bookmarks are not showing up on homepage

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1052]
**Describe the bug**
Bookmarks are not showing up on the `Bookmarks` homepage's section even though I have marked some items. 

**To Reproduce**
1. Go to Item
2. Click on Bookmark icon
3. Go back to the Homepage
4. See `Bookmarks` homepage's section

**Expected behavior**
I'm expecting to see all my selections on the `Bookmarks` homepage's section.

**Screenshots**

Marked Item: 

<img width="2560" alt="Screenshot 2022-02-01 at 15 26 44" src="https://user-images.githubusercontent.com/13741335/151987137-464a371b-9175-4dbc-9373-a14aae67ed1b.png">

Homepage: 

<img width="2560" alt="Screenshot 2022-02-01 at 15 26 51" src="https://user-images.githubusercontent.com/13741335/151987223-a8bd4e88-44a9-42b9-bc1d-679c5a3f01b6.png">

Desktop (please complete the following information):

OS: MacOS 12.0.1
Browser: Brave, Chrome

**Comment by EnzoVezzaro** [comment]
This seems to be cause by the `retrieveDDOListByDIDs` query in `src/@utils/aquarius.ts`. This query returns `undefined` as result for the bookmarks (as well as other parameters).

File: `src/components/Home/Bookmarks.tsx`

![Bookmarks.tsx - retrieveDDOListByDIDs.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/2b7b9f75-1a65-448f-836d-6b64dff53879)

Query `retrieveDDOListByDIDs`: `src/@utils/aquarius.ts`

![retrieveDDOListByDIDs.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/b714f77c-feb5-4e33-8d60-898f03ad6e56)

Query `queryMetadata`: `src/@utils/aquarius.ts`

![Metadata - retrieveDDOListByDIDs.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/5d628808-a677-445f-80d7-4e963b9a06b2)

**Comment by kremalicious** [comment]
you should look at the actual Elasticsearch query, meaning `query` you pass to `queryMetadata` in `retrieveDDOListByDIDs` in `src/@utils/aquarius.ts`. The query format changed a bit in Aquarius v4 and most likely the passed `query` is wrong so needs to be investigated where exactly it's wrongly created in that `generateBaseQuery`

**Comment by kremalicious** [comment]
I just get a totally weird response

<img width="1420" alt="Screen Shot 2022-02-07 at 16 14 53" src="https://user-images.githubusercontent.com/90316/152827348-f35ce0bb-f880-4423-9ba9-5f90c1a3eb8d.png">

**Comment by kremalicious** [comment]
> filter by id is not working anymore in aquarius, need to check the schema

fun stuff, was trying to find any document in Aquarius helping us figuring out what queries it supports and which fields get indexed and only found this but it's describing the old v3 DDOs 😀 https://github.com/oceanprotocol/aquarius/blob/v4main/aquarius/app/es_mapping.py

**Comment by EnzoVezzaro** [comment]
for what i can see, it seems that the query is ok:

`{
    "from": 0,
    "size": 1000,
    "query": {
        "bool": {
            "filter": [
                {
                    "terms": {
                        "id": [
                            "did:op:761a44c971acb8614d7b4a229dbce0774cdc90b96f97a014e63bf729a037733e",
                            "did:op:cb3dfc137988c8aba3a122c3bd2d9248a89ec1067deb6b06645587d56c355b5d",
                            "did:op:678e128342bce065ade40090589f430822a4a35d9d3301df2b2b4ffaf8083016",
                            "did:op:4bc4707802ca8cc2edf1cd7dc9811d44b204553a4d1234a03c1f2ecf76bdef84"
                        ]
                    }
                },
                {
                    "terms": {
                        "chainId": [
                            4
                        ]
                    }
                },
                {
                    "term": {
                        "_index": "aquarius"
                    }
                }
            ]
        }
    }
}`

but the result return only one object:

`{
    "_shards": {
        "failed": 0,
        "skipped": 0,
        "successful": 10,
        "total": 10
    },
    "hits": {
        "hits": [
            {
                "_id": "did:op:cb3dfc137988c8aba3a122c3bd2d9248a89ec1067deb6b06645587d56c355b5d",
                "_index": "aquarius",
                "_score": 0,
                "_source": {
                    "@context": [
                        "https://w3id.org/did/v1"
                    ],
                    "chainId": 4,
                    "datatokens": [
                        {
                            "address": "0x0CDF34Cf07aeB107F9DD3D7Df08DA540BD38170a",
                            "name": "Obtuse Shark Token",
                            "serviceId": "326777513f826278fd9770e42ce91ead815b5ee73d8d38be1187bd01f0c11a6a",
                            "symbol": "OBTSHA-3"
                        }
                    ],
                    "event": {
                        "block": 10092073,
                        "contract": "0xC7209B745c0eeB0d4885D2f3dAD88A44b0F025FA",
                        "datetime": "2022-02-01T08:13:21",
                        "from": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
                        "tx": "0x215e757b7281e97e08b4ae06227095c8ff3ac67e076ec58068ce0ae1c5171af0"
                    },
                    "id": "did:op:cb3dfc137988c8aba3a122c3bd2d9248a89ec1067deb6b06645587d56c355b5d",
                    "metadata": {
                        "additionalInformation": {
                            "termsAndConditions": true
                        },
                        "author": "EV",
                        "created": "2022-02-01T08:13:10Z",
                        "description": "Testing Pub",
                        "license": "https://market.oceanprotocol.com/terms",
                        "name": "Testing Pub",
                        "tags": [
                            "budget"
                        ],
                        "type": "dataset",
                        "updated": "2022-02-01T08:13:10Z"
                    },
                    "nft": {
                        "address": "0xC7209B745c0eeB0d4885D2f3dAD88A44b0F025FA",
                        "created": "2022-02-01T08:13:21",
                        "name": "Ocean Asset v4 NFT",
                        "owner": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
                        "state": 0,
                        "symbol": "OCEAN-NFT"
                    },
                    "nftAddress": "0xC7209B745c0eeB0d4885D2f3dAD88A44b0F025FA",
                    "purgatory": {
                        "state": false
                    },
                    "services": [
                        {
                            "datatokenAddress": "0x0CDF34Cf07aeB107F9DD3D7Df08DA540BD38170a",
                            "files": "0x0403d8d0058001bb7fb6f059c583889e2d16ae4cec49455cd26892db20571b41d26d57aa72637fab63daa40c0828803ed6c19072f1d20e29b59de5b03f9f11648224e425d0729dff46a8418b8f55867d03c4de4300ea0fa463443e5fc1b7dcc068e17b375a94b2756dc01258460e3e9d302a72a30c754432e4278b9b4a352dd05207451176be48b154f8c40ac8aef7004dee92f282bcbd5e45dbc9beca24f20beb729a764afca1dbdb941fdfa993b6795566c96bf1686a45ff67233a43aa9d871b2c2e6d0d5f559f18b92da162cccb0dc730e3561c616d0bccea5bcb",
                            "id": "326777513f826278fd9770e42ce91ead815b5ee73d8d38be1187bd01f0c11a6a",
                            "serviceEndpoint": "https://providerv4.rinkeby.oceanprotocol.com",
                            "timeout": 86400,
                            "type": "access"
                        }
                    ],
                    "stats": {
                        "consumes": -1
                    },
                    "version": "4.0.0"
                },
                "_type": "_doc"
            }
        ],
        "max_score": 0,
        "total": 1
    },
    "timed_out": false,
    "took": 1
}`

for what i can see on the code, it seems that the query should return 4 ddos (in this case) instead of one (line: 194). And this why I'm getting [undefined, { corect ddo }, undefined, undefined]. These undefined are the object missing from the query.

![Metadata - retrieveDDOListByDIDs](https://user-images.githubusercontent.com/13741335/152836138-9fb6541c-f328-40d8-b56c-14676e38f10b.png)

**Comment by EnzoVezzaro** [comment]
solution proposed on [issues 693](https://github.com/oceanprotocol/aquarius/issues/693) worked.

**Comment by kremalicious** [comment]
as for the styling, yes that readability issue is valid but should be handled individually in a new issue. For now, this issues original intention is done
