### ISSUE TITLE
Tokens can be created with same name, and if so, second token is not found. 

### ISSUE THREAD

**Issue by jdwstartb** [oceanprotocol/market#1058]
**Describe the bug**
I was able to create 2 tokens with the same name. This lead to errors while searching for the second one. 

**To Reproduce**
1. Go to https://market.oceanprotocol.com/ 
  - use rinkeby test net
  - Use Metamask
2. Create Data token and set pricing 
3. Create Algo token and set pricing  (unclear how to reproduce the same naming or why it happened, but the same name was assigned)
4. Search Tokens (INVSEA-47)
5. Try linking the data token to the algorithm.
6. Observe: algorithm not found.

**Expected behavior**
Token names are unique and Algo is found.

**Screenshots**
![image](https://user-images.githubusercontent.com/86761206/152460606-7fd248d6-12a3-4b89-8f9b-e00b50f4330e.png)

**Desktop:**
 - OS: Win 10
 - Browser Brave

**Additional context**

**Comment by kremalicious** [comment]
> Expected behavior
> Token names are unique and Algo is found.

This does not reflect the technology, where ERC20 contract addresses are unique but name/symbols are not. We also don't keep track of datatoken names and symbols in some big list so preventing duplicates is just not feasible as we would have to scan all chains for all existing datatoken names & symbols.

I agree though that the case you encountered should not happen, where the UI assigns same name & symbol to 2 different assets. This pretty much should be solved with new publish flow in `v4`, so we won't look into this into current `v3` version any further.

As we are not using the datatoken name & symbol to find algos I am almost sure this is unrelated with the double naming.
