### ISSUE TITLE
Specific token approvals have to be done for every transaction

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1063]
Not sure this is a bug or a feature but as described in point 4 of #1050, token approval behavior seem to have changed.

 but if I remember correct on live: 
- I approve 5 OCEAN for a pool and add 5 OCEAN
- I can then add 5 OCEAN again without approving again

Currently in v4:
- I approve 5 OCEAN for a pool and add 5 OCEAN
- Afterwards I need to approve 5 OCEAN again to be able to add it

Expectation would be that if I approve the pool to take 5 OCEAN this is meant for all future transactions for 5 OCEAN. Or did I get something wrong here?

**Comment by mihaisc** [comment]
the v4 way sounds right

**Comment by alexcos20** [comment]
When you approve, you have 2 options:
- approve a large number (2^256) and have several transactions
- approve 5 ocean tokens and execute one transactions that moves 5 ocean tokens.


Each transferFrom call will decrease the allowance.    So, the following scenario is possible:
 - approve 100 tokens
 - call transferFrom (10 tokens) x 10 times
 - for the 11th time, you will need to do another approve

**Comment by mihaisc** [comment]
@kremalicious is this still an issue?
