### ISSUE TITLE
Show gas cost estimation for buy

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1066]
We can display how much the tx will cost to order ( or buy dt + order for pool).  So somewhere in the use tab we can display this.

**Comment by EnzoVezzaro** [comment]
I was thinking of implementing something like this. Please let me know if could work.

I intend to add a suggestion badge (similar to Approval Ocean Token's button) with the estimation amount. Here some examples.

![localhost_8000_profile (1)](https://user-images.githubusercontent.com/13741335/158572828-038d9410-34af-4ff7-b00f-58cbc0a6b3a9.png)
![localhost_8000_profile (3)](https://user-images.githubusercontent.com/13741335/158572910-8d146395-35c5-4fce-b200-d15d56b54276.png)

Could this work @kremalicious ?

**Comment by EnzoVezzaro** [comment]
Looking at the code I have identify these methods to get the estimation prices for all our operations:

**USE**
fixed - Datatoken.estGasMint()
dynamic - Datatoken.estGasMint()
free - Datatoken.estGasMint()

**POOL**
add liquidity - Pool.estJoinPool()
remove liquidity - Pool.estExitPool()

**TRADE**
swapIn - Pool.estSwapExactAmountIn()
swapOut - Pool.estSwapExactAmountOut()

are all of these correct @mihaisc ?

**Comment by kremalicious** [comment]
reopen if anybody starts using ETH mainnet
