### ISSUE TITLE
Publish flow - blocked FREE pricing tab 

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1078]
**Is your feature request related to a problem? Please describe.**
If you leave the "Continue" button disabled, you're not able to continue in the "FREE" tier.

**Describe the solution you'd like**
The user should be able to continue in the publishing flow because in the "FREE" tier nothing is required. 

<img width="1805" alt="Screenshot 2022-02-10 at 14 18 24" src="https://user-images.githubusercontent.com/13741335/153416156-c501aa98-3c98-497e-9eec-adc63dbad975.png">

**Comment by EnzoVezzaro** [comment]
yes, exactly. I like the idea of having a disclaimer checkbox. To be sure the user actually agrees.

**Comment by mihaisc** [comment]
is this not a duplicate https://github.com/oceanprotocol/market/issues/1060?

**Comment by kremalicious** [comment]
right, we have more issues with that free screen so continuing over in #1060
