### ISSUE TITLE
replace use-dark-mode

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1085]
Our used library to implement light/dark mode is a bit abandoned and leads to npm installation problems in some case. As the library is super small and has rather standard functionality, we should just copy it into our own hook and be done with it:

https://github.com/donavon/use-dark-mode

Bonus for the UI, could be also done in extra issue: 

We need 3 options:
- System (default)
- Light
- Dark

Right now, we default to system setting but as soon as user manually interacts with Light/Dark switches there is no way to go back to system setting.

**Comment by mihaisc** [comment]
moved to mid so we can remove that annoying npm install command.

**Comment by kremalicious** [comment]
`npm install` without anything else should work already, as I replaced with https://github.com/oceanprotocol/use-dark-mode in #1700

So this issue here could be further reduced in priority, as remaining goal would be only to add a 3rd option. When not interacting with the appearance setting, this is all working out nicely already

**Comment by mihaisc** [comment]
awesome didn't notice that, in that case I'd close this.
