### ISSUE TITLE
Show gas cost estimation for publish

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1093]
For each method we call during publish we have a corresponding method to estimate its gas usage in ocean.js. So make use of those in the submission screen and display estimated cost (in ETH + user's currency, or just user currency) for each step beside the transaction count labels

**Comment by EnzoVezzaro** [comment]
are these the methods i need to call, right?

file: node_modules/@oceanprotocol/lib/dist/src/factories/NFTFactory.d.ts 
methods: 
- Step 1 (Create Tokens & Pricing)
- - estGasCreateNFT
- Step 2 (Construct & Encrypt DDO)
- - none
- Step 3 (Publish DDO)
- - estGasCreateNftWithErc20

**Comment by EnzoVezzaro** [comment]
I've been trying to debug these params but for what i can see all params are being populated, I'm not sure if the information is actually right thought. Here's the full payload for each call.

Free Pricing - method: estGasCreateNftErc20WithDispenser

`accountId: 0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e,
nftCreateData : {
    "name": "Ocean Asset NFT",
    "symbol": "OCEAN-NFT",
    "templateIndex": 1,
    "tokenURI": "data:application/json;base64,eyJuYW1lIjoiT2NlYW4gQXNzZXQgTkZUIiwic3ltYm9sIjoiT0NFQU4tTkZUIiwiZGVzY3JpcHRpb24iOiJUaGlzIE5GVCByZXByZXNlbnRzIGFuIGFzc2V0IGluIHRoZSBPY2VhbiBQcm90b2NvbCB2NCBlY29zeXN0ZW0uIiwiZXh0ZXJuYWxfdXJsIjoiaHR0cHM6Ly9tYXJrZXQub2NlYW5wcm90b2NvbC5jb20iLCJiYWNrZ3JvdW5kX2NvbG9yIjoiMTQxNDE0IiwiaW1hZ2VfZGF0YSI6ImRhdGE6aW1hZ2Uvc3ZnK3htbCwlM0Nzdmcgd2lkdGg9Jzk5JyBoZWlnaHQ9Jzk5JyBmaWxsPSd1bmRlZmluZWQnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyclM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5Mjc3JyBkPSdNMCw5OUwwLDIxQzgsMjMgMTcsMjUgMjUsMjVDMzIsMjQgMzgsMjIgNDcsMjBDNTUsMTcgNjUsMTYgNzUsMTdDODQsMTcgOTEsMjAgOTksMjNMOTksOTlaJy8lM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5MmJiJyBkPSdNMCw5OUwwLDQ2QzUsNDUgMTEsNDUgMjEsNDZDMzAsNDYgNDIsNDcgNTIsNTBDNjEsNTIgNjgsNTUgNzYsNTZDODMsNTYgOTEsNTQgOTksNTNMOTksOTlaJyUzRSUzQy9wYXRoJTNFJTNDcGF0aCBmaWxsPSclMjNmZjQwOTJmZicgZD0nTTAsOTlMMCw2OUM4LDcwIDE3LDcyIDI1LDcyQzMyLDcxIDM5LDY4IDQ3LDcwQzU0LDcxIDYzLDc3IDcyLDc5QzgwLDgwIDg5LDc2IDk5LDcyTDk5LDk5WiclM0UlM0MvcGF0aCUzRSUzQy9zdmclM0UifQ=="
},
ercParams : {
    "templateIndex": 2,
    "minter": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "feeManager": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "mpFeeAddress": "0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d",
    "feeToken": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
    "feeAmount": "0",
    "cap": "1000",
    "name": "Comely Cod Token",
    "symbol": "COMCOD-10"
},
dispenserParams: {
    "dispenserAddress": "0x5FfDe8179E095803de22CBe1D405Eeef18406852",
    "maxTokens": "1000000000000000000",
    "maxBalance": "1000000000000000000",
    "withMint": true,
    "allowedSwapper": "0x0000000000000000000000000000000000000000"
}
`

Fixed Pricing - method: estGasCreateNftErc20WithFixedRate

`accountId: 0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e,
nftCreateData : {
    "name": "Ocean Asset NFT",
    "symbol": "OCEAN-NFT",
    "templateIndex": 1,
    "tokenURI": "data:application/json;base64,eyJuYW1lIjoiT2NlYW4gQXNzZXQgTkZUIiwic3ltYm9sIjoiT0NFQU4tTkZUIiwiZGVzY3JpcHRpb24iOiJUaGlzIE5GVCByZXByZXNlbnRzIGFuIGFzc2V0IGluIHRoZSBPY2VhbiBQcm90b2NvbCB2NCBlY29zeXN0ZW0uIiwiZXh0ZXJuYWxfdXJsIjoiaHR0cHM6Ly9tYXJrZXQub2NlYW5wcm90b2NvbC5jb20iLCJiYWNrZ3JvdW5kX2NvbG9yIjoiMTQxNDE0IiwiaW1hZ2VfZGF0YSI6ImRhdGE6aW1hZ2Uvc3ZnK3htbCwlM0Nzdmcgd2lkdGg9Jzk5JyBoZWlnaHQ9Jzk5JyBmaWxsPSd1bmRlZmluZWQnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyclM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5Mjc3JyBkPSdNMCw5OUwwLDIxQzgsMjMgMTcsMjUgMjUsMjVDMzIsMjQgMzgsMjIgNDcsMjBDNTUsMTcgNjUsMTYgNzUsMTdDODQsMTcgOTEsMjAgOTksMjNMOTksOTlaJy8lM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5MmJiJyBkPSdNMCw5OUwwLDQ2QzUsNDUgMTEsNDUgMjEsNDZDMzAsNDYgNDIsNDcgNTIsNTBDNjEsNTIgNjgsNTUgNzYsNTZDODMsNTYgOTEsNTQgOTksNTNMOTksOTlaJyUzRSUzQy9wYXRoJTNFJTNDcGF0aCBmaWxsPSclMjNmZjQwOTJmZicgZD0nTTAsOTlMMCw2OUM4LDcwIDE3LDcyIDI1LDcyQzMyLDcxIDM5LDY4IDQ3LDcwQzU0LDcxIDYzLDc3IDcyLDc5QzgwLDgwIDg5LDc2IDk5LDcyTDk5LDk5WiclM0UlM0MvcGF0aCUzRSUzQy9zdmclM0UifQ=="
},
ercParams : {
    "templateIndex": 2,
    "minter": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "feeManager": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "mpFeeAddress": "0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d",
    "feeToken": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
    "feeAmount": "0",
    "cap": "1000",
    "name": "Comely Cod Token",
    "symbol": "COMCOD-10"
},
freParams: {
    "fixedRateAddress": "0xdf29DA8FF979170eBfEd7133068dA247dc04CdC9",
    "baseTokenAddress": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
    "owner": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "marketFeeCollector": "0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d",
    "baseTokenDecimals": 18,
    "datatokenDecimals": 18,
    "fixedRate": "5",
    "marketFee": "0",
    "withMint": true,
    "allowedConsumer": "0x0000000000000000000000000000000000000000"
}`


Dynamic Pricing - method: estGasCreateNftErc20WithPool

`accountId: 0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e,
nftCreateData : {
    "name": "Ocean Asset NFT",
    "symbol": "OCEAN-NFT",
    "templateIndex": 1,
    "tokenURI": "data:application/json;base64,eyJuYW1lIjoiT2NlYW4gQXNzZXQgTkZUIiwic3ltYm9sIjoiT0NFQU4tTkZUIiwiZGVzY3JpcHRpb24iOiJUaGlzIE5GVCByZXByZXNlbnRzIGFuIGFzc2V0IGluIHRoZSBPY2VhbiBQcm90b2NvbCB2NCBlY29zeXN0ZW0uIiwiZXh0ZXJuYWxfdXJsIjoiaHR0cHM6Ly9tYXJrZXQub2NlYW5wcm90b2NvbC5jb20iLCJiYWNrZ3JvdW5kX2NvbG9yIjoiMTQxNDE0IiwiaW1hZ2VfZGF0YSI6ImRhdGE6aW1hZ2Uvc3ZnK3htbCwlM0Nzdmcgd2lkdGg9Jzk5JyBoZWlnaHQ9Jzk5JyBmaWxsPSd1bmRlZmluZWQnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyclM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5Mjc3JyBkPSdNMCw5OUwwLDIxQzgsMjMgMTcsMjUgMjUsMjVDMzIsMjQgMzgsMjIgNDcsMjBDNTUsMTcgNjUsMTYgNzUsMTdDODQsMTcgOTEsMjAgOTksMjNMOTksOTlaJy8lM0UlM0NwYXRoIGZpbGw9JyUyM2ZmNDA5MmJiJyBkPSdNMCw5OUwwLDQ2QzUsNDUgMTEsNDUgMjEsNDZDMzAsNDYgNDIsNDcgNTIsNTBDNjEsNTIgNjgsNTUgNzYsNTZDODMsNTYgOTEsNTQgOTksNTNMOTksOTlaJyUzRSUzQy9wYXRoJTNFJTNDcGF0aCBmaWxsPSclMjNmZjQwOTJmZicgZD0nTTAsOTlMMCw2OUM4LDcwIDE3LDcyIDI1LDcyQzMyLDcxIDM5LDY4IDQ3LDcwQzU0LDcxIDYzLDc3IDcyLDc5QzgwLDgwIDg5LDc2IDk5LDcyTDk5LDk5WiclM0UlM0MvcGF0aCUzRSUzQy9zdmclM0UifQ=="
},
ercParams : {
    "templateIndex": 2,
    "minter": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "feeManager": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e",
    "mpFeeAddress": "0x9984b2453eC7D99a73A5B3a46Da81f197B753C8d",
    "feeToken": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
    "feeAmount": "0",
    "cap": "1000",
    "name": "Comely Cod Token",
    "symbol": "COMCOD-10"
},
poolParams: {
    "dispenserAddress": "0x5FfDe8179E095803de22CBe1D405Eeef18406852",
    "maxTokens": "1000000000000000000",
    "maxBalance": "1000000000000000000",
    "withMint": true,
    "allowedSwapper": "0x0000000000000000000000000000000000000000"
}`

**Comment by mihaisc** [comment]
Maybe try to work with local version of ocean.js and debug there as well

**Comment by EnzoVezzaro** [comment]
Now i'm at a good point, but there's an issue is driving kind of nuts 😅

Basically, the "Create token & pricing" estimates seems right, but the "PublishDDO" estimates are way off.

<img width="1400" alt="1" src="https://user-images.githubusercontent.com/13741335/154661613-9526158b-bc65-4821-a69c-449a7ce7edc2.png">

Now I'm trying to debug this issue. 

<img width="1400" alt="2" src="https://user-images.githubusercontent.com/13741335/154661619-a99a8b79-3639-4424-8211-986067f05cec.png">

**Comment by mihaisc** [comment]
You can estimate them both before hitting submit. If you estimate the second after submit it kinda misses the point. To estimate the second you can just pass some dummy addresses ( i think it should work) to make the estimation. This would be ideal if possible

**Comment by EnzoVezzaro** [comment]
I did it that way because it seems that the `estGasSetMetadata` need `erc721Address` which I get after the first transaction and `encryptedDdo` and `metadataHash` (which I the `ddo` that I  get on the second transaction)

Basically the query I'm trying to do is this one:
`await nft.estGasSetMetadata(
    feedback['1'].erc721Address, // this is provided by the first transaction
    accountId, 
    0,
    services['0'].providerUrl.url,
    '',
    flags,
    feedback['2'].encryptedDdo, // this is provided by the second transaction
    '0x' + metadataHash // this is provided by the second transaction
  )`

Of course I'm assuming this by the `setMetadata` and whats in the `estGasSetMetadata` in the lib.

Can you share some dummy data or is there a way to find an example call to copy from like a documentation of some sort? Because unfortunately this methods doesn't return any issue as discussed, just `10000` as value (probably because the params are not correct)

**Comment by EnzoVezzaro** [comment]
Problem solved. It has been solve on [ocean.js](https://github.com/oceanprotocol/ocean.js/pull/1303). Now i get the connect estimate for the publishDDO step.

**Comment by EnzoVezzaro** [comment]
> You can estimate them both before hitting submit. If you estimate the second after submit it kinda misses the point. To estimate the second you can just pass some dummy addresses ( i think it should work) to make the estimation. This would be ideal if possible

I'm still trying to figure out what data to send as Dummy data, can i just use whatever data? can i just hardcode the data of a  real successful call? 

because as previously discussed, the metadataHash is made of `getHash(JSON.stringify(feedback['2'].ddo))`, where I need to process the first transaction to get the `feedback['2'].ddo`. The same for the `_encrptedDdo` parameter. I get these params only after processing the first transaction (after the createNftErc20 calls).

**Comment by EnzoVezzaro** [comment]
at the moment we have this behaviour:

1) the `Create Tokens & Pricing` step displays the correct gas fees, but the `Publish DDO` shows 0 as values. Until this the first transaction si succeful
<img width="1183" alt="Screenshot 2022-02-22 at 10 38 20" src="https://user-images.githubusercontent.com/13741335/155104980-a8a5f543-3ede-49b2-9085-88a4ae9095a6.png">

2) after the transaction is succesful, the `Publish DDO` step will show the correct gas fees. As discussed, this is not very effective as you get the gas fees at the moment of payment which is being trigger immediately. So, this becomes kind of useless. 

<img width="1167" alt="Screenshot 2022-02-22 at 10 38 44" src="https://user-images.githubusercontent.com/13741335/155104989-f442d62a-4749-4812-b575-7448b236c44f.png">

The possible solutions I proposed are:

- implement dummy data as @mihaisc suggested or
- allow the user to trigger himself the `Publish DDO` payment by clicking again to the submit button before running the transaction. So the user has the time to see the gas fees before transacting

**Comment by kremalicious** [comment]
reopen if anybody starts using ETH mainnet
