### ISSUE TITLE
Restore global stats

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1096]
Restore existing global market stats in the footer, and look into what other useful data we could show/replace based on new subgraph.

Can only be reliably tested once we have test assets on multiple test networks.

**Blocked by https://github.com/oceanprotocol/ocean-subgraph/issues/316**

**Comment by mihaisc** [comment]
[Query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20globalStats%7B%0A%20%20%20%20id%0A%20%20%20%20totalLiquidity%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20totalSwapVolume%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20orderCount%0A%20%20%20%20nftCount%0A%20%20%20%20datatokenCount%0A%20%20%20%20poolCount%0A%20%20%7D%0A%7D)

**Comment by mihaisc** [comment]
Unblocked https://github.com/oceanprotocol/ocean-subgraph/pull/319
