### ISSUE TITLE
Flag a dataset and give notification to marketplace 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#11]
kremalicious commented 26 days ago • 
Define "Flag". Define "notification". What does a user see? What does a user do? What is happening in background when user does it?

**Comment by trentmc** [comment]
I think #194 supersides this. It's also more clearly described. Closing. If you think we need to re-open, we can discuss.

Related: [IP Rights violation epic](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/34)
