### ISSUE TITLE
new asset action: Swap

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#110]
Add a new tab in the asset actions widget allowing users to swap OCEAN ←→ Datatoken.

This is so we do not end up handling this on the _Use_ screen, which should stay focused on the usage of dataset, so only 1 Datatoken can be bought from there.

In there, handle those rules:

```
2. Swap:
        a) buyDT
                       i) Make sure that DT_AMOUNT_REQIRED < getMaxBuyQuantity(pool, dtaddress)
                      ii) Calculate how many ocean you need:  getOceanNeeded(pool, DT_AMOUNT_REQUIRED)
        b) sellDT
                      i) Calculate how many ocean you will receive:  getOceanReceived(pool,DT_AMOUNT)
                     ii) Make sure that ocean_amount < getMaxBuyQuantity(pool, pool.oceanAddress)
```

Motivation: people can't sell datatokens. Yet Ocean Market is meant to be an *exchange*; so selling is a critical part; it's also critical to truly establish datatokens as assets. There's also a sub-problem: people who buy to speculate may end up inadvertently consuming, and losing. 

It's for these reasons that this issue is a bug (vs enhancement), and high priority.

----

Defer until later:
- Slow slippage. [Github issue](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/197)
- Show "max/min expected amount received" (like uniswap or Balancer do)

**Comment by kremalicious** [comment]
was this closed by accident or was there some decision? Cause @mihaisc was working on that

**Comment by trentmc** [comment]
Was closed by accident
