### ISSUE TITLE
web3 https.Agent error

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1100]
**Describe the bug**
I get this error on single item: `https.Agent is not a constructor`

**To Reproduce**
1. Go to an item
2. An Error modal will open

**Screenshots**
<img width="2560" alt="Screenshot 2022-02-15 at 08 47 05" src="https://user-images.githubusercontent.com/13741335/154016549-934088c7-4358-425f-8465-56e584b69584.png">

**Comment by mihaisc** [comment]
are you using the latest v4 branch? if yes delete node_modules and install again. This was a webpack/next.js issue.

**Comment by EnzoVezzaro** [comment]
ok, perfect. Yes, I'm using the latest v4 branch.

**Comment by EnzoVezzaro** [comment]
closing issue
