### ISSUE TITLE
Hide "Your compute jobs" functionality in Publish Preview

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1101]
**Describe the bug**
The minting process seems to get fired when you click on the "Your compute jobs" tab in the Preview section on publish.

**To Reproduce**
1. Go to Publish
2. Fill of the information until preview
3. Click on "Your compute jobs" (HIDE/SHOW)
4. See started minting process

**Expected behavior**
user's computes History

**Screenshots**

https://user-images.githubusercontent.com/13741335/154022627-4a90c2a7-1a7f-4647-8632-d74d0b29bed6.mp4

PS: you can't see metamask, but i was interacting with metamask

**Comment by mihaisc** [comment]
that is not minting, it just ask you to sign. Good catch

**Comment by EnzoVezzaro** [comment]
by disable, you mean hide it? what should we display instead? or just remove the whole dropdown?

**Comment by mihaisc** [comment]
Yep, hide it. There is no use for it there

**Comment by EnzoVezzaro** [comment]
I'm confused now 😅. Can i go ahead and open a PR or this will be fixed on the refactor?

**Comment by mihaisc** [comment]
No need to do anything, it will be handled in the compute pr

**Comment by EnzoVezzaro** [comment]
Ok good, closing issue then 👍🏽

**Comment by EnzoVezzaro** [comment]
closing issue, it will be fixed on [Restore compute functionality #1069](https://github.com/oceanprotocol/market/pull/1069)
