### ISSUE TITLE
failed to download free dataset

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1102]
**Describe the bug**
If I try to download this file: 

http://localhost:8000/asset/did:op:0b956f2938fc4249a36057a5bc9fed3d71ff49e3b6e6ebcd1c9765e26e3efa58

but when i click download, the platform redirect me to (after signing): 

URL: https://providerv4.rinkeby.oceanprotocol.com/api/services/download?fileIndex=0&documentId=did:op:0b956f2938fc4249a36057a5bc9fed3d71ff49e3b6e6ebcd1c9765e26e3efa58&transferTxId=0xba15533f5e83a26dc999005e90b772016ea7509fca70df1846d076d045058bc2&serviceId=e42cdbb60bcaa2602fb4ae83d43ddb35484dadba01ee653a0f70ce2bfca0f89a&consumerAddress=0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e&nonce=1644916932631&signature=0xe3a0b58d88d76726403d4ff1a918e9c345524d2420a9dcc1fa499374cfcecf0a6b91701cea1a3b00f77e3b4e2ab09c5518874d23f7ad33a356b263089e483fe41b

with error:

`{"error":"=Order with tx_id 0xba15533f5e83a26dc999005e90b772016ea7509fca70df1846d076d045058bc2 is not found on chain."}`

**To Reproduce**
1. Go to a free item
2. Click on buy
3. After buying, click on Download

**Expected behavior**
I expect the file to be downloaded on my machine.

**Screenshots**
<img width="2560" alt="Screenshot 2022-02-15 at 10 18 14" src="https://user-images.githubusercontent.com/13741335/154032083-8def6b39-a96a-4d0a-959f-cd97e14a3274.png">

**Comment by mihaisc** [comment]
This is because of rinkeby. It timeout when provider tries to get the order. This indeed needs more testing. No actions needed at the moment

**Comment by EnzoVezzaro** [comment]
ok, closing at the moment
