### ISSUE TITLE
show "insuficient funds" and disabled the "submit" button on publish if the user has low balance

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1112]
**Is your feature request related to a problem? Please describe.**
when the user has low balance, the UI doesn't reflect that and allows users to continue on their interactions with the contracts. 

It should be better to check if the user has enough balance on his wallet, if not we should block the submit button (like Uniswap for example). This is will prevent weird messaging from the EVM if the balance is not enough. 

<img width="2557" alt="Screenshot 2022-02-17 at 11 06 51" src="https://user-images.githubusercontent.com/13741335/154460695-d039188a-17e1-49cf-b259-2a82913e4a31.png">

**Comment by mihaisc** [comment]
This can be based on the estimation of transaction + a delta

**Comment by EnzoVezzaro** [comment]
this is being worked out on [Show gas cost estimation for publish #1093](https://github.com/oceanprotocol/market/issues/1093)

**Comment by mihaisc** [comment]
Please link prs, not issues.
