### ISSUE TITLE
Profile image

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1143]
![image](https://user-images.githubusercontent.com/26000280/155557283-51030ecf-d2c8-4192-8e0b-b6cd30684d9b.png)
The image says it all

**Comment by mihaisc** [comment]
fixed in https://github.com/oceanprotocol/market/pull/1047

**Comment by mihaisc** [comment]
Apparently still an issue
![image](https://user-images.githubusercontent.com/26000280/156571032-6d138743-b971-4058-9c3f-18d670f52bc6.png)
I don't understand why it works locally 
![image](https://user-images.githubusercontent.com/26000280/156571091-77e89c0d-e94c-4b3d-8b90-34aa2c08911c.png)

**Comment by kremalicious** [comment]
css specificity, somewhere during production build Next.js reorders style

Locally, as intended, `.account.image` overwrites default width/height of `.blockies`:

<img width="352" alt="Screen Shot 2022-03-09 at 13 40 34" src="https://user-images.githubusercontent.com/90316/157453082-38b81547-9d01-4e81-992f-1a7aa6508eb6.png">

But in production build, `.blockies` ends up twice in CSS and one of it way earlier than the rest so this kicks in, rendering the profile image at about 18px:

<img width="368" alt="Screen Shot 2022-03-09 at 13 42 17" src="https://user-images.githubusercontent.com/90316/157453395-208ec721-32f6-47e9-bf0e-03b8d480b171.png">
