### ISSUE TITLE
Clickable max values pattern

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1149]
The max values in the trade tab should be clickable

![image](https://user-images.githubusercontent.com/26000280/156521282-21817e4c-af2a-479b-a0e2-e7462c19417d.png)

If you click on 6.759 the first field will be filled with this value.
If you click on 62.571 the ocean field will be filled with this value.

Another topic is if it makes sense to have 2 "max" values for each token
You can see [here](https://github.com/oceanprotocol/ocean.js/blob/dfb42e546441992f09a8d8cc0b43c83f55730be0/src/utils/PoolHelpers.ts#L4) that a user can add a maximum of tokens equal to half the amount existing in pool and can remove maximum a  third of the pool. So basically the max value is a mix of calculation of maximums that you can take from pool and what you have in your wallet. I say that we can remove 'Available from pool'

**Comment by mihaisc** [comment]
Also take [this](https://github.com/oceanprotocol/market/pull/1141#issuecomment-1057952454) into consideration

**Comment by kremalicious** [comment]
In addition, quick drafts to unify between trade, add, remove:

<img width="447" alt="Screen Shot 2022-03-03 at 12 33 30" src="https://user-images.githubusercontent.com/90316/156565527-90634f26-af2a-47ad-bac1-e20d3f77f44d.png">

As for remove the maximum slider value should then represent that maximum pool shares to spend and user should not be able to move it further then:

<img width="452" alt="Screen Shot 2022-03-03 at 12 36 34" src="https://user-images.githubusercontent.com/90316/156566001-929cef0c-30f7-45b6-b341-c0c0a34ad012.png">
