### ISSUE TITLE
Some wallets show a client-side error when interacting with free assets

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1156]
**Describe the bug**
When opening the asset detail page of a free asset the page flashes the correct content but then throws an error. With the same wallet all the other functionalities (like publishing, buying free or pool etc…) work.
Specifically it happened with this address: [0xbEe7E78668fd81d02D33Fc41aAD70AAa815B0916](https://rinkeby.etherscan.io/address/0xbEe7E78668fd81d02D33Fc41aAD70AAa815B0916)

https://user-images.githubusercontent.com/20192135/156627080-89b72407-fb9b-429b-844f-c6b9bb965bfd.mov

**Additional context**
Happens on all test network

**Comment by LucaMilanese90** [comment]
I just updated the video staying on the correct network. 
Algos seem to work fine on all networks. 

On the Rinkeby testnet it happens on some assets  [276a1b01a2865d8c90446254ba6373f610dbd3a0079393bcacb155fa8fc2d7d5](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:276a1b01a2865d8c90446254ba6373f610dbd3a0079393bcacb155fa8fc2d7d5) 
but not on others 
[6bbe53684f933fdd826ff316ea566891fec3d1b44dd41a11a1aba719660fae73](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:6bbe53684f933fdd826ff316ea566891fec3d1b44dd41a11a1aba719660fae73)

On Ropsten and Mumbai it happens with all the dataset I tried.

**Comment by mihaisc** [comment]
https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:276a1b01a2865d8c90446254ba6373f610dbd3a0079393bcacb155fa8fc2d7d5 this is a compute asset published by daimler, we didn't finish implementing compute so it's not relevant yet.

**Comment by LucaMilanese90** [comment]
Still getting this error when looking at free assets both in Brave and Firefox, those 2 errors in the console come up and the page stop working.
It seems to only happen when opening free assets published by the same account, looking at other free assets does not trigger the error.
![screenshot_2022-03-17_at_12 27 06](https://user-images.githubusercontent.com/20192135/158806359-9a3b4a0b-3bb4-4042-91d0-ccc73b833bc5.png)
![screenshot_2022-03-17_at_12 33 22](https://user-images.githubusercontent.com/20192135/158806374-e90882b7-bcea-4e41-9871-7418b3f47fd6.png)

**Comment by EnzoVezzaro** [comment]
this should be related to https://github.com/oceanprotocol/market/issues/1213#issuecomment-1076357510
