### ISSUE TITLE
Publishing assets with pool price require 3 transactions

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1158]
**Describe the bug**
The page specify only 2 transactions are needed but actually there are 3 that need to be approved to successfully publish the asset.

**Additional context**
Happens on all test network

**Comment by LucaMilanese90** [comment]
Just tried again on the same asset [did:op:ca285f858304b20e4e319e9c1b17fcc60b8a2e08af8e52d88fd2b9427f9d5649](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:ca285f858304b20e4e319e9c1b17fcc60b8a2e08af8e52d88fd2b9427f9d5649) and it's still happening.

**Comment by LucaMilanese90** [comment]
Yes you are right, that's what I was referring to.
![Screenshot 2022-03-03 at 19 39 38](https://user-images.githubusercontent.com/20192135/156631236-ab144ffc-8ae5-43b2-8123-dba3824f0fb6.png)
 But from a user pov I think every pop up is seen as a transaction, so if there are 3 needed instead of 2 it can create some confusion.

**Comment by mihaisc** [comment]
You are right, it is actually a tx, so for pool we need to say that there are 2 tx in the first step

**Comment by AnaLoznianu** [comment]
Update the number of transactions displayed in the publish page

**Comment by claudiaHash** [comment]
Checked it again against v4 branch and seems to be already fixed by : https://github.com/oceanprotocol/market/blob/3ea832d2707faea143566fd00723c1f2889ef020/src/components/Publish/Steps.tsx#L34 and https://github.com/oceanprotocol/market/blob/3ea832d2707faea143566fd00723c1f2889ef020/src/components/Publish/Steps.tsx#L39
