### ISSUE TITLE
Published asset never show up

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1159]
**Describe the bug**
Sometimes the publish process gives the confirmation an asset has been published but the asset never shows on the market (at least up until now, almost 24h after the publish.

**example**
[did:op:7c5f7614b3da9e334bced3585fc5be41a4d2db4137408c37f5abd543c3623ab1](https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:7c5f7614b3da9e334bced3585fc5be41a4d2db4137408c37f5abd543c3623ab1)

**Screenshots**
![Screenshot 2022-03-02 at 18 58 28](https://user-images.githubusercontent.com/20192135/156610518-45162f11-e8bd-45a9-aa82-6c1dec18a731.png)

**additional context**
Happens randomly on all testnets

**Comment by LucaMilanese90** [comment]
Happened yesterday evening (around 21-22) as well as this morning and early in the afternoon, but not consistently

**Comment by mihaisc** [comment]
Can you share a link with a tx that failed today so we can check logs. We couldn't find that did in todays logs

**Comment by LucaMilanese90** [comment]
I might be wrong but the notification of the transaction said 'succeeded', so I'm not sure which one it is.
I was testing with this 2 addresses: 0xbEe7E78668fd81d02D33Fc41aAD70AAa815B0916 and 0xb9A3649639B619e45Ce1ed93f3be7b3D02F7941d

**Comment by mihaisc** [comment]
Without a tx or did , i would just have to go through all the nfts that you created on those two accounts, and this is not feasible. I'll see if i can do something

**Comment by LucaMilanese90** [comment]
I see, but what "did" are you referring to?  Not the one mentioned in the issue description right? I'll try to make it happen again and see if I can spot the exact transaction.

**Comment by mihaisc** [comment]
The one in the description is too old, we don't have logs :) So we need something from the same day

**Comment by mihaisc** [comment]
Is this being worked on? Can we even replicate?

**Comment by kremalicious** [comment]
sometimes we have delayed showing up but did not encounter this at all where it never shows up. Please reopen if this is happening for anyone again

**Comment by mihaisc** [comment]
When someone encounters this, like i said above post all the details , did, tx and an approximate time
