### ISSUE TITLE
Interacting with "Your pool transactions" inside the publish preview triggers some transactions

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1162]
**Describe the bug**
During step 4 of data set publishing, in the pool tab, if the user clicks on show in the "Your pool transactions" section two transactions get triggered and after that, most of the times, step 5 fails.

**To Reproduce**
1. Start publishing a data set
2. On step 3 set a pool price
3. On step 4 select the "pool" tab
4. Click on "show" in the "Your pool transactions" section
5. After a few seconds 2 transactions get triggered

**Screenshots**
![Screenshot 2022-03-02 at 19 30 19](https://user-images.githubusercontent.com/20192135/156614018-bb047f39-f398-4aca-bee8-87e12cd64759.png)
![Screenshot 2022-03-02 at 15 53 03](https://user-images.githubusercontent.com/20192135/156614065-a49bfa66-5260-4ea1-aa16-6d5f085bffd5.png)

**Comment by mihaisc** [comment]
That section should not be rendered at all in the preview

**Comment by kremalicious** [comment]
the Pool tab and the Trade are supposed to be disabled in publish preview but the logic fails somewhere. Disabling those tabs solves the reported issue too as there is no value to look at an empty pool tab.
