### ISSUE TITLE
Step 2 of publish in Moonbase Alpha fails to validate the file url

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1163]
**Describe the bug**
When publishing a data set in the Moonbase Alpha network, on step 2, the verification of the data link fails and doesn't allow to pass to step 3.
The same link works in all the other test nets.

**Screenshots**
![Screenshot 2022-03-02 at 21 06 19](https://user-images.githubusercontent.com/20192135/156614905-f1f5f4ee-e3fa-441a-9fa9-99bd04d9922d.png)

**Comment by mihaisc** [comment]
Please paste the link in the image so we can debug provider.

**Comment by AnaLoznianu** [comment]
The issue has been fixed, we just need an ocean.js release
