### ISSUE TITLE
Buying a compute job not enabled saying wallet has not enough ocean

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1165]
**Describe the bug**
When trying to buy a compute job the buy button is disabled and says there are not enough ocean in the wallet even though there are more than enough to cover the price.

**Screenshots**
![Test dataset publish fixed price](https://user-images.githubusercontent.com/20192135/156618548-69863c12-3842-4387-b59d-484e94f526c7.png)

**Comment by mihaisc** [comment]
Compute is not implemented
