### ISSUE TITLE
Unified representation of value in pools/profile

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1166]
Currently we still have a mix of liquidity and tvl 
![image](https://user-images.githubusercontent.com/26000280/156739433-82f329df-f166-466e-acb3-7853cfc3f49a.png)
![image](https://user-images.githubusercontent.com/26000280/156739449-2071e5c2-80f3-48cd-a668-f0f1164a78d3.png)

We need to be consistent and the data to make sense . Also when you add/remove liquidity you see liquidity

![image](https://user-images.githubusercontent.com/26000280/156739993-43f11a66-ae7e-4e3a-bedc-46c1b4e8c965.png)

So i have a tvl of 1090 but when i remove i can remove 67% ~ 579 ocean , 100% ~ 874 ocean (rough calculation, not accurate)

Also we need to validate these numbers
This is more of a discussion issue. I'll handle the changes in the pool shares pr

**Comment by kremalicious** [comment]
Mostly tackled in #1139 but some mentions of "Liquidity" are valid, think of "User adds liquidity in the form of OCEAN to a pool, which represents a Total Value Locked of ...".

This should be now much more consistent, both in wording and in value representation:

<img width="580" alt="Screen Shot 2022-03-09 at 12 35 30" src="https://user-images.githubusercontent.com/90316/157442873-5b7cf86b-5709-45ca-ac51-9cbd779a1594.png">

<img width="1138" alt="Screen Shot 2022-03-09 at 12 40 09" src="https://user-images.githubusercontent.com/90316/157443532-77d5afbf-5197-460c-932b-e2075a746ce8.png">

<img width="448" alt="Screen Shot 2022-03-09 at 12 39 02" src="https://user-images.githubusercontent.com/90316/157443406-d22dcdbc-9095-4820-ac76-e571e9112b9d.png">

That very bottom part of Pool tab still is kinda WIP, just want to dump the info on there first which makes sense
