### ISSUE TITLE
Confusing Publish "Dynamic" price experience

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1176]
When Publishing an asset with "Dynamic" price, the user needs to provide 2 values: 
* the Ocean price
* the datatoken liquidity pool (Ocean token) value
The report between these two values is directly correlated to the "Precipitate Manatee Token" value that is automatically generated. 
If the proportion is not correct, an error is shown on the 3rd field and the "Continue" button is disabled. Is not very clear the values the user needs to add in order to be able to proceed. 
Maybe we can add an instruction message or display a better error message

![Screenshot 2022-03-10 at 12.24.22.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/13fd7c80-41f4-4525-b236-bf8a29307653)

![Screenshot 2022-03-10 at 12.23.47.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/2ff3f54a-5c2d-4506-814b-271ca0bf9f2e)

**Comment by AnaLoznianu** [comment]
When changing the Ocean Price of the asset, let's automatically adjust the minimum Ocean Datatoken liquidity pool value.

**Comment by DMats** [comment]
I was also confused by this, briefly.

**Comment by malvonme** [comment]
Yes, we had in testing session yesterday. 

Added: the error message also acts as "distorter" or "Call to Action".

Meaning: what adds to the "confusion" is that the error message implies that I shall do something THERE to fix the error. 

Wherever we want users to take action, that's where the red error message could live best. 

Solution-Idea B:
As far as I remember Alex proposed an even sleeker "hack", auto-setting the init_OCEAN_liq_to_pool to at least 50X (min to resolve error) and not allowing user to turn it lower, only higher, but ofc up to you guys.

**Comment by malvonme** [comment]
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630613232363265373464383139313939336238386131312f31336664376338302d343166342d343532352d623233362d626638613239333037363533](https://user-images.githubusercontent.com/101562291/160117511-8bc5b5de-aa48-4b16-996b-00b464830a36.png)

**Comment by jamiehewitt15** [comment]
Yeah, the confusing thing about this is that the message is shown on the value that you can't change. The message should be shown on the Ocean value which the user is actually able to adjust e.g. "For this price, the minimum Ocean liquidity must be 500"
