### ISSUE TITLE
Fix code scanning alert - DOM text reinterpreted as HTML

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1192]
Tracking issue for:
- [ ] https://github.com/oceanprotocol/market/security/code-scanning/2

Explore options first, ideally replace need to use `dangerouslySetInnerHTML` altogether, if not, start stripping things from `content` in there. Could also be this is solved already by our `markdownToHtml()` method as the code comment suggests

**Comment by AnaLoznianu** [comment]
Needs to be doubled-check

**Comment by mihaisc** [comment]
Did some tests and it seems the malicious content is not being rendered
