### ISSUE TITLE
Hardcoded SVG width/height in NFT image

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1196]
We hardcode width/height with `99` in the generated SVG markup so wherever it is getting displayed it will only ever reach 99px, or more precisely will always use this if no CSS styles specifically overwrite it for inlined SVG. Like on OpenSea:

<img width="1495" alt="Screen Shot 2022-03-16 at 17 25 34" src="https://user-images.githubusercontent.com/90316/158650725-3be51142-5531-40ea-9dd0-4fd4a6c0958d.png">
 
As it's a SVG, expectation is that it scales to whatever size its container is so most likely we should not add any width/height attributes and if needed rather play around with `viewBox` so it still stays square. 

Requires some research as we could end up having to set something for width/height attributes as otherwise browsers might use their defaults for SVG rendering of 300×150px.

https://css-tricks.com/scale-svg/
https://www.sarasoueidan.com/blog/svg-coordinate-systems/
https://www.sarasoueidan.com/blog/svg-object-fit/

**Comment by LucaMilanese90** [comment]
Would this result be ok for you? 
![Screenshot 2022-03-23 at 19 06 12](https://user-images.githubusercontent.com/20192135/159769311-3ccaf3c9-b9ec-47a4-b794-983a33e96342.png)
![Screenshot 2022-03-23 at 19 11 22](https://user-images.githubusercontent.com/20192135/159769313-17778e81-32e0-4d67-a338-7a0421082617.png)

**Comment by mihaisc** [comment]
shiny big waves, looks cool

**Comment by kremalicious** [comment]
ship it

![giphy](https://user-images.githubusercontent.com/90316/159901492-e2c55faf-9061-4981-888a-f56846c417dd.gif)
