### ISSUE TITLE
Pool transactions tab in profile section not refreshing correctly

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1200]
**Describe the bug**
When switching accounts while in pool transactions section, the transaction list gets reloaded only if the account has at least one transaction. If the account is new and has no transaction to display, the page keeps showing the transactions from the previous account until the page gets refreshed or you switch back and forth from another tab. Other tabs (like download) seem to work as intended.

**To Reproduce**
1. While in the transaction pool tab, select one wallet with some transactions in it
2. Switch to another wallet with some transactions (the list will reload correctly to show the new wallet transactions)
3. Switch to another wallet with no transactions in it (the list will not refresh and will display the transactions from the previous wallet)

**Screenshots**

https://user-images.githubusercontent.com/20192135/158796962-972176d0-a10b-4e12-83ca-273c14893105.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.3 
 - Browser Firefox and Brave

EDIT: 
The page only shows correct details for the most recent transaction.
![screenshot_2022-03-17_at_11 21 10](https://user-images.githubusercontent.com/20192135/158807350-894e6aa3-98d8-4792-a135-3d0fd3767fd0.png)
![screenshot_2022-03-17_at_11 34 09](https://user-images.githubusercontent.com/20192135/158807358-35a69657-a6ef-44a8-90c3-5c9026a68127.png)

**Comment by AnaLoznianu** [comment]
Linked issue: https://github.com/oceanprotocol/market/issues/1210
