### ISSUE TITLE
Swap transaction gets reverted `SafeERC20 low-level call failed`

### ISSUE THREAD

**Issue by trizin** [oceanprotocol/market#1201]
The transaction is getting reverted with `Fail with error 'SafeERC20: low-level call failed'` when I'm trying to swap Ocean for DT.

I think this is related to the approved amount. It worked when I approved more tokens. Maybe a solution would be asking the user to approve (the exact amount+1) tokens or unlimited tokens (also saves gas).

Tx: https://ropsten.etherscan.io/tx/0x56a204d8b6a7dd4f67b6550f077946cc310aff516bfb441c23500826e95bf02a
Asset: `did:op:d3dd90c2fa7df8236af2b13a90030d0facaeb5dfe4a90b86ed3c4d29ca19d544`

**Comment by AnaLoznianu** [comment]
Additional information from Norbert:

I can’t trade Ocean for DT on Mumbai ( tx: 0x92624b21ebf1779721f7946e582a0cb1b18d7d8056de69b5bf307ed26d06a93b), I get the following error in console and nothing showing up in the UI 
![Uploading Screenshot 2022-03-18 at 11.05.18.png…]()

**Comment by mihaisc** [comment]
A fix in subgraph was done, maybe some math was wrong because of this. Can you retest/replicate it anymore ?

**Comment by AnaLoznianu** [comment]
We were able to reproduce the issue today. It looks like in the 'Approve' step, we are not taking into account the 'Slippage Tolerance' value and we are approving fewer Oceans.
Also, another weird behavior as you can see in the video attached is that the value I added(10) changes automatically to 9.

Transaction: https://rinkeby.etherscan.io/tx/0x7c7f0a4f806db471a715e484fc20dd759afcf375e986962033682dc4dcfa7832

https://drive.google.com/file/d/1ZKL2zcj5ZIgZQw_9qaGg3Y0RsHLbh3P9/view?usp=sharing
