### ISSUE TITLE
Failed to calculate PoolOutGivenSingleIn

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1206]
**Describe the bug**
Getting an error from the pool tab:
`ERROR: Failed to calculate PoolOutGivenSingleIn : execution reverted: ERR_BPOW_BASE_TOO_HIGH`

Was happening on Rinkeby with [this](https://v4.market.oceanprotocol.com/asset/did:op:cf94d27ae9e0cc7a420f19884609afd76a26c5c9d0fbc1fc877235eed396f5f6) asset. 

![Errors from the pool tab - 2022-03-17_13-58](https://user-images.githubusercontent.com/20739535/158805618-fad868a5-fb70-4c30-b868-9a7c9f723b98.png)

**Comment by AnaLoznianu** [comment]
This is a subgraph issue

**Comment by kremalicious** [comment]
new subgraph has been deployed. Please check again and close issue if fixed

**Comment by kremalicious** [comment]
whoops, got it, saw something about deployment in my myriad of channels some hours ago

**Comment by mihaisc** [comment]
Sub deployed. Should work now

**Comment by kremalicious** [comment]
no error seen on any Pool in any asset right now, so considering this fixed
