### ISSUE TITLE
pool creation tx are missing from pool transactions lists

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1209]
Consider this pool which was created by currently connected user:

<img width="496" alt="Screen Shot 2022-03-17 at 14 09 34" src="https://user-images.githubusercontent.com/90316/158826522-ece31559-3966-405b-bcab-58bc71f4b381.png">

And 50 OCEAN were sent into that pool upon creation:
https://rinkeby.etherscan.io/tx/0x9465e0f040323faedfa94ea0e938cab382c9a9ea60c7ba831ef2e868c6c3ee5e

So the pool transactions list at very end should include an entry `Created pool with 50 OCEAN`. This applies to pool transactions list on profile page too. Worth double checking if pool exit tx are missing too

**Comment by mihaisc** [comment]
Sub seems ok [pool tx](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20poolTransactions(where%3A%7Bpool%3A%220x7807e6ac970fd11cac8e491b711b70c5187aa9ee%22%7D)%7B%0A%20%20id%0A%20%20type%0A%7D%0A%7D&variables=%7B%0A%20%20%22account%22%3A%20%220x3e81aa994f774ee914d57946ddf2486ea7d42d65%22%2C%0A%20%20%22datatokenId%22%3A%20%220xf5ff5e6ba0424f145b81dc2261b265a728e6c522%22%0A%7D)

**Comment by AnaLoznianu** [comment]
Related issue: https://github.com/oceanprotocol/market/issues/1210
