### ISSUE TITLE
While publishing, Spanish characters make final asset inaccessible ('Could not retrieve asset') 

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1212]
**Describe the bug**
When you enter some spanish characters (spanish in my case), when you go to the asset is not accessible. You only get the "Could not retrieve asset" message.

**To Reproduce**
1. Go to 'Publish'
2. Complete all the steps using 'Básico, Básico Adultos Formal, Modalidad General, Técnico Profesional, Académicos y Artes' in the title or description
3. Complete all the transactions
4. Click on "View Asset"

**Expected behavior**
See the asset correctly

**Screenshots**
<img width="1440" alt="Screen Shot 2022-03-17 at 2 04 55 PM" src="https://user-images.githubusercontent.com/13741335/158867198-a8b93832-adfe-4ef3-b70b-27a08a95b911.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Additional context**

**DID**: did:op:b97804d3421e5d1fca7a986e376707a2c92d71b285cb0c41ceda1052968a2f38
**Network**: Polygon Mumbai
**Transactions**:
- 0xa793a10e5e6cb4c9e25fa6dd37002ee7e6c009bb42afff6cf169ea50fec8f2d6
- 0x413cca1070a09284d553924b27df1ebd8c844c4ce550daaedc47f85e251a7d86

**Comment by kremalicious** [comment]
as it looks like, any "special" (they're not special if its a user's native language) characters do this so most likely somewhere Aquarius then has problems with that

**Comment by md0x** [comment]
Probably related to https://github.com/oceanprotocol/aquarius/issues/750

**Comment by kremalicious** [comment]
The market is no Node.js app. Its build process uses Node.js, but never RUNS with Node.js but always in the browser. And on the web we specifically set the `charset` to `utf-8` no now encoding/decoding any and all user input seems completely overkill.

Again, this is first time anyone of us ever encountered this, and most of us are non-native English language speakers so we all worked on apps dealing with special characters before. Also no problem at all with v3 Aquarius & market so why should we suddenly have to encode/decode all user input in all our app?

**Comment by kremalicious** [comment]
Searched a lot but could not find any indication frontend changes something regarding charset, neither in Formik nor in React itself. Are we absolutely sure using e.g. `headers: { 'Content-Type': 'application/json; charset=utf-8' }` over in ocean.js isn't the solution?

Also over in ocean.js notice that in provider.encrypt method we have `body: decodeURI(JSON.stringify(data))`, yet on market we never `encodeURI` that data.  But not sure at all why ocean.js does that with the passed DDO `data`

**Comment by bogdanfazakas** [comment]
I'm working on a oceanjs fix for this, curently testing locally with the v4market, going to push the PR once i'll be able to have an asset with special chars indexed. using the https://www.npmjs.com/package/utf8  does not seem to be a good option since it looks it's not supporting es6

**Comment by alexcos20** [comment]
We need to compare the hash generated by ocean.js  vs hash generated by aquarius using validate endpoint.
If they are the same, we should be fine.
Otherwise, some character conversion is done somewhere on the way

**Comment by bogdanfazakas** [comment]
fixed with the 4.0.2 release of Aquarius, see asset containing spacial characters (including Spanish 😄 ) https://market-git-v4-oceanprotocol.vercel.app/asset/did:op:f152dc23dd5ac61310483828e2f8e99fd2dea7b061f3bd3e538d5dc1c5009fff
