### ISSUE TITLE
missing baseToken symbol breaks Download component

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1213]
**Describe the bug**
In Free asset: did:op:0acc800639868d472a6faffcb599c5e0a54e059d9f425dacc06a623c3a381ec4
Page breaks with error: Cannot read properties of undefined (reading 'symbol')

**To Reproduce**
1. Go to Asset with Free pricing
2. Open asset

**Expected behavior**
Should display this asset's information

**Screenshots**
DEV env
<img width="1440" alt="Screen Shot 2022-03-18 at 6 33 53 AM" src="https://user-images.githubusercontent.com/13741335/158988023-b664c154-63c5-4313-885f-1978c7c5923c.png">

Live env
<img width="1428" alt="Screenshot 2022-03-18 at 10 21 20" src="https://user-images.githubusercontent.com/13741335/158988158-7750d83f-cc5e-4a99-bf4d-3895176fc3ee.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave

**Comment by kremalicious** [comment]
this has not been fixed and is the actual reason for #1241 so this issue here should take precedence as #1241 has no info on the actual reason.

**Comment by EnzoVezzaro** [comment]
Maybe I got it wrong, but I understood that the "Collect" button was going [to be removed](https://github.com/oceanprotocol/market/issues/1222). This issue is related to a parameter on this ["Collect" button](https://github.com/oceanprotocol/market/blob/v4/src/components/Asset/AssetActions/Download.tsx#L244:L244).

**Comment by kremalicious** [comment]
well even better if #1222 solves 3 other issues but as of right now the open bugs are correct as nothing is fixed
