### ISSUE TITLE
Trade tab showing wrong balances

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1218]
### Describe the bug
Trade tab is showing that there are zero datatokens available to swap but the pool stats tab shows that there are 33.806 DTs in the pool. It says 0 Ocean in the top part - which I think should be the Ocean balance in my wallet?  I have 1,771

### To Reproduce
Have a look at the trade tab for [this asset](https://v4.market.oceanprotocol.com/asset/did:op:cf94d27ae9e0cc7a420f19884609afd76a26c5c9d0fbc1fc877235eed396f5f6) on Rinkeby

![image](https://user-images.githubusercontent.com/20739535/159240290-62968636-1b4d-4364-9e38-9e9ef1de3dc6.png)

![image](https://user-images.githubusercontent.com/20739535/159240335-50875628-439f-4a73-82cf-67ebb622911c.png)

**Comment by mihaisc** [comment]
Indeed, there are still some math issues, thus the error

**Comment by kremalicious** [comment]
what's the error in browser console? If all numbers on Trade tab are 0 then there was an error reading out your wallet and doing web3 calls to get the datatoken max value.

Corrected all mentions of "pool" in this issue and its title as it concerns the Trade tab, not the Pool tab

**Comment by mihaisc** [comment]
Apparently a bug in the subgraph, the base token liquidity is 74 instead of 73.976, will debug

**Comment by kremalicious** [comment]
new subgraph deployed, is this still an issue?

**Comment by claudiaHash** [comment]
> new subgraph deployed, is this still an issue?

Still there for me:
![Screenshot from 2022-03-23 15-29-06](https://user-images.githubusercontent.com/49017601/159710742-a3432b97-75c1-4de0-a1cc-fc849a708543.png)

I think there's a problem with computing the maximum amount for the input param

**Comment by kremalicious** [comment]
can also reproduce now, just weird not even the user balance is read out, when in other parts of UI the same thing works

<img width="580" alt="Screen Shot 2022-03-23 at 13 35 15" src="https://user-images.githubusercontent.com/90316/159711882-bdec6072-28e1-4573-be8b-0d15c57a45e9.png">

**Comment by mihaisc** [comment]
Deployed, did some tests and it's working for me now on pools that failed before.

**Comment by kremalicious** [comment]
Looks good, also working as expected now for me on https://v4.market.oceanprotocol.com/asset/did:op:bfa03dc8d250da7786f596b6098532007d3b25f5869027bf528a347984f105cc

**Comment by EnzoVezzaro** [comment]
Working for me too. Tested and everything seems alright 👍🏽
