### ISSUE TITLE
No error message for swapping more than max tokens

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1219]
### Describe the bug
There is no error message shown in the UI when trying to swap more than the maximum allowed. There is just an error in the console. Ideally there would be some form validation and a pop-up error message if people try to swap more than the maximum available datatokens.

### To Reproduce
Go to [asset](https://v4.market.oceanprotocol.com/asset/did:op:cf94d27ae9e0cc7a420f19884609afd76a26c5c9d0fbc1fc877235eed396f5f6) trade tab. Try to swap 100 Ocean tokens. An error will be shown in the console but nothing shown to the user in the UI

![image](https://user-images.githubusercontent.com/20739535/159240768-5976dc00-4644-416f-a813-b4d2c0401606.png)

**Comment by EnzoVezzaro** [comment]
Probably here there's more a communication issue. When you enter a value over the allow to spend, the UI (aka Swap button) will get disabled. It turn enabled when you enter a valid value below "maximun to spend" value.

https://user-images.githubusercontent.com/13741335/159274929-5bcc623d-739c-4b9c-b4a7-f34f1f56355f.mp4

 It happens the same if you try to over spend the datatoken. Basically, it a dynamic validation that checks every time you enter a value, but if the value is not valid it will just disabled the "Swap" button.

If the button is enabled with a value over the "Maximun to spend" this is an issue, and we need to look more into it as I couldn't replicate this. Instead, if it's more a communication issue (the user doesn 't know why the button is disabled), then we can change a little bit the UI to reflect an issue on the value entered.

**Comment by kremalicious** [comment]
just thought dumping, shouldn't a `max` attribute on that input field we fill with that max value trigger some formik error in this case?

**Comment by EnzoVezzaro** [comment]
yes, it does. It's actually validating the values correctly. When the input is over the `maximun to spend` (is also set as `max` attribute in the input field), the "Swap" button get disabled correctly (the value is getting validated). The problem is that disabling the "Swap" button doesn't seem to be enough to let know the user that his value is not allowed. 

Maybe what we can do is, besides disabling the "Swap" button, marking the input field as error field to let the user know there's something wrong with the value he entered. As an exaggeration (in my opinion is too much), we could also show an Alert banner.

**Comment by kremalicious** [comment]
> yes, it does. It's actually validating the values correctly.

ah cool, then that was my point, the bug then is that the validation rules are not output properly in the established error state, which is this as an example:

<img width="249" alt="Screen Shot 2022-03-21 at 15 13 18" src="https://user-images.githubusercontent.com/90316/159291693-e613278c-de00-46fd-a408-f183bd26c863.png">

That message is the Yup validation message, and if we have that validation in place in trade too, then that message should be shown

**Comment by EnzoVezzaro** [comment]
> > yes, it does. It's actually validating the values correctly.
> 
> ah cool, then that was my point, the bug then is that the validation rules are not output properly in the established error state, which is this as an example:
> 
> <img alt="Screen Shot 2022-03-21 at 15 13 18" width="249" src="https://user-images.githubusercontent.com/90316/159291693-e613278c-de00-46fd-a408-f183bd26c863.png">
> 
> That message is the Yup validation message, and if we have that validation in place in trade too, then that message should be shown

Yeah, you're right. I wasn't thinking about this little alerts. Cool 👍🏽 got it now, it'll be done soon then
