### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by air3ijai** [oceanprotocol/market#1227]
**Describe the bug**
Run Marketplace in development mode ignore variables from `.env` file

**To Reproduce**
Steps to reproduce the behaviour:
1. `cp .env.example .env`
2. `vi .env`
3. `METADATACACHE_URI="https://aquarius.domain.tld"`
4. `node start`
5. Open Marketplace
6.  It will point to the https://aquarius.oceanprotocol.com from `app.config.js`

**Expected behavior**
Documentation should describe how we can set environment variables in different modes and start the application

For example, in development mode we should use `.env.development` file and in production `.env.production`

> [In Gatsby you cannot work with a plain '.env' file but only with '.env.development' or '.env.production'.](https://dev.to/steeeeeph/how-to-implement-env-variables-in-gatsby-and-react-252d)

**Additional context**
https://github.com/oceanprotocol/market#-environment-variables
https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables

**Comment by kremalicious** [comment]
sorry, except for critical security issues, we are not supporting the v3 version of the market anymore whereas the `v4` version does not use Gatsby and its weird `.env` restrictions anymore
