### ISSUE TITLE
TX pending but market indicates failure on Ropsten

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1231]
Can be reproduced by trying to submit again, same outcome. https://ropsten.etherscan.io/tx/0xd706270fbeddcd06e5fc21c9e74dcdec7c5bda324fc506ae19560b7d3fc976ab
Ropsten is too slow, publish flow seems to run into some kind of timeout issue.
The TX has been reverted now, so repeating is not an option as it seems.
The process does not resume after TX came through.

https://ropsten.etherscan.io/tx/0xc1d2f9886c870254f87e5a2d453c8d46c6d72d36f9e1045dca5aee8d80c443e5
![image (1).png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/c9589e40-59d3-40da-8285-fde70e7d76bd)![image.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/82138b13-0b92-48bd-a383-f0dfa08349fd)

**Comment by kremalicious** [comment]
this might be related to #1199 as also in here we seem to be only catching the first error
