### ISSUE TITLE
Transaction popup doesn't show up

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1232]
**Describe the bug**
I’ve been waiting for 5 minutes (on Firefox) for a transaction popup to come up but still, nothing happens and in metamask, there are no pending transactions

**Expected behavior**
The transaction popup should be shown 

**Screenshots**
![Screenshot 2022-03-17 at 10 42 55](https://user-images.githubusercontent.com/84312885/159673206-23675ee8-8c61-4348-9220-c8eed0193f71.png)

**Comment by AnaLoznianu** [comment]
@LucaMilanese90 You mentioned this issue. Can you try to reproduce it again and provide the console log?

**Comment by kremalicious** [comment]
reopen if anybody is running into this again
