### ISSUE TITLE
Error when downloading asset 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1234]
Trying to download an asset with dynamic price, right after I confirmed the transaction to generate the signature to access the download url, I got this error message

![Screenshot 2022-03-17 at 11 14 02](https://user-images.githubusercontent.com/84312885/159677096-43b14389-93a7-4b95-8843-f481aca801a0.png)

Now I went back and confirmed the transaction again but the page is stuck at this loading phase (even though there are no pending transactions)
![screenshot_2022-03-17_at_11 18 31](https://user-images.githubusercontent.com/84312885/159677117-fe85b35c-c505-4618-9a99-d32fb25a9f96.png)

**Comment by kremalicious** [comment]
this is impossible to reproduce. Please provide an example asset where this happens, otherwise close issue

**Comment by AnaLoznianu** [comment]
During the testing phase, @KatunaNorbert @bogdanfazakas @md0x encountered the error described here. Can one of you offer more details?

**Comment by mihaisc** [comment]
This is not a market issue, it is a provider issue. And if i remember correctly it was fixed last week
