### ISSUE TITLE
Text input allowed for trade inputs

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/market#1238]
Text input is allowed for numeric inputs in trade tab, on **Firefox** . The error message, 'Required',  is not relevant.

![Screenshot from 2022-03-23 12-48-53](https://user-images.githubusercontent.com/49017601/159683748-8df5e1d9-45f5-4251-9549-996a977b74a9.png)

**Comment by kremalicious** [comment]
what appears to be a bug turned out to be feature of browser vendors interpreting the HTML spec and there can be many use cases where non-numbers need to be allowed, especially if decimals are involved. So introducing potential new bugs is not worth the effort for what we get out of it so closing
