### ISSUE TITLE
Issue with connecting to MetaMask wallet

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1239]
Describe the bug
An issue with connecting to MetaMask wallet:
I have registered with my MetaMask account and after I selected the virtual wallet, it didn't appear the MetaMask pop-up;
it worked after refreshing the page.

Desktop
OS: Windows 10
Browser: Chrome
Version: 99.0.4844.74 64 bit

**Comment by kremalicious** [comment]
what's the "virtual wallet"? What's the "MetaMask pop-up"?

**Comment by mihaisc** [comment]
And if you open metamask , what does it show?

**Comment by kremalicious** [comment]
From what I see what happened here is most likely either:

1. you were logged out in MetaMask which can happen multiple times a day automatically, as every automatic browser extension update will log you out of MetaMask. So then opening MetaMask and logging in again should connect you right away.
 
2. You were connected in MetaMask with an account you have not been connected before in market which upon repeated visit triggers this UI in MetaMask, which needs to be acted upon before any account can be read out by us:
  <img width="398" alt="Screen Shot 2022-03-23 at 15 03 41" src="https://user-images.githubusercontent.com/90316/159730313-cded11dd-f11d-4463-b865-5e52e4df22b0.png">

For both cases, repeat visit to market then results in "Reconnecting...." which is only there if you have connected before but we can't access any account. And for both cases MetaMask is not really helpful as there is no indication whatsoever on the toolbar icon that something is going on in the extension.
