### ISSUE TITLE
Opening the OpenSea link from the NFT preview tooltip shows the image and the correct metadata only for assets with fixed price

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1240]
Opening the OpenSea link from the NFT preview tooltip shows the image and the correct metadata only for assets with fixed price like https://testnets.opensea.io/assets/0xae5f20912e9508D8fa80AAc0dad81F027E2b1121/1 .

Free https://testnets.opensea.io/assets/0xF1E0221c7Cc4507Ce936D052cd074CFcE93080Fd/1
and dynamic https://testnets.opensea.io/assets/0x5CfF34710986e410D9a131E945332Ba31BaF6600/1) price assets don’t get recognized.

**Comment by kremalicious** [comment]
cannot reproduce.

Dynamic asset:
https://v4.market.oceanprotocol.com/asset/did:op:2c33b5fea530508a9f019a1dab89122a10b51503b7947db02513cfc6dd511f65
https://testnets.opensea.io/assets/0xF5FBa06eff6D179e31C3C17ADBe4dB7F9be84429/1

Please be aware that OpenSea takes some time to index new tokens.
