### ISSUE TITLE
A very large string will crash the application

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1242]
To Reproduce
1 visit https://v4.market.oceanprotocol.com/publish
2 Type random values in "description" field
3 Copy the text and paste as often as possible
=> Web app crashes "Application error: a client-side exception has occurred (see the browser console for more information)." (I used dark theme)

Expected
There is a max number of characters and web app does not crash
Application Error text should be in black (wrong when using dark theme)
Desktop
 - OS: MacOS 12.2.1
 - Browser: Firefox
 - Version 98.0.1 64 bit

![image (2)](https://user-images.githubusercontent.com/84312885/159717978-a219841b-f5a9-497e-a65f-e6e1d83d1b96.png)

**Comment by kremalicious** [comment]
What's "very large"? Cannot reproduce with a lot of pasting.

![Untitled](https://user-images.githubusercontent.com/90316/159708411-86bcc2b8-1d35-4c88-bf23-3bc3ac08807c.gif)

> Application Error text should be in black (wrong when using dark theme)

This is the native default Next.js error screen, we don't control this although we could but sounds like more hassle then necessary as we should simply fix the bugs making users see this error screen

**Comment by mihaisc** [comment]
Didn't create gif but you can see based on scroll bar 
![image](https://user-images.githubusercontent.com/26000280/159715345-33045b3c-6095-487e-8812-72642c6c6fd8.png)

A small possibility that i may see is that you ran out of ram and the browser thread crashed.

**Comment by AnaLoznianu** [comment]
We're limiting the description length to 5K characters. Closing this as the user will not be able to insert long description
