### ISSUE TITLE
After metadata edit the user needs to refresh the page to see the changes reflected

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1245]
The metadata cache needs some time to index the metadata updates and if you go back to the asset details page before that happens the updated values won't be reflected.

The experience is visible here: https://drive.google.com/file/d/1QCKPjfQbRh7SoNJPXNMLy1_IYZxfAxal/view?usp=sharing

Maybe we can update the user experience and provide a better experience.

**Comment by kremalicious** [comment]
From @DMats came this idea of waiting for certain amount of block confirmations, e.g. for the last tx. We could show that to user on submission screen and only after like 5 block confirmations the _View Asset_ button becomes active

**Comment by DMats** [comment]
I think block confirmations after both the "create data tokens" transaction and the "set metadata" transaction are needed to mitigate against chain reorgs. I suppose it would have the added benefit of giving aquarius more time to cache the asset.

**Comment by mihaisc** [comment]
hmm, not a bad idea, but we need to implement something at a global level in the market so we can use it on all actions

**Comment by mihaisc** [comment]
While not a bad idea, not sure how we can implement this. The effort seems a bit too much and the gains are not that big.
