### ISSUE TITLE
The download fails for assets published that are not publicly available

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1246]
The publish form allows asset publication even if the asset is not publicly reachable. This creates an issue when downloading the file. 

https://v4.market.oceanprotocol.com/asset/did:op:f66b072ec293aa76a29668df9ba7dbaf2cb0bb610f3475f8ebeebcfb731749b8

Video with the issue: https://drive.google.com/file/d/1I9lOBTEgI4iLDXh72W9rCEDQGGHgNDXJ/view?usp=sharing

**Comment by jamiehewitt15** [comment]
I think a good solution here would be to have an alert if the file that the provider receives is an HTML file e.g. "Are you sure you meant to upload an HTML file?". If the user meant to upload something else (csv, pdf, etc...) they can correct the error themselves before publishing.

I think this should stop the majority of cases where this error happens. When files are inaccessible, most file-hosting sites (Dropbox, Google Drive, OneDrive etc) will return a 404 page, which is how we end up with Html files hosted - as in this case.

**Comment by kremalicious** [comment]
> I think a good solution here would be to have an alert if the file that the provider receives is an HTML file

agreed, this is the best compromise as it's technically not feasible dealing with the unique properties of each and every way of hosting files, and then keeping this maintained too.

**Comment by kremalicious** [comment]
but I think you can simply make the file accessible later on, no? So then download should work without re-publishing? Or does Google Drive change URLs when permissions are changed?

**Comment by kremalicious** [comment]
revisiting #459 might help here too although not sure this would help in those cases where the error page html file tries to be fetched.

Cause we always hit the `/fileinfo` endpoint and almost always if we get this:

<img width="144" alt="Screen Shot 2022-03-24 at 11 08 08" src="https://user-images.githubusercontent.com/90316/159912533-4bd55a56-295d-46cf-ba55-dfef2b7f0e22.png">

it means the file is not available and we could change message here. We always hesitated to introduce a dedicated "file-is-present-and-can-be-downloaded" check as it could lead to lots of false positives as web tech for hosting is highly diverse

**Comment by jamiehewitt15** [comment]
> but I think you can simply make the file accessible later on, no? So then download should work without re-publishing? Or does Google Drive change URLs when permissions are changed? This would be preferable as now more people run into the same issue on that asset.

Did a quick test on this and the link remained the same when you change the sharing permissions on Google Drive. If it is a Google doc it still wouldn't work though, you have to publish them to the web in order for it to be downloadable (which does changes the link). THis may work differently with Dropbox and others. 

> not sure this would help in those cases where the error page html file tries to be fetched.

Yeah, the html 404 page file will always pass the file info check, that was one of the issues with the data connectivity PR that was eventually closed without merging https://github.com/oceanprotocol/market/pull/479

**Comment by mihaisc** [comment]
One drive has similar behaviour
![image](https://user-images.githubusercontent.com/26000280/160109383-3a739dff-6ef7-47a9-8af5-784ba9dcd0b1.png)
But when you download it you don't get the file 
![image](https://user-images.githubusercontent.com/26000280/160110314-273714f2-a92f-4378-991b-c14af291e29e.png)

**Comment by jamiehewitt15** [comment]
> You get a html that kinda redirects you to the file

So this would get picked up if we present the user with a notification before publishing saying "Are you sure you want to publish an HTML file"

Another possible solution to this could be to have a button on the preview page that says "Test your file is downloadable" then it's downloaded in the same way it would be by another user

**Comment by mihaisc** [comment]
How would this test work ?

**Comment by jamiehewitt15** [comment]
We could potentially just do it with fetch

**Comment by kremalicious** [comment]
mechanism is working in #1279, suggestions on exact copy welcome:

<img width="898" alt="Screen Shot 2022-03-29 at 22 16 18" src="https://user-images.githubusercontent.com/90316/160709199-fbca08f8-0a88-4799-8162-2122c77c581d.png">
