### ISSUE TITLE
Pool Tab: The "Your Locked Value" is wrongly set to 0 after a refresh 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1248]
**Describe the bug**
As you can see in this video: https://drive.google.com/file/d/1eUrzKJqsZU7PanTPvo46HRbZwIkhGtHx/view?usp=sharing, if you refresh the pool liquidity page the value will go to 0 after a few seconds and the "Remove" button will be removed as well.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 99.0.4844.74

**Comment by kremalicious** [comment]
something something interval fetching https://github.com/oceanprotocol/market/issues/1152#issuecomment-1062854164

This looks like interval is created before `accountId` or something else is not present yet, then actual fetching is correct but when interval is fired again it fetches with those initial missing values

**Comment by OceanRaymond** [comment]
Continuing on Ana's statement, if you go to home page, access the dataset again, and click on the POOL tab it will show the correct value and display the REMOVE button... until you hit REFRESH again.
