### ISSUE TITLE
Publish preview actions lead to unintended consequences

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1255]
On the publish preview interacting with various elements is possible and can lead to users loosing their publish form data as some lead away from the route/app

Solution: put `pointer-events: none` on whatever container wraps the preview. Also means the CSS we have in place for disabling the AssetActions can be removed with this change.

**Comment by mihaisc** [comment]
Bookmark button needs to be removed/disabled as well.

**Comment by kremalicious** [comment]
yes, just `.preview { pointer-events: none }` will automagically disable everything clickable on that screen.

**Comment by kremalicious** [comment]
wait, it's quicker doing this as PR than writing comments here 😀
