### ISSUE TITLE
#DAOcomms: Follow all Grantees (and eco heroes)

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/market#1259]
**## Goal:**
Increase reach and engagement of OceanDAO Twitter account

**### Recommendation:**
Follow all projects that received a grant from OceanDAO, plus relevant players in the ecosystem, outreach, institutional and other DAOs alike (Lobster, TEC, etc.)

**### DoD:**
- [ ] All grantee handles follow by OceanDAO_
- [ ] 10 DAO accounts followed

**Comment by mihaisc** [comment]
How is this related to the market? I think you might have mistaken the repo

**Comment by malvonme** [comment]
I'm sorry! Will change rn.

**Comment by malvonme** [comment]
Issue moved to [oceanprotocol/oceandao #192](https://github.com/oceanprotocol/oceandao/issues/192) via [**ZenHub**](https://www.zenhub.com/)
