### ISSUE TITLE
fix Formik context warning

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1272]
**Is your feature request related to a problem? Please describe.**
Following up on this [thread](https://github.com/oceanprotocol/market/pull/1226#issuecomment-1080727267): when you are inside an asset, formit throws this warning as there's no formit context from which calling the `useFormitContext` hook.

Message:
`Warning: Formik context is undefined, please verify you are calling useFormikContext() as child of a <Formik> component`

**Describe the solution you'd like**
We need to check dynamically and call the hook only if necessary (on preview page). The result should cleared any warning in console.

<img width="1440" alt="Screen Shot 2022-03-29 at 9 36 54 AM" src="https://user-images.githubusercontent.com/13741335/160623916-2bfa949a-2146-4953-885c-8d2e85a1d819.png">

**Comment by mihaisc** [comment]
Too much effort for something nice to have at best
