### ISSUE TITLE
add pragmatic testing

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#128]
We still have the test setup leftovers in the app so we should make them work again. So components can either have a Storybook story, or a dedicated unit test with `react-testing-library`.

So the current `npm test` _just_ needs to succeed.

Ideally we get full unit testing coverage, and ave additional integration test runs.

After this is all setup, the branch protections should be updated to not allow any regression of coverage.

Better alternative: add integration testing with Cypress as we had in Commons for the very basic user flows:

- publish
- search
- consume

This is way more valuable to catch errors

**Comment by kremalicious** [comment]
Better alternative: add integration testing with Cypress as we had in Commons for the very basic user flows:

- publish
- search
- consume

This is way more valuable to catch errors

**Comment by DimitarSD** [comment]
Moved this to progress again. I managed to connect an account. It turned out that we needed `window.ethereum` instead of `window.web3`. Web3Modal check for both but for some reason only `window.ethereum`works. 

Still trying to figure out why the `Submit` stays disabled.

**Comment by kremalicious** [comment]
reopen when we have bandwidth for it
