### ISSUE TITLE
fix `null` dt in Pool transaction history

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1285]
**Describe the bug**
Fixing issues on the transaction history list when DT is null

**Screenshot**
<img width="1439" alt="Screen Shot 2022-03-30 at 11 49 29 AM" src="https://user-images.githubusercontent.com/13741335/160877072-1b66acd3-9359-45c5-91f2-03e25981d1d0.png">

**Comment by EnzoVezzaro** [comment]
related https://github.com/oceanprotocol/ocean-subgraph/issues/394

**Comment by mihaisc** [comment]
Not a subgraph bug, it is as intended. 
We need to make sure : 
- we just fetch the tx of the user basically restore [this](https://github.com/oceanprotocol/market/commit/4a102722b7c647fb40927d52125e71d0e74d6586) 
- we don't run [this](https://github.com/oceanprotocol/market/blob/v4/src/components/@shared/PoolTransactions/index.tsx#L172) when the components is in it's minimal state
- make sure the nulls are handled properly (should already work)

**Comment by EnzoVezzaro** [comment]
> Not a subgraph bug, it is as intended. We need to make sure :
> 
> * we just fetch the tx of the user, basically restore [this](https://github.com/oceanprotocol/market/commit/4a102722b7c647fb40927d52125e71d0e74d6586)
> * we don't run [this](https://github.com/oceanprotocol/market/blob/v4/src/components/@shared/PoolTransactions/index.tsx#L172) when the components is in it's minimal state
> * make sure the nulls are handled properly (should already work)

I think there's still something wrong on the subgraph side. If we add the userId like [this](https://github.com/oceanprotocol/market/commit/4a102722b7c647fb40927d52125e71d0e74d6586) then the call results are empty, [example](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xfb2b24e77091206ca408e8e51449050d4b047d68%22%2C%0A%20%20%20%20%20%20user%3A%20%220xb2b4037cbdec699c6894290df36d9a6a2063def1%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A). By removing the userId, I get [correct results](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xfb2b24e77091206ca408e8e51449050d4b047d68%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A) but inconsistent. 

For example: 
- This query with [user](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xfb2b24e77091206ca408e8e51449050d4b047d68%22%2C%0A%20%20%20%20%20%20user%3A%20%220xb2b4037cbdec699c6894290df36d9a6a2063def1%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A) = `"poolTransactions": []`
- Same query [without user](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xfb2b24e77091206ca408e8e51449050d4b047d68%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A):  returns values as expected with datatoken
- Another [network's query with user](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24user%3A%20String%2C%20%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xdf23f986e697645324593beab8269ac8aa62c3d2%22%2C%0A%20%20%20%20%20%20user%3A%20%220xb2b4037cbdec699c6894290df36d9a6a2063def1%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A): returns values but all the results are missing the datatoken
- Another [network's query without user](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24user%3A%20String%2C%20%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7Bpool%3A%20%220xdf23f986e697645324593beab8269ac8aa62c3d2%22%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A): returns values but some of them are missing the datatoken.

These inconsistencies are weird, specially when we add the user (which might be the reason why it was removed). The fact is that without having the datatoken information we can't do these lines of code: [L173](https://github.com/oceanprotocol/market/blob/fix/issue-1285-null-dt-pool-history/src/components/@shared/PoolTransactions/index.tsx#L173:L173), [187](https://github.com/oceanprotocol/market/blob/fix/issue-1285-null-dt-pool-history/src/components/@shared/PoolTransactions/index.tsx#L187), [L183](https://github.com/oceanprotocol/market/blob/fix/issue-1285-null-dt-pool-history/src/@utils/aquarius.ts#L183:L183). That are necessary to display correctly the transaction history. In our use case we need to take care of the datatoken being `null` then we might need to refactor this [whole function](https://github.com/oceanprotocol/market/blob/fix/issue-1285-null-dt-pool-history/src/@utils/aquarius.ts#L173). 

Do you think is fixable these datatoken (datatoken object information) being `null`?

**Comment by mihaisc** [comment]
Does that user have transactions? And you don't need all the transactions, the component is supposed to show the users transactions. I'll take a look

**Comment by EnzoVezzaro** [comment]
> Does that user have transactions? And you don't need all the transactions, the component is supposed to show the users transactions. I'll take a look

Here is a [first implementation](https://github.com/oceanprotocol/market/tree/fix/issue-1285-null-dt-pool-history) after restoring the user in the graphql call. On this example, my user has a bunch of tx but they all missed the datatoken, so the final result is an empty result (because of the lines above).

**Comment by mihaisc** [comment]
Because on exit and join we only add/remove base token , the datatoken is added/removed by the ss bot so it doesn't appear there. I'll handle it , pool is already fixed, thinking about some minor refactoring for the profile transactions

**Comment by EnzoVezzaro** [comment]
Ok great. What did you do to fix the pool? It will help me understand better this flow as I can see on [this query](https://v4.subgraph.mumbai.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?operationName=TransactionHistoryByPool&query=query%20TransactionHistoryByPool(%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%20%20pool%3A%20%220xfb2b24e77091206ca408e8e51449050d4b047d68%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A) a `JOIN` type with a datatoken. Maybe it was an old implementation?

**Comment by mihaisc** [comment]
Like i said, just added user to the query and stopped fetching the assets when the components is in minimal state. 
When it is not in minimal i fixed how we fetch the data from aquarius and then added the datatoken from the pool so we have it's address consistantly.

**Comment by EnzoVezzaro** [comment]
> fix pool tx #1288

oh I see now. I din't though about getting the datatoken from the pool. Seems reasonable, testing now
