### ISSUE TITLE
pool creation tx show 0 tokens and datatoken

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1291]
Like so:

<img width="1081" alt="Screen Shot 2022-03-31 at 12 45 44" src="https://user-images.githubusercontent.com/90316/161047769-ced3c6a1-720c-45d1-ac46-e7a272434389.png">

Checking out this account's many tx:
https://v4.market.oceanprotocol.com/profile/0xb2B4037CbdEc699c6894290DF36D9a6a2063def1

Expectation:

`Create pool with xxx OCEAN`

**Comment by mihaisc** [comment]
Not a market issue  :[ sub query](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20TransactionHistoryByPool(%24user%3A%20String%2C%20%24pool%3A%20String)%20%7B%0A%20%20poolTransactions(%0A%20%20%20%20orderBy%3A%20timestamp%0A%20%20%20%20orderDirection%3A%20desc%0A%20%20%20%20where%3A%20%7B%0A%20%20%20%20%09pool%3A%20%220x81c4efb0692d2e7ee3428f7c8caca6564f48dc3c%22%2C%0Auser%3A%20%220xb2b4037cbdec699c6894290df36d9a6a2063def1%22%0A%20%20%20%20%7D%0A%20%20%20%20first%3A%201000%0A%20%20)%20%7B%0A%20%20%20%20baseToken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20baseTokenValue%0A%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20address%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20datatokenValue%0A%20%20%20%20type%0A%20%20%20%20tx%0A%20%20%20%20timestamp%0A%20%20%20%20pool%20%7B%0A%20%20%20%20%20%20datatoken%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D%0A) i'll check out what's going on
