### ISSUE TITLE
Author field is mandatory in publish, but is not in edit asset

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1296]
**Describe the bug**
The Author field is mandatory during the publish flow, but it's not during edit. I think they both should be mandatory.

**To Reproduce**
1. Go to Asset
2. Click on Edit
3. Clear "Author" field
4. Save

**Expected behavior**
The submit button in edit should stays disabled is the author field is not valued.

**Screenshots**

Publish:
<img width="1440" alt="Screen Shot 2022-04-01 at 5 49 25 AM" src="https://user-images.githubusercontent.com/13741335/161240398-0d8b84da-326a-47a8-b20a-f28a70ccc83a.png">

Edit: 
<img width="893" alt="Screen Shot 2022-04-01 at 5 49 15 AM" src="https://user-images.githubusercontent.com/13741335/161240457-e58add02-c675-44e0-94dd-731eb90a8e45.png">

**Comment by kremalicious** [comment]
this is a feature, see https://github.com/oceanprotocol/market/pull/763#issuecomment-891623094

**Comment by jamiehewitt15** [comment]
It is a bit odd that it's required in one place but not the other, maybe it doesn't need to be mandatory in the publish form?
