### ISSUE TITLE
"transaction underpriced" error on Trade

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1300]
**Describe the bug**
when i try to approved the tokens, the tx fails (without letting the user know) with an "transaction underpriced" error in console. This is happening only with assets on Mumbai

**To Reproduce**
1. Go to Asset (any in the mumbai network)
2. Click on Trade
3. Approve some tokens
4. See error in console

**Expected behavior**
Fix the error and If it fails should notify the user

**Screenshots**

https://user-images.githubusercontent.com/13741335/161257449-3cb32cdb-ca6d-4bb0-b9f7-30d5cecc5951.mp4

**Comment by mihaisc** [comment]
i never saw this error before

**Comment by EnzoVezzaro** [comment]
could be something on infura? I wander if this morning's change has something to do with it. I'm investigating.

**Comment by EnzoVezzaro** [comment]
> From the logs it's an rpc error

Still facing this. What's worse is that is happening to me on all operations in mumbai, with all my accounts. For example, this is another user with a different wallet and on a different browser:

https://user-images.githubusercontent.com/13741335/161521508-67c9722c-91b2-459f-bcbb-70739e845771.mp4

@mihaisc Do you have any idea why I'm experiencing this issue? I have tried so far:
- Unistall / Reinstall Metamask extension
- Increase Gas Fees on Metamask (as suggested)
- Change browser, account, etc...

None of this have solved my issue. I can't access any asset on Mumbai at the moment because of this, sure looks like a RPC issue, but I haven't been able to overcome this.

**Comment by kremalicious** [comment]
Which RPC are you using? Generally better not using any default one for Polygon as they are constantly overcrowded. E.g. create account on https://rpc.maticvigil.com/ and use your own account RPC then

**Comment by EnzoVezzaro** [comment]
> Which RPC are you using? Generally better not using any default one for Polygon as they are constantly overcrowded. E.g. create account on https://rpc.maticvigil.com/ and use your own account RPC then

I was actually using Metamask on [V4 Market](https://v4.market.oceanprotocol.com/asset/did:op:c2a31770d4e6a8fde05a8a90e30fa98b35443b21f7ef155baedd2cd0a5fb3fe8) directly like (I believe) most of our users. 

Ok, I'll try that

**Comment by EnzoVezzaro** [comment]
> > Which RPC are you using? Generally better not using any default one for Polygon as they are constantly overcrowded. E.g. create account on https://rpc.maticvigil.com/ and use your own account RPC then
> 
> I was actually using Metamask on [V4 Market](https://v4.market.oceanprotocol.com/asset/did:op:c2a31770d4e6a8fde05a8a90e30fa98b35443b21f7ef155baedd2cd0a5fb3fe8) directly like (I believe) most of our users are.
> 
> Ok, I'll try that

It worked.  It'a a RPC issue related to an unreachable RPC URL configuration (I was using https://chainstacklabs.com and their endpoint seems [down](https://matic-mumbai.chainstacklabs.com)).

Issue closed.
