### ISSUE TITLE
incorrect wallet balance on trade tab

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1301]
**Describe the bug**
The balance shown in the trade tap doesn't reflect what actually on the wallet. 

These assets on mumbai are not correct: 
- https://v4.market.oceanprotocol.com/asset/did:op:c2a31770d4e6a8fde05a8a90e30fa98b35443b21f7ef155baedd2cd0a5fb3fe8
- https://v4.market.oceanprotocol.com/asset/did:op:84577212e4b8c1ce4a46e43360e45c6b9904e0eb366cacbad25a8a09cb66e2c2

These assets on rinbeky have the correct amount:
- https://v4.market.oceanprotocol.com/asset/did:op:bfa03dc8d250da7786f596b6098532007d3b25f5869027bf528a347984f105cc
- https://v4.market.oceanprotocol.com/asset/did:op:f66b072ec293aa76a29668df9ba7dbaf2cb0bb610f3475f8ebeebcfb731749b8

~Maybe it's related just to mumbai, but I'm still investigating~

**To Reproduce**
1. Go to Asset
2. Click on Trade tab
3. See amount balance (& other numbers)

**Screenshots**

Wrong:
<img width="1440" alt="Screen Shot 2022-04-01 at 9 30 03 AM" src="https://user-images.githubusercontent.com/13741335/161274590-43c5c1bc-257a-45c9-9663-04db19046173.png">

Correct:
<img width="1440" alt="Screen Shot 2022-04-01 at 9 39 07 AM" src="https://user-images.githubusercontent.com/13741335/161274810-35f7930e-1207-4216-885c-f4305350bdd4.png">

Some issue on rinkeby too:

- https://v4.market.oceanprotocol.com/asset/did:op:f66b072ec293aa76a29668df9ba7dbaf2cb0bb610f3475f8ebeebcfb731749b8

<img width="1440" alt="Screen Shot 2022-04-01 at 9 42 15 AM" src="https://user-images.githubusercontent.com/13741335/161275602-d3384e69-1de6-443f-8447-32d6de8eb928.png">

**Comment by mihaisc** [comment]
Not related to mumbai
![image](https://user-images.githubusercontent.com/26000280/161275894-335278e8-40f4-4e41-8782-fe4a4e676ea0.png)
