### ISSUE TITLE
Pool statistics not working when no wallet connected

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1311]
https://market.oceanprotocol.vercel.app/asset/did:op:091102da55a2648501758e6c202dffe7131ac423c670a274f22594808c9ea522

**Comment by kremalicious** [comment]
yeah, we stop everything in `fetchAllData()` in pool context when no `accountId` is found for whatever reason. So easy fix

**Comment by EnzoVezzaro** [comment]
added PR in case we decided to make this change before the rest 👍🏽
