### ISSUE TITLE
Confusing experience with the 'timeout' field in the publish form

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1313]
When publishing an asset, is not very visible that the timeout field is a mandatory field. 
After adding the file URL, is a bit confusing why the user cannot move to the next steps using the continue button. It gives the impression that he needs to submit a sample file, although that field is not mandatory.
Maybe we can highlight what the missing field is.

![Screenshot 2022-04-05 at 10.23.47.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/30160295-a247-42e0-89f9-cc27a20f7cb2)

**Comment by kremalicious** [comment]
> Maybe we can highlight what the missing field is

But when? We just can't show the error states all the time. But this is the reason in ideal case there should be no disabled buttons, but users need to be able to trigger the error state. So all buttons are enabled by default and clicking them triggers the validation and would highlight fields which are missing with our existing error state. So this has to be changed for whole form

**Comment by jamiehewitt15** [comment]
This will only really affect users who are rushing through without considering what each field means. I'm sure there are users who take that approach on testnets, but on mainnet you would expect someone to enter a value here. 

A simple solution would be for the timeout field to have a default value that is valid, e.g. it's set to "forever" by default unless it's changed.

The ideal solution is what Matthias is suggesting - the error state is triggered when the user clicks continue.

**Comment by mihaisc** [comment]
Default value is actually worse i think. Yes what Matthias suggested is the right way (we knew about this for a long time) but how is this different from Title for example? We have exactly 4 fields on the page ... how low ones attention span needs to be?
![image](https://user-images.githubusercontent.com/26000280/161771534-b18e9446-a822-49c3-a34b-c3b60fbdd17c.png)

**Comment by jamiehewitt15** [comment]
Yeah, I agree. Someone publishing a serious dataset (not just a test) would pay attention to each field. 

Another minimal effort change would be to play around with the placeholder text. Maybe it's more obvious the user needs to enter something if it's blank rather than with the dashes ---

![Timeout placeholder text - 2022-04-05_17-26](https://user-images.githubusercontent.com/20739535/161776761-fd6cf48b-e472-434b-b84b-d71dfb8ad8c4.png)

**Comment by mihaisc** [comment]
Hmm, might work
