### ISSUE TITLE
NFT metadata not showing up on OpenSea

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1330]
Our NFTs are missing a read out of our metadata on OpenSea, not sure since when, and not sure if this is just an OpenSea indexing problem where they may only decode full metadata in testnets for some NFTs. But we had this working, only change done was the `viewBox` addition in #1247 which should have not affected this.

<img width="1362" alt="Screen Shot 2022-04-06 at 15 11 06" src="https://user-images.githubusercontent.com/90316/161994623-5090c6a5-d762-473d-9bcc-c15e0d6750d7.png">

Already decoded some `tokenURI` directly to see if we have some syntax error or anything but couldn't find anything suspicious.

But might still be on OpenSea's side, case in point, as I wanted to screenshot the state of our current NFTs on there I got after a reload:

<img width="1217" alt="Screen Shot 2022-04-06 at 15 03 32" src="https://user-images.githubusercontent.com/90316/161992925-5425c20f-ea7a-4477-bce8-452e825e8ae7.png">

**Comment by alexcos20** [comment]
On etherscan appears to be fine:  https://rinkeby.etherscan.io/token/0x1a880dbd3bea1ab77c3c82a6f512ac66c36ddddc

will dig more

**Comment by alexcos20** [comment]
I triggered an update on opensea and now it looks good:

https://testnets.opensea.io/assets/0x1a880dbd3bea1ab77c3c82a6f512ac66c36ddddc/1


![Ocean Asset NFT - Ocean Asset NFT - 92G3TZ6ass _ OpenSea - Google Chrome 4_8_2022 8_19_12 AM](https://user-images.githubusercontent.com/7489447/162369872-653ddd41-fd6c-446a-9c95-ea674c16d80e.png)

**Comment by alexcos20** [comment]
also, saw a bunch of other tokens published by the same address:

https://testnets.opensea.io/0x491aecc4b3d690a4d7027a385499fd04fe50b796

if you go one by one and trigger "refresh" button, opensea will queue them for update and they will be available in about one minute.

**Comment by mihaisc** [comment]
can confirm it works flawlessly with refresh

**Comment by EnzoVezzaro** [comment]
can also confirm it works with the refresh button

**Comment by kremalicious** [comment]
phew, crisis averted. So looks like OpenSea does not decode and index `tokenURI` by default anymore, still hoping they only do this on testnets. So for time being, we can only tell people to hit that refresh button
