### ISSUE TITLE
`key` props warning in Footer links

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1332]
**Describe the bug**
React is trowing some warning because the `key` prop is missing in loop

**Screenshots**
<img width="1440" alt="Screen Shot 2022-04-06 at 11 18 49 AM" src="https://user-images.githubusercontent.com/13741335/162009800-8e043b8c-58ec-41f8-828b-3ac7ca424bdd.png">

**Comment by kremalicious** [comment]
my bad, forget them on the iterating footer links. I like how React says warning but spits it as an error

**Comment by EnzoVezzaro** [comment]
> my bad, forget them on the iterating footer links. I like how React says warning but spits it as an error

yeah 😂 that's the first thing I noticed, it's Bold "Red" Warning 😂 pushed PR to fix it #1333
