### ISSUE TITLE
Excessive contract calls

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1336]
When on asset details, it looks like to calculate the final price, we do about 15 `POST` requests to infura when looking at browser networks tab. That seems excessive.

**Comment by mihaisc** [comment]
Not a market bug, it's a ocean.js bug. We fetch multiple times the number of decimals and other redundant stuff

**Comment by kremalicious** [comment]
oh boy, I mean if our Infura account can take it, fine. UX would be better with less calls though, as the final price coming in can take quite some time. Would it be worth moving this issue over to ocean.js or would that require too much of a refactor over there?

**Comment by mihaisc** [comment]
yes for both questions 😆  It is worth having there, and a proper refactor would take some time.
