### ISSUE TITLE
Kill input type="number"

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1345]
We already found many problems with it in our interface but the list just goes on:
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

Especially, value change when field is focused and scrolling happens is something which could lead to unintended values being sent, as we do not display e.g. amount of OCEAN again in the preview.

Gov.uk design team's proposed solution should be implemented, so make our `Input` component spit out this markup when we define a number input in the form data files:

```html
<input type="text" inputmode="numeric" pattern="[0-9]*" />
```

Then see how Yup validation behaves with that and possibly adapt. We might be able to ditch the `pattern` part depending on for which exact version of iOS this is a fallback for.

**Comment by mihaisc** [comment]
Are we really going to spend time on this?

**Comment by kremalicious** [comment]
nope, think we only have one number input left so not worth it
