### ISSUE TITLE
No validation error message displayed on edit form 

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/market#1365]
No validation error message is displayed in edit form when changing input content, although the `Submit` button remains disabled:

![Screenshot from 2022-04-27 13-50-24](https://user-images.githubusercontent.com/49017601/165502672-683f9bf3-1505-46ef-bbce-3962041ef179.png)

**Comment by jamiehewitt15** [comment]
Interesting, we had the form validation working for the edit form in the V3 market
