### ISSUE TITLE
Remove "Risks" view from the pool and trade tabs

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1369]
Currently, in both the pool tab and the trade tab we are linking to an outdated 2020 [article](https://blog.oceanprotocol.com/on-staking-on-data-in-ocean-market-3d8e09eb0a13) about the risks of rug pulls (which we're claiming to have solved). 

We need something new to link to here. Either in the docs, somewhere in the market, or elsewhere.

Trade tab:
![Risks 1 - 2022-04-28_13-56](https://user-images.githubusercontent.com/20739535/165737941-32887c9d-2f65-401a-994e-a1bcd9c2c039.png)

Pool tab:
![Risks 2 - 2022-04-28_13-56](https://user-images.githubusercontent.com/20739535/165737967-7da665f4-a6c9-4059-a978-644a20dc95f8.png)

**Comment by jamiehewitt15** [comment]
I think it makes sense to have the new section on risks to sit within the docs so I've made an [issue](https://github.com/oceanprotocol/docs/issues/976) on that repo. All we need to do here is update the link when we have a new section to link to

**Comment by AnaLoznianu** [comment]
Let's remove this banner.
