### ISSUE TITLE
Liquidity doesn't update correctly

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1372]
**Describe the bug**
After adding liquidity, your balance doesn't get updated and it's not reflected in the Pool tab.

**To Reproduce**
1. Go to 'Asset'
2. Click on Pool'
3. Add liquidity

Asset: https://v4.market.oceanprotocol.com/asset/did:op:4f3dcfb883376d1ff8c2a31270485cbd1f65fe3aeab7a6f50a1f7bfff5e3314e
Network: Rinkeby

**Screenshots**

https://user-images.githubusercontent.com/13741335/165926705-93ec7a45-1ec2-48ef-be8e-cce372452417.mp4

https://user-images.githubusercontent.com/13741335/165926726-ffefc635-3f7d-4615-b034-c02376936794.mp4

Transactions: 
- https://rinkeby.etherscan.io//tx/0x3186ad33956b9b47abd1a281e31cc81fa7a5a9a675e5980061422dbade77df71
- https://rinkeby.etherscan.io//tx/0x6e4d9a984e9c357aa94cc383c59e237ae4e62683308e32d3a54cc59da54797d4

**Comment by mihaisc** [comment]
It's a caching issue with urlq 
![image](https://user-images.githubusercontent.com/26000280/165937125-8e7947da-fada-49c8-afb5-20c4bf83e8ef.png)
![image](https://user-images.githubusercontent.com/26000280/165937158-8432c6f0-e5ae-48aa-a97c-a9f1a6470a8e.png)

**Comment by EnzoVezzaro** [comment]
I see. We already worked on this, right? If I'm not mistaken, there was a PR related to urlq and caching, but I can't find it. It would help us understand what was done.

**Comment by EnzoVezzaro** [comment]
> It's a caching issue with urlq ![image](https://user-images.githubusercontent.com/26000280/165937125-8e7947da-fada-49c8-afb5-20c4bf83e8ef.png) ![image](https://user-images.githubusercontent.com/26000280/165937158-8432c6f0-e5ae-48aa-a97c-a9f1a6470a8e.png)


I see. We already worked on this, right? If I'm not mistaken, there was a PR related to urlq and caching, but I can't find it. It would help us understand what was done.
