### ISSUE TITLE
Price in edit view is not reflected correctly

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1374]
**Describe the bug**
I tried changing the price on this [asset](https://v4.market.oceanprotocol.com/asset/did:op:462ff6f02e0dec7853dacf1833189f2d1c18a72098c1afa2cd57028224107ee3)

In edit we show the previous price instead of the new one.

**To Reproduce**
1. Go to Asset
2. Edit Price and save
3. Reopen edit and See Edit Form (the price is the old one)

**Screenshots**
![Screen Shot 2022-05-03 at 6.48.05 AM.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/5bb9fbf4-1fd3-40c2-862c-27130939bc26)

On Edit: 
![Screen Shot 2022-05-03 at 6.48.11 AM.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/14830b3c-7a4d-4960-a269-43c6fce79cda)

**Comment by mihaisc** [comment]
From what i can see you are not testing on the compute branch .

**Comment by EnzoVezzaro** [comment]
> From what i can see you are not testing on the compute branch . If this happens on non compute related assets then it's a bug, otherwise close it

It actually does. [This asset](https://v4.market.oceanprotocol.com/asset/did:op:f8730af159b51790570373a2bc4acce90062844448814b834879a179f0897aac) for example is a dataset. Right now, I changed the price to 20 Oceans, but on edit I still see 10 Oceans. I changed the price 3 times, but in edit the price is always the initial price.

<img width="1440" alt="Screen Shot 2022-04-29 at 7 51 07 AM" src="https://user-images.githubusercontent.com/13741335/165939102-e764567a-4384-4ba3-87e9-ee755976d2a0.png">

**Comment by jamiehewitt15** [comment]
I tried to test this out but now I'm finding that I can't edit any assets that I've published 🤔

Created a separate issue for that here: https://github.com/oceanprotocol/market/issues/1376

**Comment by kremalicious** [comment]
did you reload any page at any point in time, or are are you waiting for numbers to update during normal session browsing?

**Comment by EnzoVezzaro** [comment]
> did you reload any page at any point in time, or are are you waiting for numbers to update during normal session browsing? Is there still a price mismatch after editing and then reloading app? We need to be clearer in issue reports like this. We know we have issues with auto-updating numbers which includes browsing between screens, so please always say under what circumstances exactly something didn't update.

In my case, we are getting the old value when editing even after reloading the page. In this video you can see clearly the issue.

https://user-images.githubusercontent.com/13741335/166216473-36b3505b-4e55-402a-afd5-c9359473c010.mp4

PS: found another bug, if you reload the page when editing, the market crashes. See [issue](https://github.com/oceanprotocol/market/issues/1379)

**Comment by jamiehewitt15** [comment]
Yeah, on some occasions the edit page shows the old price for a while (several minutes) after it has been changed. I don't think this is actually a bug though, it's just a bit slow. The price that's used as the placeholder is coming from Aquarius which can take a bit of time to update, so I also don't really see this being a front end issue

**Comment by EnzoVezzaro** [comment]
> Yeah, on some occasions the edit page shows the old price for a while (several minutes) after it has been changed. I don't think this is actually a bug though, it's just a bit slow. The price that's used as the placeholder is coming from Aquarius which can take a bit of time to update, so I also don't really see this being a front end issue

On my end, it happens all the time. If I go to edit, I always see the old price. I can see the correct price on edit only if i refresh the page inside the edit form (on this [PR](https://github.com/oceanprotocol/market/pull/1380) because otherwise it crashes. See separated [issue](https://github.com/oceanprotocol/market/issues/1379)). Every time I go to edit, I see the old price.

https://user-images.githubusercontent.com/13741335/166239820-8994dbea-9cf7-4f77-9aff-21ff721dd92f.mp4

**Comment by jamiehewitt15** [comment]
Tested again and it seems that there aren't any failed requests and the price is received correctly. After refreshing the edit page, Asset context logs the price as 30 (which is correct), but the edit page still shows the price as 10.

![Wrong price shown - 2022-05-03_12-41](https://user-images.githubusercontent.com/20739535/166433246-86f9a075-bdf8-4868-9760-0275a0822b1b.png)

**Comment by EnzoVezzaro** [comment]
> Tested again and it seems that there aren't any failed requests and the price is received correctly. After refreshing the edit page, Asset context logs the price as 30 (which is correct), but the edit page still shows the price as 10.
> 
> ![Wrong price shown - 2022-05-03_12-41](https://user-images.githubusercontent.com/20739535/166433246-86f9a075-bdf8-4868-9760-0275a0822b1b.png)

yeah, there's something happening with the requests. Since like we get 1 request with the old data and the other ones with the correct value. The UI just need to update, but i'll try to see if we could do something about the request. It's probably a cache problem or something similar.

<img width="1440" alt="Screen Shot 2022-05-03 at 5 53 32 AM" src="https://user-images.githubusercontent.com/13741335/166436682-8eced60c-19b5-43a1-b6cf-c6bcae4beccd.png">
