### ISSUE TITLE
Show compute results and logs in UI instead of having to download them

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1381]
**Is your feature request related to a problem? Please describe.**
I think we should develop a component to visualized the compute results and logs directly in the UI instead of having to download them every time (if I'm not misinterpreting our UI).

**Describe the solution you'd like**
I propose adding a "View" label next to the download buttons (or somewhere else) which pressed would show a code block with the result (or logs). Right now, we need to download the file to see the result which is ok for now, but I think this is an UX improvement we can easily implement after the public testing phase.

<img width="938" alt="Screen Shot 2022-05-02 at 7 26 00 AM" src="https://user-images.githubusercontent.com/13741335/166227387-6db6b49d-b0f2-4971-9e55-9d56e2ce9a0d.png">

**Comment by mihaisc** [comment]
Not really practical. The result of the compute is a dataset that you want to download and use. Just viewing it doesn't have that much value.

**Comment by mihaisc** [comment]
This might make sense at a future time when we have some concrete use cases.
