### ISSUE TITLE
Stucked loader spinner on assets with no price

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1384]
**Describe the bug**
I found that the assets with no price are not loading correctly in the homepage, as well as presenting some issues on the details page.

**To Reproduce**
1. Go to Homepage
2. Click on any asset with the stucked loader spinner
3. Open console

**Screenshots**
<img width="1440" alt="Screen Shot 2022-05-03 at 6 39 43 AM" src="https://user-images.githubusercontent.com/13741335/166442804-207c1753-1c7c-4ba1-982b-3d63b94c3ad5.png">

<img width="1440" alt="Screen Shot 2022-05-03 at 7 07 48 AM" src="https://user-images.githubusercontent.com/13741335/166442826-425e31b7-fd99-4cd9-aa2f-bc4436318fdc.png">

**Comment by EnzoVezzaro** [comment]
it seems a problem on the NFT creation process. All assets with emojis in the title, have no NFT image or metadata. Probably something is failing on the publish side.

**Comment by jamiehewitt15** [comment]
There isn't a problem with assets showing emojis. If you check the DDO for those assets you'll find an almost empty `accessDetails` object. 

```JSON
  "accessDetails": {
    "publisherMarketOrderFee": "0"
  }
```

**Comment by jamiehewitt15** [comment]
I would actually propose that we hide assets that don't have prices. They create clutter and make the browsing experience worse. A bit like if you went on Amazon and a load of products were missing prices. If someone wants their asset to be shown on Ocean Market they are welcome to add a price

**Comment by mihaisc** [comment]
You can't hide them now, and we don't plan on this for now. It would imply either a hacky and bad UX on front end or significant more dev on backend

**Comment by kremalicious** [comment]
never happened for any new assets so considering this solved across the stack somewhere
