### ISSUE TITLE
wrong ENS name if account owns multiple ENS names

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1388]
When using an account which has multiple ENS names registered under its account, we show one of them, but not the actual reverse record.

- account 0xf50f267b5689b005fe107cfdb34619f24c014457
- has `kremalicious.eth` set as reverse record
  <img width="830" alt="Screen Shot 2022-05-05 at 12 06 19" src="https://user-images.githubusercontent.com/90316/166911059-d55f573f-3087-4eb0-b9ae-af6c6ca59fd9.png">

- some other ENS domain shows up instead, one which is owned by this account, but is not set as reverse record:
  <img width="588" alt="Screen Shot 2022-05-05 at 12 00 01" src="https://user-images.githubusercontent.com/90316/166910612-0023023d-39ff-42a3-ad65-875b895bfda0.png">

### Expectation

Only the ENS name which is set as reverse record for an address is displayed.

### Possible solution

For performance reasons we query an ENS subgraph, this might only hold infos about registered domains for an account, but not for its actual reverse record. Look if this is actually possible with this implementation.

Alternatively, replace this mechanism with the commented out code which does actual blockchain query to find and verify reverse record.

**Comment by mihaisc** [comment]
Create a small backend to cache this?
