### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by LoznianuAnamaria** [oceanprotocol/market#1398]

**Comment by kremalicious** [comment]
what needs to be done to close this? For testing there needs to be a goal, like coverage of at least 80% of the codebase. Then `80% test coverage` can be a milestone in itself as we always don't really do anything with those epic issues here on GitHub.

**Comment by AnaLoznianu** [comment]
@kremalicious Together with @EnzoVezzaro and @claudiaHash we've compiled a list of unit tests we need to add and divided them into separate issues. Hence this Epic gathers all of them together.
