### ISSUE TITLE
coverage reporting not working

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1409]
Our `coverage` job runs successfully but with weird values in the end (we don't use `yarn`):

<img width="437" alt="Screen Shot 2022-05-09 at 14 47 57" src="https://user-images.githubusercontent.com/90316/167425306-e86f2db7-494d-420e-a41b-14d0fcc18250.png">

In any case, no coverage is reported anywhere, neither on CodeClimate or in console or wherever, and goal is to have something show up, which then also gives us coverage diff comments on all PRs.

<img width="482" alt="Screen Shot 2022-05-09 at 14 54 52" src="https://user-images.githubusercontent.com/90316/167425700-05014710-32da-4d63-b696-1c9e36c2868b.png">

Another ting worth trying is to generate coverage in the `coverage` job, as the multiple overwrites of our coverage artifacts (because `npm test` runs as matrix multiple times, also uploading artifacts multiple times) might lead to problem here.

**Comment by kremalicious** [comment]
this is how it should look like, from [one of my own projects](https://github.com/kremalicious/portfolio/runs/6341173734?check_suite_focus=true).

<img width="714" alt="Screen Shot 2022-05-09 at 18 48 05" src="https://user-images.githubusercontent.com/90316/167467762-fc78d4bb-3b81-4ae7-bca0-816dbaca22ff.png">

Also seems we are using slightly older version of that action, maybe what we encounter was a bug in older version of action

**Comment by EnzoVezzaro** [comment]
> bumped to v2.7.5 over in #1415 and right away getting actual error:
> 
> <img alt="Screen Shot 2022-05-10 at 14 26 28" width="1117" src="https://user-images.githubusercontent.com/90316/167639344-3f5552f7-dd3b-4e76-9b02-4ec05bc93a40.png">
> 
> Update: never mind, we ran into this already as it looks like

Yes, exactly. This is the reason why we decided to downgrade it, but it might be actually related somehow. It would be great anyway to move this to the lastest (as today [v3.0.0](https://github.com/paambaati/codeclimate-action/releases))

**Comment by kremalicious** [comment]
first step, we now have correct coverage reporting in the console with #1415:

<img width="577" alt="Screen Shot 2022-05-10 at 15 41 01" src="https://user-images.githubusercontent.com/90316/167655546-329c4a00-dd94-454b-a5af-4d07b21615e8.png">

Now we finally have visibility into what's covered and what's not. Cause in the end we most likely do not need to create stories or test files for all components for pure rendering tests. Like, I setup Button & Alert stories alone which already gives 100% coverage for the Markdown component. So unless we want to further test interaction, there would be no need to create dedicated Markdown test. 

The rule is that every component should be 100% covered, not every component having a test file. So first step in following this rule is to get visibility into actual coverage. Sending to CodeClimate is the cherry on top as that gives us nice insights and PR comments, but this is simply a replication of what we now see in console, or when checking out `coverage/` folder locally

**Comment by kremalicious** [comment]
practical example for deciding if additional test file should be created, and what to use it for: https://github.com/oceanprotocol/market/pull/1415#issuecomment-1122711497

**Comment by kremalicious** [comment]
and going back to sending coverage reports to CodeClimate, I now get a completely new error after all the latest changes over in #1415, that external action is really a pain to use. Again, can just download the artifacts on each test run and all is fine, that action just does not want to upload.

<img width="946" alt="Screen Shot 2022-05-10 at 19 18 03" src="https://user-images.githubusercontent.com/90316/167696027-d89e4211-db9d-43b6-b8e4-9e6f9f84527a.png">
