### ISSUE TITLE
Sample field in edit form not working as expected

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1411]
**Describe the bug**
The `sample file` field in the edit form doesn't show the current value of the link property. This field is always empty when you enter the form. If there's a sample file uploaded, the field should reflect that.

**To Reproduce**
1. Go to Owned asset
2. Click on Edit
3. Scroll down to Sample
4. if the asset doesn't have a sample, add a sample and save 
5. Click again on Edit
6. the Sample field is empty again

**Screenshots**

https://user-images.githubusercontent.com/13741335/167446415-d57e2d20-3dcc-4d75-9843-03470e3843f5.mp4

**Comment by EnzoVezzaro** [comment]
is this necessary? at the moment we don't show the current file and sample file in edit page. Probably is ok the way it is, but I want to make sure. 

Current state:

![Screenshot 2022-07-11 at 11 00 22](https://user-images.githubusercontent.com/13741335/178295150-5e920ac2-ce01-4f73-8cce-9b269b173abb.png)

Possible solutions:

Validate URLs like publish

![Screenshot 2022-07-11 at 11 03 00](https://user-images.githubusercontent.com/13741335/178295389-0e1d12d7-d457-498b-ad08-c62ded922390.png)

@AnaLoznianu @bogdanfazakas

**Comment by AnaLoznianu** [comment]
We don't show the file URL as we don't have access to it. Is encrypted and only the provider has access to the contents of that file.
For the sample field, I don't think this is necessary.
