### ISSUE TITLE
Implement redirects for all v3 assets in v4 code base

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1413]
Research: investigate if this is possible

- [ ] implement redirects for all v3 assets in v4 code base
  - generate a list of DIDs from v3 Aquarius
  - do a redirect on the Vercel/Netlify level to `v3.market.oceanprotocol.com` URL when their URLs are accessed under `market.oceanprotocol.com`
  - See https://vercel.com/docs/cli#project-configuration/redirects & https://docs.netlify.com/routing/redirects/

**Comment by kremalicious** [comment]
ideally 301 redirects, but focus is that user's don't end up in dead links, so any redirect works for this, including ones based on js or file system only.

**Comment by LucaMilanese90** [comment]
When you mention the v3 DIDs list do you mean to filter between the displayed assets in the v4 market (given that the v4 market is going to display also the v3 assets) or are you talking of a complete list of all the v3 assets that are not in purgatory? For example, if a user manually looks for a v3 DID that is not showed in the v4 market, should that redirect or just show the "not available" error message?

**Comment by kremalicious** [comment]
> given that the v4 market is going to display also the v3 assets

they are isolated from each other, so v3.market.oceanprotocol.com will only show v3 assets, and market.oceanprotocol.com will only show v4 assets.

And as soon as we switch to this setup (making current v4.market.oceanprotocol.com show up under market.oceanprotocol.com), accessing any v3 asset will result in 404 as market.oceanprotocol.com/asset/:DIDv3 then won't work.

So the v4 market needs to know if a given DID in the URL path is a v3 DID, and if so, redirect to v3.market.oceanprotocol.com/asset/:DIDv3. It's really only about redirects in backgrounds so none of this will get any UI

The list of DIDs seemed like the most feasible and unobtrusive, there might be other ways. Like, in asset details loading, when asset isn't found, do another request to v3 Aquarius to see if it's there, and if so, redirect.

**Comment by LucaMilanese90** [comment]
Ok, now it's clear, thanks! 😄
