### ISSUE TITLE
storybook: needs a theme toggle button

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1418]
Every UI component needs to be tested against our light and dark theme. And using Storybook UI during the night burns eyes. 

To solve both, in `.storybook/preview.js`:

- figure out how to add e.g. toolbar button which upon click toggles between light & dark
- activating dark mode does:
  - add `dark` class to the iframe `<body />`
  - switch to Storybook dark UI theme
- activating light mode does:
  - remove `dark` class from the iframe `<body />`
  - switch to Storybook light UI theme

Just toggling that `dark` class will make all our rendered components automatically switch their colors too.

For Storybook UI theming:
https://storybook.js.org/docs/react/configure/theming

Adding things to toolbar is straight forward, but most likely we have to create our own local addon: 
https://storybook.js.org/docs/react/essentials/toolbars-and-globals
https://storybook.js.org/docs/react/addons/addon-types#toolbars

There are various dark mode addons out there but this is not what we want, as we just want to toggle a css class.

Bonus would be adding a `prefers-color-scheme` media query and use that to switch dark/light automatically

**Comment by mihaisc** [comment]
Is this still relevant? Are we willing to allocate more time on this?

**Comment by kremalicious** [comment]
I think it's already good enough implementation in #1584, will check that
