### ISSUE TITLE
"Your Liquidity" Value in the pool doesn't make sense 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1430]
For a pool created with 100 Ocean tokens, the value of "Your Liquidity" is 75 Ocean. I understand that from a mathematical perspective it makes sense, but from a UX perspective, it doesn't. 

I would expect to see the maximum amount the user can remove from the pool. In this case, 100.

<img width="434" alt="Screenshot 2022-05-13 at 17 36 17" src="https://user-images.githubusercontent.com/84312885/168307970-7dd2e2e8-2982-448a-840f-22a278deeffe.png">

**Comment by alexcos20** [comment]
fixed in contracts
