### ISSUE TITLE
pool shares & transaction tables not showing data

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1440]
On this profile, those 2 tables don't show anything although they should, and produce console errors:

https://v4.market.oceanprotocol.com/profile/winstonwolfe.eth

<img width="1218" alt="Screen Shot 2022-05-18 at 14 50 05" src="https://user-images.githubusercontent.com/90316/169056293-5f47fdae-eeb6-40b8-b963-ab281e607d0b.png">

<img width="1262" alt="Screen Shot 2022-05-18 at 14 49 59" src="https://user-images.githubusercontent.com/90316/169056319-3d6b61a9-402d-41a5-be42-8e03424d0efb.png">

**Comment by mihaisc** [comment]
For some reason you have one share with a datatoken that doesn't exist on an asset. Investigating more

**Comment by EnzoVezzaro** [comment]
yeah, I confirm is working for me too

<img width="1440" alt="Screen Shot 2022-05-18 at 11 10 27 AM" src="https://user-images.githubusercontent.com/13741335/169075521-c9bdc3db-3b29-41b0-8e23-12f9a78f2a33.png">

**Comment by mihaisc** [comment]
is this market or subgraph issue? I tend to agree with you just remove the dt part. The users doesn't add it anyway. So, it should be just 'Create pool with 100 ocean'

**Comment by EnzoVezzaro** [comment]
> On this profile, those 2 tables don't show anything although they should, and produce console errors:
> 
> https://v4.market.oceanprotocol.com/profile/winstonwolfe.eth
> 
> <img alt="Screen Shot 2022-05-18 at 14 50 05" width="1218" src="https://user-images.githubusercontent.com/90316/169056293-5f47fdae-eeb6-40b8-b963-ab281e607d0b.png">
> 
> <img alt="Screen Shot 2022-05-18 at 14 49 59" width="1262" src="https://user-images.githubusercontent.com/90316/169056319-3d6b61a9-402d-41a5-be42-8e03424d0efb.png">

Now having the same issue. Not sure what changed since las week, but now I'm having this issue on `pool shares` and `pool transactions`.

https://user-images.githubusercontent.com/13741335/169840444-6dc564a4-5721-40e0-803a-f5325d461878.mp4
