### ISSUE TITLE
Bookmarks don't update correctly

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/market#1442]
The Bookmarks component content doesn't update correctly when deselecting a network (Polygon)

1. Go to multiple assets pages, from multiple networks and add bookmarks
2. Go to home page, make sure the networks you need are selected
3. Deselect networks 
4. When deselecting Polygon, the asset(s) published on Polygon remain in the Bookmarks section

**Comment by mihaisc** [comment]
The correct approach is that the bookmarks are displayed all the time, they ignore the network selection.

**Comment by mihaisc** [comment]
Is this still an issue ? @EnzoVezzaro  did you check it?

**Comment by EnzoVezzaro** [comment]
> Is this still an issue ? @EnzoVezzaro did you check it?

The issues as described is not present anymore, but the bookmark works with the selected networks. If you deselect a network from the Networks List, the assets bookmarked from that network get removed.
