### ISSUE TITLE
Timeout doesn't work on Free assets

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#1447]
**Describe the bug**
The timeouts on free assets are not working. Have tried with a few different timeout values and none of them seem to work.

**To Reproduce**
Steps to reproduce the behavior. For example:
1. Publish an asset with free pricing and timeout of forever
2. Click Get and pay gas fees, can now download the asset. The user should be able to come back to this page indefinitely and just see the download button.
3. Refresh the page and the Get button reappears. This means that the user has to pay the gas fees again to get another datatoken and completely defeats the purpose of setting a timeout

**Expected behavior**
For a free asset with timeout of forever, the user should be able to come back to the page indefinitely and just see the download button.

**Comment by bogdanfazakas** [comment]
Can this still be reproduced? Tried on https://v4.market.oceanprotocol.com/ and was not able to reproduce after the merge of #1445

**Comment by AnaLoznianu** [comment]
It seems to work on my end now. @jamiehewitt15 Can you try again? It doesn't reproduces on my end anymore
Just published an asset you can try with: https://v4.market.oceanprotocol.com/asset/did:op:f2b6e6d5120979b459dcbf2a4a342e85cc256ed83388e2336abb6965724977a8

**Comment by jamiehewitt15** [comment]
Yeah, it's working now. Tested again with three different assets
