### ISSUE TITLE
OCEAN user balance is null randomly

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#145]
Happens a lot on Rinkeby. Ran into that on the Cobra Capital asset during the demo:

<img width="889" alt="Screen Shot 2020-10-27 at 16 22 27" src="https://user-images.githubusercontent.com/90316/97323066-b2cb3e00-1870-11eb-8656-76d63d55ec4d.png">

**Comment by mihaisc** [comment]
I think this may be a reason
![image](https://user-images.githubusercontent.com/26000280/97323744-c929c780-1879-11eb-9193-54181fa617f5.png)
![image](https://user-images.githubusercontent.com/26000280/97323818-d8107a00-1879-11eb-9e1d-e263f41ae1ca.png)

**Comment by kremalicious** [comment]
this seems an infura problem where as a result we do not get the OCEAN balance back, leaving the buy button disabled.

**Comment by mihaisc** [comment]
await account.getOceanBalance() returns null , where account is of type `Account`  and is ` const account = (await ocean.accounts.list())[0]` .
