### ISSUE TITLE
Inform algorithm publishers that algo file can't be updated later

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1454]
Contrary to datasets, algo checksum is checked on order. If content is changed, compute jobs will fail. As first line of defense, inform publishers about it during publish flow if they select _Algorithm_, most likely on the File field

**Comment by bogdanfazakas** [comment]
Yep, but the checksum is updated once the dataset publisher updates the publisher trusted algo list. And if he added an algorithm in the list that was published by someone else, he will not be notified if the algorithm was updated by it's publisher so won't know that he needs to update the checksum for that algo.
