### ISSUE TITLE
C2d initializeCompute after reuseOrder the previous provider fee is always expired

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/market#1465]
**Describe the bug**
C2d initializeCompute dataset or algorithm transferTxId is always the asset order tx.

During initializeCompute provider will always use dataset or algorithm tx, regardless if user has been reuseOrder before.
https://github.com/oceanprotocol/provider/blob/c7f6b8cc3c1d17b00c4b7158aab60944d92ff0c4/ocean_provider/utils/provider_fees.py#L125
<img width="432" alt="image" src="https://user-images.githubusercontent.com/7642607/169691862-8e5500bb-6869-4bcb-87f6-a94b5c39eafa.png">
https://github.com/oceanprotocol/provider/blob/c7f6b8cc3c1d17b00c4b7158aab60944d92ff0c4/ocean_provider/utils/datatoken.py#L68
![image](https://user-images.githubusercontent.com/7642607/169691883-090f087a-beb3-485a-95b5-e80ab8ad59ce.png)
validate_order and datatoken_contract.events.ProviderFee().processReceipt is based on dataset or algorithm order tx, thus, the returned provider_fee_event_logs are from the asset order tx.
If reuseOrder been trigger before, should use the latest reuseOrder tx ProviderFee.

So if initializeCompute were trigger after exceeded computeEnv maxJobDuration will always has expired provider fee session.
When reuseOrder, the previous provider fee will always expired.

**To Reproduce**
1. Publish any C2D dataset and algorithm with timeout longer (maybe 1 week) than computeEnv maxJobDuration
2. Rerun the same pair of dataset and algorithm after maxJobDuration (default probably are 60min) but before dataset and algorithm expired.
4. handleComputeOrder will always goes to reuseOrder even-though were just reuseOrder 1min ago

**Contract Event**
https://github.com/oceanprotocol/contracts/blob/e60e5bc7a8d7780193b5d20341e25e750188e5d7/contracts/templates/ERC20TemplateEnterprise.sol#L532
<img width="186" alt="image" src="https://user-images.githubusercontent.com/7642607/169691672-110fdaa2-5538-4814-a4a5-f102b0a08146.png">
and
https://github.com/oceanprotocol/contracts/blob/e60e5bc7a8d7780193b5d20341e25e750188e5d7/contracts/templates/ERC20TemplateEnterprise.sol#L413
<img width="288" alt="image" src="https://user-images.githubusercontent.com/7642607/169691694-620f43c8-6152-4081-be59-67c2564a02a1.png">
Seem like OrderReused event emitted with asset order tx, not sure of subgraph could have an event handlers to track the OrderReused event, then market would passed reuseOrder tx as part of provider.initializeCompute request.

**Comment by bogdanfazakas** [comment]
fixed in the following PR's #1069 , https://github.com/oceanprotocol/ocean-subgraph/pull/444, https://github.com/oceanprotocol/provider/pull/456
