### ISSUE TITLE
Add manual image upload to our data NFT minting for V4

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1477]
Add manual image upload to our data NFT minting for V4 (next to our default waves-artwork-set).

Could be something nice for everyone to try out the Ocean Market, minting "your own dataNFT as profile pic" for fun, caring about further functionality/ opportunities later, like creating datatoken (or adding features/to data unions/services we build/3rd party services/). 

Creating this mostly for discussions...

**Comment by mihaisc** [comment]
There are already ideas for using data nft as credentials or as profile . In first case you have the nft you have access to something. In second you use the data nft to store your profile data.

**Comment by malvonme** [comment]
Hi all,
Hi @AnaLoznianu,

thank you for raising this to the market team!

As I wrote Ana, the mass-minting of data NFTs, replacing current "V1" fun-NFTs, or better: improving their forward-looking compatibility towards data consume and demand play by the masses - is not the goal here, yet we can see users doing this some time in the future. 

This idea here is really just about allowing to add a custom jpg when minting a data NFT, which could serve different purposes.

Having this on API level (mass-mint, etc.) would be a second, and I know Core Tech started looking into this lately (as several DAO teams would like to start testing this), but this would be probably (way) more of an effort for us.

Btw, in sync with Trent, I compiled a lil bootleg post on this, maybe adds to the discourse/thinking:
https://mirror.xyz/cryptowally.eth/cl0azXM44ndABXhoHsJY0PWJdew2GD63j6um9-FmFqk

**Comment by malvonme** [comment]
A later, second, higher effort route for this, if interest in it exists, would be 

the mass-minting of data NFTs, replacing current "V1" fun-NFTs, or better: 
improving their forward-looking compatibility towards data consume and demand play by the masses - it's not the goal here yet, but I can see builders doing this some time in the future. 

Hence, having this on API level (mass-mint, etc.) would be the "first full scope" of it, and I know Core Tech started looking into this lately (as several DAO teams would like to start testing this), but this would be probably (way) more of an effort for us and def outta scope anything near term. 

Thx

**Comment by malvonme** [comment]
PS:
If NFT is still new/unrelateable to you, maybe you like this (NFT profile pic trend in a nutshell): https://mirror.xyz/cryptowally.eth/YkaO0vPgwzzaYsZft7ONTmqURVwzgG2iCtjGj3Wxsxk

**Comment by malvonme** [comment]
A community member just made a graphic, giving you the fastest way to the concept/idea
https://twitter.com/AquaNauxt/status/1531296780687749124?s=20&t=1Jnqt3Ch7KuJ7pv6H3f8Yg

![FUBCSTJXoAAxP3k](https://user-images.githubusercontent.com/101562291/171025022-175c59bc-e616-48bb-803d-2d8a4c52ec70.jpeg)

**Comment by AnaLoznianu** [comment]
This is already possible by overriding the tokenURI. There are published assets with custom images: https://market.oceanprotocol.com/asset/did:op:39b9fa755de838a1a912e8589f64ce1601157cc2f1418ee9a3e77b7c7342f986 
so for now, we will not focus our efforts in this direction.

**Comment by malvonme** [comment]
I understand.

Just for some context:
The goal behind this was to increase actionability of the we collect (and collect more data overall), not just an image to the data NFT, in a seamless manner. Seamless as in: bring the data that you supply (write user settings/parameter) closest possible to the data you CONSUME (read additional settings/parameters stored by other platforms "through" my data NFT when I log in). It was supposed to be a early fun test (mint "your" NFT as data NFT), and by that, as a trojan horse, a  complementary move to our current strategy of "build the market and wait for supply and demand, incentivize demand".

But as said: I understand if this is no priority. 

Thanks for considering, Ana!

**Comment by malvonme** [comment]
Awesome @kremalicious, thank you!! Will insta-share with community
