### ISSUE TITLE
The estimated amount of pool shares the user receives on adding liquidity is not accurate

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1481]
**Describe the bug**
When adding liquidity to a pool, the number of estimated pool shares is not correct.
When adding 50 Oceans in a pool of 100 Ocean tokens, the estimated pool percentage is 20% but it should be in fact 33.33%(1/3 out of 150). 
After adding the liquidity, the pool shares and percentages owned are correct. 

**Screenshots**
![Screenshot 2022-06-02 at 10 37 11](https://user-images.githubusercontent.com/84312885/171650039-92bc1a04-0e99-4164-8bcc-8e184c39aa3a.png)
![Screenshot 2022-06-02 at 10 37 26](https://user-images.githubusercontent.com/84312885/171650050-179fa5d4-2147-4f49-bfa3-fe4446b08434.png)
![Screenshot 2022-06-02 at 10 38 43](https://user-images.githubusercontent.com/84312885/171650055-394a184b-c5e5-4e4b-93f2-786febb93dec.png)

**Comment by mihaisc** [comment]
This was commented before the release and needs to be fixed
