### ISSUE TITLE
some assets are crashing the app on unsupported networks

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1485]
**Describe the bug**
When surfing on unsupported network, some assets crashes the app.

Assets: 
- [Asset 1](https://market.oceanprotocol.com/asset/did:op:98fe77267bc2628999b735cc0f34c51e34190b7434665d6b67842ae7273076a4)
- [Asset 2](https://market.oceanprotocol.com/asset/did:op:fe0783468b51cb1c59ba75c6868b278dd85eaf9c790a983ae6c8a094f2174af3)

**To Reproduce**
1. Change wallet to unsopported network
2. Open above files
3. See error

**Expected behavior**
The market should not crash.

**Screenshots**

https://user-images.githubusercontent.com/13741335/172154646-8c148588-d567-41a4-8116-ecab2026f4b7.mp4

**Comment by kremalicious** [comment]
not reproducible anymore, both assets can be viewed with wallet connected to unsupported network.
