### ISSUE TITLE
The Algorithms are not visible in the Compute Dataset

### ISSUE THREAD

**Issue by tharunprabhakaran** [oceanprotocol/market#1493]
**Describe the bug**
The algorithms in the Ocean market are not visible on the Compute Dataset page for starting a compute job.

**Expected behavior**
The Algorithms should be visible on the Dataset page to start a compute job.

**Screenshots**
1. Dataset 
![Dataset](https://user-images.githubusercontent.com/40835224/172535852-c190dafb-d9cd-400b-9ff2-bcacba46f930.jpeg)

2. Dataset Compute Settings
![Dataset Compute Setting](https://user-images.githubusercontent.com/40835224/172535867-aaaf441c-1bec-4df2-b45e-b70140ad0050.jpeg)

4. Algorithm
![Algorithm](https://user-images.githubusercontent.com/40835224/172535883-a1e1dc36-0570-471f-8890-619329197c79.jpeg)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 100.0.2
 - Network: Ropsten

**Additional context**
1. The Dataset and the Algorithm are priced as Free.
2. The Algorithms are not visible even on the Dataset Compute Settings page. (Refer to Dataset Compute Settings Screenshot)

**Comment by tharunprabhakaran** [comment]
Thanks, can we use v3 for compute to data ?

**Comment by kremalicious** [comment]
v3 is deprecated, and e.g. publishing has been disabled. So no.
