### ISSUE TITLE
limit CoinGecko API calls

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#150]
CoinGecko API has a limit of 100 requests per minute and we seem to be hitting that constantly resulting in `0` value displayed.

Find a replacement API with enough quota and replace the conversion component with it. Or try to limit the requests with a `PriceProvider`

**Comment by mihaisc** [comment]
We can remove the timer, but that doesn't help either, the limit is too low for what we need.
A temporary fix would be to show the conversion only in asset details, not in home/search

**Comment by kremalicious** [comment]
seems more reliable now with the new PriceProvider. Revisit replacement API once this becomes a problem again
