### ISSUE TITLE
Some assets have empty tokenURI after publish

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1515]
Resulting in empty NFT image.

- https://market.oceanprotocol.com/asset/did:op:4c54dd587dfc388907ff6a3847fa2e8631e36643ec5c489e9ee5cbf29b0e6314
- https://market.oceanprotocol.com/asset/did:op:af35b35faf234b99d73d6fe33f6da3ab89d09110d654a26e5c47d02e03be30c7

So far, buggy ones are always on some Polygon network. Need to go back into tx and see what happened there

**Comment by AnaLoznianu** [comment]
Re-test this firstly to see if it's still an issue.

**Comment by claudiaHash** [comment]
Can't reproduce it anymore. All the assets I published in the last days (mainly on Polygon testnet, but also on Rinkeby and Ropsten) come with a defined nft token uri.
