### ISSUE TITLE
Data asset with value < 0 

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1521]
<img width="447" alt="Screenshot 2022-06-15 at 17 33 43" src="https://user-images.githubusercontent.com/84312885/173856067-a5f44cb4-b2b2-4629-bcf0-ea9b2890c384.png">

https://market.oceanprotocol.com/asset/did:op:9d4596375970f4fce60c93368e8632088cb52beaecda2ee310ca52e134578875

**Comment by mihaisc** [comment]
We should take in consideration 'isPurchasable' when displaying the price. When it is false show a message instead of the price.
