### ISSUE TITLE
Volume charts with missing data

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1523]
Looking [at this volume chart](https://market.oceanprotocol.com/asset/did:op:ba8753de3a2715d05960092f35bc2c74a0d63bb4998a4fcb583bae60e335cf89) and comparing with the liquidity in the pool, it seems good chunk of data is missing:

<img width="508" alt="Screen Shot 2022-06-16 at 13 18 25" src="https://user-images.githubusercontent.com/90316/174068246-339445ee-526e-463e-bdde-5923eed457b0.png">

From this screenshot, chart only shows total of around 2100 OCEAN when counting bars together.

Not sure if bug or wrong expectation as to what that chart shows.

**Comment by mihaisc** [comment]
That is just swap. Pool setup is not taken in consideration. So if you swap in 100 ocean and swap out 150 ocean , volume is 250.

**Comment by AnaLoznianu** [comment]
Let's rename the button to 'Swap Volume'
