### ISSUE TITLE
Wallet balance can't be fetched on Polygon sometimes

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1528]
Sometimes, the balance of user's wallet and the maximum amount to add to a pool is 0 even though, the value is not correct. 

The RPC call fails initially. After some time or a refresh, the values are displayed correctly and the user can add liquidity to the pool

![[Data Whale] Ocean ONDA DataFi Directory V4 - Ocean Market - Google Chrome 6_21_2022 12_15_06 PM.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/b41b9a5e-a6ef-421d-8234-cea9c34f97cd)

![[Data Whale] Ocean ONDA DataFi Directory V4 - Ocean Market - Google Chrome 6_21_2022 12_15_29 PM.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/69b76996-8d71-4e08-ab80-2c329e89fd9f)

![[Data Whale] Ocean ONDA DataFi Directory V4 - Ocean Market - Google Chrome 6_21_2022 12_15_59 PM.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/02d8e810-fb78-467c-9adb-c67b7d45fd67)

**Comment by mihaisc** [comment]
What rpc are you using?

**Comment by AnaLoznianu** [comment]
https://polygon-rpc.com

**Comment by mihaisc** [comment]
Is this using walletconnect or metamask?

**Comment by AnaLoznianu** [comment]
Metamask

**Comment by mihaisc** [comment]
Can we replicate this? This was done by Alex when rpc/cloudflare etc were down/having issues :) . In theory we could improve the UX here with extra checks and some nice components. Definitely not a priority

**Comment by kremalicious** [comment]
Cannot reproduce with MetaMask so far but I'm using custom RPC account with https://rpc.maticvigil.com

**Comment by mihaisc** [comment]
Is this still happening? I can't reproduce this

**Comment by kremalicious** [comment]
Haven't seen any complaint about this despite Polygon being used by majority of our liquidity providers so closing for now
