### ISSUE TITLE
Dataset list where algorithm is allowed to run

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1532]
On `did:op:f965d5a61e5d73c5a9c91f67926bdd9e97a15f20f1e76467fca4f6e59b401ce1` the list is empty:

<img width="541" alt="Screen Shot 2022-06-22 at 14 18 34" src="https://user-images.githubusercontent.com/90316/175038972-cd4bab8e-87fc-4709-9f1f-57294bc55d35.png">

But on `did:op:f6a9d9a7cb59bac6e1819e4321e3d4c8f19fe307f3dec12eb938ef6fd4284c0e`, where I assume all published algos are allowed, it can be selected:

<img width="414" alt="Screen Shot 2022-06-22 at 14 16 28 copy" src="https://user-images.githubusercontent.com/90316/175039125-ec8e2efd-eb4f-4231-9290-a0f970eecbce.png">

Expectation would be that on an algo all datasets show up where it is allowed to run, including those with all published algorithms allowed.

**Comment by mihaisc** [comment]
This is not an enhancement, it's a bug. It used to work in v3. It's cause by a faulty filtering if i remember correctly
