### ISSUE TITLE
Listing of Compute jobs on asset details and profile constantly gets into loading mode

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1533]
And whenever its loading state kicks in, the compute job details modal closes automatically.

1. Go to an asset you have started a compute job on
2. Open up _Your Compute Jobs_
3. Click _Show Details_
4. Wait like 10 sec.
5. See the modal close cause list refreshes from very beginning with empty compute jobs incl. spinner

<img width="640" alt="Screen Shot 2022-06-22 at 14 36 23" src="https://user-images.githubusercontent.com/90316/175042524-2f728ce0-8117-477f-8d84-1bc9847f85be.png">

Sounds like bad data refresh management. A loading spinner should only appear at very beginning when no data is available. Every further refresh of data needs to update existing data on screen, instead of replacing them all with empty list. But in end most likely component shouldn't refresh at all, as nothing changed.

**Comment by LucaMilanese90** [comment]
I had a look at this some time ago and it's due to the balance refresh timer, we patched it in this way if it can help 😉  https://github.com/deltaDAO/mvg-portal/pull/41

**Comment by bogdanfazakas** [comment]
thanks will take a look on the PR 👍 , but yep you are right they are related, we fixed this in a prev commit but for somehow we broke it again 😄
