### ISSUE TITLE
Type error: Cannot find module 'src/@types/subgraph/OpcQuery' or its corresponding type declarations.

### ISSUE THREAD

**Issue by gitakileus** [oceanprotocol/market#1535]
> @oceanprotocol/market@1.0.0 build D:\dev\Tutorial\ocean\market
> npm run pregenerate && next build

> @oceanprotocol/market@1.0.0 pregenerate D:\dev\Tutorial\ocean\market
> bash scripts/pregenerate.sh

scripts/pregenerate.sh: line 2: $'\r': command not found
scripts/pregenerate.sh: line 5: $'\r': command not found
npm ERR! missing script: codegen:apollo
npm ERR!
npm ERR! Did you mean this?
npm ERR!     codegen:apollo

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-22T23_14_24_782Z-debug.log
scripts/pregenerate.sh: line 8: $'\r': command not found
info  - Loaded env from D:\dev\Tutorial\ocean\market\.env
Failed to compile.

./src/@context/MarketMetadata/index.tsx:10:26
Type error: Cannot find module 'src/@types/subgraph/OpcQuery' or its corresponding type declarations.

   8 |   useState
   9 | } from 'react'
> 10 | import { OpcQuery } from 'src/@types/subgraph/OpcQuery'
     |                          ^
  11 | import { OperationResult } from 'urql'
  12 | import { opcQuery } from './_queries'
  13 | import { MarketMetadataProviderValue, OpcFee } from './_types'

info  - Checking validity of types .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @oceanprotocol/market@1.0.0 build: `npm run pregenerate && next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @oceanprotocol/market@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Akileus\AppData\Roaming\npm-cache\_logs\2022-06-22T23_15_20_773Z-debug.log

**Comment by gitakileus** [comment]
I can't find 'src/@types/subgraph/OpcQuery'
Where can I find this file?

**Comment by jamiehewitt15** [comment]
`src/@types/subgraph/OpcFeesQuery.d.ts` is an automatically generated file. The steps for running that market are [here](https://github.com/oceanprotocol/market/)

It would be helpful if you could explain what steps you have run or what guide you are following and then we can offer more assistance.

**Comment by gitakileus** [comment]
Thanks
Now I am following https://docs.oceanprotocol.com/tutorials/compute-to-data-architecture/
But It is difficult to understand
Which tutorial is the better?
Could you tell me about it?
And How to integrate with Front end.
If you have your own project, Could you send me, please?
Thanks in advance.

**Comment by jamiehewitt15** [comment]
> Thanks Now I am following https://docs.oceanprotocol.com/tutorials/compute-to-data-architecture/ 

That guide is aim at people who want to create their own compute-to-data environment. Is that what you're trying to do?

> Which tutorial is the better? 

It really depends on what you are trying to build? Are you trying to build a new app based on Ocean or are you looking to fork Ocean Market (this repo)?

> And How to integrate with Front end. 

This repo (Ocean Market) is the front end. In most cases, the easiest way to start your own project is to fork this repo and then adapt it from there. You will find that everything works straight away and you can focus on the new features that you want your app to have.

**Comment by gitakileus** [comment]
Thanks

**Comment by gitakileus** [comment]
Do you have any project using ocean?

**Comment by jamiehewitt15** [comment]
[Ocean Market](https://market.oceanprotocol.com/) is the best example of a project built on Ocean

There are a couple more marketplaces:
https://acentrik.io/
https://bigdataprotocol.com/

I'd also recommend having a look at the project funded through Ocean DAO: https://oceanpearl.io/projects

**Comment by gitakileus** [comment]
Hello Sir
How are you
I want to implement the our data sharing using ocean Dao protocol.
So, How can I do?

**Comment by kremalicious** [comment]
Hi @gitakileus thanks for dropping by but unfortunately this here is an issue tracker, and not a forum. If you are looking to get questions answered around your development flow with Ocean, I would suggest hitting `#dev-support` channel in our Discord where the chances of getting an answer from other internal and external developers is way higher.
