### ISSUE TITLE
Wallet balance not being fetched when using wallet connect

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1545]
Cannot add liquidity/trade on mobile. 
Even if I have funds In my metamask account: mOcean and MATIC and a connection via WalletConnect, on the ocean market the wallet balance is not correctly fetched and I cannot do basically anything. Please see the screenshots: 

![289280548_537528818068598_7730857693071466717_n](https://user-images.githubusercontent.com/84312885/175506790-d272613f-6f67-469a-8d5d-6c251fc45a20.jpeg)
![289333194_577349857366879_1858074185413467295_n](https://user-images.githubusercontent.com/84312885/175506797-4e170ff0-979f-48e1-8655-255645cfc475.jpeg)
![289589030_1027360548173831_3861162979188949792_n](https://user-images.githubusercontent.com/84312885/175506806-876e7735-39c9-4d42-9a96-72845fdc0247.jpeg)

OS: Android 12.0.0.134

**Comment by kremalicious** [comment]
Use case of wallet connect: on one screen you have the app, and on the other screen you have your wallet and with WalletConnect you connect them both. Trying to use WalletConnect to connect multiple apps on one device rarely works. Then it seems it's always Polygon with those issues and if the wallet balance call fails then most likely it's an RPC issue and there's nothing we can do

**Comment by kremalicious** [comment]
Also, what's the difference to #1528? This here seems like duplicate

**Comment by AnaLoznianu** [comment]
The #1528 reproduces using metamask. This one is strictly related to mobile and wallet connect

**Comment by AnaLoznianu** [comment]
RPC: https://polygon-rpc.com
