### ISSUE TITLE
price & shares do not update after user interaction without browser refresh

### ISSUE THREAD

**Issue by innoprenuer** [oceanprotocol/market#155]
the pool still thinks I have the same pool share even after withdrawing.
(from discord user)

**Comment by kremalicious** [comment]
yes, only reload helps right now, we stopped price re-fetching in background because of performance reasons for now.

**Comment by innoprenuer** [comment]
okay so basically refreshing the browser should help?

**Comment by kremalicious** [comment]
yup, that, refreshing the page in browser
