### ISSUE TITLE
Support headers in UrlFile

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1554]
Provider issue: https://github.com/oceanprotocol/provider/issues/504

Support setting multiple headers for the file URL when publishing an asset.

The file url structure is : 
```
{
    "type": "url",
    "url": "https://url.com/file1.csv",
    "method": "GET",
    "headers":
      [
       {"Authorization": "Bearer 123"}, 
       {"APIKEY": "124"},
      ]
}
```
Currently we just set the url with the default GET method. This would imply a significant change in the file component or create a new one because the current one is used in other places as well.

We also need a new component to add multiple key/value pairs. This would be used in other components as well (for example multiple parameters for algorithms). This component would allow us to add/remove multiple key value pairs and return a json. 

The url component will have the following fields: url, method (a select list) and headers (the previous defined component)

**Comment by AnaLoznianu** [comment]
Good point, I've updated the description of this issue based on Calina's comment on the provider issue: https://github.com/oceanprotocol/provider/issues/504#issuecomment-1168486572. Makes more sense now?

**Comment by mihaisc** [comment]
Updated the initial description

**Comment by alexcos20** [comment]
graphql storage has headers as well, so make sure that this can be used for both

**Comment by mihaisc** [comment]
implemented
