### ISSUE TITLE
Feature Request - TVL display

### ISSUE THREAD

**Issue by innoprenuer** [oceanprotocol/market#156]
It would be very helpful to Ocean community to see the total value locked within Ocean ecosystem. Its a most important metric in Defi space right now. And would be cool if we can display it on Ocean Market.

**Comment by kremalicious** [comment]
Totally needed but not so simple, outlined a bit in https://github.com/oceanprotocol/market/issues/160#issuecomment-718216512

**Comment by trentmc** [comment]
This does not need to be a feature in Ocean Market. It's easily something that the community could build.

A full-blown version of this is like a datatoken version of CoinMarketCap, CoinGecko, and DefiPulse. With top-level stats across tokens, and a zoom in for a given datatoken.

**Comment by trentmc** [comment]
We're going to incentivize for this in DEC, btw.

**Comment by kremalicious** [comment]
This all needs historical data to be useful, only outputting current value is not that useful. Only historical data makes this useful and there's  no way to make graphs without it. This is not something quickly done as a bounty but needs modifications in our core tech, probably Aquarius. Or a whole new indexing component or subgraph. Only then we can think about interface but we need to create the data source first

**Comment by trentmc** [comment]
Why does it need modifications in the core tech? Can't someone grab all the data from Ethereum blockchain (including past blocks) ? That's how CMC, CoinGecko etc work.

**Comment by kremalicious** [comment]
no, that is too expensive. Look at the history page where we fetch everything from chain. For me, the pool transactions take about 5 min. to load... This will get worse over time. We need something in between. No tool out there fetches that stuff directly from chain on client-side

**Comment by trentmc** [comment]
Think of it this way. Imagine that someone is building an app to show all this. CMC for datatokens. Their app can have centralized components, it's just displaying stuff (ie doesn't ask user to attach a wallet, transfer funds, etc). So it can have a centralized backend to do the compute as needed, for final & fast frontend rendering.

In this setup, is there an issue?

**Comment by kremalicious** [comment]
just saying that this issue here is not just a display and UI issue. Necessarily it means building the data source and on top of that building a UI for it. And if we want to have useful values and graphs in our own UI we also need to make sure we trust the data source, so it needs to be constantly maintained too

**Comment by kremalicious** [comment]
data source has been created https://github.com/oceanprotocol/ocean-subgraph

once #284 has been solved, we can revisit this here and decide what exact aggregated market statistics makes sense, and where to show them

**Comment by trentmc** [comment]
Is this not already done?

The bottom of Ocean Market mainpage says e.g. "1,298,085.446 OCEAN≈ €499,448.76  and 40,107.252 datatokens in 167 data set pools."

The first number is TVL, no?

**Comment by kremalicious** [comment]
well, kinda but only partial. Cause the datatokens also have a value but we can't easily calculate this right now. So the actual TVL value would be the converted value of OCEAN + Datatokens in all pools

**Comment by trentmc** [comment]
Agreed. However this request was made even before that. There's a good case to be made that the current value is good enough. (Why make extra work for ourselves? :)

**Comment by kremalicious** [comment]
right, good point. Wanted to actually rewrite the issue here once we know what other aggregated stats we want to show but let's do this in new issue when the time is right

**Comment by trentmc** [comment]
+1
