### ISSUE TITLE
Can't publish. "Input argument is not an HTMLInputElement", "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#1562]
**Summary**

I tried to publish on Ocean Market, and it fails when I click "Continue" in step 3 (pricing). It fails for the 3 chains I tried, and all 3 pricing schemes. It fails in both chrome and firefox (ubuntu).

Obviously this is a showstopper for people trying to publish - since they can't.

**Details:**

My IT setup:
- Ubuntu 22
- Browsers tried: Chrome, Firefox
- With metamask extension
- Chains tried: eth mainnet, polygon, moonriver. FYI I am able to do other stuff with metamask + these chains, eg yesterday I dispensed DF rewards

I went to market.oceanprotocol.com, connected my wallet, clicked "publish". 

In publish steps 1, 2, 3 I filled out the following info:

_Title:_ 
Data Farming DF1 CSVs

_Description:_ 
CSVs generated as part of dispensing rewards for DF1. 

Includes DCV, stakes, rewards.

Generated via https://github.com/oceanprotocol/df-py

_Author:_
DF Core team

_Label:_
data farming

_Access type:_

Download

_Provider url:_
(The default. It says url confirmed.)

_File:_
(it's a link to a GFolder)
https://drive.google.com/drive/folders/15UdsxaSl7SAgoWRQaQgHtARpLUXb5p3B

(clicked "Validate" button, it worked)

_Sample file:_
None

_Timeout:_
1 week

Pricing: I tried all three (fixed price, auto, free). 

Then I click "Continue" (in step 3) and that's where it fails. 

Below I show errors from both (a) Chrome and (b) Firefox.

**Error info from Chrome**

(Screenshot below)

_Error in the application:_

``` 
 Error: Application error: a client-side exception has occurred (see the browser console for more information).
```

_In the browser's console:_
```console
Assertion failed: Input argument is not an HTMLInputElement
  getFormProfile @ onloadwff.js:71

TypeError: Cannot read properties of undefined (reading 'stats')
framework-1d5e83d989279221.js:1 
    at Ho (422-1255b24773590789.js:1:91329)
    at ko (framework-1d5e83d989279221.js:1:62749)
    at ki (framework-1d5e83d989279221.js:1:120248)
    at ys (framework-1d5e83d989279221.js:1:109193)
    at vs (framework-1d5e83d989279221.js:1:109121)
    at hs (framework-1d5e83d989279221.js:1:108984)
    at ls (framework-1d5e83d989279221.js:1:105768)
    at rs (framework-1d5e83d989279221.js:1:104319)
    at S (framework-1d5e83d989279221.js:1:131184)
    at MessagePort.T (framework-1d5e83d989279221.js:1:131718)
```

![error](https://user-images.githubusercontent.com/5305452/176867821-8fd8b547-724a-4c94-b553-4bd3534acb60.png)

**Error info from firefox**

(Screenshot below)

_Error in the application:_

``` 
 Error: Application error: a client-side exception has occurred (see the browser console for more information).
```

_In the browser's console:_

```console
SearchSettings: get: No settings file exists, new profile? DOMException: Could not open the file at /home/trentmc/.mozilla/firefox/i9qlr0wp.default-release/search.json.mozlz4 [SearchSettings.jsm:108:18](resource://gre/modules/SearchSettings.jsm)
LoginManagerPrompter: _getShortDisplayHost couldn't process moz-extension://33a77b54-3536-4b07-a3ea-e7ea2f75379d [LoginManagerPrompter.jsm:995:11](resource://gre/modules/LoginManagerPrompter.jsm)
Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture [menupopup.js:169:13](chrome://global/content/elements/menupopup.js)
Error: Can't find profile directory. 2 [XULStore.jsm:66:15](resource://gre/modules/XULStore.jsm)
    load resource://gre/modules/XULStore.jsm:66
    XULStore resource://gre/modules/XULStore.jsm:24
```

_Screenshot:_
![firefox](https://user-images.githubusercontent.com/5305452/176869651-f8572f39-b349-417c-88b1-037e06d34f56.png)

**Comment by kremalicious** [comment]
preview again, tries to read out something from DDO which we don't have yet in our dummy DDO constructed in publish.
