### ISSUE TITLE
Add sales number on asset teaser

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1565]
It would be useful to add the sales number on the asset teaser as well. Works really well with https://github.com/oceanprotocol/market/issues/1522

![image](https://user-images.githubusercontent.com/26000280/176914633-e248e660-6ba2-47b8-ba98-2365a1813677.png)

**Comment by EnzoVezzaro** [comment]
> It would be useful to add the sales number on the asset teaser as well. Works really well with #1522
> 
> ![image](https://user-images.githubusercontent.com/26000280/176914633-e248e660-6ba2-47b8-ba98-2365a1813677.png)

Agree. I propose one of this UI options: 

1) 
![Screenshot 2022-07-04 at 12 04 36](https://user-images.githubusercontent.com/13741335/177189720-680b4bd6-28fb-4a37-948c-d246250d1b9d.png)

2) 
![Screenshot 2022-07-04 at 12 03 18](https://user-images.githubusercontent.com/13741335/177189734-08363531-b143-4248-906a-2d535f71ad97.png)

3)
![Screenshot 2022-07-04 at 11 59 20](https://user-images.githubusercontent.com/13741335/177189752-47715331-e0b3-4dc2-957e-b9c4d90ee91f.png)

**Comment by mihaisc** [comment]
1 looks nice
