### ISSUE TITLE
Add REQUEST DATA feature

### ISSUE THREAD

**Issue by dalovar** [oceanprotocol/market#1566]
I just found out about Ocean protocol.

After checking the app, I would recommend that you incorporate a feature to REQUEST DATA since I only see where I could sell data, or buy data.

Further, these DATA REQUESTS **could** come with a pre-funded bounty that is put in escrow so this request becomes more valuable than just a soft indication of interest, so that whoever is getting this data and curating it has a guaranteed payment once they are done.

The person that requested data can then unlock the funds from escrow (which can be a simple escrow smart contract with control of ERC20 tokens like OCEAN or ETH) once the requester receives the data they want, the bounty is finally paid to whoever found and curated the data.

If the bounty isn't released by the requester of the data for some reason or complaint, such as the data being invalid, or not being according to the original requirements, a 3rd party arbiter could resolve the escrow in favor of either the requester or the data provider, depending on who is right according the original request conditions.

In order to avoid spam conflicts, you could require a security deposit in OCEAN, every time a data provider makes a complaint about not receiving a bounty and the other way around. This security deposit could be refunded to the initiator of the arbitration if they are right, or burnt/confiscated if it is found that the complaint was bogus or malicious.

**Comment by kremalicious** [comment]
Sounds like a great feature, but this is out of scope of this repo. This would be a great external app though with its own revenue stream so would be good candidate to get realized through OceanDAO https://oceanprotocol.com/dao
