### ISSUE TITLE
Market and Barge Script results in TypeError

### ISSUE THREAD

**Issue by Simon-Pokorny** [oceanprotocol/market#1567]
Hi everyone,

I would like to setup a local development environment and want to use the barge script to have all depencencies running locally. Unfortunately I am confronted with a TypeError as soon as I switch the network to localhost in Metamask. You can find a detailed bug description below. Any help with this issue is much appreciated.  
Thank you in advance!  

**Describe the bug**
As soon as I switch the network in metamask to localhost 8545 I see the following issue:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/54535910/177133799-d213ab4d-91cd-4ff7-b52f-93f8ce6a4c7e.png">

**To Reproduce**
1. Started Barge script with `./start_ocean.sh --with-thegraph`
2. Build a docker image with market with the following dockerfile:

        FROM node:16.14  
        COPY . /market   
        RUN chown -R node /market  
        WORKDIR /market  
        USER node  
        RUN npm install
      Where the copy comand in line 2 simply copies the content from this repository into the folder /market
3. Set NEXT_PUBLIC_METADATACACHE_URI="http://127.0.0.1:5000" in .env file
4. Adjusted subgraphUri to http://127.0.0.1:9000 in the function getDevelopmentConfig in /src/@utils/ocean.ts
5. Copy contact addresses  

          ./scripts/copy-contracts.sh
6.   Start market container with artifacts

          docker run -it --rm --network host -v $(pwd)/node_modules/@oceanprotocol/:/market/node_modules/@oceanprotocol/ontracts/artifacts <IMAGENAME> npm start
        
7. Added private key to metamask wallet and confirmed, that the expected balance is shown. 
8. Switched network in metamask to localhost and the error above occures.
**Expected behavior**
I would expect, that the market works in the same way as with other networks

**Desktop (please complete the following information):**
Browser: Chrome
OS:  Ubuntu 16.04.7 LTS

**Comment by kremalicious** [comment]
looks like an oversight in code as local network can't be found in the network metadata. So in the error you could try adding a `!network` to the condition at the beginning.

Developing market against barge has always been a bit tricky so we always suggest to use a remote test network, which the app is setup to do by default.

**Comment by htcarr3** [comment]
@kremalicious, can you explain what you mean by "test network"? Do you mean running all of those containers in the cloud as opposed to running them locally?

**Comment by Simon-Pokorny** [comment]
No I think he means instead of running all those containers on your own to choose an existing testnetwork and their corresponding components. Here is a list of all supported networks: https://docs.oceanprotocol.com/core-concepts/networks
