### ISSUE TITLE
Refreshing profile page fails

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1572]
If you simply reload a profile page it will fail. From what i can see the aquarius query fails. To reproduce just go to a profile page (not your own, and don't have a wallet connected) and just refresh

![image](https://user-images.githubusercontent.com/26000280/177348850-d7602c0e-df35-42b7-937f-b8a87d14ae63.png)

**Comment by mihaisc** [comment]
to quote myself `and don't have a wallet connected)` 

![profile](https://user-images.githubusercontent.com/26000280/177355433-d3320f8d-a7b3-4856-9284-5bd35ef256ed.gif)

**Comment by EnzoVezzaro** [comment]
> 

Yeah sorry 😅  forgot to post the video with the account NOT connected. 

https://user-images.githubusercontent.com/13741335/177356989-a7177fe4-190a-4ae8-af9a-91693223c4b2.mp4

**Comment by mihaisc** [comment]
try this one https://market.oceanprotocol.com/profile/0x9cEE6de6D601Edb9284C8538b5a041cbEffc463F

**Comment by EnzoVezzaro** [comment]
> https://market.oceanprotocol.com/profile/0x9cEE6de6D601Edb9284C8538b5a041cbEffc463F

Yeap, this one breaks 👍🏽  it seems related to this profile

**Comment by mihaisc** [comment]
nope, more break , this was just an example

**Comment by EnzoVezzaro** [comment]
😅  in local I can't reproduce it either. It works for the profile above too

https://user-images.githubusercontent.com/13741335/177362964-4571cea5-3e5f-44f0-95ea-41b36f25c9d1.mp4

**Comment by mihaisc** [comment]
I'm going to close this since it's not replicating
