### ISSUE TITLE
Sales line should not be in asset details

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1576]
The sales number we added in #1570 appears now wrong on asset details, and it should not appear there:

<img width="590" alt="Screen Shot 2022-07-06 at 11 39 42" src="https://user-images.githubusercontent.com/90316/177532319-07d8fe2b-d265-4c46-880b-059b6b0b3fac.png">

**Comment by mihaisc** [comment]
This is a "feature"
