### ISSUE TITLE
WalletConnect connection does not work

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#158]
Console says:

```
TypeError: this.send is not a function. (In 'this.send(e)', 'this.send' is undefined)
```

This prevents all mobile wallets from connecting, like Argent, Rainbow, Trust Wallet

**Comment by kremalicious** [comment]
we have this issue:
https://github.com/Web3Modal/web3modal/issues/197

**Comment by mihaisc** [comment]
Should we remove WalletConnect until then?

**Comment by alexcos20** [comment]
blocked by web3 upcoming release
