### ISSUE TITLE
Add 2 risk warnings and investment disclaimers 

### ISSUE THREAD

**Issue by andreaarmanni** [oceanprotocol/market#1588]
**Problem:** 
Currently, the average user believes that staking/LPing in V4 is risk-free. Rug pulls have been solved, but there are still risks involved.

**Objective:** 
Manage expectations and make it clear that risks still exist when LPing due to the nature of AMMs. 

**Solution:**
Add a risk warning/investment disclaimer in proximity to the 2 major CTA. 

Disclaimer: "Providing liquidity to a pool is subject to the same dynamics of AMMs. Invest at your own risk. Losses may occur."

- [ ] Location A: Below "Add Liquidity" call to action
<img width="496" alt="Screenshot 2022-07-10 at 09 20 37" src="https://user-images.githubusercontent.com/35074712/178137086-3c9d441a-fe19-4d49-bccb-f33611c69c61.png">

- [ ] Location B: Below "Supply" call to action 
<img width="411" alt="Screenshot 2022-07-10 at 09 20 44" src="https://user-images.githubusercontent.com/35074712/178137082-fa9013f8-18ad-4d5c-bb6b-c0cabee7e1cd.png">

**Comment by jamiehewitt15** [comment]
We can just add back in the same warning that was removed: https://github.com/oceanprotocol/market/pull/1420 The text needs to be updated though as it was linking to an out-of-date blog post. 

> Rug pulls have been solved

For the time being at least, I think we should hold back from saying this.

**Comment by jamiehewitt15** [comment]
> Andrea's drafts would be more fitting in this context and we could only put it on the Add screen to have 1 clear message. Then right at the top under _Add Liquidity_ heading. There we could see if using a warning style for it is too dominant, but in any case already way better than. forcing users to dismiss messages again.

Sure, yeah let's do it that way. Less intrusive

**Comment by mihaisc** [comment]
Please stop working on this, more details will come
