### ISSUE TITLE
Proper state check for assets

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1600]
We need to have a proper message based on state. For example https://market.oceanprotocol.com/asset/did:op:73fcf31760687e5deb8e75688e3ae090adc29c8699e3e74d23bbac9a28627f7d has state 3 , revoked.

**Comment by EnzoVezzaro** [comment]
As for now, we could catch that state and show a message like this: 

![Screenshot 2022-07-14 at 08.48.53.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/c0437ff2-e0da-405f-8810-da1a180a6a3a)

Not sure what's the best message. At this point I'd change all the states, but I'm not sure what are there. Do we have any docs about that?
