### ISSUE TITLE
html in description is not showing up

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1603]
**Describe the bug**

[Reported](https://discord.com/channels/612953348487905282/720631837122363412/997130217174863882) by user

This [asset](https://market.oceanprotocol.com/asset/did:op:65e051b2d4e6d5053b021a0bb1d1699d0cf16c628559f0c111d090535bba50d6) has been published, but for some reason, the market is not showing the description.

Description:
![Screenshot 2022-07-14 at 10 02 03](https://user-images.githubusercontent.com/13741335/179000787-e824b647-9447-4a99-aada-0cc080f473d3.png)

![Screenshot 2022-07-14 at 10 01 52](https://user-images.githubusercontent.com/13741335/179000815-852c6ad0-ad66-499e-ae4a-ed2b89f3d6ad.png)

UPDATE: this issue is caused by the [markdownToHtml](https://github.com/oceanprotocol/market/blob/feature/issue-1496-markdown-toolbar-element/src/components/@shared/Markdown/index.tsx#L12) method. This is returning an empty string. The user is entering html instead of markdown. Our function doesn't handle htmlToMarkdown

**Comment by mihaisc** [comment]
Not really a bug, this was intended. Not sure if we should support html at this point.

**Comment by EnzoVezzaro** [comment]
> Not really a bug, this was intended. Not sure if we should support html at this point.

Yes, just checked with the user, he's fine now 👍🏽. 

Maybe we can add a quick regex check (or other method) on the content string. If it's html we can just pass it to the component without `markdownToHtml`.

Should solve this.

**Comment by EnzoVezzaro** [comment]
Closing as for [comment](https://github.com/oceanprotocol/market/issues/1603#issuecomment-1185301719)
