### ISSUE TITLE
Cannot run algorithm on a dataset that is free

### ISSUE THREAD

**Issue by umesh-spirinova** [oceanprotocol/market#1618]
Steps to repro - 

1. Create a free dataset.
2. Create an algo in the same network and provider.
3. Edit the dataset and select "Allow all algorithms" or algorithm you want to give permission to.
4. Press Submit.

Nothing happens in UI. Console shows below error -

_app-b4ad25b31e429259.js:1 No config found for given network '0xb1915627debeb3148c10e6e16f8c056d7f390456'

**Comment by mihaisc** [comment]
Is this till an issue? If so please give more details.

**Comment by bogdanfazakas** [comment]
issue confirmed, will take a look
