### ISSUE TITLE
Checksum is always empty for custom docker algorithm

### ISSUE THREAD

**Issue by umesh-spirinova** [oceanprotocol/market#1619]
1. Create a new algorithm and select Docker Image as Custom.
2. Fill all the steps and publish the algo.

The checkum is not picked from the docker image. it stays empty, can also be seen by activating debug mode.

![image](https://user-images.githubusercontent.com/109719287/181222473-97508a6d-f897-4a59-a664-b8b4ab7d2b00.png)

You can later not run this algo in any dataset unless you bypass the checksum error in code

**Comment by kremalicious** [comment]
This is not implmented, Compute-to-Data in v4 is not shipped yet. Changes had been done in the background to the way we deal with container checksums which will be implemented in market. The first part of this was shipped 8 hours ago in #1615, covering the default Docker images. Implementing the same thing for custom images is up next.
