### ISSUE TITLE
Compute jobs tab fails to show the results list on profile

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1620]
**Describe the bug**
When I go to the "Compute Jobs" tab in the profile page, the list doesn't appear. In console this shows up:

![Screenshot 2022-07-27 at 07 20 51](https://user-images.githubusercontent.com/13741335/181234867-fd10b929-3a46-4ff8-8de0-e5f1293f0b70.png)

In network:

`
{
    "context": {
        "consumerAddress": "0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e"
    },
    "error": "HTTPConnectionPool(host='15.206.100.41', port=8050): Max retries exceeded with url: /api/v1/operator/compute?providerAddress=0x1BDD96Fa11b44b392B6A760640A34504585c3b29&owner=0xC50ce98B13Aa9782cAc4aF6809007B2b035E599e&providerSignature=0x8ee30af4c9f0cdd110c1455da8247564eb64b8c5e899adbf0690710b4da662f56f4ca1d210aedf57bf2a068eab7f0e72ea74e082ae49e96a22cccbd6f3dcb38601&nonce=1658920538.626672&chainId=4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4b72072220>: Failed to establish a new connection: [Errno 111] Connection refused'))"
}
` 

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Compute Job'
3. See console

**Comment by mihaisc** [comment]
We need to do some basic checks so that if a providers fails we move on. This is basically a custom provider that is not working anymore.

**Comment by mihaisc** [comment]
Is this issue still there?

**Comment by bogdanfazakas** [comment]
I think we can close this
