### ISSUE TITLE
Profile images in publisher teasers not woking for some users

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1623]
![image](https://user-images.githubusercontent.com/26000280/181507311-7d56ed8c-e004-4319-b9ad-60c5b11942a1.png)

in my network tab there are some infura ipfs calls that are failing 
![image](https://user-images.githubusercontent.com/26000280/181527471-0ff3e8d5-0201-4df3-b86d-9c07719b7f9c.png)
ex: https://infura-ipfs.io/ipfs/QmWHkFZvQwGgw2WMwfpC91ofG8qdvTsUYbh8BX8dhA1Bp2
Not sure if they are relevant

**Comment by corrie-sloot** [comment]
The error message from Infura is "Public Gateway Is Not Supported Anymore - Setup a Dedicated Gateway"

I think if you setup a gateway, it will work. For example we created https://mpowered.infura-ipfs.io/
