### ISSUE TITLE
gas fee estimation is wrong on Polygon

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1633]
This seems too high:

<img width="559" alt="Screen Shot 2022-08-03 at 14 27 49" src="https://user-images.githubusercontent.com/90316/182619870-f74de88e-326d-4131-91f8-d29accc06bcc.png">

**Comment by mihaisc** [comment]
It's high quality artwork. We should wait until https://github.com/oceanprotocol/ocean.js/issues/1566 is done and then focus more on gas estimation.
