### ISSUE TITLE
npm run serve not working as expected

### ISSUE THREAD

**Issue by htcarr3** [oceanprotocol/market#1637]
**Describe the bug**

**To Reproduce**
Clone the app
`npm run build`
`npm run serve`

**Expected behavior**
I would expect this to point to the newly created ./out folder and serve the static content. Instead it points to public which is mostly empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/9591402/183525052-cf918f39-2ad6-4878-9d69-3d322d89e6da.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 

**Additional context**
Maybe this comes from a misunderstanding of how nextjs projects are typically done, let me know if I am off base here. Are you expecting devs to copy over the content of that folder into ./public? I am happy to push up a pr for this.

**Comment by mihaisc** [comment]
We never use that so it's an old version. The correct way would probably be `"serve": "next start",` .

**Comment by kremalicious** [comment]
`next export && npm run serve` should work, command was not updated when we moved from Gatsby to Next.js. Most likely we will remove this command

**Comment by htcarr3** [comment]
`"build:serve": "next export && npm run serve",`

Thoughts on this change? Also is there any interest in setting a ./.vscode/launch.json file with some default debug session configs?

`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Next.js: debug server-side",
      "type": "node-terminal",
      "request": "launch",
      "command": "npm run start"
    },
    {
      "name": "Next.js: debug client-side",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:8000"
    },
    {
      "name": "Next.js: debug full stack",
      "type": "node-terminal",
      "request": "launch",
      "command": "npm run start",
      "serverReadyAction": {
        "pattern": "started server on .+, url: (https?://.+)",
        "uriFormat": "%s",
        "action": "debugWithChrome"
      }
    }
  ]
}
`

**Comment by jamiehewitt15** [comment]
Yeah, the deployment instructions also need updating in the docs as well. I'll handle that https://github.com/oceanprotocol/docs/issues/1084

**Comment by htcarr3** [comment]
@jamiehewitt15, I can close this if you are incorporating this in your issue, don't want to duplicate things.

**Comment by jamiehewitt15** [comment]
The docs will have up to date instructions for a static deployment of the market when this is merged: https://github.com/oceanprotocol/docs/pull/1107

I've also added some links in the readme here to point people to the relevant guides in the docs: https://github.com/oceanprotocol/market/pull/1649
