### ISSUE TITLE
Integrate new error status codes from Provider

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1644]
Blocked by: https://github.com/oceanprotocol/provider/issues/523

Display user-friendly error messages for C2D failed jobs

**Comment by AnaLoznianu** [comment]
The provider issue is merged. We can start working on this one

**Comment by AnaLoznianu** [comment]
Waiting for the documentation of the provider errors before merging this

**Comment by bogdanfazakas** [comment]
fixed with #1940
