### ISSUE TITLE
Better error handling for basic template usage

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1653]
When downloading an asset published with the basic template: https://market.oceanprotocol.com/asset/did:op:bd81f459ff83ceeb06c917aa7a6e42c3d2e42ad805ad2ce028ed40bb39b46213 an error is thrown

<img width="1280" alt="Screenshot 2022-08-09 at 18 50 38" src="https://user-images.githubusercontent.com/84312885/183699305-abfb5c61-e904-4a6e-82a6-8aab1a672130.png">

When the basic template is used instead of the enterprise one, the consume fails with a Provider error. We should check which template is used and display a proper error message.

Please see: https://github.com/oceanprotocol/provider/issues/522#issuecomment-1212883303

**Comment by mihaisc** [comment]
Already an issue for this https://github.com/oceanprotocol/market/issues/1652
