### ISSUE TITLE
Fetch price from aquarius

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1654]
Get price from aquarius so we don't have to do multiple sub queries. 

```
"price": {
      "value" : 33,
      "tokenAddress": "0x0....",
      "tokenSymbol": "ocean"
}
```
If value is 0 the it's a dispenser so it's free
if the price object is empty  (`{}`) then no valid pricing was found.

Requires new aquarius deployment( > 4.2.0)
Aqua issue: https://github.com/oceanprotocol/aquarius/issues/853

**Comment by jamiehewitt15** [comment]
@mihaisc actually, I'm not sure this is going to work as aquarius isn't sending the fees. So it might need extra work in aquarius first. 

The subgraph sends the following info which we then use to calculate the final price, including the fees:

```
{
baseTokenAmount: "1.001"
consumeMarketFeeAmount: "0"
marketFeeAmount: "NaN"
oceanFeeAmount: "0.001"
}
```

**Comment by mihaisc** [comment]
You do this just for teasers mostly. In asset details it remains the same logic.

**Comment by jamiehewitt15** [comment]
> You do this just for teasers mostly. In asset details it remains the same logic. You just have to replace it in things like `AssetList` , so we don't have to use `getAccessDetailsForAssets` to get price. You just add it from aqua. You don't need fees for teasers. There is just the price.

Ok cool, fair enough

**Comment by AnaLoznianu** [comment]
Blocked till the new refactored aqua release as currently aqua doesn't deliver reliable pricing information
