### ISSUE TITLE
publish form: add entry for data context

### ISSUE THREAD

**Issue by jsotomayor** [oceanprotocol/market#167]
Add a new field where the data publisher can provide data context. For example, my company Transport Genie was the first data publisher on your new system but unless you previously understood the value of localized environmental data as livestock animals are in transit, i can see a lot of non-epidemiological data scientists gloss over the data set because they didn't know what real-world use cases that they can apply it to. Also by adding this data context, it would incentive the data publishers to put more time and effort into filling these fields correctly because it would lead to possibility a greater chance of their data being bought in the open marketplace

**Comment by trentmc** [comment]
There's a tradeoff. Every new field adds complexity for users.

Could context simply be given in the description? Or linked as a url to a more detailed page.

**Comment by jsotomayor** [comment]
yes i understand, i just wanted to make sure that there was an easy way for data purchasers to know the value of this data. we will be more descriptive and add it to the description
