### ISSUE TITLE
Testing manual

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#1673]
Sometimes, we need to test all scenarios in the market, especially when big updates are introduced.
By doing this manually, it's easy to forget about a edge case, or a small feature that is not used so much.  And bugs can be introduced.

Proposal:
 - have a .md file which describes all the tests that needs to be performed

In time, we can add more and more scenarios and flows

**Comment by jamiehewitt15** [comment]
We have an internal document on testing (created prior to the V4 release) which this can be based on.

**Comment by AnaLoznianu** [comment]
I'll take this on and create a test suite.

**Comment by AnaLoznianu** [comment]
The document for testing is available here: https://docs.google.com/spreadsheets/d/1yJx7QJ97i3ZHAMo3GzmGZ_WA4_s8j7mgEPLI7c1Ipis/edit?usp=sharing
