### ISSUE TITLE
@tippyjs/react: Cannot use `className` prop in conjunction with `render` prop.

### ISSUE THREAD

**Issue by catalin8v** [oceanprotocol/market#1692]
There is a warning in the console:
```
@tippyjs/react: Cannot use `className` prop in conjunction with `render` prop. Place the className on the element you are rendering. 
```

Exclude `className` from this object in order to fix it:

https://github.com/oceanprotocol/market/blob/4dca7d3442bbba51d98195150b78314967094234/src/components/%40shared/atoms/Tooltip/index.tsx#L63

____________

```
const { className, ...restProps } = props
const { content, children, trigger, disabled, placement } = props
```

and use `restProps` instead if `props`

**Comment by AnaLoznianu** [comment]
Hello @catalin8v! Thanks for opening this issue :) Considering you also have the solution here, can you please open a PR? 
Thanks for your contributions! 🙏
