### ISSUE TITLE
unnecessary comparation

### ISSUE THREAD

**Issue by catalin8v** [oceanprotocol/market#1693]
https://github.com/oceanprotocol/market/blob/4dca7d3442bbba51d98195150b78314967094234/src/%40utils/aquarius.ts#L192
this could be `if (!didList.length) return`
_________________
https://github.com/oceanprotocol/market/blob/4dca7d3442bbba51d98195150b78314967094234/src/%40utils/aquarius.ts#L214
this could be `if (!dtList.length) return`

![Screenshot 2022-09-17 at 11 47 19](https://user-images.githubusercontent.com/23175624/190848657-a00e151b-e5a5-48c2-9e4b-b6f35d6a8ddf.png)

**Comment by AnaLoznianu** [comment]
Hello [@catalin8v](https://github.com/catalin8v)! Thanks for opening this issue :) Considering you also have the solution here, can you please open a PR?
Thanks for your contributions! 🙏
