### ISSUE TITLE
Add ipfs and arweave storage type support

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1711]
Support all 3 storage types : url, ipfs, arweave

![Screenshot 2022-09-27 164004](https://user-images.githubusercontent.com/26000280/192542432-d298f278-671e-489e-a1a1-88ff0c4fd695.png)

For ipfs

![Screenshot 2022-09-27 163336](https://user-images.githubusercontent.com/26000280/192541188-ea33d88b-9cd3-4b12-b838-033f159e30ad.png)

Structure : 
```
 {
      "type": "ipfs",
      "hash": "XXXX"
    }
``` 

For arweave 

![Screenshot 2022-09-27 163848](https://user-images.githubusercontent.com/26000280/192542250-47d05ca6-7445-4f5c-bb3a-b2c973e0bffd.png)

Structure:
```
{
  "type": "arweave",
  "transactionId": "a4qJoQZa1poIv5guEzkfgZYSAD0uYm7Vw4zm_tCswVQ"
}
```

The validation is done the same way on the `fileInfo` endpoint, using the relevant structure.

WIP: 

- [X] add new fields to publish form
- [X] handle `storageType` selection UI
- [x] integrate `Ipfs` and `Arweave` type from `oceanjs` lib (opened an issue for ipfs, [missing interface](https://github.com/oceanprotocol/ocean.js/pull/1640))
- [x] handle txs with different `storageType` in publish
- [x] change edit (UI & Logic) accordantly

**Comment by EnzoVezzaro** [comment]
Hi @AnaLoznianu 👋🏽, I have some question regarding the implementation:

- Can users edit the storage type?
- Are the file and sample file fields managed together, right? I guess the answer is yes, but for example: If I select a storage type, that means that this type is going to be used for both fields right (file and sample file) ? or are they handled independently?
- What happens when we edit? For example: If the user changes the storage type, does he need to enter both file and sample file again every time? 

Thanks 😊

**Comment by AnaLoznianu** [comment]
Hello @EnzoVezzaro 
1. Well, it's like with each file URL. You cannot edit just the storage type. If the user wants to edit the file, he'll need to go to the edit page, pick the storage type he likes and add the details. 
2. No, they are separate things. The user can use Arweave for the file and IPFS for the sample file.
3. The user cannot change just the storage type. In edit, we don't have information about his file URL and the storage type he used during publishing. He will need to go, pick a storage type and enter the details if he wants to edit the details(URL, transaction id) of his file.
I am on the fence about the sample file so cc @mihaisc

**Comment by mihaisc** [comment]
Yes on all points except the sample. The sample is just a url, it's out of the scope. No changes needed for the sample file

**Comment by EnzoVezzaro** [comment]
> 1. Well, it's like with each file URL. You cannot edit just the storage type. If the user wants to edit the file, he'll need to go to the edit page, pick the storage type he likes and add the details.

Yes, of course 👍🏽 if the user changes the storage type, he needs to change the file also. Probably I wasn't clean on the question, sorry 😅what I meant was, our backend is already setup for this, right? The users can change the storage type (with new details of course) at any time, right? I think so, but I just want to make sure it's.



> 2\. No, they are separate things. The user can use Arweave for the file and IPFS for the sample file.

Ok, then we need add another "Storage Type" field for the Sample file 🤔 I don't like having two "Storage Type" fields in the UI, can we do something like this instead: 

<img width="1206" alt="Screenshot 2022-10-27 at 09 23 02" src="https://user-images.githubusercontent.com/13741335/198298039-efb05568-75b4-47b4-a493-b61d5e910b07.png">

This is just a quick UI in figma 😅 don't pay to much attention to the details 😂 What I mean is incorporating the dropdown inside the field. I think is more pleasant when using on both file and sample file

**Comment by mihaisc** [comment]
> Ok, then we need add another "Storage Type" field for the Sample file 🤔 I don't like having two "Storage Type" fields in the UI, can we do something like this instead:

No, check my previous comment (we probably were writing at the same time  😄  ). No changes on the sample.

**Comment by EnzoVezzaro** [comment]
> we probably were writing at the same time

yes 😂. Ok, got it 👍🏽 but don't you think it will confuse the user?

**Comment by mihaisc** [comment]
why? The file is encrypted and kept safe. The Sample file is just a string, a url , it has no preferential treatment. Implementing those storage types for sample needs a totally separate implementation that is out of scope.

**Comment by EnzoVezzaro** [comment]
> The file is encrypted and kept safe. The Sample file is just a string

well that's also true 👍🏽
