### ISSUE TITLE
Enhance the “Sharing Profile” functionality

### ISSUE THREAD

**Issue by andreaarmanni** [oceanprotocol/market#1713]
Currently someone’s own profile URL looks like this: `https://market.oceanprotocol.com/profile`

I propose to either: 

- [ ] Edit the URL to include the wallet address (or ENS, when present) at the end or;
- [ ] Add a “Share Profile” button in the Profile page as a visible CTA like in the following example: 
<img width="662" alt="Screenshot 2022-09-29 at 14 08 46" src="https://user-images.githubusercontent.com/35074712/193040100-97f33006-60da-45ba-b9a2-219a9c2b3b28.png">

Objective: Increase profile sharing amongst data publishers to drive more traffic to OM -> leading to better profile custom/optimisation -> more data on OM

**Comment by mihaisc** [comment]
Cool idea. 
We can implement the [Web Share Api](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), seems supported by most.  The implementation seems easy enough. 
We can have two buttons
1. Copy link  : just add the link to clipboard
2. Share : does the web share thingy

**Comment by kremalicious** [comment]
> Edit the URL to include the wallet address (or ENS, when present) at the end or;

I don't get this, what is the requested behavior here? This is already present. Either use the address, or ENS name in the URL. If we find ENS name, address in URL is replaced with ENS name. This exactly follows [use case 1 of ENS design guidelines](https://docs.ens.domains/dapp-developer-guide/front-end-design-guidelines). 

Usually people know how to share a URL as all OS have their builtin mechanisms for that so. But as long as we use Web Share API triggering the default OS share sheets it's fine.

**Comment by mihaisc** [comment]
The thing is if you go to your profile page the url is just /profile , so you manually have to add address or ens. The copy link button i though for those who don't support web share ... firefox 😁  . But you are right , too many buttons. I think just a small share would be ok from all points of view.

**Comment by andreaarmanni** [comment]
Currently if you want to share your URL with, ideally, a client the only way is to assemble the URL yourself. 
What I mean by this is that if you click on your profile and copy your URL it doesn't contain any profile ID. 

That's why I proposed 2 solutions, either the first one or the second one should work.

**Comment by kremalicious** [comment]
> The thing is if you go to your profile page the url is just /profile , so you manually have to add address or ens.

ah, good point, so only for own profile. This is mainly a technical reason so for better UX right solution here would be to always attach address/ENS name to the URL at all times

**Comment by mihaisc** [comment]
Honesty just adding a small share button here and on asset would fix everything, with minimal changes and no potential extra bugs :d

**Comment by jamiehewitt15** [comment]
> Honesty just adding a small share button here and on asset would fix everything

@mihaisc @kremalicious so the idea is a share button that copies the profile URL to the clipboard? No social share options?
