### ISSUE TITLE
Publishing without setting tags sets empty strings

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1727]
When publishing and not touching the tags field, in the final DDO we get this:

```json
"tags": [
  ""
]
```

Expected behavior is to have empty array or `null` when no tags have been set.

**Comment by EnzoVezzaro** [comment]
It's this still valid? Couldn't replicate what's in description. During publishing I see an empty array:

<img width="1000" alt="Screenshot 2022-10-10 at 09 12 16" src="https://user-images.githubusercontent.com/13741335/194874483-62ece08c-d597-4e53-84c3-00038fc3bb2f.png">

In edit the same:

<img width="1000" alt="Screenshot 2022-10-10 at 09 06 04" src="https://user-images.githubusercontent.com/13741335/194874611-6f5a9c38-54a1-4507-8efa-b4afbb15cb32.png">

What I did find is the fact that the submit button is enabled (without doing any change), and when you click it, it does nothing. So, there's an issue there, but it's not related to what described. 

https://user-images.githubusercontent.com/13741335/194874909-8127b1e1-7732-4f36-a2e2-69d3f4f9d46c.mp4

**Comment by jamiehewitt15** [comment]
Yeah, I tested this out ([this asset](https://market.oceanprotocol.com/asset/did:op:2c814b9b8bf18a3f78f1d3b48a02d154047729994a5a0352f0a5d5e5a82468c4)) and also got the same as you @EnzoVezzaro 

```
"tags": [],
```

**Comment by mihaisc** [comment]
also can't replicat [example](https://market.oceanprotocol.com/asset/did:op:87864f6b02fc8c36a5feaac6b9026c28efe5a57e7c1609004c101cfbcd8e1faf)
