### ISSUE TITLE
Search button does not work

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/market#1735]
**Describe the bug**
Pressing the search button after entering text in the search box has no effect.

**To Reproduce**
1. Go to market.oceanprotocol.com
2. Enter some text in the search box
3. Click on the search button 

**Expected behavior**
The results list is displayed.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome (version106.0.5249.103) or Microsoft Edge (version 106.0.1370.42)

**Comment by kremalicious** [comment]
firing search either with enter or by using the search icon is intended so this is valid bug.
