### ISSUE TITLE
 Cap the staking amount

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#175]
Cap the staking amount, for a given Eth address, to 10% of a pool. (Only from GUI) (Can only do after initial publish of course) (This is easier to implement than capping OCEAN)

**Comment by trentmc** [comment]
I believe this ticket is obsolete in light of the "Better IDOs" work (V4). That is, with that work, this issue is unneeded. Therefore, closing. Reopen if you believe otherwise:)
