### ISSUE TITLE
encourage datatoken holders to put back datatoken into pool

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#176]
tbd

**Comment by trentmc** [comment]
I recommend we close this. Here's why:

- Better IDOs epic will solve this definitively
- Doing this before that increases the risk of DT Minting Attack by publisher

@kremalicious ok?

**Comment by kremalicious** [comment]
Not sure, yet. While it could be the "novelty effect" we see that pattern increasing since the trade feature rollout: buying the datatoken instead of pooling, and HODL'ing it. So draining the pool of datatokens, effectively blowing up the price. So if we want to make people understand the advantages of pooling over only buying datatoken, we should nudge them in UI somehow

**Comment by trentmc** [comment]
This isn't enough of a priority to happen anytime soon, and by the time it might, [Better IDOs](https://github.com/oceanprotocol/multi-repo-issue/issues/36) handles it. On roadmap for Q4.
