### ISSUE TITLE
Round veOCEAN amounts

### ISSUE THREAD

**Issue by corrie-sloot** [oceanprotocol/market#1769]
On the market homepage, at the bottom of each asset card, it is difficult to discern commas and decimal points in the veOCEAN value, especially with the grey colour.

For example, it is hard to tell that 403,832.438 veOCEAN is 403 thousand and not 403 million.

If this value was rounded (as is done in other places in the market), it would make comparing the values easier.

**Comment by jamiehewitt15** [comment]
Yeah I see what you mean, it would be clearer if it was rounded.
