### ISSUE TITLE
Allow publishers to edit paymentCollector

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#1775]
Sometimes, a publisher will decide that entire revenue for a service should be sent to a different address (not the publisher's one).

Let's allow this in UI as well (maybe in Edit Metadata).

It's already in ocean.js (https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/Datatoken.ts#L418), so this is mostly design

Caller must be:  NFT.owner() or have feeManager rights

To get the current collector account, use https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/Datatoken.ts#L458

**Comment by AnaLoznianu** [comment]
We need to add information on the paymntCollector on the docs before having the UI. So people understand what it's all about: https://github.com/oceanprotocol/docs/issues/1150
