### ISSUE TITLE
Allow publishers to retire their assets

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#1776]
Sometimes, a publisher will decide that he/she wants to retire their asset.
We should allow this in UI as well.

It's already implemented in the backend (https://github.com/oceanprotocol/ocean.js/blob/main/src/contracts/NFT.ts#L639)

This requires UI work and some thinking about warning messages (are you sure, etc..)

Only nft.owner can call this

**Comment by mihaisc** [comment]
We can have a state dropdown in edit. In profile we will show the owner all his assets, regardless of state. There he can switch back  the state to 0 if he wants to

**Comment by kremalicious** [comment]
For the time being:

1. Go to NFT etherscan page (hover over NFT image `i` in market).
2. Go to contract tab, write contract.
3. Go to `setMetaDataState`, type your [desired state](https://docs.oceanprotocol.com/core-concepts/did-ddo#state) and write, done.

**Comment by AnaLoznianu** [comment]
Blocked by the lack of specs: https://github.com/oceanprotocol/docs/issues/1159
