### ISSUE TITLE
Data Farming - Round Allocation vs. Current Allocation

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/market#1791]
We have updated the /nft_info route in dfsql to include the round_allocation and the current_allocation.
- ve_allocated is the number Data Farming calculates to distribute rewards.
- ve_allocated_realtime is just a straight sum of all voting power allocated to each dataNFT.

Right now, marketplace is reporting ve_allocated
You may want to change this to ve_allocated_realtime, or report both.

**Comment by mihaisc** [comment]
Thanks, Alex already created an issue in `Aquarius` , that will be enough. No further changes needed in the market.
