### ISSUE TITLE
Gateway issue when navigating directly to publish route

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/market#1808]
When navigating directly to `https://market.oceanprotocol.com/publish/1`  by entering the url, user will be met w/ gateway error.

![screen_shot_2022-12-02_at_12.27.32_pm.png](https://images.zenhubusercontent.com/601eeb154030993736fc619e/41555897-247b-4424-bd04-2223bf756b77)

### DoD:
- [ ] User can navigate directly to publishing url w/o experiencing gateway issues

**Comment by jamiehewitt15** [comment]
Can you test this again? It worked for me straight away, maybe it has been fixed in another PR

**Comment by kremalicious** [comment]
Netlify issue, solved for time being by using Vercel deployment
