### ISSUE TITLE
CI job to purge Cloudflare cache 

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#1810]
Create individual workflow file which only gets triggered upon every `main` push, which hits the Cloudflare API and purges the `market.oceanprotocol.com` cache.

Most likely whole cache for all subdomains has to be purged so needs to be investigated. Ideally only caches for `market.oceanprotocol.com` get purged.

Vercel has a good explanation of the problem which applies to Netlify too https://vercel.com/guides/using-cloudflare-with-vercel#summary

**Comment by mihaisc** [comment]
not using cf so no need for this
