### ISSUE TITLE
Unlisted assets not visible in the profile page

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1826]
Assets with state [5(unlisted)](https://docs.oceanprotocol.com/core-concepts/did-ddo#state) should be visible on the profile page, but they are not.

Example: https://market.oceanprotocol.com/asset/did:op:b4c0ce0fb3402b8fc4d164da1aed2e581b6ec9d20b22c5fa84c3575686779124 

The asset's state was updated with tx: https://polygonscan.com//tx/0x6ba2290c9c150e467ff9c0d636080008d85eb0f3739c623c31347eff5b9427c2

The Ocean Market is connected to the profile that published this asset. 

<img width="1273" alt="Screenshot 2022-12-09 at 14 42 31" src="https://user-images.githubusercontent.com/84312885/206704975-49d0cc01-b4d5-443d-894c-b864d8226336.png">

**Comment by jamiehewitt15** [comment]
Can you have a look at again? The asset has ` "state": 0` and it's visible in the profile.

Profile page: 
![image](https://user-images.githubusercontent.com/20739535/206719353-1ae2265f-8fd9-4dbc-9fdc-1128138eafc0.png)

Asset DDO:

![image](https://user-images.githubusercontent.com/20739535/206719533-7c69fb6e-35b7-493f-a43e-87d15c24ff1c.png)

**Comment by jamiehewitt15** [comment]
The implementation that @mihaisc did was to make them visible on the profile page for the publisher but not anyone else: https://github.com/oceanprotocol/market/pull/1749 

That's also what was discussed on the issue at the time: https://github.com/oceanprotocol/market/issues/1747#issuecomment-1283609321

**Comment by AnaLoznianu** [comment]
You are right, after a hard refresh, the asset showed up. Thanks :)
