### ISSUE TITLE
Google doc file urls should be validated similarly to G drive url's

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/market#1831]
file url input validation for gDrive assets can be bypassed if the user is hitting the validate multiple times in a row

**Comment by jamiehewitt15** [comment]
Have you recreated this? The "validate" button is deactivated when you enter a Google drive link so I'm not sure how you can click it multiple times. Was it definitely a Google Drive link or was it a Google doc?

**Comment by EnzoVezzaro** [comment]
yeah, I'm not able to replicate this either

**Comment by bogdanfazakas** [comment]
it was G doc file sorry for confusion, forgot to update the title

**Comment by jamiehewitt15** [comment]
Ok cool, yeah google docs make sense. I can do a quick fix for that
