### ISSUE TITLE
The UI is messy for NFT published with non-existing image URLs

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1833]
Example asset: https://market.oceanprotocol.com/asset/did:op:989fe8b28fb6638da0bb50ab184f918acde4d3a65d8c39a2b83207da95d5d4d9
Assets published by ocean.py miss the PNG for the data NFT and that is causing a weird UI in the market.

We cannot expect that all published assets have all the fields properly set so we should make sure things are looking ok even if something is missing.

![Screenshot 2022-12-13 at 17 16 38](https://user-images.githubusercontent.com/84312885/207372155-998da5fd-61fb-4523-a5c9-00be12a100dc.png)

**Comment by jamiehewitt15** [comment]
Yeah good spot, that doesn't look good

**Comment by kremalicious** [comment]
that asset's image URL is set to `https://oceanprotocol.com/nft/` so from technical standpoint this has an image set, it just doesn't exist. If there is no image set at all we would show a fallback image. We won't add logic to detect if a set image actually remotely exists

**Comment by AnaLoznianu** [comment]
Issue moved to [oceanprotocol/ocean.py #1219](https://github.com/oceanprotocol/ocean.py/issues/1219) via [**Zenhub**](https://www.zenhub.com/)
