### ISSUE TITLE
Add hosting info to Asset Details

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#1834]
With https://github.com/oceanprotocol/provider/pull/584, we are going to have filetype available when calling provider.FileInfoEndpoint, so we can add it to asset details and make it visible for all users

TBD: pictures or text

**Comment by kremalicious** [comment]
Already implemented since the very beginning of market, always shown on top of file icon when present in fileinfo response. Does anything change to how we get the file type right now?

**Comment by AnaLoznianu** [comment]
If I am not wrong, this is related to where the file is hosted: ipfs, arweave, simple URL.

**Comment by EnzoVezzaro** [comment]
In PR #1794 we have the Current state:

- IPFS Assets are displayed correctly

DDO: did:op:b5b6cb8620c7100f370961040a21e098d8006e596a915d83db086d768a8ef749

Payload:
`{
    "did": "did:op:b5b6cb8620c7100f370961040a21e098d8006e596a915d83db086d768a8ef749",
    "serviceId": "a504dc5037573f370302a640e8fbd141509f1c143621874ad030c5570175f94f",
    "checksum": false
}`

Response: 
`{
    "contentLength": "80556",
    "contentType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "index": 0,
    "type": "ipfs",
    "valid": true
}`

- Arwave assets are displayed correctly

DDO: did:op:e9831a65f2064b66a36b1f5e39353174975933819e081257e5a8fa0692c276c2

Payload:
`{
    "did": "did:op:e9831a65f2064b66a36b1f5e39353174975933819e081257e5a8fa0692c276c2",
    "serviceId": "7e8a1b2b959b2b4a7698be6cd6ba5ce3cba26b1a765b1ee50438164830072fef",
    "checksum": false
}`

Response: 
`{
    "contentLength": "88512",
    "contentType": "image/png",
    "index": 0,
    "type": "arweave",
    "valid": true
}`

On https://github.com/oceanprotocol/provider/pull/584 I don't see `GraphQL` or `SmartContract` storage type, we might need to add those too.
