### ISSUE TITLE
404 page not working correctly

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1847]
**Describe the bug**
404 page doesn't seems to work correctly: the dark mode doesn't work.

Link: https://market.oceanprotocol.com/profile/autobotocean.eth/0xEB18BaD7365a40E36A41fB8734eB0B855d13b74F

https://user-images.githubusercontent.com/13741335/211004457-87c81663-5123-4592-a702-f32b9ce36608.mp4

the page scheme color should be dark not light.

**Comment by jamiehewitt15** [comment]
Yeah, I'm seeing the same issue
