### ISSUE TITLE
show user's pool transactions for a specific dataset

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#185]
The pool transactions list on history page loads painfully slow, and it would be useful to show pool transactions in place on a specific asset details page. Cause when deciding on interacting with a pool it's crucial to know what was put in/removed before.

Could be just simple table below the asset actions widget. And if we can have a method with a reduced query only for specific pool we might get a faster result.

**Comment by alexcos20** [comment]
you can use https://github.com/oceanprotocol/ocean.js/blob/main/src/balancer/OceanPool.ts#L964

once aqua will cache the pools, the method will use that instead of querying the chain

**Comment by kremalicious** [comment]
quick test, oh boy is that useful! Also loads pretty fast 

<img width="511" alt="Screen Shot 2020-11-02 at 13 35 42" src="https://user-images.githubusercontent.com/90316/97868616-505ebb80-1d10-11eb-9ae3-b3c6661d0432.png">
