### ISSUE TITLE
Remove 'Infinite approval' setting

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#1854]
The value of this setting was used for AMM pools, but now that pools have been deprecated, this is not needed anymore.
- [ ] Remove the option from the settings dropdown
- [ ] Remove any reference to the infinite approval variable

<img width="302" alt="Screenshot 2023-01-13 at 16 38 48" src="https://user-images.githubusercontent.com/84312885/212346965-57c183ca-2eea-45af-85b3-ba1a9cd9bb6b.png">

**Comment by jamiehewitt15** [comment]
Closed by https://github.com/oceanprotocol/market/pull/1857
