### ISSUE TITLE
header disappears on purgatory assets

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1878]
**Describe the bug**
I have an asset in purgatory that has no header (title).

<img width="1300" alt="Screenshot 2023-02-02 at 09 16 43" src="https://user-images.githubusercontent.com/13741335/216335879-4c8b2ac1-92bc-434a-ada6-f29c74ddb302.png">

Asset: https://market.oceanprotocol.com/asset/did:op:4f8e2a408c136ae9a50768728df8b9371a97d12b32a285ae6ec03f8c920f5944

**Comment by kremalicious** [comment]
all assets in purgatory behave like this based on what the code says:

https://github.com/oceanprotocol/market/blob/b5a853fcf0b620ca84843974d602e05ccc14ba8d/src/components/Asset/index.tsx#L19

Not fully sure about the exact reasoning anymore but we might not want to change anything here.

**Comment by jamiehewitt15** [comment]
> Not fully sure about the exact reasoning anymore but we might not want to change anything here.

I assume it's in case someone has written something offensive in the title that we wouldn't want to show. So I'd suggest it should stay as it is.
