### ISSUE TITLE
Implement SW for positive-label lists (Made pledge, Data launch partner, etc) for trust signals in UI

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#189]
- create a new repo like `list-datapartners` or `list-official` similar to token lists standard
- define schema, can be as simple as providing data example in README
- add first entries, start with our official launch partners
- define and outline process to get onto that list
- publish as npm module

In UI then output those verification signals, like an official badge, social links etc.
- official badge on asset teaser
- modify `Published by` line on asset details
- new row on frontage for those publisher assets

This would add an editorial layer in our UI which, despite the centralized mechanism, is justified and clearly communicated as a curated list by the Ocean Protocol team. Later on, we could open up another `list-verified` which would be community maintained.

_To be discussed..._

`0x000000000000000000000.json`
```json
{
  "name": "Publisher Display Name",
  "links": {
    "home": "https://publisher.com",
    "twitter": "https://twitter.com/publisher"
  }
}
```

**Comment by trentmc** [comment]
This is a dangerous precedent because it restricts access to just a small number of players. And, who gets to be the gatekeeper?

**Comment by trentmc** [comment]
Won't stop IP violation, but will help OCEAN stake go to better datasets in the near term. Maybe remove later.

**Comment by trentmc** [comment]
Call "Data Launch Partners" list

**Comment by trentmc** [comment]
I had a discussion with Razvan this morning. We are in sync on the current recommendation:

- Never use labels that imply a stamp of approval: "verified", "authenticated", "partner" (beyond launch partners)

- Use these labels:
  - `"pledged"` -- pledged to not sell DTs for OCEAN, to not stake way more DTs in the pool, and to not rug pull; pledged to only remove 1% per week. Gave contact information that has been verified.
  - `"data launch partner"` -- one of the 8ish partners that launched with Ocean. (Do *not* grow this list). At some point, remove this label completely.
  - `"publicly traded"` -- is a publicly-traded company that must follow public-company rules and has reputational skin-in-the-game

For each of these three labels above, the SW needs: 
- a JSON list of it
- a UI affordance to show. E.g. sea animal for each + accompanying tooltip.

Finally, we'll want to rename the repo from `list-datapartners` to e.g. `positive-labels-list`.

Each of the three labels above also has an accompanying process, of how to get into the list. That process is outside of the scope of this issue, and instead is in [FIXME issue].

**Comment by kremalicious** [comment]
this issue was done and should have been closed instead of repurposing it, nothing in here relates to the marke code. As soon as we know what needs to be done in market, we can add an issue for it. I do not know why this issue exists when there are epics and sub-epics and 3 other issues in multiple repos saying the same thing.

**Comment by trentmc** [comment]
In working on the policies it became clear that having a "data partners list" is infeasible, because it places too much onus on OPF (as I'm sure you would agree with). The solution is to have more narrowly scoped claims that can be authenticated. 

There are 3 separate tasks do be done roughly 3 separate groups of people: write the policy, implement the sw, populate the lists. They are all grouped into one overall epic.

The sw part of the lists needs to be inplemented. It could be done in this issue (basically as a tweak of scope), or another issue. I'm fine with either.

At the end of the day, the market needs to supply positive signals to users in a way that doesn't burden opf.

**Comment by trentmc** [comment]
> [Matthias] this issue was done and should have been closed instead of repurposing it

> [Trent] The sw part of [many positive-label lists] needs to be implemented. It could be done in this issue (basically as a tweak of scope), or another issue. I'm fine with either.

I thought about this more. It makes sense to go with the suggestion you made, Matthias. So renamed this issue to the original narrower scoping, and created a new issue for the broader scope stuff (not high priority at this time). [Here](https://github.com/oceanprotocol/list-datapartners/issues/6)
