### ISSUE TITLE
Mumbai not working while connected to Metamask Mobile Wallet through WalletConnect 

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/market#1897]
this error is raised many times in the console.

![image](https://user-images.githubusercontent.com/13447142/225684893-a2fdaf04-cd5d-4b05-809e-e8e87c91722c.png)

**Comment by AnaLoznianu** [comment]
Re-test this issue with wallet connect v2

**Comment by bogdanfazakas** [comment]
Tested and happy to announce that this is no longer an issue once bumping to wallet connect v2 🎉 
<img width="1665" alt="Screenshot 2023-07-14 at 17 20 05" src="https://github.com/oceanprotocol/market/assets/13447142/4606a008-4aff-4dc2-a9c1-05b15653302e">
