### ISSUE TITLE
node 16.13.1   with and without legacy peers..   .js doesnt compile

### ISSUE THREAD

**Issue by johnda98** [oceanprotocol/market#1919]
![Screen Shot 2023-05-05 at 8 26 15 AM](https://user-images.githubusercontent.com/13384285/236470507-fefaa0c4-62c6-4194-b8fa-d099a1858577.png)
![Screen Shot 2023-05-05 at 8 26 21 AM](https://user-images.githubusercontent.com/13384285/236470514-08f367e4-998b-450e-abf5-20632cc65e4a.png)

**Comment by jamiehewitt15** [comment]
Yeah, you need to use node 18

**Comment by johnda98** [comment]
> If you are using multiple different versions of node if different projects, we recommend running the `nvm use` command, which will select the right version of node for you

i use brew as pm. .. yes yr Docs need updating.

**Comment by johnda98** [comment]
yes 18.. docs say 16.


*John D Allen.*



*Voice  +1 417 300 4812 ** CST  | ***@***.***
***@***.***>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | johnda98#4728 - discord.*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.
