### ISSUE TITLE
Error trying Market+Barge

### ISSUE THREAD

**Issue by chusweb** [oceanprotocol/market#1924]
When trying to deploy on Linux the Market (fix/issue-fix-barge-connection) with Barge, the following error appears in console

`[MetaFull: getInitialPaymentCollector] Error: This contract object doesn't have address set yet, please set an address first.`

**Comment by AnaLoznianu** [comment]
This is done and fixed via the PR Bogdan linked. Thanks for raising the problem with us. Please let us know if you face other issues
