### ISSUE TITLE
Allow google storage files

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1934]
**Describe the bug**
If you try to use a file on google storage, the market blocks your request which is right for google drive, but not for google storage.

<img width="965" alt="Screenshot 2023-06-15 at 16 31 21" src="https://github.com/oceanprotocol/market/assets/13741335/3413a429-f2a4-4f4f-9fce-cf5e3e436d3b">

**Comment by impactcapital** [comment]
Can we have Microsoft Office OneDrive solution?

Respectfully,
Silvio


* If urgent, pls call.

-------------------------------------

Silvio F. Pupo | Logos Capital

MIA•DC•SEU•TOK•ACC•LAG•BOG

360 NW 27th Street, Miami, FL 33127

Cel: +1.786.355.4261 | Tel: +1.818.564.6708

e: ***@***.******@***.***> w: www.LogosCapital.io <http://www.logoscapitalgroup.com/>

-------------------------------

All U.S. securities transactions are handled via SEC registered Broker Dealer(s), Member FINRA, SIPC, MSRB| This message may contain information that is confidential or privileged. If you are not the intended recipient, please advise the sender immediately and delete this message.

<https://aka.ms/o0ukef>
________________________________
