### ISSUE TITLE
File download fails 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1938]
downloading this https://market.oceanprotocol.com/asset/did:op:8de687b14e5181c160a8ab602038f16ddc6557ed3ab494d4bc488d221686164d

returns a json with `{"error":{}}`

**Comment by AnaLoznianu** [comment]
@bogdanfazakas I need your help a bit. The link of this file has an issue, but one of the problems that I'm seeing is that the loader never stops. I have the tab opened for > 10 minutes and I cannot tap on buy.  ![Screenshot 2023-07-25 at 12.11.38.png](https://images.zenhubusercontent.com/60a2262e74d8191993b88a11/d36e8ff5-1c81-48fd-9679-0f13af834147)

**Comment by AnaLoznianu** [comment]
Even if the file info endpoint failed and the initialize endpoint, the spinner is still displayed: 

![Screenshot 2023-07-25 at 13 37 37](https://github.com/oceanprotocol/market/assets/84312885/be8a9fbb-f64f-4e12-ac98-fea39aefcbbb)

**Comment by mihaisc** [comment]
@AnaLoznianu @bogdanfazakas  status on this? i have a feeling it was fixed in another issue

**Comment by AnaLoznianu** [comment]
No, this issue still persists
