### ISSUE TITLE
Theming from env variable

### ISSUE THREAD

**Issue by ishmeet121** [oceanprotocol/market#1944]
I want to have multiple theming as per company theming policy who is using this marketplace.

Can we setup a value in env file and use that to apply different theme on build time.

Current mode support changing color and font on static css files

**Comment by jamiehewitt15** [comment]
It's not something that's part of our current pipeline but it's definitely possible. Everything is open source so you could open a PR to work on this if you are interested?

**Comment by mihaisc** [comment]
thanks for the suggestion. I hope you managed to make it work into your company. We are not planning on adding this type of feature since anyone who would modify the UI/UX based on their needs.
