### ISSUE TITLE
File input not always populated in edit form

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/market#1949]
When using big files or api's behind the url used when creating the file, the file input doesn't get populated always which makes the whole validation form to fail and the submit button can't be used being disabled.
Eg in the image below, also in the debug the files type is no longer 'hidden' it defaults to 'ipfs' when this is reproduced.

![Screenshot 2023-07-20 at 1 19 43 PM](https://github.com/oceanprotocol/market/assets/13447142/33bd4d52-5e5e-4143-b176-16034768ea37)

**Comment by mihaisc** [comment]
So this is related to big files. Any proposed solution? And what would be the effort?

**Comment by bogdanfazakas** [comment]
> @bogdanfazakas let's move this to someone else ;)

agreed, I was not able to reproduce the issue (tried big files 1gb, url, ipfs etc, rest-api's etc), 
tho if we can reproduce it somehow i'm happy to help with fixing it :)

**Comment by EnzoVezzaro** [comment]
This is so weird, but I found a way to reproduce it. 

- Go on your nework tab
- Set "slow 3g"
- Refresh

If the internet connection is slow, for some reason the file input gets override / cleared. 

https://www.loom.com/share/982976088011432f97e232aec528f7e3?sid=1f54558a-8dcc-41ca-b2fb-778d39c08c3e

I'll look into it 👍🏽
