### ISSUE TITLE
Free algorithms not displayed in c2d

### ISSUE THREAD

**Issue by bogdanfazakas** [oceanprotocol/market#1964]
- free algorithm are not displayed in edit compute section 
- free algorithms are not available in algorithm selection list for datasets with allow all algorithms true
- The main flow starts from the assets. So, let's remove the component that displays the list of assets for an algorithm

**Comment by AnaLoznianu** [comment]
The main flow starts from the assets. So, let's remove the component that displays the list of assets for an algorithm

**Comment by AnaLoznianu** [comment]
@bogdanfazakas please check the attached PR as well. In the meantime, Luca decided to look over
