### ISSUE TITLE
Consumer parameters fields redirect to blank page

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/market#1979]
**Describe the bug**
Consumer parameters fields redirect to blank page. When filling the consumer parameters for algorithm (also for dataset additional information regarding user data that can be specified for dataset publish) at the publishing part (publish/1), it redirects the user to a white page of Ocean Market.

**To Reproduce**
1. Go to `Metadata` step when publishing an algorithm
2. Check that the algorithm has consumer parameters (custom data)
3. Fill one field and click to fill another one

**Expected behavior**
To be able to complete all the fields necessary for custom data

**Screenshots/ Screen recordings**

https://github.com/oceanprotocol/market/assets/50501033/7b1b8992-1528-4209-aeb6-89282eaf4bfe

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Browser Chrome

**Comment by LucaMilanese90** [comment]
The issue seems to be connected to the changes made in https://github.com/oceanprotocol/market/pull/1965/commits/5186f5aa6eb6f380850e17d7b24877156f7ea451

**Comment by mariacarmina** [comment]
Updated the description, also happening for user data filed when publishing a dataset.
