### ISSUE TITLE
Remove subgraph query from algorithm component 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#1994]
In the algorithm component we are doing an aquarius query and then a subgraph query to get the prices. Keep the query when you select the algorithm, we want to calculate the price once the user selects an algorithm
<img width="463" alt="image" src="https://github.com/oceanprotocol/market/assets/26000280/9ca134b9-92da-4511-956d-a9c37d393b95">

In the list we can just put the price we get from aquarius, it's good enough.

**Comment by EnzoVezzaro** [comment]
I'm looking at the code. The price gets calculated when you select an algo, what do you mean for "we want to calculate the price once the user selects an algorithm" (it's already like that)?

Basically we need to:

- [ ] remove subgraph query from component (only use aquarius)
- [ ] show the price from aquarius (i'll check again, but it seems already like that)

**Comment by EnzoVezzaro** [comment]
@mihaisc @AnaLoznianu 

I still have some question: 

> * [X]  remove subgraph query from component (only use aquarius)
Is this what's required?

> * [ ]  show the price from aquarius (i'll check again, but it seems already like that)
I see on the [code](https://github.com/oceanprotocol/market/blob/feature/issue-1994-remove-subgraph-query-algorithm-component-/src/@utils/assetConvertor.ts#L29) we're showing the price from aquarius. Am I wrong?

> * [ ]  show the missing asset
I can't find the [dataset](https://market.oceanprotocol.com/asset/did:op:084eaf28666b836ae09ed01847ed1a2049a823322869d3dac6e17bc1753f814a), we discussed on the standup. Are we supposed to find it in the list?

**Comment by AnaLoznianu** [comment]
@EnzoVezzaro I'm not sure if this is helpful but lemme give some context for this story. Currently, there is a limitation of 1000  elements in that view(that is dictated by the subgraph query). We reached that limit and new algos are no longer shown in that list. If we remove the subgraph query we should be able to bypass that limitation and display more algos.

**Comment by EnzoVezzaro** [comment]
> Currently, there is a limitation of 1000 elements in that view(that is dictated by the subgraph query)

What I see on the code is that we're making a [query to aquarius ](https://github.com/oceanprotocol/market/blob/feature/issue-1994-remove-subgraph-query-algorithm-component-/src/@utils/compute.ts#L181) to get the algoriths (query endpoint: https://v4.aquarius.oceanprotocol.com/api/aquarius/assets/query). This query is the one returning the 1000 records for the [c2d dataset](https://market.oceanprotocol.com/asset/did:op:348f03dc6347b3ca78734b6b3387316afa5d46570fcb8e44febd994e72d7e3a8). There's no subgraph query involved in the retrieving of the algos. 

UPDATE: I found the issue, is not on the subgraph side, it's the aqurious query [here](https://github.com/oceanprotocol/market/blob/feature/issue-1994-remove-subgraph-query-algorithm-component-/src/@utils/aquarius/index.ts#L68). If we increase the value, [c2d energy](https://market.oceanprotocol.com/asset/did:op:084eaf28666b836ae09ed01847ed1a2049a823322869d3dac6e17bc1753f814a) shows up. Currently there's 1146 records for this [dataset](https://market.oceanprotocol.com/asset/did:op:348f03dc6347b3ca78734b6b3387316afa5d46570fcb8e44febd994e72d7e3a8).
