### ISSUE TITLE
App crashes rendering markdown strings

### ISSUE THREAD

**Issue by LucaMilanese90** [oceanprotocol/market#1995]
**Describe the bug**
Some markdown strings using ` make the app crash. 

**To Reproduce**
1. Got to `/publish`
2. Fill the metadata and use this example markdown string as description:
```
test `description`
```
3. Move to the `preview` step
4. The app crashes

**Expected behavior**
The app should correctly render a valid markdown string.

**Additional context**
The issue has been introduced with #1973.
The bump of `remark-gfm` to 4.0.0 requires the update of all the other `remark` related packages to the last versions, specifically:
`remark`: 14.0.2 -> 15.0.1
`remark-html`: 15.0.1 -> 16.0.1

**Comment by jamiehewitt15** [comment]
Right yeah, just tested this out and it crashes just like you said. I'm looking into the cause

**Comment by LucaMilanese90** [comment]
As mentioned in the issue, it should be enough to update `remark` and `remark-html` to be compatible with the `remark-gfm` version currently in use in the market.
The compatibility list is here: https://github.com/remarkjs/remark-gfm#compatibility

**Comment by jamiehewitt15** [comment]
Yeah, seems like the package updates fix the issue: https://github.com/oceanprotocol/market/pull/1997
