### ISSUE TITLE
Docker Image validation in publish is not working as expected

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/market#1998]
**Describe the bug**
It seems there's an issue with the Docker Image validation in the publish form.

https://www.loom.com/share/d5e9d4648ed747be9f839d20d6066bc0?sid=15801e09-757a-45ba-896a-61b882009164

**Comment by AnaLoznianu** [comment]
The problem was introduced with: https://github.com/oceanprotocol/market/commit/0c5a29d6541d92e247a2fbae51b7f3c6da8758d4

**Comment by AnaLoznianu** [comment]
Marking this issue as critical as algorithms cannot be published via the marketplace due to this problem
