### ISSUE TITLE
Footer stats not loading

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#2032]
<img width="381" alt="image" src="https://github.com/oceanprotocol/market/assets/26000280/c1b13ba8-f169-47f5-a01d-151291ac1d09">

**Comment by MarianButucel** [comment]
What info should we show here? 
The stats are not being displayed because the Mumbai Network is deprecated

![image](https://github.com/oceanprotocol/market/assets/107684688/c15224a9-8301-4453-a0bd-ddc62e370932)

**Comment by mihaisc** [comment]
Just remove them

**Comment by tom1145** [comment]
> Just remove them

It's done with this PR.
