### ISSUE TITLE
All new pools created from Gui are 70-30 OCEAN-DT. Helps rug pulls & price.

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#207]
Why this makes sense: aligns interests of publishers & others even better than 50-50. 

Initial price may be low, but then with lotsa staking it will pull the price up. A low initial price means that price "spiked by staking" will be less insane.

Furthermore, publishers with highly valued assets, should be able to put high initial ocean stake.

Steps:
- [x] Make the change in a branch
- [x] Experiment with it on rinkeby, to validate whether this mitigates rug pulls & price.
- [ ] Tweet about it, from Ocean Market Updates channel. E.g. "Weights for pools have been changed from 50-50 OCEAN-datatoken to 70-30 OCEAN-datatoken. This better aligns incentives of publishers and stakers, and reduces rug pulls".  Reference: Trent's tweet on going from 10-90 to 50-50 is [here](https://twitter.com/trentmc0/status/1322134558121336837).

This is a bug because rug pulls & high prices are big issues. High priority because it can help a lot, with relatively low effort.

Related: we'll migrate existing 10-90 OCEAN-DT pools to the new pools. PrivateIssue#1

**Comment by kremalicious** [comment]
think this also needs this https://github.com/oceanprotocol/market/pull/218 being rolled out at same time
