### ISSUE TITLE
Problem: publisher published two identical data sets

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#209]
One of our data launch partners asked:

I accidentally published two identical data sets:

https://market.oceanprotocol.com/asset/did:op:Ac3a39F843316c83Db11a9E6D703a7473c26aCe0
and
https://market.oceanprotocol.com/asset/did:op:fd28195e3d30d5a63a87A2502030CE648FFa4884

How do I go about removing the second one from the marketplace?

**Comment by mihaisc** [comment]
The solution would be to add an `isRetired` flag. The publisher can 'retire' the asset (basically just an update to the ddo with the `isRetired=true` ). In all our queries we would need to add this flag to ignore the ddos with it.

**Comment by mihaisc** [comment]
already discussed more extensively here https://github.com/oceanprotocol/market/issues/445, and will also be part of v4
