### ISSUE TITLE
Help users' mental model via better text when staking

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#210]
**What:** In "add liquidity" screen, make it clear that "your provided ocean will buy _ DT" and "fee will be __"

**Intended benefit:** Helps users' mental model of what happens when they stake: they realize that they're actually purchasing some DT. In turn this helps wrt user understanding of rug pulls and IL. While at the same time we keep it easy, by allowing them to only have to stake a single token (OCEAN).

Future, *not* the scope of this issue: "User has option to stake DT at same time as staking OCEAN"  [Market-236](https://github.com/oceanprotocol/market/issues/236)

**Comment by kremalicious** [comment]
What's the status of this? It is marked as High so I would start right away. We still want this?

**Comment by trentmc** [comment]
It's in "PM to discuss" column. That's the next step.

**Comment by kremalicious** [comment]
tinkering over in #277 and I think we are looking for something like this (prototype, numbers are hardcoded):

<img width="495" alt="Screen Shot 2020-11-27 at 15 53 30" src="https://user-images.githubusercontent.com/90316/100461216-c7496300-30c8-11eb-9719-99beb0ca7fb0.png">
