### ISSUE TITLE
[redundant] Support >1 (a) initial token distribution (b) datatoken markets

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#232]
Motivations:
(a) is about better IDOs. There are many ideas.
(b) is about >1 pools etc. There's lots of great AMM variants, and new ideas.

Ideally we have a way where people can choose from among many options for (a), and for (b).

Ideally we have a way where devs in the community can build new ideas for (a) and (b) and things are structured such that it's easy for people to try them.

Possible approaches:
- One monolith app: Ocean Market. plug-in architecture for both (a) and (b)
- Many monolith apps: fork Ocean Market and have a culture of >1 markets
- One main on-ramp/off-ramp app, many in-between apps: Decompose Ocean Market into >1 apps. E.g. one for publish & consume, another for IDOs, and an aggregator for markets.

**Comment by kremalicious** [comment]
what does this mean? What needs to be done to close this issue?

**Comment by trentmc** [comment]
Closing this issue, as it is superseded by other V4 issues.
