### ISSUE TITLE
Custom badges for assets in Ocean Market

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#271]
Overall goal: mitigate rug pulls, mitigate IP violation, and more. 
Strategy here: give the community more tools to self-curate *assets*. Twin: custom badges for *accounts*, [here](https://github.com/oceanprotocol/market/issues/252).

**What's below forms the scope of this issue.**
- Just like Metamask or Uniswap allows users to add custom tokens...;
- Ocean Market could allow users to **add custom badges to assets, by simply providing the url of the list repo of assets**. 
- the community can go nuts adding whatever list repos they like. 

It's a simple plug-in architecture for badges. Evolution will drive towards great lists over time. It could get increasingly sophisticated. But no extra effort from us, once we have the foundation, which we're already close with. This also allows us to avoid building a ratings systems for assets (which is problematic). Once there are more good community-based badges, we can turn on a few by default. 

**TODOs for this issue:**
* First, build custom badges for accounts. [Here's the issue](https://github.com/oceanprotocol/market/issues/252).
* Based on that, devise specific TODOs here

**Comment by kremalicious** [comment]
duplicate of #271

**Comment by trentmc** [comment]
Not a duplicate. This one is for assets. The other one is for accounts.

**Comment by trentmc** [comment]
Lol, folding this into #271
