### ISSUE TITLE
A bug discovered in charts while using mobile version. 

### ISSUE THREAD

**Issue by starzingersaga** [oceanprotocol/market#273]
Ive discovered a bug in the marketplace, while using mobile. The charts for each given dataset, isn't shown entirely. It is cropped of 10% from both ends on timescale. ONLY way to see the whole chart in its total time span, is to tilt the mobile horizontal, otherwise you miss out on about 20% of the chart. It would be great if it could be fixed as soon as possible.

**Comment by kremalicious** [comment]
Confirmed.

Desktop:

<img width="483" alt="Screen Shot 2020-11-27 at 15 15 13" src="https://user-images.githubusercontent.com/90316/100458015-5b183080-30c3-11eb-9a99-71cc0cfa6732.png">

mobile, Safari, iOS:

![IMG_46148C122227-1](https://user-images.githubusercontent.com/90316/100458070-7420e180-30c3-11eb-97ef-a6ddab4ac73d.jpeg)
