### ISSUE TITLE
Asset edit history

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#282]
- Use TheGraph to get history
- Display history in asset details

**Comment by kremalicious** [comment]
a new metadata history component is included in #292, but will be not shipped initially:

<img width="732" alt="Screen Shot 2020-12-09 at 13 13 02" src="https://user-images.githubusercontent.com/90316/101628765-96e6ba80-3a20-11eb-8707-288e7a3b30c3.png">

It runs on fake data so once we have The Graph in place, we can ship it

**Comment by kremalicious** [comment]
this can be re-evaluated to see if current subgraph allows us to ship the existing component seen in screenshot above. Or to figure out what we need in the subgraph to fill that component with real data

**Comment by kremalicious** [comment]
unblocked. Subgraph now has `updates` on `Datatoken`:
- https://github.com/oceanprotocol/ocean-subgraph/blob/625389490e0c83d07d0d8866f7d462d1d61e6e1a/schema.graphql#L119-L154
- [some example query](https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20datatokens%20%7B%0A%20%20%20%20id%0A%20%20%20%20metadataUpdateCount%0A%20%20%20%20updates%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20tx%0A%20%20%20%20%20%20timestamp%0A%20%20%20%20%20%20userAddress%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
