### ISSUE TITLE
"Number of datatokens" displayed in the market footer is meaningless/confusing; TVL would be super-useful

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/market#286]
The Ocean Market footer currently shows e.g. "1,298,989.836 OCEAN≈ €502,197.26  and 40,107.252 datatokens in 167 data set pools."

The part "40,107.252 datatokens" is meaningless. It's like giving a stat for "# BTC tokens" + "# ETH tokens" + "# XRP tokens" + ... . Each token has a different value / meaning. This does not help users, and can actually confuse them as they try to sort out what it might mean.

This is precious real estate. There are plenty of stats that are more useful. E.g. min/avg/max # consumes per dataset, min/avg/max OCEAN price per dataset, min/avg/max OCEAN liquidity per dataset. And more. 

[Originally proposed] TODO for this ticket: simply remove the part that gives "40,107.252 datatokens". 

[Updated proposed] TODO for this ticket: Update the footer to give information that accounts for the value of the datatokens (and doesn't show "number of datatokens"). Full proposal is a comment in this PR:  https://github.com/oceanprotocol/market/pull/311#issuecomment-758425502

### Spec

Replace current footer statistics line with:

```
€1,209,894.27 TVL (total value locked) across 156 dataset pools that contain 1,095,651.439 OCEAN and the datatokens for each pool. 
```

**Comment by kremalicious** [comment]
Following the discussion in the PR #311, we agree that only once we output TVL, the number of datatokens becomes meaningless. Updated the issue with that new proposed statistics line

**Comment by alexcos20** [comment]
https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20pools%20%7B%0A%20%20%20%20id%0A%20%20%20%20datatokenReserve%0A%20%20%20%20oceanReserve%0A%20%20%20%20spotPrice%0A%20%20%20%20lockedValue%0A%20%20%7D%0A%7D

**Comment by trentmc** [comment]
Note: Samer says we have TVL in TheGraph. So this just needs to get propagated upwards.

**Comment by kremalicious** [comment]
https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolFactories%20%7B%0A%20%20%20%20totalLockedValue%0A%20%20%20%20totalLiquidity%0A%20%20%20%20totalSwapVolume%0A%20%20%20%20totalSwapFee%0A%20%20%20%20poolCount%0A%20%20%20%20finalizedPoolCount%0A%20%20%7D%0A%7D%0A
