### ISSUE TITLE
Proposal - Variable Liquidity Ratio/Weights for High Value Publishers

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#305]
During the discussion with potential publishers with high value data one very important point was in the center of discussion, initial liquidity.

While serious publishers of high value data do not have problems with a liquidity pledge to keep initial liquidity locked for a given amount of time (months) the initial amount of Ocean needed to assure a minimum market price is a potential reason to not participate in the market. The initial liquidity for a data set that is worth about 20.000 EUR (60.000 Ocean) or more per use will surpass that amount by far if a reasonable amount of initial tokens is desired.

In this example nearly 1.000.000 Ocean are needed to create a pool with approx. 20 Token in it.

![image](https://user-images.githubusercontent.com/59994024/102724978-a238c080-4313-11eb-9558-d4a33cab0af4.png)

A possible way to solve this would be to allow flexible weights in the pool after a certain threshold has been reached, i.e.

Initial Liquidity <20.000 , only 70/30 weights available
Initial Liquidity <100.000, 70/30 and 50/50 are available
Initial Liquidity <500.000, 70/30, 50/50 and 30/70 become available

This would provide incentives to provide a higher level of liquidity while the weights would still be visible for all market participants and thus give the market a chance to value a potential risk associated with it.

A potential lock-in time for initial liquidity could further be used in combination with the thresholds described above.

70/30 - no lock-in of initial liquidity
50/50 - 3 months of lock-in for initial liquidity
30/70 - 6 months lock-in for initial liquidity

An underlying assumption is that high value data providers on commercial level that provide this level of liquidity pose a significant lower risk of rug pulls and at the same we already have rugpullindex.com and the wonderful badges by Tim Daubenschütz at hand.

I am very much looking forward for a discussion in this topic.

**Comment by trentmc** [comment]
Hey Kai! This is a great idea. 

Ocean V4 (Better IDOs) will include Balancer V2 and things will be a lot more flexible then. And it will do this issue out-of-the-box.

Therefore I will close this issue. Stay tuned for v4:)
