### ISSUE TITLE
Need to set a Custom Timout of Consumption of Datasets

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#306]
Dear Developers,

we need to configure the consumption timeout of a dataset to restrict unlimited downloads of the set. 

Currently the timeout default is 0 [infinite].

We want to change this to  somewhere between 3600 [1h] or 86400 [24h] so enable a confortable download, but at the same time restrict the opportunity of infinite downloads, since the underlying data is subject to change and shall be bought multiple times.

Could this value be integrated in the "Publish GUI" and in the "Edit Metadata" GUI or could you give us a way to change this for a specific asset through a beta/dev function we could use? 

{
      "type": "access",
      "index": 1,
      "serviceEndpoint": "https://provider.mainnet.oceanprotocol.com",
      "attributes": {
        "main": {
          "creator": ".........",
          "datePublished": "...........",
          "cost": "1",
          **"timeout": 0,**
          "name": "dataAssetAccess"
        }
      }
    }

**Comment by kaimeinke** [comment]
Maybe this is already been taken care of in the publish form in https://github.com/oceanprotocol/market/pull/272 if I get it right? Would this work for the edit function as well? This would solve our problem.

**Comment by kaimeinke** [comment]
After talking to @alexcos20 , this issue would be the one to solve the edit timeout problem. https://github.com/oceanprotocol/market/issues/310

**Comment by kremalicious** [comment]
closing in favor of #202
