### ISSUE TITLE
Large files failures - market side - test new provider

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#314]
Epic / High-level problem: described at https://github.com/oceanprotocol/provider/issues/40

This issue is to do the fix needed for https://github.com/oceanprotocol/market

**Comment by alexcos20** [comment]
Test new provider

**Comment by kaimeinke** [comment]
Today we were able to successfully download files > 1GB on the Rinkeby marketplace. Thanks a lot for making progress @alexcos20 , these signals are highly appreciated. Thank you.

**Comment by alexcos20** [comment]
we have a fix for the UI, we are going to roll it out tommorow.

**Comment by kaimeinke** [comment]
The test of 5GB downloads on Rinkeby worked. The connection was nearly instant and the download went fast. Wow, amazing work. Has been tested with https://market.oceanprotocol.com/asset/did:op:e115a919B9eb125BBEa1Ff37c22Ab725B63c1335 

Thanks a lot @alexcos20
