### ISSUE TITLE
Pool Shares and Pool Transactions at History page take a long time to load

### ISSUE THREAD

**Issue by soonjing** [oceanprotocol/market#326]
**To Reproduce:**
1) Go to[ market.oceanprotocol.com/history](https://market.oceanprotocol.com/history)
2) Scroll down to below as shown in screenshot.
3) Sometimes it takes up to a minute or more to load the pool shares and pool transactions data.

![image](https://user-images.githubusercontent.com/39853992/105005192-f1d3ee80-5a6f-11eb-9bb5-4258d57711aa.png)

**Comment by kremalicious** [comment]
thanks, we're on it. Will be solved with #284 and #307

**Comment by KatunaNorbert** [comment]
While using the graphs `poolShares` method to get the Pool Shares I get an empty list, although I have a shared pool and `ocean.pool.getPoolSharesByAddress` finds it. I also got the entire list of pool shares and checked if my address is there but it isn't.
This is how I used `poolShares`:
![Screenshot 2021-01-27 at 14.45.06.png](https://images.zenhubusercontent.com/5ff449b376fe2511ba59495d/51b21af3-2aa8-430a-8c05-6f92e8c90c99)

**Comment by mihaisc** [comment]
please link the query not a image of the query 😄

**Comment by KatunaNorbert** [comment]
I edited the comment and put the query with the address in lowercase format but still not working

**Comment by mihaisc** [comment]
with my account seems to be returning  [query](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20PoolsQuery%20%7B%0A%20%20%20%20poolShares(orderDirection%3Adesc%2C%20where%3A%7BuserAddress%3A%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20%20%20%20id%0A%20%20%20%20%09%20balance%0A%20%20%20%20%09%20userAddress%20%7B%0A%20%20%20%20%09%20%20%20id%0A%20%20%20%20%09%20%7D%0A%20%20%20%20%09%20poolId%20%7B%0A%20%20%20%20%09%20%20%20id%0A%20%20%20%20%09%20%7D%0A%20%20%20%20%7D%0A%20%20%7D&operationName=PoolsQuery)

**Comment by KatunaNorbert** [comment]
on **test46**

**Comment by mihaisc** [comment]
Added issue on subgraph repo https://github.com/oceanprotocol/ocean-subgraph/issues/12

**Comment by KatunaNorbert** [comment]
After obtaining the poolShares from the graph I need to get the ddos by pool did, but the poolShares doesn't contain that field.

**Comment by mihaisc** [comment]
You get the ddo from the datatoken, you have that on pool , check https://github.com/oceanprotocol/market/blob/ab609b93c0aa41b1dc567bba2163c95b71434828/src/components/molecules/PoolTransactions.tsx#L162
