### ISSUE TITLE
Edit Metadata hang

### ISSUE THREAD

**Issue by TSS-LauKY** [oceanprotocol/market#328]
**Edit Metadata **
Edit Metadata is hang in the loading icon after the transaction is done

**Screenshots**
![image](https://user-images.githubusercontent.com/71874741/105341369-f9cf9200-5c19-11eb-8ea4-c2846529a868.png)

**Comment by mihaisc** [comment]
I just tested and it seems to be working ok

![image](https://user-images.githubusercontent.com/26000280/105377492-89257700-5c13-11eb-8284-6cd11a0a88df.png)

Can you test again and open the developer tools before (f12 on chrome, may differ on other browsers) and then include the developer tools in the screenshot

**Comment by TSS-LauKY** [comment]
screenshot as below
![image](https://user-images.githubusercontent.com/71874741/105428602-a21d3f00-5c8a-11eb-9e99-64bdab556a4c.png)

**Comment by kremalicious** [comment]
So it looks like this asset on Rinkeby was created outside of the market publish flow
https://market.oceanprotocol.com/asset/did:op:79c0b9f5737D2654a69384C0ead6968bD01dee48

Cause it's an algorithm to be used with Compute-to-Data which we do not support in the current market. We are not able to reproduce this error with any asset created through the market UI which implies either:
- something was missing during the asset creation with the libraries
- the market app may need an update to support editing assets of type `algorithm`

Could you try editing one of your assets which is not a compute asset, and is not of `type: algorithm`, does this succeed?

**Comment by ssallam** [comment]
It seems the metadata was actually updated.

**Comment by TSS-LauKY** [comment]
I edit on another algorithm type asset is working.
maybe the metadata of DID 79c0b9f5737D2654a69384C0ead6968bD01dee48 have issue.

**Comment by kremalicious** [comment]
good info, thanks! Then this sounds like some issue with that particular asset's metadata during the creation outside of market.
