### ISSUE TITLE
Add volume chart per pool

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#334]
Add another chart tab visualizing the volume of a data set pool. Probably best to use some vertical bart chart for this https://www.chartjs.org/samples/latest/

Requires: https://github.com/oceanprotocol/ocean-subgraph/issues/10

**Comment by mihaisc** [comment]
Added as a comment in this issue https://github.com/oceanprotocol/market/issues/671

**Comment by mihaisc** [comment]
After further examination realized that this can be done using pool transaction ( [subgraph-query](https://subgraph.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolTransactions%7B%0A%20%20%20%20timestamp%0A%20%20%20%20event%2C%0A%20%20%20%20tokens%7B%0A%20%20%20%20%20%20poolToken%7B%0A%20%20%20%20%20%20%20%20tokenAddress%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20value%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) ) . We just need to group by day and do a sum for the values of ocean tokens
