### ISSUE TITLE
Fetch compute history from the graph

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#338]
The current compute job history format is ok, the main problem is that it's very slow. We need to move this to the graph, `ocean.assets.getOrderHistory` needs to be fetched from [here](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20PoolsQuery%20%7B%0A%20%20tokenOrders(where%3A%20%7Bpayer%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20amount%0A%20%20%20%20datatokenId%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20serviceId%0A%20%20%20%20consumer%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=PoolsQuery)

**Comment by kremalicious** [comment]
As described [on the implementation](https://github.com/oceanprotocol/market/pull/462#issuecomment-811764879) this issue can't be solved unless we have compute job history in our subgraph. Our current implementation uses `ocean.compute.status` to get the jobs. With new implementation it would be the same, adding no benefit whatsoever.

**Comment by mihaisc** [comment]
Unfortunately we can't get around fetching the status from the provider. I will check why `ocean.compute.status` it taking so much time, it shouldn't.
The long term fix is : 
- The compute provider will hold jobs and host the results for 3 month (we will need disclaimers and whatever else is necessary)
- In `Compute History` we show only the latest 30 days  and have a button to show all. 
- On each compute asset we can show compute history (like we do with transaction history on pools)
