### ISSUE TITLE
Publish algorithm

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#341]
On the Publish page:

- introduce tab interface: Data Set, Algorithm. Data set is selected by default
- new form for algorithm publishing
   - title
   - description
   - file URL
   - pre-defined Docker image selection: Node.js, Python
   - tags
   - optional checkbox "Keep my algorithm private"
- needs to be synced with editing form
- algorithm is public by default

**Comment by mihaisc** [comment]
From [EPIC](https://github.com/oceanprotocol/multi-repo-issue/issues/53)

The publish form will have the following fields: title, description, file (url of the algo), author, tags, t&c, agree with t&c check, image (it's either the name of a docker image or the full url if it's from a 3rd party repo, ex: node , oceanprotocol/algo_dockers), version, entrypoint. We will have a list of predefined images and option for custom. If user selects custom then he will need to fill : image, version, entrypoint
The image will be checked/validated using an endpoint in the provider
We will use the same pricing component as in the data assets (with fixed price and pools)

**Comment by kremalicious** [comment]
worth noting using existing file URL input field for the algorithm is just the most simple solution to get going. We might want to spin this out into smaller issue to figure out what UI pattern is good here, like an editor textarea where the algorithm can be authored/pasted
