### ISSUE TITLE
Algorithm detail view

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#342]
Main question: what should be removed compared to data sets?

Suggestions:
- remove all actions, except for editing

**Comment by mihaisc** [comment]
In the first iteration of algos yes, no need for anything else

**Comment by kremalicious** [comment]
based on what was initially discussed in #341 and then today where we want to keep the flow the same for pricing as with data sets: this implies that we will have the same `AssetActions` as for data sets. _Use_, _Pool_, _Trade_, the whole thing.

In that context _Use_ could be redefined for algorithms. Downloading them might not be the most useful thing to do with them, but rather running them on data sets they are allowed to run. And that could be represented somehow in the _Use_ tab for an algorithm

**Comment by mihaisc** [comment]
I agree, after the latest talks we should just keep it the same as for datasets. And in the use tab : if it's "public" show the download button and if it's "private" don't show it
