### ISSUE TITLE
Start compute job on data set

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#343]
On the asset details page under the _Use_ tab there's a _Select Algorithm_ action which opens a modal with a list of existing algorithms. Alternatively only populate a `select` with pre-defined default Algorithms we publish.

Then there's a _Start Compute Job_ button which starts compute job with selected algorithm.

On dedicated screen, or modal show:

- list of algorithms published in market, where they show sufficient infos for users to know hat they are (title, linked to algorithm detail)
- one needs to be selectable
- with selected algorithm start compute job
- show status → ideally use new to be created global transaction provider around the app, and show further compute job status there as defined in #385

**Comment by kremalicious** [comment]
quick mockup, this was my first thought apart form a `select`, to allow us to show mire metadata in place. Still lots of room for getting more space out of the _Use_ screen, like the file is not that important anymore so we could make it way smaller giving us more space.

<img width="516" alt="Screen Shot 2021-03-09 at 11 51 29" src="https://user-images.githubusercontent.com/90316/110459881-ca8fba00-80cd-11eb-8425-4d417e5c78eb.png">

Just to check: did I get this right that if algorithms have price set, then that price is added to the data set price upon ordering on the data set, right? If so then we need to show both prices. Ideally we can also show a sum under the action button

**Comment by mihaisc** [comment]
The file icon has no meaning here, we can remove it completely.
Yes we need a sum ( data set + algo ) somewhere at the bottom

**Comment by mihaisc** [comment]
> show status → ideally use new to be created global transaction provider around the app, and show further compute job status there as defined in #385

With the suggested implementation this status is not that prio now. You can just check the compute history.

**Comment by kremalicious** [comment]
I think those are all the elements we want on there:

<img width="454" alt="Screen Shot 2021-03-09 at 16 03 31" src="https://user-images.githubusercontent.com/90316/110490869-012afc00-80f1-11eb-8046-eb8978c6f082.png">

The algorithm titles should be linked to their details pages, get pink on hover, and possibly best to open them in new tab. Not sure how useful the image type is but we can add it as a smaller label instead of _| Node.js_. The `+` before the algorithm price implies that we could have some `prefix` param on our `PriceUnit` component where either non, or our existing `≈` is the default.

Then we should see if we can have titles at maximum of 2 lines per row and then truncate, or if 1 line is also enough. In any case their `title` attribute should include the full non-truncated title.

Semantically, it looks like this could be a `form` with multiple `input type="radio"` although this might clash with the title actions we want to have on it.
