### ISSUE TITLE
public analytics

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#355]
For the sake of transparency it would make sense exposing key traffic statistics to everyone.

Possible solutions:

1. use https://simpleanalytics.com for the `market` which would give us a public analytics page like this https://simpleanalytics.com/simpleanalytics.com
2. build a page within `market` fetching data from our Netlify project's analytics, and display them. Needs verification if that's actually possible 

In a later stage and most likely in a different issue, exposing key financial metrics for the whole market could find a place on this page too.

**Comment by mihaisc** [comment]
Starting point for netlify analytics https://www.raymondcamden.com/2019/10/05/building-a-netlify-stats-viewer-in-vuejs

**Comment by DimitarSD** [comment]
Netlify Analytics doesn’t have a documented API endpoint, but we can track down the endpoint calls we need through dev tools. Do we know what key stats we want to show?

A potential block: The data provided from the API is only for 30 days. It's not possible at the moment to get older data ([more info](https://community.netlify.com/t/change-to-unofficial-analytics-api/29979/2)). Are 30 days OK for us?

**Comment by kremalicious** [comment]
While internally it would be better to have longer-ranging stats, 30 days is totally enough for public stats so that's fine.

Conceptual first ideas as MVP:
- create new route `/usage` (working title)
- a line graph of page views 
- a line graph of unique visitors
- list/table of 10 most visited page routes, showing/linking route & page views number per route

But this page could be really flexible and a combination of traffic stats and financial stats but let's start with the traffic stats. 

So then we can now figure out if that's possible. For graphs we currently use chart.js so we would  need to see if we can create the data structure it needs to plot a line graph:
- https://www.chartjs.org/docs/latest/charts/line.html
- https://github.com/oceanprotocol/market/blob/main/src/components/organisms/AssetActions/Pool/Graph.tsx

We can make use of https://github.com/oceanprotocol/market-stats for external, authenticated API calls and create the response we need there and `market` then hits that to construct the data for graph/table.

**Comment by kremalicious** [comment]
There is of course always a different tactic based on some overall tracking strategy across all our web properties, but would create a bunch of pre-requirements to build the page described here. This would be coming up with a self-hosted analytics solution for which nice solutions exist by now, among them I quickly checked out:

- https://plausible.io, deploy docs: https://plausible.io/docs/self-hosting
- https://ackee.electerious.com, deploy docs: https://docs.ackee.electerious.com/#/docs/Get%20started#with-netlify
- https://matomo.org, install docs: https://matomo.org/docs/installation/

Where Plausible seems ready for production and high-traffic, Ackee is really nice and easy to deploy but seems to have problems keeping up with high traffic. Matomo is a monster and a bit of a pain to maintain. But all of them provide an API too.

Just adding this here for reference, preferred way for quicker shipping would be to somehow make it work with Netlify Analytics but if we can't these would be some alternative options

**Comment by DimitarSD** [comment]
Plausible looks like a great alternative to GA, and it definitely should stay on our radar. 

The FE page (`/usage` - another good name -> `/stats`) doesn't really need to know where the data is coming from as long as it follows the needed data format. 

I can start working on tracking down the Netlify API endpoints and then creating the functions with responses within market-stats for what we need. After integrating Plausible (or any of the other solutions) we can just update the functions inside market-stats to work with it instead of Netlify.

**Comment by DimitarSD** [comment]
Short documentation on the different endpoints, requests, and responses for the Nelify Analytics API can be found in the [netlify-analytics-api-docs](https://github.com/DimitarSD/netlify-analytics-api-docs) repo.

**Comment by kremalicious** [comment]
dropping here for inspiration from recent AllianceBlock post https://blog.allianceblock.io/powering-the-new-data-economy-72d35ba0f196

They have a perfect dashboard with visual patterns I had in mind for a combined traffic/financial page with a mix of highlight key numbers and historical data:
![1*bUH30JcV1sjcy_p19H_e2g](https://user-images.githubusercontent.com/90316/113282755-aa77a300-92e7-11eb-8a47-36c23f2fa74c.jpeg)

**Comment by idiom-bytes** [comment]
Familiarized myself with task, and what DAO participants are up-to.
I agree with Matthias re: 

> Conceptual first ideas as MVP:

This is a good separation between market usage stats vs. financial stats.

We're spinning up a doc so we can organize deliverables vs. future work.
I will organize a wireframe so we can review it before moving forward.

**Comment by idiom-bytes** [comment]
Put together a layout/component set that maps to ALBT dashboard, and utilizes basic site metrics to fill out the table.
- Starting to  organize information a bit more.
- Am planning to make it more Ocean-Market-Like (and less ALBT), after layout/information is agreed upon.

![basic_components](https://user-images.githubusercontent.com/69865342/114610162-7344b280-9c54-11eb-96e4-c1c48e61751a.png)

**Comment by kremalicious** [comment]
some more data we should have:

- TVL, let's start with the current connected network, later we have combined TVL for multiple networks.
- would decide on either views or visitors, depending on what's more important. One metric is enough to communicate web traffic 
- that table of dataset ranking based on views has too much unneeded data shown at once. Whole screen/selected items should get a time switch, so all this data just switches in the table which can have only 2-3 columns then
- number of data sets
- number of pools

**Comment by kremalicious** [comment]
we are going with scope reduction and depriorization of traffic data:

- add a new line to footer's `MarketStats`, something like `800 pageviews & 600 unique visitors in last 30 days`
- could spend some testing on how a `Most visited assets` section on front-page would look like, meaning if it is sufficiently different from the Highest Liquidity assets
- no new stats page, but rather find ways to highlight TVL  in context, e.g. in a new front-page section, or as part of a new Pool/Dex/Trade page

**Comment by kremalicious** [comment]
Let's revisit after the v4 split as we ant to sprinkle various statistics throughout the whole interface, not just footer
