### ISSUE TITLE
Error in DT exchange

### ISSUE THREAD

**Issue by TSS-LauKY** [oceanprotocol/market#371]
**Describe the bug**
Error in DT exchange during consume and asset

**Screenshots**
![image](https://user-images.githubusercontent.com/71874741/107457169-87a0fc00-6b8c-11eb-8ebd-1717199e0bab.png)

**Error**
DT exchange buy response 

Object { blockHash: "0x1228b968cf59fc67f146ea50499a9843b8a0b08a121ee138272168a5b02bfc28", blockNumber: 8046397, contractAddress: null, cumulativeGasUsed: 126309, from: "0x1aef750253b4954b42c980d99856d32474b2c3db", gasUsed: 84152, logsBloom: "0x00000000000000000000000000000000000000000000000000000100000000000000000000000002000000000000020000000020000000000000000000200000000000000000000000000008000000020000000000000000000400000000000000000000000000000000200020000000000000100000000000000010000000000000000000000000000000000000000000000000000000400000000000000000020000000000000000020000002000001000000000008008000000000044004000000002000000000000000000010000000200010000000020000000000200000010000000000000000000000000000400000000000000000000000000000000", status: true, to: "0xed1dfc5f3a589cfc4e8b91c1fbfc18fc6699fbde", transactionHash: "0x4e55b244d914355e0e29411e581badcbb1132b9543742db601a543208db09dd2", … }
Logger.js:102:20

**Comment by TSS-LauKY** [comment]
@alexcos20 
We have issue on compute on data, during buy data token.
Can we get your team help to check on this as we will have demo.

![image](https://user-images.githubusercontent.com/71874741/109097660-b6a59900-775a-11eb-9ecb-5a69c7cab05d.png)

**Comment by TSS-LauKY** [comment]
@alexcos20, here is the DID:
did:op:f8e4fA3d6677aA8aAC702e86FdeA9E32ff3638cc

**Comment by alexcos20** [comment]
don't get it. first screen shoot is an download asset.  but the 2nd is with compute.  are you sure that it's the same dataset?
