### ISSUE TITLE
validate DDO metadata before form submission

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#373]
Following the issue which led to #367, we should generally expose all possible metadata errors before the user can submit anything. The reason for that is the publish process which only puts the DDO on-chain, from which Aquarius is supposed to pick it up and index it, but fails if it finds metadata errors.

For this purpose, Aquarius has a `validate` endpoint we can make use of for this: https://docs.oceanprotocol.com/references/aquarius/#assetsddovalidate

The implemented flow could be:

- Upon form submission we first check the transtormed data against this endpoint
- When it succeeds we can start with the submission process
- When it fails we should expose through the form errors the place in the form where the error was caused and then display it

**Comment by alexcos20** [comment]
please delay this for a couple of days, those functions will be avaiable in ocean.js

**Comment by kremalicious** [comment]
seems to be a solution looking for a problem. We already have form model validations going on, and it seems validating all this data again with API request is only really useful for developers but not for end users
