### ISSUE TITLE
Scalability upgrade for large scale datasets: Sliced Dataset

### ISSUE THREAD

**Issue by tmanthey** [oceanprotocol/market#379]
**Is your feature request related to a problem? Please describe.**
Ocean Market does not easily support the publishing of large scale datasets. AI image datasets can easily contains millions of images which results in datasets in the hundreds of GB or even TB. The amount of initial liquidity required to create a pool would be just beyond most publishers possibilities. 

**Describe the solution you'd like**
For our dataset we worked around the issue by slicing the dataset in 53 slices and do a weekly rotation on the download side. Nevertheless this approach is not sustainable as potential customers would have to wait a year to consume a full dataset.
Therefore I propose the option to publish "sliced datasets". This requires that the publisher can configure the number of slices for his dataset during the publishing process. The slices must be numbered. The download URL must contain a placeholder for the sliceId.

http://foobar.com/datasets/mydataset_%.zip 

where % is a placeholder for 1...#slices

This would reduce the requirement to provide initial liquidity to a single slice and would encourage the consumption of datasets.

https://market.oceanprotocol.com/asset/did:op:2a76F680279CE629a9F5E601BDa7246e06F226f0

**Describe alternatives you've considered**
Very cool would be to download datasets in percentage of the total dataset or coins in the wallet. (Similar to the slider in the Binance market that allows to spend a certain percentage of your coins for a particular transaction). But that would require tracking the dataset slices that the user has already downloaded so that he does not download the same slices on the next purchase.

**Comment by Koesters** [comment]
Definitely a good idea. I have 7 TB zipped or 70 TB unzipped data to sell.

**Comment by trentmc** [comment]
Note: this idea / issue was initially described in Discord. Here's the link.
https://discord.com/channels/612953348487905282/612953349003673629/809887981291700307

**Comment by trentmc** [comment]
"Fix gas costs" is targeted (and on track) to be completed by end of Q1. That should address the issue.

It's addressed even better in "Better IDOs" (Q4) which decouples amount of stake from price. (Therefore price won't shoot up in the face of a lot of staking.)

Would these be sufficient to address your needs?

**Comment by trentmc** [comment]
Closing since there were no responses to the Q's; that there some are ways to handle the concerns now, and that other roadmap plans / github issues handle them even better going forward.
