### ISSUE TITLE
Statistics not visible on Rinkeby Marketplace

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#381]
I just checked the Rinkeby marketplace to prepare a product presentation of the Data Market and ran into some inconvenience.

The statistics do not show up after I created a new pool and made a transaction.

This is kind of a downer when doing the onboarding and product presentations.

https://market.oceanprotocol.com/asset/did:op:279659A4Dea23A0a2a18b417A99A7bcFbA9cE576

https://rinkeby.etherscan.io/token/0x8967bcf84170c91b0d24d4302c2376283b0b3a07?a=0xDBa344332f5a52FbFe3098d42A08381c0FB5E65F

![image](https://user-images.githubusercontent.com/59994024/107863412-886bb380-6e54-11eb-8fac-cea9534c66d8.png)

Best
Kai

**Comment by kaimeinke** [comment]
Pool transactions and "Remove liquidity" button are also not available.

![image](https://user-images.githubusercontent.com/59994024/107863520-48590080-6e55-11eb-9931-825248adb4eb.png)

**Comment by kaimeinke** [comment]
Seems to be an issue only with new pools, for old pools I get the statistics and remove liquidity option.

See https://market.oceanprotocol.com/asset/did:op:83c92519f4A791DdF3f8ae0C6912ED3D05953349 

![image](https://user-images.githubusercontent.com/59994024/107863612-01b7d600-6e56-11eb-9374-e667968cab1e.png)

**Comment by kaimeinke** [comment]
Just tried with a new pool to reproduce the error: https://market.oceanprotocol.com/asset/did:op:9C91bc4146A6f78cdBc8A399F56e606F94412323 

Looks like I am getting errors from the subgraph here:

{"data":{"pool":null}}`

![image](https://user-images.githubusercontent.com/59994024/107872417-892f3480-6eaa-11eb-9ea6-d7f4565fd431.png)

![image](https://user-images.githubusercontent.com/59994024/107872434-ae23a780-6eaa-11eb-9573-25cbcb310956.png)

![image](https://user-images.githubusercontent.com/59994024/107872522-212d1e00-6eab-11eb-9a0a-3e16d8144a97.png)

**Comment by kremalicious** [comment]
thanks for the report, our Graph nodes in Rinkeby indeed stopped indexing for whatever reason. We manually restarted that indexing and Graph data should start to show up also for newer data sets again.

**Comment by kaimeinke** [comment]
Thanks a lot @kremalicious , I am feeling MUCH better now.
