### ISSUE TITLE
transaction status context provider for compute jobs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#385]
Compute jobs take a long time so the current pattern of showing transaction feedback status in place of user action is not feasible because e can't make users stay on the same screen for what can be hours.

### Solution

Create a global context provider around the app which holds infos about all transactions send into it. The provider needs to handle getting the status of those transactions in real-time. Some sort of shopping-cart like UI in some popover can be triggered by users from the main menu bar. As a start, the UI then shows a list of compute jobs and their status, and for finalized jobs an action to retrieve their results.

This provider combined with the UI might make the compute jobs list on the History page redundant.

We can then further extend usage of this transaction context provider and show all market transactions we can find for a user account at a later stage. Won't be part of this issue but should be considered when planning the context provider

**Comment by kremalicious** [comment]
As for UI the data collected in that provider could be output like so in its simple form:

<img width="549" alt="Screen Shot 2021-03-09 at 12 56 10" src="https://user-images.githubusercontent.com/90316/110467125-e77cbb00-80d6-11eb-8fdd-7f63ad7a2771.png">

**Comment by trentmc** [comment]
Matthias and Mihai say: close, not gonna do
