### ISSUE TITLE
Search filter bar reorganization 

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#392]
With #388 a new filter group is introduced to switch between algorithms & datasets in addition to existing filters:

<img width="1154" alt="108505305-73a97880-72b7-11eb-9f6d-17bbc3fd19c5" src="https://user-images.githubusercontent.com/90316/108505718-1f52c880-72b8-11eb-988e-4588b701c21d.png">

Some possible options:
- put existing filters on one line on big viewports
- add label to each filter group, following the style of sorting bar 
- combine price & type filter bars into one. So that _All_ refers to all of both, and all other items in that one group can be clicked and preferably combined, so multi-selection

**Comment by claudiaHash** [comment]
I believe each option comes with its pros

- putting existing filters on one line, would simplify a lot the search implementation since one filter can be used at a time, but the filtering options are limited
- regarding the combined search functionality, the last option has them all, even if I'm not sure how can we integrate an _All_ referring to all of both filter categories

**Comment by kremalicious** [comment]
The combination could be already just work with what's currently in #388. So then we could make the bar like so:

<img width="645" alt="Screen Shot 2021-02-22 at 15 19 16" src="https://user-images.githubusercontent.com/90316/108720645-5c6dc380-7521-11eb-8541-61e88123cd2d.png">

From quick testing combinations then also work, although interaction-wise there should be a way to deselect a given selection maybe in a pattern what Material calls [deletable chip](https://material-ui.com/components/chips/#chip-2) with that `x`:

<img width="197" alt="Screen Shot 2021-02-22 at 15 27 01" src="https://user-images.githubusercontent.com/90316/108721566-6ba14100-7522-11eb-9397-90e7d9df0e05.png">

Simple click/click again to deselect instead of hitting tiny `x` could be fine too, but the `x` nicely shows that this is possible to user
