### ISSUE TITLE
Market: Only allow code merges if unit test code coverage ratchets up

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#396]
**Is your feature request related to a problem? Please describe.**
We constantly have bug "fixes" where it's just a change to the code, but there are no unit tests. Over time the quality of the sw deteriorates. The excuse is "not enough time" but this is simply untrue because we *do* pay back in spades. Quality comes for free, and then some. So we need to do more tactics to enhance quality. And helping to ratchet up code coverage ratchets up is a good one.

Towards code quality, if we have a constraint where % code coverage must go upwards, it not only prevents code quality from degrading due to missing tests, over time it ratchets the % coverage upwards and therefore quality upwards.

**Describe the solution you'd like**
Only allow a PR to be merged (or a direct commit) if % code coverage doesn't go down.

This is pretty common SW engineering practice. We did it on the bigchaindb code base with good success. Let's do it here.

**Comment by trentmc** [comment]
Making high priority to prevent further slippage of quality.

**Comment by kremalicious** [comment]
this is exactly how we operate. But we never had time to catch up with the tests, there actually needs to be a testing strategy implemented first based on #128. Setting the branch protection so only increases in test coverage are mergeable is trivial, done anyway, and does not need it's extra issue

**Comment by trentmc** [comment]
I love that we already have it here! +10
