### ISSUE TITLE
Incorrect processing of markdown in asset teaser

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#410]
The asset is on the polygon network. did:op:b27E48a56CD372355918192A46052Cef012Cc07b.
In the teaser we get `\n\n###`
![image](https://user-images.githubusercontent.com/26000280/109502747-1032fe00-7aa2-11eb-92be-ad1f2f3081de.png)
![image](https://user-images.githubusercontent.com/26000280/109502776-1a54fc80-7aa2-11eb-8181-bd661a38b533.png)

**Comment by kremalicious** [comment]
seems like https://github.com/stiang/remove-markdown fails somewhere, the intention is to strip out any markdown-related characters from the description.

**Comment by DimitarSD** [comment]
[Remove markdown](https://github.com/stiang/remove-markdown) is working fine and it replaces everything correctly, including `\n\n`. It breaks with the format of the `additionalInformation.description`

The Rinkeby version is:
```json
"description": "The wordlist used by ocean.js to generate datatoken names within the Ocean Protocol ecosystem.\n\n### Data Structure\n\nThe json object holds 2 arrays of strings, nouns and adjectives.\n\n```\n{\n  \"nouns\": [ \"Crab\", \"Fish\", \"Shark\", \"Squid\", \"Whale\"],\n  \"adjectives\": [ \"adamant\", \"adroit\" ]\n}\n```"
```

The Polygon version is: 

```json
"description": "The wordlist used by ocean.js to generate [datatoken](https://oceanprotocol.com/technology/data-tokens) names within the Ocean Protocol ecosystem.\\n\\n### Data Structure\\n\\nThe json object holds 2 arrays of strings, `nouns` and `adjectives`.\\n\\n```json\\n{\\n  \"nouns\": [ \"Crab\", \"Fish\", \"Shark\"],\\n  \"adjectives\": [ \"adamant\", \"adroit\" ]\\n}\\n```"
```

There is only one difference. All `\n\n` are actually `\\n\\n` in the second version deployed on Polygon. This is where remove markdown can't process the description and returns the response from above `\n\n###`

**Comment by mihaisc** [comment]
Ok so basically it's bad formatted and the component  is doing its best
