### ISSUE TITLE
Add slippage indicator as proxy for data set pool quality of liquidity

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#430]
**Challenge:** I want to swap OCEAN for datatokens (or vice versa), and a pool's liquidity is low, and I'm super concerned about losing $$ because of slippage. I don't have visibility into the tradeoff of amount traded versus price slippage. 

I *do* know the pool's liquidity (and some other stats). Liquidity is a useful signal towards dataset pool quality, as are others. However not seeing the exact slippage for my trade feels like flying partly blind when swapping, and is concerning.

**Proposed solution:** add slippage indicator to the UI, like Uniswap and other DEXes do.

**Related:** this was borne out of an issue with a different scope: #391

## Scope

Add a "price impact" metric that is based on a pool's slippage to the UI. An example from Uniswap:

![image](https://user-images.githubusercontent.com/2758453/110489821-fc197d00-80ef-11eb-9e15-1ef0f72852ee.png)

Note how they use color coding to predict the trade's safety (red: danger, green: ok).

**Comment by trentmc** [comment]
There's already partial support for this.

Note: there's already a "price impact" tolerance dropdown. If the slippage > chosen impact, the trade doesn't go through.

![impact.png](https://images.zenhubusercontent.com/5df770bc5c7a2019891bc4a0/7b714865-bf1c-4622-ab25-c9d0a3cf0ed9)

**Comment by kremalicious** [comment]
So that UI should probably be something like this, where we switch the labels. Without knowing the actual price impact for the respective trade, the slippage setting is still a hit or miss for users:

<img width="467" alt="Screen Shot 2021-03-11 at 13 03 18" src="https://user-images.githubusercontent.com/90316/110784592-298a3600-826a-11eb-9caf-8138cc330b0b.png">

**Comment by KatunaNorbert** [comment]
There are multiple formulas for calculating the price impact, this is the one used by Uniswap:
https://github.com/Uniswap/uniswap-interface/blob/dcaed9094e48d4f0bba3d2285d134a927fd75975/src/utils/computeFiatValuePriceImpact.tsx#L5

They convert the input and output values to fiat and get the difference in percent
