### ISSUE TITLE
Edit history shows updates on never updated assets

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#436]
Edit history for any asset shows at least 2 entries, even if it has never been updated after initial creation:

<img width="333" alt="Screen Shot 2021-03-11 at 17 39 08" src="https://user-images.githubusercontent.com/90316/110821812-bba53500-8290-11eb-9d25-dc60124fbe29.png">

This is caused by market implementation assuming that in the GraphQL query, `datatokens.updates` only contains updates after the creation, hence the additional query for `createTime` & `tx`. But the `datatokens.updates` has the metadata creation event as the first item, 

There are 2 ways to solve that:
1. in `market` assume the first item in `datatokens.updates` is the creation event, and output accordingly to switch text. Then `datatokens.createTime` & `datatokens.tx` can be removed.
2. in `ocean-subgraph`, remove the creation event from `datatokens.updates` as done in https://github.com/oceanprotocol/ocean-subgraph/pull/54

As [pointed out in `ocean-subgraph`](https://github.com/oceanprotocol/ocean-subgraph/pull/54#issuecomment-796705670) using the actual metadata creation (not the datatoken creation) transaction seems more in line how we display it in the UI so 1. would be preferred.

While we are at it, we could simply output both, datatoken creation, and metadata creation which in turn makes this more transparent too. Like `created datatoken 22 min. ago` & `created metadata 22 min. ago`

**Comment by mihaisc** [comment]
I don't really like the assumption part but I see no other way, so option 1 is the way to go.
