### ISSUE TITLE
Better document icon in consume 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#443]
![image](https://user-images.githubusercontent.com/26000280/111456938-3ef6d880-8720-11eb-9f81-24e63a71894b.png)
- the text is out of bounds, not sure how to proceed
- is the information relevant ?
- do we need to display it like this

**Comment by kremalicious** [comment]
Yeah, this got way worse since we use the provider to detect file info, which most of the time gives us back stuff like that. It can't properly handle files on IPFS, while our former js solution could.

**Comment by DimitarSD** [comment]
Any progress on this issue? 

> The above example is a csv file and that's all the provider endpoint should tell us

Should we then display only the type of file? We could have something this :

![Screenshot 2021-04-22 at 10.13.31.png](https://images.zenhubusercontent.com/6017d0882d567e541be6f1e1/bcfa0bb7-ccef-4a00-a13c-ca05381d5136)

If we want to display more data we could show it `onHover()` or maybe add it under the icon?

**Comment by jamiehewitt15** [comment]
To me it looks like this issue has already been solved, I haven't found any examples with the text of bounds. Could you share a link to any datasets still effected? If it's solved already lets close this. 

![csv snip- 2021-05-13_13-10](https://user-images.githubusercontent.com/20739535/118111703-bc6f5a00-b3ec-11eb-820b-332113a42736.png)

**Comment by mihaisc** [comment]
This was probably fixed in the provider. Seems ok to me as well
