### ISSUE TITLE
Hide outdated / old / redundant assets

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#445]
As discussed with @trentmc during the last DAO town hall meeting I would like to request to hide a dataset / data service from the market interface once it is outdated or migrated to another chain.

This would require the same functionality as for the purgatory with slight modifications:

a. The publisher should not be put into purgatory
b. There should not be any attribution to purgatory because this would impact the reputation of the publisher

This feature would be all about cleaning the marketplace interface up and allow for better visibility of "good" datasets and -services.

I would request to hide i.e. this one: https://market.oceanprotocol.com/asset/did:op:10b1CfF754bE22181a5bE5c2825F1bBC56473DFE

It has been created and due to an error in the process it has been made obsolute by creating a new dataset.

In my opinion it is necessary, that publishers and LPs and token holders still have the option to interact with "hidden" pools as they might want to remove the last bit of liquidity later on.

Looking forward to a discussion and implementation.

**Comment by trentmc** [comment]
Thanks for documenting this, Kai.

**Comment by kaimeinke** [comment]
I followed the discussion in https://github.com/oceanprotocol/market/issues/452 and I would like to add that this "unlist" feature might get additional priority due to regulatory concerns. During April and May the German Authorities are working on a new law regarding tokenized assets. This might lead to the need to unlist assets that do not comply with regulatory requirements. I would love to have this feature rather sooner than later.

**Comment by alexcos20** [comment]
what happens when there is pool and people have liquidity ? if we "retire" the asset, it's not going to be visible.

**Comment by kaimeinke** [comment]
This could work as in purgatory. All people invested in it can still access it and remove liquidity, but interactions from new participants would be impossible.

**Comment by kremalicious** [comment]
This can be revisited with v4, as the Data NFT includes a new `state` field, see https://github.com/oceanprotocol/docs/blob/feature/ddo_v4/content/concepts/did-ddo.md#state

Still pending to be defined which component does what with which state.

**Comment by mihaisc** [comment]
https://docs.oceanprotocol.com/concepts/did-ddo/#state Updating the state to 1,2,3 will remove the asset from `Aquarius`
