### ISSUE TITLE
Data Assets Visibility or Migration across networks

### ISSUE THREAD

**Issue by srikanthkaja31** [oceanprotocol/market#460]
As per discussion with @alexcos20, Enterprises launch the marketplace on a specific network. However for some scenarios (like high gas fees in ETH) they might have to migrate to a different network to ensure marketplace operates with low transactions costs or high speed. For such scenarios if they arise,

a. How can the marketplace migrate their data assets without manually creating all of them?
b. Is there any way that data assets can be available across networks?

**Comment by trentmc** [comment]
> Data asset visibility across networks

This is being handled in Q2 work: for Ocean Market to see data assets across >1 networks at once. The core idea is for Aquarius to cache metadata across chains. multi-repo-issue#67

> Migration across networks

This will be handled after the issue above, likely in Q3. The core idea is: easily bridge ERC20 datatokens among the networks. That's in issue [multi-repo-issue#94](https://github.com/oceanprotocol/multi-repo-issue/issues/94).

There's a workaround for people with data assets on Eth mainnet right now: remove enough liquidity in the old AMM, and then it's kosher to re-publish; if you re-publish without doing this you'll get put into purgatory. Details in the "Prior-Published Datasets / Services" of the  ["Ocean's on Polygon" blog](https://blog.oceanprotocol.com/ocean-on-polygon-network-8abad19cbf47).

----

To answer the questions specifically: 

> a. How can the marketplace migrate their data assets without manually creating all of them?

Bridge datatokens. See "migration across networks" section above.

> b. Is there any way that data assets can be available across networks?

Ocean Market (or any market) see >1 chains at once. Details above.

----

Given that the questions were answered, and that the actual scope of work is already covered by other issues (referenced here), I am closing this ticket. Please re-open if you deem appropriate.
