### ISSUE TITLE
Dataset Provenance for Authenticity Confidence

### ISSUE THREAD

**Issue by seldamat** [oceanprotocol/market#465]
**Is your feature request related to a problem? Please describe.**
Verifiable version history of a dataset can install confidence for authenticity and quality. Stakers and dataset consumers can be more confident in a dataset if they can view a verifiable version history that includes the genesis, revision, and updates to a dataset. 

**Describe the solution you'd like**
Provenance tracking for datasets is missing on Ocean Market. I envision a simple drop-down UI that shows the version history of the dataset, including detailed information for each commit, timestamps, and perhaps signed tags by the owner to validate updates.

An example of dataset versioning is nicely done with datalad: http://handbook.datalad.org/en/latest/index.html

**Describe alternatives you've considered**
Current alternative solutions for ensuring dataset quality include verification with 3box profiles. A simple in-house solution that doesn't depend on external software would be to include a version history of a dataset. This would work well with other authentication sanity checks.

**Additional context**
Following up on the conversation from OceaDAO Townhall 24, Mar

**Comment by mihaisc** [comment]
This is a good topic but unfortunately no easy solutions. Thank you for your feedback
