### ISSUE TITLE
Ocean Market supports >1 market per datatoken

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#467]
### What / TODO for this issue

Give an affordance for the user to discover >1 markets for a given datatoken. Some of these may be markets within the Ocean Market app (e.g. Bal V1 friendly fork); others could simply be linked to (e.g. Uniswap DT pool). 

Prerequisite issue: [MultiRepo#59](https://github.com/oceanprotocol/multi-repo-issue/issues/59) "Publish|DEX|Consume Tabs"

### Motivation

A given datatoken may be in one or more of the following markets / pricing schemes:
- FRE
- OCEAN-DT 90/10 pool on Bal V1 friendly fork
- OCEAN-DT 30/70 pool on Bal V1 friendly fork
- OCEAN-DT 50/50 pool on Uniswap
- OCEAN-DT 50/50 pool on Bancor
- DT1-DT2-..-DT8 pool on Bal V1 ("data index pool")
- OceanO-DT 30/70 pool on Bal V1 friendly fork
- OceanO-DT 30/70 pool on Bal V2
- OceanO-DT pool on Bal V2 with 1MM

### Benefits

Doing this issue will bring many benefits listed in [MultiRepo#59](https://github.com/oceanprotocol/multi-repo-issue/issues/59), especially:

- Support requests by enterprise engagements for other pricing methods
- Easier to support OCEAN-backed stablecoin pricing, 3rd party marketplace token, >1 of these for a given datatoken
- Easier to support "Better staking"
- Gives a path to migrate from old pools (eg 90/10) to newer ones (eg 30/70) or upcoming ones (eg 1SS)

**Comment by kremalicious** [comment]
> Give an affordance for the user to discover >1 markets for a given datatoken

Based on this, issue implies simply adding a link to a secondary market on any asset where the respective datatoken can be found in some external pool. And that's it. We keep the concept of our Balancer pools being the primary source of price.

But then don't see how most of the benefits are met. And the last listed benefit implies even more, some way to make a new pool into the primary pool for the dataset. It also implies giving users the option to create a new (Bal V1 friendly fork) pool through the market interface. To me this is a feature in itself requiring many different user flows. Considering Bal V2, we should simply skip that and rather think of migrations between Bal V1 friendly fork & Bal V2. Again, none of that is solved by just showing more secondary markets.

If we want to get rid of primary/secondary markets, then we need to solve the price issue and figure out a way to have a consolidated price based on multiple markets.

**Comment by trentmc** [comment]
>  Based on this, issue implies simply adding a link to a secondary market on any asset where the respective datatoken can be found in some external pool. And that's it. 

No. That's not just it. Read the very next line.

> Some of these may be markets within the Ocean Market app (e.g. Bal V1 friendly fork); others could simply be linked to (e.g. Uniswap DT pool).

So there could be >1 markets in the Ocean Market app itself. And there likely _should_ be. Look at the "Benefits" section: it points to the use cases that we want to cover. This includes migration from an old pool to a new one. A good way to solve that ise >1 markets in the Ocean Market app itself.

> If we want to get rid of primary/secondary markets concept, then we need to solve the price issue first and figure out a way to have a consolidated price based on multiple markets. Which should also be implemented in the subgraph first.

I'm not advocating getting rid of primary/secondary markets concept. The feature of this issue has both primary market and secondary market, and doesn't actually need to distinguish them (a good thing). Eg the publisher could create two pools and put DTs into each. 

We don't need a "consolidated price". Each market could have it's own price, that's kind of the point of markets! Traders can discover what's best for them, just like they do right now with other tokens in blockchain land.
