### ISSUE TITLE
Market code can support different base token

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#468]
**What**

Ocean backend code supports different base tokens. Ocean frontend code has a stronger bias to use OCEAN as a base token. 

Goal of this issue: make it more straightforward for Ocean frontend code to use a different base token.

**Motivation**

This helps in two ways:
1. Helps several 3rd party marketplaces, which would like to use their own token at the frontend level, eg for pools staking/swapping and for FRE.
2. Helps Ocean Market switch from using OCEAN, to an OCEAN-backed stablecoin -- [market#447](https://github.com/oceanprotocol/market/issues/447)

**Comment by kremalicious** [comment]
No, we had this in mind when refactoring things but we never tested a different base token, and there are still places which assume OCEAN alone. We always said to do this after v4

**Comment by mihaisc** [comment]
Ok, closing this. Concrete implementation of multiple approved tokens will be tracked here https://github.com/oceanprotocol/market/issues/1335
