### ISSUE TITLE
Toggle pricing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#469]
**What**

An instance of an Ocean-based market can be configured to show / not show each of: 
- AMM
- Fixed Rate Exchange

And more in the future as they get supported:
-[Free](https://github.com/oceanprotocol/multi-repo-issue/issues/91)
-Royalties and other fancier pricing schemes

This configuration can simply be in envvars or config files; no need for a dashboard or anything fancy.

**Motivation**

- Many 3rd party marketplaces only want certain pricing features. E.g. just FRE, or just AMM. 
- Supporting "free" allows data sharing use cases side-by-side with priced cases
- Easier to try out new pricing schemes in one market; other markets can opt-in when they want

**Comment by kremalicious** [comment]
done in https://github.com/oceanprotocol/market/pull/453

**Comment by trentmc** [comment]
> We can't support what is not there.

Very zen, lol :P 

> done in #453

Great! :)
