### ISSUE TITLE
deal with isConsumable

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#473]
I lost track if we can expect to trust Aquarius any time soon for https://github.com/oceanprotocol/aquarius/issues/409

As of right now, there is no `isConsumable` check for the compute action (there is for download). If the above issue gets fixed, we need to add this check to compute too and do the same in the UI as in consume.

**Comment by alexcos20** [comment]
let's ditch it

**Comment by mihaisc** [comment]
I suggest we don't fix it here. There is already an issue for this https://github.com/oceanprotocol/market/issues/497 that will fix it in all market. We can do a temp hack here until the issue mentioned is fixed. In `AssetProvider`, in `initMetadata` , before `setPrice(ddo.price)` we put a `ddo.price.isConsumable=true`. We remove this once the proper fix is in place.
