### ISSUE TITLE
no logs for compute jobs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#505]
When clicking on any of my latest compute jobs from within the last 5 days, none of them show me logs after I signed with MetaMask:

<img width="1123" alt="Screen Shot 2021-04-14 at 11 02 42" src="https://user-images.githubusercontent.com/90316/114684160-f0cdf880-9d10-11eb-9e90-66cada71a92f.png">

**Comment by mihaisc** [comment]
Not a bug in market, the c2d infrastructure is being fixed
