### ISSUE TITLE
main search button became pink

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#506]
something just happened on live, and the search button became crazy pink. We neither have plain pink buttons, nor should that button be that prominent. 

<img width="858" alt="Screen Shot 2021-04-14 at 12 55 30" src="https://user-images.githubusercontent.com/90316/114699516-b3716700-9d20-11eb-9142-1a402e7de0a5.png">

Should be the default grayish button as before

<img width="817" alt="Screen Shot 2021-04-14 at 12 57 06" src="https://user-images.githubusercontent.com/90316/114699731-f5021200-9d20-11eb-9659-b83ab09d8ffd.png">

That change suggests somewhere some CSS selector was used without proper scoping

**Comment by kremalicious** [comment]
in #461, all our default buttons across the app were changed to pink and all buttons were given a too harsh box-shadow. Was this intended?

https://github.com/oceanprotocol/market/commit/7c09ceca06b71164d1bacc5418c13f1b6a591c11#diff-d66f98cce76a1dc53cbd3a3ba64035e748e7e5c1c527446cfb4a621ff88a40feR16

Please use the `<Button>` component styles if you want to highlight a specific button, our primary button is `<Button style="primary">...</Button>`

**Comment by jamiehewitt15** [comment]
On of the suggestions in https://github.com/oceanprotocol/market/issues/366 was to "make it more obvious that the 'ADD FILE' text is actually a *button*.".  So I changed the colour and shadow to make it more obvious it was a button. 

I have changed the default styling back to how it was here: https://github.com/oceanprotocol/market/pull/507/files

**Comment by mihaisc** [comment]
totally missed that change, my bad.

**Comment by kremalicious** [comment]
Got it, so for that intention the solution is to add `style="primary"` to the place where the button component is used. So here https://github.com/oceanprotocol/market/blob/main/src/components/molecules/FormFields/FilesInput/Input.tsx#L28

**Comment by jamiehewitt15** [comment]
Ok, thank you for that explanation @kremalicious, I appreciate the feedback. 

I have implemented that change in this pull request: https://github.com/oceanprotocol/market/pull/507

**Comment by kremalicious** [comment]
thanks for the quick fix!

**Comment by jamiehewitt15** [comment]
Happy to sort it out, sorry for the initial issue
