### ISSUE TITLE
Sync status randomly fails

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#508]
This component fails randomly, can't replicate consistently. We need to investigate further
![image](https://user-images.githubusercontent.com/26000280/114704987-e53dfa00-9d2f-11eb-892c-12bd721018bd.png)

**Comment by kremalicious** [comment]
for me, when it happens, it happens on the production build, was not able to get it reproduced in dev build. And only happens for me when wallet network is different than default ETH main
