### ISSUE TITLE
Assets ordered for starting compute jobs show up under Downloads in History

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#509]
Not sure what the best solution here is but it feels confusing because from user perspective they did not download anything, here the last 2 assets:

<img width="1193" alt="Screen Shot 2021-04-14 at 14 36 12" src="https://user-images.githubusercontent.com/90316/114711220-fe927680-9d2e-11eb-9da2-ac5f60aa220a.png">

One solution could be to simply hide non-download orders in this list.

**Comment by mihaisc** [comment]
yes, because we don't do any filtering here like we do on the compute page. So basically for each asset check if it has a compute or access service. If it's access show, if it's compute ignore.
