### ISSUE TITLE
Probable issue with previous order

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#529]
From discord 
```
Below is current behaviour.
Let's say I have > 2.0 of the same datatoken in my wallet.
1) I buy the dataset and the UI button changes to Download. I download the dataset.

2) I go off and then navigate back to the same page. The UI button links to BUY again.

    But, perhaps I just want to re-download the dataset (for example, maybe I misplaced it).

    * If I click on BUY then reject the transaction, the UI button changes to Download again...
```

Did not investigate further but this seems to be an issue with fetching the previous order.

**Comment by kremalicious** [comment]
>  * If I click on BUY then reject the transaction, the UI button changes to Download again...

yeah got specifically this too and should be investigated too, only this might have nothing to do with previous order checking and is just some UI logic going wrong. So basically hit Buy button wherever, and then reject first MetaMask transaction. Buy button will always become Download button
