### ISSUE TITLE
Compute results storage info

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#532]
I remember some talk about a restriction where we store the results for a finite amount of time? If so, we should add some help text within the job detail modal informing users about that.

**Comment by mihaisc** [comment]
@alexcos20 what are the constraints that we should enforce? 
- Compute time
- Results held for x amount of time
-  Maximum size of results/logs

**Comment by alexcos20** [comment]
For now, we have the following:
 - max dataset(s) size:  1GB
 - max algo running time: 1 min
 - results stored in ipfs for 30 days (wip)
