### ISSUE TITLE
Search by Token Name

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/market#536]
In order to find data assets as quick and comfortable as possible the full text search could include the token names.

Example:
LUMSTA-42 belongs to https://market.oceanprotocol.com/asset/did:op:a2B8b3aC4207CFCCbDe4Ac7fa40214fd00A2BA71 

![image](https://user-images.githubusercontent.com/59994024/115058531-a8b3ff00-9ee5-11eb-9521-aba1c8a7a923.png)

**Comment by kremalicious** [comment]
almost sure this has worked before so considering this a bug most likely introduced when we switched the those new search queries in Aquarius
