### ISSUE TITLE
Proxy for docker hub validation

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#572]
We need to create a proxy for `https://hub.docker.com/v2/repositories` so we don't run into CORS issues when publishing an algorithm

**Comment by kremalicious** [comment]
After proxy is in place, put back check disabled in 52280105759c415c287cf164651ae26530822074

**Comment by kremalicious** [comment]
We now have:
- repo: https://github.com/oceanprotocol/dockerhub-proxy
- auto-deployed under: https://dockerhub-proxy.oceanprotocol.com

@bogdanfazakas just feel free to push to `main` in that repo however you want to make it work. Basically copied the setup of our old `fileinfo` repo so all just suggestions, would be also no need to specifically use axios here

Prepared the api key here https://github.com/oceanprotocol/dockerhub-proxy/blob/main/api/index.ts#L5 but have not figured out yet where to get this on DockerHub, this would need to be added to the Vercel project then

**Comment by bogdanfazakas** [comment]
Thanks @kremalicious 🚀 
 Updated the repo all fine for the moment. I'm going to update the market now and create a new PR for this to put back in place the disabled check from here [5228010](https://github.com/oceanprotocol/market/commit/52280105759c415c287cf164651ae26530822074) and use our new endpoint for it.
