### ISSUE TITLE
List of algorithms to select seems capped

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#580]
When editing compute settings of a compute data set, the `AssetSelecttion` list of algorithms seems to be capped at 35 items.

Example on Rinkeby, when searching for all algos with a price like so:
https://market.oceanprotocol.com/search?serviceType=algorithm&sort=created&sortOrder=desc&priceType=all
<img width="842" alt="Screen Shot 2021-05-04 at 21 22 11" src="https://user-images.githubusercontent.com/90316/117058344-cd4e0a80-ad1e-11eb-9bb4-bbec1e23e483.png">

So when editing compute settings, 58 algos should show up in AssetSelection yet in my case I count 35. 

If I remember correctly we do not do any `provider` match check yet as is worked on in #510, so there should be no other restrictions in place for algos to show up for selection. Might be that we specifically need to set some pagination parameters when querying Aquarius and we're just hitting some pagination default.

Worth checking if we have some unintended cap in place for `AssetSelection` within the start compute job component too.

**Comment by bogdanfazakas** [comment]
True no `provider` match check yet in here, but we have another filter for assets without price, so in `AssetSelection` from both edit compute and start compute job we display just the algorithms that have `price` created. This filter is done here https://github.com/oceanprotocol/market/blob/main/src/utils/aquarius.ts#L125 and the array of prices is populated here https://github.com/oceanprotocol/market/blob/main/src/utils/aquarius.ts#L125
So not sure if we should remove those checks or it should stay as it is or maybe even trying to display different lists for edit compute and start compute job in `AssetSelection`
