### ISSUE TITLE
Add method to check dataset file length

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#581]
Story:
- As a data seller, my data in file endpoint is updated daily, and there will be some day where it doesn't have any data (eg: sales data on holiday)
- Hence, I would like my data set to have some warning message to notify user when the file at the endpoint is empty. 

Solution:
- Add a helper method to check data set endpoint file length
- If the file is empty, show a warning message to the user

**Comment by jamiehewitt15** [comment]
This is being handled in: https://github.com/oceanprotocol/market/pull/479#issuecomment-847552554
