### ISSUE TITLE
Remove liquidity estimation fails on some pools

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#584]
On some pools when trying to remove liquidity the estimation of OCEAN user would receive fails:

<img width="1337" alt="Screen Shot 2021-05-05 at 21 20 08" src="https://user-images.githubusercontent.com/90316/117197095-af98a800-ade7-11eb-9d03-83f2917e0b39.png">

When hitting the 100% MAX in this case estimation works again.

I could reproduce this on ETH mainnet for this one so far:
https://market.oceanprotocol.com/asset/did:op:7Bce67697eD2858d0683c631DdE7Af823b7eea38

**Comment by DimitarSD** [comment]
Hmm, I was getting the same error after we switched from `bignumber.js` to `decimal.js`. When using decimal.js sometimes the results contain more than 18 digits after the decimal point which causes the conversion to wei to fail. I've included [precision](https://github.com/oceanprotocol/market/blob/49cd032274788271f06d1c7e8c7c0143dd8ae171/src/components/organisms/AssetActions/Pool/Remove.tsx#L176) `toPrecision(18)` which fixed it. Not sure if the error is happening in the same place.

**Comment by kremalicious** [comment]
Think it's over in ocean.js. No matter what I do on market (using `.toFixed(18)` instead of `.toPrecision(18)`) I get the correct decimal number when outputting in console.log, yet the error then has a `0` more at the end:

<img width="988" alt="Screen Shot 2021-05-06 at 11 48 51" src="https://user-images.githubusercontent.com/90316/117278406-09898400-ae61-11eb-85fa-a775170df12e.png">

**Comment by mihaisc** [comment]
Check out https://github.com/oceanprotocol/market/blob/6cc268bd3fac39dd6afe25403c7aa964574f5ba8/src/components/organisms/AssetActions/Trade/FormTrade.tsx#L79
Don't remember exactly why i went with precision 15.

We still use number here https://github.com/oceanprotocol/market/blob/6cc268bd3fac39dd6afe25403c7aa964574f5ba8/src/components/organisms/AssetActions/Pool/Remove.tsx#L160

We should use toString, not `setAmountPoolShares(`${amountPoolShares}`)`

**Comment by kremalicious** [comment]
remaining Number usage in Remove is fine cause that's just for UI presentation. Tried some more, but we might not get around rather working with wei everywhere. This is with 15 precision:

<img width="980" alt="Screen Shot 2021-05-06 at 12 12 46" src="https://user-images.githubusercontent.com/90316/117281846-5f136000-ae64-11eb-8e9a-acc8375d108e.png">

**Comment by mihaisc** [comment]
This needs to be debugged full stack, with ocean.js, to see where the number changes.

**Comment by DimitarSD** [comment]
The issue is coming from `decimal.js`. If we have the following number:

0.000002245678912345679 - as a result of calculations
0.00000224567891234567900 - as a result of calculations with `.toPrecision(18)`

Decimal.js counts significant digits and [it doesn't include 0s](https://mikemcl.github.io/decimal.js/#toPrecision). In the example above it counts the digits after `0.00000` (i.e. 2245678912345679 - 16 digits). It's always 16 digits so when we use `.toPrecision(18)` it adds two 0s to make them 18.

If we have, let's say, 12.3456789123456789 (18 digits) it will return 12.34567891234567 (16 digits), and with`.toPrecision(18)` it will return 12.3456789123456700.

I'll try with `.toFixed()`, I think it might work

**Comment by kremalicious** [comment]
Also checking out `ethjs-unit`, we are hitting this check:
https://github.com/ethjs/ethjs-unit/blob/master/src/index.js#L140

Maybe important for ocean.js:

> the toWei returns a BN instance while fromWei always returns a string number

https://github.com/ethjs/ethjs-unit#about

**Comment by DimitarSD** [comment]
Yep, `ethjs-unit` checks for 18 (or less) digits after the decimal point. I tried `.toFixed(18)` instead of `.toPrecision(18)` it seems now it always returns 18 digits after the decimal point (what `ethjs-unit` wants) and it works. Not sure if we need to change something in `ocean.js`

**Comment by kremalicious** [comment]
nice, can confirm, this is a success:

```js
    const amountPoolShares = new Decimal(e.target.value)
      .dividedBy(100)
      .mul(new Decimal(poolTokens))
      .toFixed(18) // in some cases the returned value contain more than 18 digits which break conversion to wei
      .toString()

    setAmountPoolShares(amountPoolShares)
```

testing the difference in my case:
<img width="350" alt="Screen Shot 2021-05-06 at 12 59 50" src="https://user-images.githubusercontent.com/90316/117287725-f4195780-ae6a-11eb-88d9-2965ca4c0c9e.png">

**Comment by kremalicious** [comment]
But! Here this could lead to problems cause now the `toFixed(18)` produces higher number than before?

<img width="347" alt="Screen Shot 2021-05-06 at 13 02 54" src="https://user-images.githubusercontent.com/90316/117288067-62f6b080-ae6b-11eb-99a5-98571bca5871.png">

**Comment by DimitarSD** [comment]
What do you use for `amountPoolSharesPrecision`?

**Comment by kremalicious** [comment]
Same as for `amountPoolShares` but with original `.toPrecision(18)` in place of `.toFixed(18)`

```js
    const amountPoolSharesPrecision = new Decimal(e.target.value)
      .dividedBy(100)
      .mul(new Decimal(poolTokens))
      .toPrecision(18) // in some cases the returned value contain more than 18 digits which break conversion to wei
      .toString()
```

**Comment by mihaisc** [comment]
https://mikemcl.github.io/decimal.js/#toPrecision
https://mikemcl.github.io/decimal.js/#toFixed

So yes, i think the correct way would be toPrecision(18).Please change this in all places that uses decimal

**Comment by kremalicious** [comment]
sorry, example not clear, `toPrecision(18)` is what we have right now, resulting in the bug so `amountPoolShares` in my examples is the tried fix with `toFixed(18)`

so for an example like this
<img width="348" alt="Screen Shot 2021-05-06 at 14 53 09" src="https://user-images.githubusercontent.com/90316/117301290-c76d3c00-ae7a-11eb-9557-fe0669777339.png">

we could make sure to rather round down instead of up, then at least we would not run into failed tx. UX downside is some pool tokens leftover in wallet

**Comment by kremalicious** [comment]
think I got it, we need to set the `Decimal` [rounding mode](https://mikemcl.github.io/decimal.js/#modes).

```js
Decimal.set({ precision: 18, rounding: 1 })

const amountPoolSharesPrecision = new Decimal(e.target.value)
      .dividedBy(100)
      .mul(new Decimal(poolTokens))
      .toString()
```

With that some samples on a real pool where I was running into errors before where `amountPoolSharesPrecision` looks like the thing we want:

<img width="525" alt="Screen Shot 2021-05-06 at 16 37 50" src="https://user-images.githubusercontent.com/90316/117317029-6d27a780-ae89-11eb-976d-3610bafc9c1d.png">
