### ISSUE TITLE
Buying a compute job throws "error ordering asset" in random cases

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/market#593]
When the user is buying a compute job he gets an error "Error ordering assets". It's a random bug, it's not happening always. However, it's happening frequently enough to be a problem not provoked by something simple.

I managed to narrow down the bug to a few cases and "predefined environments":

- Buying a compute job for the first time (or after the timeout has passed for your last purchase). Most of the time I'm getting the error when working with "Ocean Chlorophyll Concentration Annual Composite Image (2018)" or "Daily Fishing Effort" both on Polygon. But it could be happening with others too.
- I'm getting the error when testing on Polygon
- In the console, I'm getting the following errors:
  - DOMException: Aborted
  - ERROR: Failed to order: HTTP request failed
  - Finding the service endpoints failed: DOMException: Aborted
- Trying to buy the compute job again (after receiving the error and without refreshing) will either:
  - keep showing the same error
  - successfully buy the compute job ([as in the video](https://drive.google.com/file/d/1LbP5kgBN5Zfh41Xfe7Xp4Mhtdqo2H5FX/view?usp=sharing))

I'm not sure if the issue is coming from a bug in the code, it might be also RPC-related.

![error-ordering-asset.png](https://images.zenhubusercontent.com/6017d0882d567e541be6f1e1/e27609de-80d5-430a-b8be-7222adbc352d)

**Comment by mihaisc** [comment]
What http request failed?

**Comment by bogdanfazakas** [comment]
@DimitarSD  can you please try to reproduce this on this #588 PR's live preview, in my opinion this issues are related (not 100% sure tho). I personally tried and reproduced the issue on our live market but never bumped into it when using the mentioned preview, so maybe something related to caching of subgraph values or the added checks for previous orders that were fixed there are also the root of the problem

**Comment by DimitarSD** [comment]
@mihaisc I can't see it. It doesn't return any information.

@bogdanfazakas I'll check it now

**Comment by mihaisc** [comment]
Check network tab and see what failed

**Comment by DimitarSD** [comment]
@mihaisc I think I managed to track it down (not 100% if this is the request - I was testing other stuff too). But this is the only request for that compute job that failed today (a couple of hours ago when I got the error above)

```
fetch("https://provider.polygon.oceanprotocol.com/api/v1/services/initialize?documentId=did:op:38D471eC06d2bA6DF6Fd14E48268CABFe6d2bF1C&serviceId=1&serviceType=access&dataToken=0x38D471eC06d2bA6DF6Fd14E48268CABFe6d2bF1C&consumerAddress=0x47F899a8F4dF04C75eDdc05E091cA26ed93a46Df", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,bg;q=0.8",
    "content-type": "application/json",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\"",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrer": "http://localhost:8000/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by mihaisc** [comment]
@md00ux can we get some logs from the polygon provider?
@DimitarSD can we get better timing on when that request was made?

**Comment by DimitarSD** [comment]
Yep, it should be somewhere between `10:50:00 GMT` - `11:05:00 GMT`, May 12th. Maybe around 11 am GMT since the request that passed happened on `Wed, 12 May 2021 11:03:03 GMT` and a few minutes before that was the one that failed.

**Comment by bogdanfazakas** [comment]
So i was able to reproduce the issue also, it happens all the time for me with this `dataset(did:op:aa82a24d62de1eB817c2173fff8B8c12d7b1Bbf9)` + `algorithm(did:op:3723dED928610F8F546482DB740C40Ae8E887e5a)` combination on `Rinkeby` and if fails all the time at ordering algorithm. The error is a `400 {"error":"Asset URL not found or not available."}` thrown by the provider on this `Get` `request https://provider.rinkeby.oceanprotocol.com/api/v1/services/initialize?documentId=did:op:3723dED928610F8F546482DB740C40Ae8E887e5a&serviceId=3&serviceType=access&dataToken=0x3723dED928610F8F546482DB740C40Ae8E887e5a&consumerAddress=0x968d4670c346275edd5CC1A7535D14b631FFc49C` . I have attached some screenshots below. 
From what i can see not sure if this can be a problem is that the algorithm has 2 `services`, and the `metadata` service has `"index": 0` but the `access` service has the `"index": 3`.
![Screenshot 2021-05-14 at 11 12 51](https://user-images.githubusercontent.com/13447142/118242587-2d267d00-b4a6-11eb-894e-e58e01573e91.png)
![Screenshot 2021-05-14 at 11 13 17](https://user-images.githubusercontent.com/13447142/118242597-2e57aa00-b4a6-11eb-97cf-49fc8c36251f.png)

**Comment by bogdanfazakas** [comment]
@calina-c  see mentioned issue above 😃
