### ISSUE TITLE
Make it easier for forks to avoid infringing on copyright

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#599]
There are various aspects of the Ocean market that are subject to copyright, including the typeface. There are a couple of things that we can do to make it easier for users to fork the market and avoid infringing on any copyright: 

- We should make it clear in the readme which assets and aspects of the styling are subject to to copyright, and are required to be changed. 
- We can look at ways to refactor the market to make it easier and quicker for people to get started with non-copyright infringing styling, possibly using the app.config.js file and environmental variables.

**Comment by trentmc** [comment]
Which aspects are subject to copyright: I believe it's just the typeface. If there are others it would be good to document here.

Everything else is made open according to apache2.

**Comment by jamiehewitt15** [comment]
I suspect the following are also covered by copyright:
- Ocean Protocol Logo
- The name "Ocean Market"

**Comment by jamiehewitt15** [comment]
I have added the above list to the readme: https://github.com/oceanprotocol/market/pull/613/files
