### ISSUE TITLE
completely implement ocean-mock

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#6]
ocean-mock has a minimal implementation so that tests run but stories don't reflect the actual scenarios. This impacts mostly compute and job related components.

-----kremalicious 
good point, because of the way jest works we should rather change the scope to mocking squid. We have to create tests/__mocks__/@oceanprotocol/squid.ts and this will automatically be picked up by all the tests and just with ocean-mock we can use it in the stories too.

**Comment by kremalicious** [comment]
needs complete redefinition after testing setup anyway so closing
