### ISSUE TITLE
Investigate swapping Apollo for urql

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#608]
This might be better for us 
https://formidable.com/open-source/urql/docs/
https://formidable.com/open-source/urql/docs/comparison/

**Comment by kremalicious** [comment]
What are the current problems with Apollo? To me Apollo feels a bit big and overkill for what we use it for so I would tend looking into more minimal approaches, like https://github.com/nearform/graphql-hooks but looks like that `urql` is quite small in API & size too

**Comment by mihaisc** [comment]
That is kinda the point : 
- it's very big  (and we have increased our overall payload without any clear benefit)
- it's overkill, a lot of "features" that we don't use 
- as you saw in the latest time ( the price fetching) we kinda went out of our way to implement it. It was not the recommended and properly documented way.

But, as the label states "prio:low" 😄

**Comment by kremalicious** [comment]
done in #693
