### ISSUE TITLE
too many layout shifts on asset details

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#609]
With the removal of getting data for initial rendering from the DDO we need to maintain the layout better and make sure to minimize layout shifts and repaints as much as possible, for better UX and performance.

One of those places where this becomes very noticeable is the asset details page whose initial layout shifts around a lot, isolated in a looping gif:

![Untitled2](https://user-images.githubusercontent.com/90316/118781913-d944db00-b88d-11eb-9939-414ea7a42dcc.gif)

There are multiple patterns we could use to have layout elements in the right places before we have the data we want to put into this layout, like skeleton UI, longer loading spinner, etc. But in this specific case seems worth looking into:

- why do we get the title so late, leading to one main layout shift?
- why do we get the file info data so late, leading to layout shift because of document icon rendering too late?
- why do we get the description so late, leading to big layout shift within the main content box?
- price initially says "No price set", which is misleading

Everything except price is right there in the DDO so I don't see any reason why this should not be in the initial render. Only price and the tabs coming in late are justifiable

**Comment by mihaisc** [comment]
Everything loads slow because it waits for the price for some reason. This should be fixed. We shouldn't touch anything more complicated, just wait for the redesign.
Like you said everything should load instantly and the action tab should have a better loading state to wait for the price.
