### ISSUE TITLE
Link to datasets and algorithms with pool on home page not working as expected

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/market#630]
**Describe the bug**
When clicking on "DATASETS AND ALGORITHMS WITH POOLS" link, all the assets are displayed

**To Reproduce**
1. Go to home page
2. Click on "DATASETS AND ALGORITHMS WITH POOLS" link
4. See all assets instead of ones with pools

**Expected behavior**
There should be a list of assets with pools displayed

**How to fix**
Now that we don't have the price in the aquarius queries we can't retrieve only the assets with pools.
So we might need to change the link or remove it

**Comment by mihaisc** [comment]
This is deprecated, the pricing schema is no longer in the ddo, thus becoming irelevant.
