### ISSUE TITLE
Value of total price for algorithm asset is wrong

### ISSUE THREAD

**Issue by kianyee** [oceanprotocol/market#637]
**Describe the bug**
Value of total price for algorithm asset is wrong, when the algorithm is under your ownership

**To Reproduce**
1. Go to one of the compute asset under your ownership 
2. Click on 'EDIT COMPUTE SETTINGS '
3. Add an algorithm under your ownership and update DDO
4. From the algorithm selection of asset detail page, click on the algorithm under your ownership

**Expected behavior**
1 + 1 = 2

**Screenshots**
![Screenshot 2021-06-02 at 6 49 31 PM](https://user-images.githubusercontent.com/71874741/120468375-ba892d00-c3d3-11eb-8e27-6ec959415522.png)

**Comment by kremalicious** [comment]
what does your text under the buy button say? What does the detail calculation say in the tooltip? This looks like you have either previous order or a datatoken for one of the assets, hence it won't be included in calculation.

**Comment by kianyee** [comment]
Got it, the calculation is correct.
