### ISSUE TITLE
Allow marketowner to control what networks are supported

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#645]
Since we are deploying contracts to multiple networks, it would be nice to have an ENV variable which controls what networks are supported for a market.

Maybe as a market owner I only want to support Mainnet & Rinkeby.
Or I have a enterprise POA and I only want to allow that.

Now, all networks from contracts/ocean.js are supported by default.

**Comment by mihaisc** [comment]
Shouldn't this be done on aquarius? How would this work on market?

**Comment by kremalicious** [comment]
Done as part of #628 where the app config gets a list of supported chain IDs which then influences what chains are shown in user preference to show which network assets, and the wallet feedback when user is connected to non-supported network.

**Comment by kremalicious** [comment]
This is done in #628 but another big part when a marketplace runs their own Aquarius instance is to tell it the chains to index for which we only have those limited instructions right now https://github.com/oceanprotocol/aquarius#running-aquarius-for-multiple-chains
