### ISSUE TITLE
AssetSelection needs to be restricted to only show same network assets

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#651]
We can't run compute jobs across networks so simplest way to prevent users from running into issues is to limit the assets in `AssetSelection` always to the same network based on `ddo.chainid`

**Comment by bogdanfazakas** [comment]
Would it be a good idea to add this check also to this PR #517 and have them both merged, or better to have two PR's one for the provider match and one for the network?

**Comment by kremalicious** [comment]
good point, that might be overthinking. Cause #517 should result in the same thing, no assets from different networks should be connected with it then as same providers are always on same network. So issue here might become redundant
