### ISSUE TITLE
History page

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#656]
All queries need to change based on `chainIds` user preference so we need e.g. multiple subgraph, node and maybe provider URIs on that page.

The exact place where to get the ocean.js `ConfigHelperConfig[]` values within the app is still pending, see [remarks here](https://github.com/oceanprotocol/market/pull/628#issuecomment-857575391).

**Comment by kremalicious** [comment]
There 2 approaches:

1. simple: do the whole content box based on one network only (the one user is connected in their wallet) and provide some UI hint which network the tables display, and some help text. Can be then combined with #657 to give users way for easy wallet network switching
2. holy grail: just like the rest of the UI, we have one table for each tab which shows assets/pools/pool shares etc. across all networks, with a small UI hint as to which on each item. Filtering networks would then work as across hole app, with the networks switcher in new menubar.

No. 2 requires some architectural work up-front but would be perfect to test the solution. Problem to tackle is that we need to query multiple subgraphs at the same time, but Apollo client only allows one subgraph at a time. A possible solution is hinted at in #658

**Comment by AnaLoznianu** [comment]
@KatunaNorbert, @claudiaHash Please add the wallet network switcher on the history page if it makes sense.
