### ISSUE TITLE
User wallet network switcher

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#657]
We need a component which solves multiple things:

- user needs to be informed when their wallet is connected to another network than the viewed asset so we can assume that component is only ever used as a child of `AssetProvider`
- we need a place to push our custom network configs like for polygon so users can easily switch

For that we can ~~steal~~ get inspired by Zapper:

<img width="399" alt="Screen Shot 2021-06-09 at 12 57 40" src="https://user-images.githubusercontent.com/90316/121342784-480fd400-c922-11eb-880a-ede5c18d9cc3.png">

We will then place this prominently on asset details page, most likely in the right column maybe even above everything else

**Comment by mihaisc** [comment]
This needs to be somewhere near the action. So if you want to buy, it needs to be near buy button, if you want to trade you need to see it there, etc.

**Comment by KatunaNorbert** [comment]
So we shouldn't allow any action until the user changes the wallet network?

**Comment by kremalicious** [comment]
yeah, sounds like it. So whatever we blocked before when user has no wallet connected is now also blocked when user has wallet connected but is not connected to asset network. In `feature/multinetwork` I somewhat prepared this with an `isAssetNetwork` boolean we could maintain in `AssetProvider` so we can get this check from multiple components.

**Comment by KatunaNorbert** [comment]
Alright, I see. Then how about adding the network switcher component over here, instead of the 'No account connected part' ? Not sure how to bring it closer than that to our action buttons
![Screenshot 2021-06-14 at 16 31 09](https://user-images.githubusercontent.com/37236152/121900487-23569a80-cd2e-11eb-928f-c00a2e52b8e3.png)

**Comment by kremalicious** [comment]
yup, putting it down there should be fine. I had moved the Web3Feedback outside of the action box so that would be a good place to have this network switcher under the main content box which always puts it close to the respective actions.

We then have some other screens I can think of:

- edit metadata
- edit compute settings
- edit advanced settings
- publish, this implies some different copy than on asset details page and no check at all, user should be able to switch networks via UI there somehow too
- history, depending on which approach is done in #656
