### ISSUE TITLE
Design/Spec Publish component

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#663]
The publish form(wizzard) will have 3 components 

- component A that will create the asset (nft), resulting an ERC721. The metadata structure will not change from the current one (or have minor changes) 
- component B that will create datatoken, service 
- component C that will create a pricing schema ( free, fixed, pool )

When creating an asset you will no longer need a datatoken like you currently do. An asset can have multiple services and each service has a datatoken.

Component B and C need to be decoupled because they can be used individually. 
You need to be able to create another service for an asset at any time and you need to be able to create another pricing schema for a service at any time.

Example : 
Asset with high quality data
- access service - fixed price 30k ocean 
- compute service with 2 cores maximum of 10 minutes - pool : datatoken/ocean   ~500 ocean
                                                                                          -  pool : datatoken/eth ~too lazy to do the math
                                                                                          -
- compute service with 4 cores maximum of 30 minutes - pool : datatoken/ocean ~1500 ocean
                                                                                          -  pool : datatoken/stable ocean ~too lazy to do the math

What to do in this issue ? 
- design screens for each step in flow
- spec what should happen in each screen

**Comment by w1kke** [comment]
Will it be possible to remove a service later?
Currently a big issue is that datatokens/pools cannot be closed again e.g. for upgrades or for moving them to another chain.

For example the DataUnion pool is bound to the Ocean Protocol Ocean provider and is not a compute-to-data asset as nothing else was available at that time. But now this would be great to be changed.
I know that this might not be possible for existing data assets but it would be great if this would be taken into consideration when creating this new concept.

This will be needed especially to migrate existing pools to this new solution?!

**Comment by mihaisc** [comment]
Good points, will definitely take them in consideration

**Comment by mihaisc** [comment]
We will have only 2 steps in the wizzard 
Step 1 - define metadata related to nft/asset: 

- Stored in metadata contract:

Title
Description
Author
Tags


- Stored in NFT contract:

Name - autogenerated
Symbol - autogenerated  

- Stored in NFT Metadata
Name: autogenerated   ( ideally we add the did here so there is a link to the asset) 
Description : autogenerated
Image - autogenerated (research, maybe related to ocean) 


Step 2 - define metadata related to the service (only one service in the publish form, multiple services can be added after creation, in the asset details page) : 

Files (array )
Sample file 
Access type
Timeout
Datatoken & Symbol  and an option to add a current datatoken address instead of generating a new datatoken

Suggested background flow (work in progress): 
-
