### ISSUE TITLE
Account teaser

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#669]
The account teaser will be a component similar to asset teaser.

It will have: 
- image : default will be the one from the wallet or fetch the one from 3box profile 
![image](https://user-images.githubusercontent.com/26000280/121521692-099b1780-c9fd-11eb-9172-9aedad12da87.png)
- address 
- name if there is one from 3box profile

The teaser will be used on the front page in the best sellers section and in search. Click event will redirect to `/account/0xxxxx`
It is dependent on https://github.com/oceanprotocol/market/issues/668 but can be done before if needed.

![image (2)](https://user-images.githubusercontent.com/26000280/130062012-7f5c62ed-d08f-4a61-91c1-476c1201ba00.png)

We can have two versions of the teaser:
- small : just image, name, address (first image on the first row)
- large : add stats row (first image on second row, this will depend if the performance to fetch the stats is good enough)

**Comment by claudiaHash** [comment]
Blocked until we have the new design for the account teaser, to be provided by @CatalinUXS.
