### ISSUE TITLE
Drag & drop into decentralized storage

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#67]
Goal should be to provide publishers with an easy solution to drag and drop some files during publish flow and in background they are added to a decentralized storage network.

This could start as providing an IPFS upload for sample files, since they can be public.

Storing actual data set files needs some more advanced solution to preserve data privacy.

**Comment by trentmc** [comment]
Closing: redundant with https://github.com/oceanprotocol/multi-repo-issue/issues/6
