### ISSUE TITLE
Show most recent compute job status in asset detail page

### ISSUE THREAD

**Issue by kianyee** [oceanprotocol/market#673]
The message below will be gone when user try to refresh or re-enter the page again after compute job started.
User may tend to forget they have just started the job and they might trigger another job again
![Screenshot 2021-06-11 at 12 03 32 PM](https://user-images.githubusercontent.com/71874741/121629123-23943300-caad-11eb-980f-001578b4c171.png)

 
**Describe the solution you'd like**
Show most recent compute job status in asset detail page

**Comment by KatunaNorbert** [comment]
Should we desplay a list of compute jobs just like inside history page, with all the previous compute jobs on the selected asset?

**Comment by mihaisc** [comment]
Yes, check the pool transaction component in asset details. This should look similar but in the use component of the compute asset
![image](https://user-images.githubusercontent.com/26000280/125459472-499cf3b1-ddb4-4449-b1d4-5afa393717d5.png)
