### ISSUE TITLE
Free pricing editMetaData workaround

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#674]
editMetadata will not work if free price dispenser is created for the data asset

![image](https://user-images.githubusercontent.com/39853992/121661536-e04eba00-cad6-11eb-9809-f4f34930fd1c.png)
Etherscan error: https://rinkeby.etherscan.io/tx/0xd400f16164ba33cf9a6fc3de94b36c337deb2d2d08e36d272841d8e438cb85a5

Workaround solution is to set the minter back to the publisher --> editMetadata() --> set the dispenser back as the minter

1. cancelMinter() - (propose/accept) 
2. editMetadata() 
3. makeMinter() - (propose/accept)

**Comment by mihaisc** [comment]
@alexcos20 can you take a look, it doesn't seem like an ok behavior
