### ISSUE TITLE
Add relevance sort 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#679]
Add back `Relevance` sort when it is fixed in aquarius.
Basically just remove the comments.

https://github.com/oceanprotocol/aquarius/issues/493

**Comment by AnaLoznianu** [comment]
@claudiaHash  The [backend dependency](https://app.zenhub.com/workspace/o/oceanprotocol/aquarius/issues/493) is now fixed. We can continue working on this. Thanks

**Comment by claudiaHash** [comment]
great! thanks, @AnaLoznianu !

**Comment by mihaisc** [comment]
It was closed but that is not in aqua 3.0, so this is still blocked

**Comment by mihaisc** [comment]
Not working in aquarius 3.0.0 , investigating how complicated it would be to migrate to `es-query` endpoint
