### ISSUE TITLE
"Compute Jobs" tab in history page not fetching latest data

### ISSUE THREAD

**Issue by dungeonhao** [oceanprotocol/market#683]
"Compute Jobs" tab in history page not fetching latest data, when switching between tab.

1. Open two browser tab, compute asset & history page.
2. Tab 1: At history page, Go to "Compute Jobs" tab first.
3. Tab 2: Run a compute job 
4. Tab 1: Switch between tab, when switch back to "Compute Jobs" tab, it wont display the latest compute job. 
4. Refresh the browser, then only it will fetch all the compute job (including the latest). 

This might happened because it will only trigger a subgraph query search once on "Compute Jobs" tab. 

Expected Result: 
When switching between tab to "compute jobs" at history page, expect to fetch latest data, instead of refreshing the browser to get the latest data. 

![image](https://user-images.githubusercontent.com/34234250/122022141-e60b0f00-cdf8-11eb-8b7c-e1f0ce79cbfd.png)

**Comment by mihaisc** [comment]
the compute jobs tab has a refresh button for this purpose.

![image](https://user-images.githubusercontent.com/26000280/122181112-bbb96000-ce91-11eb-96af-0e0e0a08848f.png)

**Comment by KatunaNorbert** [comment]
Just tested this and it works for me. After starting a compute job and switching tabs, the compute jobs are refetched and I could se my compute job in the table.

**Comment by dungeonhao** [comment]
Here's what's happening on my side. At about 22seconds into the video is when I refresh my webpage. Then only I could see my compute job in the table. 


https://user-images.githubusercontent.com/34234250/123191096-4a059580-d4d3-11eb-9b18-471b9a470729.mp4

**Comment by jamiehewitt15** [comment]
@dungeonhao I can see from your video that it took a bit of time before it showed up. It seems the issue that it is slow to update rather than it not fetching the latest data. Could this possibly be because the Rinkerby network was running slowly at the time? Have you tried again since with other assets? Also, it might be worth testing it on Ropsten to see if that is quicker

**Comment by dungeonhao** [comment]
@jamiehewitt15, I've tried on Ropsten as well. I actually wait for two and a half min (0.05 -> 2.35), it still wont fetch the data. Not until I refresh the page at about 2.52min. 

https://user-images.githubusercontent.com/34234250/123278168-4e649980-d539-11eb-847b-76d21983011e.mp4

**Comment by dungeonhao** [comment]
https://github.com/oceanprotocol/market/blob/00bce63b8dab776089175c24b88922f6d246e2ca/src/components/pages/History/ComputeJobs/index.tsx#L106-L113

I suspect its because the refresh button only trigger the getJobs() method, but didnt actually trigger the query at line 106.

**Comment by KatunaNorbert** [comment]
You are right, we should refetch the data tokens orders. So it basicaly appears when you run a compute job on a dataset that you haven't already run compute jobs on. That's why we might not catched it.
