### ISSUE TITLE
To show a meaningful UI message for allow/deny list feature

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#685]
Noticed that https://github.com/oceanprotocol/market/pull/655 is already merged into `main` and that allow us to edit the `allow` and `deny` list.

Since we have the [ocean.assets.isConsumable()](https://github.com/oceanprotocol/ocean.js/blob/02693021b1d5195ad4c5e5b0d64210c96fd0be72/src/ocean/Assets.ts#L756) checking on [order()](https://github.com/oceanprotocol/ocean.js/blob/02693021b1d5195ad4c5e5b0d64210c96fd0be72/src/ocean/Assets.ts#L570) for `download`/`compute`, I suggest we should proceed to disable the `buy` button and show a meaningful error message whenever user is in `deny` list or not in `allow` list ([refer test here](https://github.com/oceanprotocol/ocean.js/blob/423ee2f2403b6f8219e7fe1c62e19e8cee1f6f15/test/integration/Marketplaceflow.test.ts#L675-L702)). This is because current implementation would cost user their ocean and tx fee to buy datatoken, only to found out later that they are blocked at `order` when user address is not in allow list / in deny list.

My suggestion for the UI is to show a `private` status tag and hovering it would let user know that their address is either not in allow list or is in deny list.
![image](https://user-images.githubusercontent.com/39853992/122158798-d0045980-ce9f-11eb-98a9-faa0759aa040.png)

@mihaisc @kianyee Lets discuss the following:
1) Is the suggestion above ok or how should the UI message look? 
2) should we do the checking on mount of the component or when user click `buy`? 
3) should we really disable the `buy` button?

**Comment by jamiehewitt15** [comment]
1. The private label looks fine to me.

The message under the button needs to be changed, from:
`"You own 1 SARPLA-65 allowing you to use this data set by spending 1 SARPLA-65, but without paying OCEAN again."`
To:
`"This dataset has been set to private and is unavailable for purchase"`

2. I would suggest doing the check on mount, that way you can convey the "unavailable" message to the user before they decide to purchase the dataset which I think is a slightly better user experience. 

3. I'm tempted to suggest removing the "Buy" button altogether and just leaving the message there saying `"This dataset has been set to private and is unavailable for purchase"`. I think either way can work though. I would say the button definitely shouldn't be enabled.

**Comment by krisliew** [comment]
@mihaisc @kremalicious what do u suggest that would have minimal impact on the complexity/maintainability?

**Comment by mihaisc** [comment]
Agree to hide the buy button (similar to purgatory).

**Comment by kremalicious** [comment]
this whole area would need some redesign as just using that status icon there for states which are simply not the same and have not the same implications will just get more confusing. 

E.g. in this particular state described here the whole messaging below the button becomes irrelevant. If you hide the button here it probably should be hidden in other states too. All in all this needs some step back and somebody looking at all those 4 different use cases and come up with consistent visual patterns for all of them. Until then we are simply hacking it together
