### ISSUE TITLE
Port from old 3box to new IDX

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/market#695]
https://blog.ceramic.network/migrating-from-3box-to-ceramic-and-idx/amp/

"3Box Labs is sunsetting 3Box products in favor of the new and more powerful combination of Ceramic Network and IDX. In this post we provide a timeline and various upgrade paths for projects currently using 3Box"

**Comment by trentmc** [comment]
https://blog.ceramic.network/migrating-from-3box-to-ceramic-and-idx/amp/

3Box Labs is sunsetting 3Box products in favor of the new and more powerful combination of Ceramic Network and IDX. In this post we provide a timeline and various upgrade paths for projects currently using 3Box

**Comment by kremalicious** [comment]
That issue most likely can't be solved right now as that blog post is from February and not much has changed. We should only start working on this once there is an actual public Ceramic mainnet, which at this point in time there is not. Only test network, and a waitlist for mainnet. Until then this all stays in prototype mode so not really worth starting it

**Comment by trentmc** [comment]
I think it's best to wait as long as possible so that the thing can be maximum stable. But not so long that we get deprecated of course :)

**Comment by mihaisc** [comment]
Tested a bit 
- 2 libraries needed (or more, not sure, didn't get stuff working)
![image](https://user-images.githubusercontent.com/26000280/122927651-f00f9f00-d31d-11eb-87ad-4718692c0dc1.png)
- documentation is not good
- getting errors on basic stuff described in examples 
- few issues on the github repo

**Comment by mihaisc** [comment]
To migrate your account you need to go here and follow the steps https://ceramicstudio.github.io/web-playground/ . First try failed for me, will update.

**Comment by mihaisc** [comment]
Currently the main net is still in closed beta and there is no way to update your idx profile. They say they will migrate the current edit tool from 3box to idx. Until that time i don't think we should migrate since at this point we don't plan on creating a profile page in our market.

**Comment by mihaisc** [comment]
Alternatives to this are welcomed

**Comment by trentmc** [comment]
> Alternatives to this are welcomed

Some  related identity plays, with DIDs at the core.
- [BrightID](https://www.brightid.org). We use it for Sybil tolerance in OceanDAO. Gitcoin does too, and many others. Seems pretty mature.
- [WaltID](https://walt.id/). The deltaDAO folks have integrated it in the Minimum Viable Gaia-X fork of Ocean Market, and work closely with them. WaltID received OceanDAO grants on this.
- [SpruceID](https://www.spruceid.com/). Younger team, Berlin based, promising. 

There's also the following:
- [Lens Protocol](https://docs.lens.dev/docs). Recently announced by AAVE after >1 yr of work. NFTs for profiles. Not sure if it has DIDs. Meant as a base layer for creating social networks.

I haven't evaluated any of these for Ocean Market case.

**Comment by kremalicious** [comment]
going more simple with #1396
