### ISSUE TITLE
Add custom provider endpoint during publish

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#702]
The user needs to have the option to set a custom provider url and not use the default OPF one. We can use the docker component (or similar) that we use in algorithm.
When adding a new url we need to validate that with ocean js, something like :
```
 const instance = new Provider()
 await instance.setBaseUrl(config.config.providerUri)  
// this is true or false if provider url is valid , eventualy we can check the version as well, instance.providerVersion
```

![image](https://user-images.githubusercontent.com/26000280/123644363-2b0c4980-d7da-11eb-9851-43403f2ffff9.png)

**Comment by krisliew** [comment]
@jamiehewitt15 Just fyi I noticed that `job.did` value is `undefined` here and the provider will end up calling the default provider. Hence, user will not be able to get the output file/log when different/custom provider is used. Correct me if I am wrong but it should be getting the DID at `job.inputDID[0]` which is the compute asset DID, so in `ocean.compute.status()` will get the correct provider from the ddo, [logic here](https://github.com/oceanprotocol/ocean.js/blob/666da8156fda8a3201b5b4cd600105017f65b275/src/ocean/Compute.ts#L211). 

https://github.com/oceanprotocol/market/blob/c6c502188a4cafab96efc373e6ca794bcc344ed9/src/components/pages/History/ComputeJobs/Results.tsx#L46-L51

**Comment by krisliew** [comment]
@jamiehewitt15 Just fyi I noticed that `job.did` value is `undefined` here and the provider will end up calling the default provider. Hence, user will not be able to get the output file/log when different/custom provider is used. Correct me if I am wrong but it should be getting the DID at `job.inputDID[0]` which is the compute asset DID, so in `ocean.compute.status()` will get the correct provider from the ddo, [logic here](https://github.com/oceanprotocol/ocean.js/blob/666da8156fda8a3201b5b4cd600105017f65b275/src/ocean/Compute.ts#L211).

https://github.com/oceanprotocol/market/blob/675da0836f00b8795629ae86aba5ee5b78ac9157/src/components/pages/History/ComputeJobs/Results.tsx#L46-L51

**Comment by kremalicious** [comment]
I still think this should not be visible by default for majority of our users as almost none of them know what a `provider` in our context is. The proposed UI even assumes that most people won't change this setting, leaving question why it's there at all.

To me everybody who runs their own provider, runs their own marketplace including components. So those users are always free to capture whatever they want during publish. But I don't see a reason why we should show this setting to all our users.

**Comment by jamiehewitt15** [comment]
Yeah that's fair enough, I agree with your point 99% of people will have no-idea what it means. 

In terms of a solution, I can do both, put it in a collapsed advanced settings section and use an env var feature flag so we can easily turn it on or off if we need to.

**Comment by jamiehewitt15** [comment]
If we have it behind an "Advanced Setttings" section then I feel like we don't really need the default/custom box selector any more. We can just have the "Custom Provider URL" input, with a message that says "Leave blank to use the default provider"
