### ISSUE TITLE
Default opf provider expectation text

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#703]
The text resulted in this issue will be added in https://github.com/oceanprotocol/market/issues/702.

> In Ocean Market, if the user chooses to use the OPF-run Provider, have a GUI affordance to set the expectation that this Provider will only be run until some specific cut-off date: Dec 31, 2021. This ensures that OPF is not bound to some weird long-term commitment that it didn't mean to make.

Not sure if we should add an explicit date, just something vague, that it may come a time when that provider is no longer available

**Comment by trentmc** [comment]
> Not sure if we should add an explicit date

Upon reflection: yes I agree

And thinking about it more: I think we can skip doing this, anyone reasonable will understand that OPF won't provide service for all infinity. 

I propose we drop this issue fully.

**Comment by mihaisc** [comment]
Ok ,great
