### ISSUE TITLE
Define user data schema in algorithm/data set publish

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#704]
Epic : https://github.com/oceanprotocol/multi-repo-issue/issues/106
The publisher can define a schema of properties that the consumer will need to input.

```
[
   {
       "name":"surname",
        "type": "text",
        "label": "Name",
        "required": true,
       "description":"Please fill your name"
    },
   {
       "name":"age",
        "type": "number",
        "label": "Age",
        "required": false,
        "description":"Please fill your age"
    },
   {
       "name":"developer",
        "type": "boolean",
        "label": "Developer",
        "required": false,
        "description":"Are you a developer?"
    },
    {
       "name":"interval",
        "type": "select",
        "label": "Date",
        "required": false,
        "options": [
             {
                    "option1" : "Option number 1"
             }, 
             {
                  "option2" : "Option number 2"
             }
        ],
        "description": "Are you a developer?"
    },
]
```
We need a component in the publish/edit form that a adds a list of the previous structure in the DDO, in `services.attributes.userdata`

Design draft: https://www.figma.com/file/jXwZIbb7zUfV2bvlTQkDhi/Data-sets-publish---Draft?node-id=21%3A2

**Comment by alexcos20** [comment]
It's not in additionalInformation.  it is under services.attributes.userdata  (userdata is a new key)

**Comment by AnaLoznianu** [comment]
Backend issues: https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/provider/177, https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/provider/176

**Comment by DimitarSD** [comment]
Quick update on this one: I'm starting to test it. I'll probably need 1-2 days before I'm ready with the issue. I lost some time working on the pragmatic testing issue.

**Comment by kremalicious** [comment]
reopen when we actually have bandwidth to do it
