### ISSUE TITLE
Account page - Account

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#709]
Main page (click to enlarge) :

[![acc1](https://user-images.githubusercontent.com/26000280/124445706-73061000-dd88-11eb-95d2-f26f86647db4.png)](https://user-images.githubusercontent.com/26000280/124445706-73061000-dd88-11eb-95d2-f26f86647db4.png)
Mobile: 
[![image](https://user-images.githubusercontent.com/26000280/124586613-512b8c80-de5f-11eb-8fc2-66dd8001a868.png)](https://user-images.githubusercontent.com/26000280/124586613-512b8c80-de5f-11eb-8fc2-66dd8001a868.png)
All these are on the selected chains (from the header component)
Nr. of published  : query in aquarius based on owner 
Nr. of sold: sum of orders 
TVL in own assets is basically a sum of all the publishers liquidity in pools of assets that he has published

**Comment by kremalicious** [comment]
Design:
https://www.figma.com/file/qJ9LShmjORMMFqIQ1rM2ob/Account

- we make the history page redundant, and transform it into an account page which gets a account metadata header
- account page for every account, so `/account/0xxxx`
