### ISSUE TITLE
Handle publish errors better

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#714]
In the publish form you can get errors like 

![Error - 2021-07-07_13-50](https://user-images.githubusercontent.com/26000280/124750833-9cf93700-df2e-11eb-846f-672b084a6b1b.png)

The suggestion is to have a more user friendly message `Something went wrong . Woops!` and then a button that show the full error `Show full error`

**Comment by jamiehewitt15** [comment]
I got this error while testing the moonbase alpha netwoprk ([slack link](https://oceanprotocol.slack.com/archives/CR8MHU7S8/p1625655119024100)) I'll see if I can reproduce it
