### ISSUE TITLE
publish form: add entry for date created

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#72]
Port over the date picker for allowing publishers to set `dateCreated`. This could follow the pattern we already had where publishers can choose a specific date or a date range for when the data was collected.

When going with date range, the output of `dateCreated` needs to be updated too.

**Comment by KatunaNorbert** [comment]
I'm not sure how this should work with `dateCreated` both as a date and date range. In case of a range shouldn't the `dateCreated` be made of 2 fields?

**Comment by kremalicious** [comment]
we had this already built in a former market version, have a look at https://dexfreight.oceanprotocol.com/publish, that custom form field worked out quite well, so we can just copy its interaction:

<img width="779" alt="Screen Shot 2021-01-25 at 13 15 55" src="https://user-images.githubusercontent.com/90316/105704770-968e7a00-5f0f-11eb-9049-033ed2a0aa8f.png">

<img width="816" alt="Screen Shot 2021-01-25 at 13 15 59" src="https://user-images.githubusercontent.com/90316/105704779-9a220100-5f0f-11eb-992f-211434ffb760.png">

**Comment by kremalicious** [comment]
but you are right, as per the spec `dateCreated` only accepts one date: https://github.com/oceanprotocol/OEPs/tree/master/8/v0.5#main-attributes

Think for the range we used a custom metadata field but we do not need to go that far if we just want to support what's in the spec. Main question is how useful one fixed date is for our use cases

**Comment by KatunaNorbert** [comment]
Than we can implement only the date input for now and leave the date range for later

**Comment by KatunaNorbert** [comment]
As for now the `dateCreated` contains both the date and the time. How relevant is the time here, do we need to let the user specify the time too, or we let him to pick the date only and the time would be the time when he published?

**Comment by kremalicious** [comment]
closing for now, until we have a real user need for it
