### ISSUE TITLE
populate chainIdsSupported from ocean.js

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#723]
To reduce repetition we should populate `chainIdsSupported` within `app.config.js` from the [`configHelperNetworks` in ocean.js](https://github.com/oceanprotocol/ocean.js/blob/main/src/utils/ConfigHelper.ts#L34). This way we do not need to manually update the app config when a new network is added in ocean.js

Another way would be to base the supported chainIds on the response from the new Aquarius endpoints `/chains/list`

**Comment by mihaisc** [comment]
Fetching the list from `/chains/list` might be a nice idea, considering that it's useless if we "support" a chain but aqua is not caching it
