### ISSUE TITLE
Make author field editable

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#724]
Based on deltaDAO research a quick win to move in direction of being GDPR-compatible is to make the author field editable, and possibly optional so it can also be cleared. This might need changes in Aquarius' metadata validation

**Comment by jamiehewitt15** [comment]
The plan is to add the `author` field to editable metadata within Ocean.js

**Comment by kremalicious** [comment]
goals from user perspective in the end:

- publisher can edit existing author as part of _Edit Metadata_ flow
- publisher can add author as part of _Edit Metadata_ flow
- publisher can remove the author as part of _Edit Metadata_ flow
- this all implies author in main publish flows becoming optional
