### ISSUE TITLE
Unable to re-download ordered asset with forever timeout 

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#726]
Step to reproduce: 
1) Create a dataset with access type `Download` , `timeout` Forever
2) Create fixed pricing. 
3) Go through full process of buy  --> download
3) Refresh Page
4) User need to buy the asset again. 

Possible issue: https://github.com/oceanprotocol/market/blob/b9bd6a3a25f027ea73661cc17f48c7d16f358a28/src/components/organisms/AssetActions/Consume.tsx#L78

Possible Solution:   `if (assetTimeout === 'Forever' || assetTimeout === '0')`

**Comment by jamiehewitt15** [comment]
Yeah, I see what you mean. This is something that needs to be fixed
