### ISSUE TITLE
datasets algorithm is allowed to run on returns nothing

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#730]
On any algorithm asset like https://market.oceanprotocol.com/asset/did:op:D92D92705b5CEe6DA62097476a830082D2FD5Eda the list of datasets it is allowed to run on is always empty. Yet this algo is allowed to run on this asset and shows up there https://market.oceanprotocol.com/asset/did:op:196cc23a2e3D7c3469662d1802ca9f497e36c845

**Comment by mihaisc** [comment]
The assets are on polygon
