### ISSUE TITLE
Publishing Compute Asset with "Forever" `timeout` value will be = 3600 instead of "Forever" or "0"

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#733]
Since timeout = 0 is passed in at here: 

https://github.com/oceanprotocol/market/blob/bea4f46c9ae65b0049d1d077c0343b04a12d4579/src/hooks/usePublish.ts#L86

https://github.com/oceanprotocol/market/blob/bea4f46c9ae65b0049d1d077c0343b04a12d4579/src/components/pages/Publish/index.tsx#L127

https://github.com/oceanprotocol/market/blob/bea4f46c9ae65b0049d1d077c0343b04a12d4579/src/utils/metadata.ts#L20-L23

Forever timeout will always be `3600` after publishing DDO.

Steps to reproduce:
1) Publish a compute dataset with timeout `forever`
2) Check published ddo `timeout` value

**Comment by jamiehewitt15** [comment]
I see what you mean, the timeout is automatically set to 3600 if you select "forever"
![timeout 3600 - 2021-07-14_12-12](https://user-images.githubusercontent.com/20739535/125596832-ae917896-da65-43da-871f-3f0729520f90.png)


@kremalicious I think you worked on this, what was the reasoning behind setting the timeout to 3600?

**Comment by AnaLoznianu** [comment]
We should remove the 'forever' timeout option for compute services.

**Comment by AnaLoznianu** [comment]
Linked issue: https://app.zenhub.com/workspaces/frontend-60acd67b133a660014278212/issues/oceanprotocol/ocean.js/918
