### ISSUE TITLE
"License" needs a commercial option as default

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#74]
Ocean marketplaces, including Ocean Market, are meant for data that's for sale. 

In Ocean Market, there's a dropdown for "License". Currently all the options are for free / open data. But this is a marketplace for commercial data. Therefore we need an appropriate license. And, it should be the default.

We should be able to take the terms developed for ascribe, and use them here.

I also question whether we want to offer any of the free / open licenses (Creative Commons). They're for open documents. Historically we had Ocean Commons, which was for open data, but it was really a demonstrator, with no real USP. If people want free / open data then they can simply use Web protocols directly, no need for extra Ocean machinery in between.

**Comment by sheriff4** [comment]
This is the updated T&C version, incorporating Ocean, Buyer and Seller: https://docs.google.com/document/u/2/d/1klOCu7uDBkWp_xcsHg3zP89LXd5JhD5TPTNszNmtDPo/edit?usp=drivesdk
