### ISSUE TITLE
statistics footer

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#741]
Add simple changes to `MarketStats` component getting it into a launchable state so we do not have to start crazy refactoring or new screens, like:

- add multiple lines, one for each selected network
- add TVL/pools/OCEAN of all selected networks together and display as one
- base it only on user network (current behavior but feels unintuitive right away)
- more ideas?

Not super pretty but simple and provides good user value until this gets all moved to a new `/pools` page:

<img width="751" alt="Screen Shot 2021-07-16 at 15 08 53" src="https://user-images.githubusercontent.com/90316/125952931-40db98cc-718a-4efc-9663-0b0bca6e7c7f.png">

**Comment by mihaisc** [comment]
Have a total for supported main chains. Optional : have the same info for each chain either in the tooltip (not sure how good the tooltip will look with multiple lines)  or have them cascading on a button click or something.

**Comment by KatunaNorbert** [comment]
Do you mean to omit the test chains and only add together the main ones?

**Comment by kremalicious** [comment]
I like the consolidated + split-up in tooltip and would agree to only show mainnets as only there the monetary value is actually true. To keep it simple we could default to all known mainnets and not base this on the network selection
