### ISSUE TITLE
Trying to get Atomic Wallet to connect, app just spins, two different browsers show two diff errors

### ISSUE THREAD

**Issue by gbolcer** [oceanprotocol/market#748]
**Describe the bug**
Wallet doesn't connnect after scanning QR code

**To Reproduce**
Go to market.oceanprotocol.com with either Chrome (Version 91.0.4472.164) (Official Build) (64-bit) or Firefox (89.0.2) (64-bit).  
Click on Connect Wallet
Click on Wallet Connect
Scan QR code with iphone (12 ios 14.7)

**Expected behavior**
market.oceanprotocol.com refreshes to connected wallet.  iphone App shows connection. 

**Screenshots**
![ocean-errors2](https://user-images.githubusercontent.com/19297096/126417064-96dae50f-ccd3-471b-b5ac-677732f3f068.png)
![ocean-errors](https://user-images.githubusercontent.com/19297096/126417066-68f8df35-fa65-48e9-9c3e-3e5eaf1e8c48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 x64
 - Browser:  Chrome (Version 91.0.4472.164) (Official Build) (64-bit) or Firefox (89.0.2) (64-bit)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: 14.7
 - Browser: N/A  Atomic Wallet (latest update)

**Additional context**
Trying to connect wallet and publish some files.

**Comment by kremalicious** [comment]
thanks for the report. Not entirely sure what's going on for you, while we know about ongoing issues with WalletConnect (#592) your reported issue seems new.

The error messages suggest there was an issue with `portis.io` which seemed to make the whole wallet connection fail. This I was not able to reproduce and I can successfully connect multiple mobile wallets like Rainbow or Trust Wallet via WalletConnect with market. 

But when trying Atomic Wallet something is indeed different where WalletConnect expects an ETH address but Atomic Wallet exposes a BNB address for whatever reason which seem to make the connection fail in the end. This is on Firefox, and with a freshly installed Atomic Wallet on iPhone, and the market in incognito window:

<img width="1086" alt="Screen Shot 2021-07-21 at 14 35 07" src="https://user-images.githubusercontent.com/90316/126489181-7430b87c-f5f2-4153-a120-cfaeb5f3c3f2.png">

This would be something out of our hands as we neither control WalletConnect, nor Web3Modal which we use for wallet connection. The issue I'm running into can be reproduced when using Atomic Wallet on https://web3modal.com so this would be an issue for https://github.com/Web3Modal/web3modal/issues

As for your other errors could you try again to be sure it wasn't some portis problem? And maybe try in incognito window to be sure no plugins or anything in your browser's cache is influencing this

**Comment by kremalicious** [comment]
Tested a bit in #749 to get our related dependencies in same state as on https://example.walletconnect.org but it does not solve the specific Atomic Wallet issue as then web3modal expects an ETH address to initiate Web3, but only gets a BNB address from Atomic Wallet and there seems to be no way in Atomic Wallet to define which address gets exposed. So this would be then on Atomic Wallet's plate, which is why I would love to see a Dapp example where Atomic Wallet + WalletConnect actually works

**Comment by gbolcer** [comment]
Thanks, the demo page shows the QR code and then just stops.  The Wallet app on the phone just hangs showing the ocean market logo and a never ending spinning loading message.  I don't have an exact dapp link, but I did transfer most of my Robinhood holdings, so it's definitely active.
