### ISSUE TITLE
Submit button not working on publish form

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#766]
**Describe the bug**
The submit button remains disabled despite filling in the whole publish form. 

**To Reproduce**
1. Go to 'https://market.oceanprotocol.com/publish'
2. Fill in the publish form
3. You'll see that it's not possible to submit the form

**Expected behaviour**
Submit button should be enabled

**Screenshots**

![submit button disabled](https://user-images.githubusercontent.com/20739535/127641606-424361c0-fc3f-48dc-b8e8-4e7cbc9ee499.png)

**Comment by kremalicious** [comment]
/blame me :slightly_smiling_face: 

can confirm and can reproduce locally. The `!ocean` in this line is the problem:
https://github.com/oceanprotocol/market/blob/main/src/components/pages/Publish/FormActions.tsx#L20

Remnant of old way of connecting, now we are not "connecting to ocean" anymore by default but only after publish button is clicked. Will prepare fix PR
