### ISSUE TITLE
Datatoken name refresh button not working

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#767]
**Describe the bug**
The refresh button for the token name also doesn't seem to be working when filling out the publish form.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://market.oceanprotocol.com/publish
2. Fill out the form
3. Click on the refresh button to change the name of the token
4. You'll see that nothing happens and the name isn't changed.

**Expected behavior**
The datatoken name should change when the refresh button is clicked.

**Screenshots**
![token name refresh](https://user-images.githubusercontent.com/20739535/127643005-59e8a21d-80cf-4cac-b969-4f5aa565de6a.png)

**Comment by kremalicious** [comment]
also missed this when moving away from always connected `ocean`. Cause we use a helper method from ocean.js but it's only exposed behind the monolithic `ocean` object: `ocean.datatokens.generateDtName()`

So this whole part needs to be refactored:
https://github.com/oceanprotocol/market/blob/main/src/components/molecules/FormFields/Datatoken/index.tsx#L10-L23

Still investigating but looks like we need to figure out to either:
- get `generateDtName()` directly out of ocean.js somehow
- create `ocean` connection on the fly when datatoken form field is rendered but this won't work without wallet as ocean requires web3

**Comment by kremalicious** [comment]
ok, isolating `generateDtName()` seemed most feasible https://github.com/oceanprotocol/ocean.js/pull/943
