### ISSUE TITLE
Search gives unexpected result for data token symbol

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#769]
Try the following:

1. Take any known data set's symbol, e.g. RUMNAR-48, and type it into the search of market.oceanprotocol.com.
2. The result will surprise you; mainly because in this specific case RUMNAR-48 is not presented as a confident first result

See screenshot:

<img width="1153" alt="Screen Shot 2021-08-02 at 15 28 27" src="https://user-images.githubusercontent.com/2758453/127869457-d9d3fe20-257f-415a-a93c-8efcc5a7a11f.png">

It'd in the search results - but what'd be less confusing or more pleasing to the users is showing it as result number 1 and potentially also removing the other false-positive results.

**Comment by kremalicious** [comment]
we have a greatly enhanced search query in #755 but can confirm that your exact example behaves the same there. Fun thing is that for any other picked symbol I really get only 1 result over there but not for `RUMNAR-48`

This specific issue might be also solved in combination with #699 where then I would expect based on relevancy to at least get `RUMNAR-48` as first result

**Comment by jamiehewitt15** [comment]
This happens because elastic search removes the hyphen when it analyses the text. I think getting `RUMNAR-48` as the first result should be a satisfactory result, I don't think we necessarily need to remove all the other results. 

If this doesn't get solved in #699, I'm happy to work on another search PR to address this

**Comment by alexcos20** [comment]
@TimDaub - can you check again ?

**Comment by TimDaub** [comment]
![Screenshot_20211005-122140](https://user-images.githubusercontent.com/2758453/136005534-59bc905e-f182-45e5-bb97-4e85fa017cbf.jpg)

The screenshot shows that RUMNAR-48 comes first. Anyways IMO when a symbol is searched, I think RUMNAR-48 should be specificallly highlighted to signal the user that indeed the token symbol that hey're looking for exists.

FYI: There are now 8 false positives instead of 3. So maybe this fix was a regression?

**Comment by kremalicious** [comment]
searching for any datatoken symbol always presents this as the first result so not sure what exactly the issue here is anymore. So closing
