### ISSUE TITLE
Web3Feedback UI message

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#777]
when `isGraphSynced` and `isBalanceSufficient` is equal to `false` in the code fragment below,

https://github.com/oceanprotocol/market/blob/af3bb86073a8522886341413da93532ae93a649b/src/components/molecules/Web3Feedback.tsx#L36-L55

This will appear which can be confusing to user, 

![image](https://user-images.githubusercontent.com/39853992/128663769-0e5c0a09-4731-4a20-9a91-67cafb9797ac.png)

### Suggesting solution:
Sync up both const variable `title` and `message` to check for `isGraphSynced` first before `isBalanceSufficient`.
So it show something like this instead, 

![image](https://user-images.githubusercontent.com/39853992/128664375-609d7ac7-4857-4c91-9b03-3deb76c67093.png)
^ Think above message have room to improve as well to be dynamic based on connected network instead of "Ethereum"?

**Comment by kremalicious** [comment]
we should look into the `Web3Feedback.tsx` component a bit more on top of reported issue, like:

- look into splitting out some messages like the `isBalanceSufficient` case, as that is only needed on _Use_ tab but we display it in context of all tabs
- ...
