### ISSUE TITLE
Search by publisher is not working

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/market#778]
**Describe the bug**
Starting from https://market.oceanprotocol.com/asset/did:op:E83A9C174Dedbe5FA753A9d54E36D2551dE365fE, I want to search for assets published by this publisher.

But I get an empty result: [https://market.oceanprotocol.com/search/?owner=0xAcca11dbeD4F863Bb3bC2336D3CE5BAC52aa1f83&sort=created&sortOrder=desc](url)
![Published by 0xAcca…1f83 — Ocean Market - Google Chrome 8_9_2021 10_44_59 AM](https://user-images.githubusercontent.com/7489447/128674161-41b95bde-c1cf-4cc9-a75c-e5b4f8d4ba71.png)

**Expected behavior**
I should see all assets published by 0xAcca11dbeD4F863Bb3bC2336D3CE5BAC52aa1f83

**Comment by alexcos20** [comment]
I only had Mumbai testnet selected.  When I select more networks, I can see assets, but from other publishers 

![Published by 0xAcca…1f83 — Ocean Market - Google Chrome 8_9_2021 10_49_53 AM](https://user-images.githubusercontent.com/7489447/128674502-0b9b8053-9397-4e3f-af1e-a889ab9b4f8b.png)

**Comment by jamiehewitt15** [comment]
I just did some testing on this, it seems to work fine if you directly search for the user's address. Which will take you to this URL:

https://market.oceanprotocol.com/search?sort=created&sortOrder=desc&text=0xAcca11dbeD4F863Bb3bC2336D3CE5BAC52aa1f83

However, if you click on the owner's address from the asset detail page it takes you to a different URL which is showing additional results from different publishers: 
https://market.oceanprotocol.com/search/?owner=0xAcca11dbeD4F863Bb3bC2336D3CE5BAC52aa1f83&sort=created&sortOrder=desc
