### ISSUE TITLE
OR || operator won't work in the case statement 

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#779]
### Steps to reproduce bug:
1) Have 1 Ocean balance in wallet
2) Visit an asset page that is price exactly at 1 Ocean
3) You will see insufficient balance msg

### Root cause: OR || operator won't work in the case statement 

https://github.com/oceanprotocol/market/blob/cf44ab7f51e7dbfdb4c437ae589bcd649975e042/src/utils/compareAsBN.ts#L8-L14

### Solution: 
``` 
 switch (compare) { 
   case 1: // balance is greater than price
   case 0: // balance is equal to price
     return true 
   default: 
     return false 
```

**Comment by AnaLoznianu** [comment]
Hi Kris, it looks like you have the solution here also. Can you please open a PR with it?

**Comment by krisliew** [comment]
Sure! I have created and linked the PR here.

**Comment by jamiehewitt15** [comment]
Thanks for spotting this @krisliew
