### ISSUE TITLE
Improve hint about why Publish Submit is disabled when Wallet is not activated 

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#8]
As stated in [this comment](https://github.com/oceanprotocol/daimler/pull/110#issuecomment-611470504) from @maxieprotocol :

Visually, there is no clear correlation b/w form submit and activate wallet section.

Perhaps we shouldn't keep it disabled but rather provide feedback to the user that he must activate the wallet in order to submit the form the same way as we do  with the rest of mandatory fields by
implementing the snack bar warning for wallet activation (that would be the faster solution to fix that)
Later the wallet activation would be a part of the wizard step

![image](https://user-images.githubusercontent.com/58465759/78888871-d2c91a80-7a62-11ea-89ca-15c9f9146130.png) 

Not sure if this is an issue anymore, but we need to take this in consideration in the new design for the market

**Comment by trentmc** [comment]
Is this still an issue?

**Comment by mihaisc** [comment]
The preview is sticky and you get the `No account connected` message pretty close
