### ISSUE TITLE
Issues with Polygon Mumbai and Moonbeam Alpha

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#808]
For some reason if you select only Polygon Mumbai and/or Moonbeam Alpha the query string is formatted weird and aqua returns 500
`{query: "() AND (chainId:80001) AND -isInPurgatory:true", fields: ["dataToken"]}`

working query
`{query_string: {query: "(chainId:4 OR chainId:3 OR chainId:80001) AND -isInPurgatory:true "}}`

We should move to boolean queries here as well, we should unify the query creation mechanism so it's just one point of failure.

**Comment by alexcos20** [comment]
this should be moved to aquarius..
