### ISSUE TITLE
make accountId always part of URL

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#810]
One goal would be to always provide a linkable URL to any user when they arrive on the profile page. This is pretty much always done when we link to a specific profile page from within app, but when wallet-connected user clicks on _Profile_ that easy link sharing functionality is currently gone.

### Proposal

Make sure the user `accountId` is always part of the profile URL. Could be done in multiple ways like:

- append `accountId` to the actual menu link, so the profile page always gets its account from there
- append `accountId` to URL after user arrives there

**Comment by mihaisc** [comment]
Should we show the `my account` link when there is no wallet connected? If we do, what would it's behavior be?

I think the first options is easier and less error prone.

**Comment by kremalicious** [comment]
I think depends on how good we are in making account page useful without wallet. So far we do not hide pages but always have fallbacks within them so users can still get the idea of the app screens. 

From #776:

> Ideal case would be to resemble the final layout with received data as much as possible when no data is present at all but also uninspired what those fallback values should be. Stats numbers could simply use 0 as fallback and right away we would have some layout up there

> Another way would be to hide everything on this page without wallet, and instead show some kind of account explore thing listing multiple account teasers users can explore.

**Comment by kremalicious** [comment]
yeah nope, we have to ditch that. After tinkering around in #776 we need a separation between a page which always renders other accounts, and one which reacts to web3 account changes. Trying to have those 2 use cases together quickly ends up in usability nightmare, like logged in user watches other profile, then switches wallet account, and we would need to switch from other profile to user account profile? Feels weird. So best strategy seems to be keeping the blank `/profile` route to be the one reacting to web3 account changes, and the routes with accountId at end of path for always rendering other profiles

**Comment by mihaisc** [comment]
Good point. Maybe on the profile page we add a button with `Share profile` and we copy to clipboard the full url
