### ISSUE TITLE
Allow referrer tracking as external project and publish data to party that has been referring

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#811]
oceanDAO is requesting proposers to commit to a metric as outlined here: https://github.com/oceanprotocol/oceandao/wiki/On-ROI#whats-a-good-metric-for-bang (e.g. see "Network revenue").

Over the course of the oceanDAO, however, there are barely any projects that can practically work with these metrics. Most ROI calculations are just invented out of thin air by their authors.

However, it's likely that many projects funded by the oceanDAO have already had an impact on the outlined ROI metrics - but nothing is tracked.

Generally, the marketplace and any other infrastructure that can potentially lead to sales is out of the reach for control for most oceanDAO projects.

For e.g. rugpullindex.com, we've tracked our web analytics since the project's beginning: https://plausible.io/rugpullindex.com, and we've also started to collect outbound link clicks as conversions.

But, as soon as the users leave our site, we cannot see whether they spend money on the marketplace. Or e.g. whether they have money.

So there are a number of options:

- (1) we introduce a buy button on our site that directly communicates with the smart contract
- (2) we collaborate with the ocean marketplace team so that maybe we can add a buy button that leads to a dedicated "checkout" page on their website
- (3) We add a "referrer" query string to any outbound ocean marketplace link click, let OP marketplace run the analytics and have report back to us.

In any case though, we should - in a rather short time frame - start to understand if for external contributors like the RPI outbound clicks are revenue generating events and e.g. to what percentage or value.

**Comment by mihaisc** [comment]
Thank you for the suggestion but we will not go into this direction in the foreseeable future. For now, chain data should be the metric (sales, fees, etc.)
