### ISSUE TITLE
Creating a free price sometimes fails

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#826]
While having only free price enabled in config (or env) creating the price sometimes throws some errors in the UI, not sure exactly what the issue is, needs some debugging.

**Comment by krisliew** [comment]
@mihaisc is there any precise step or more information to reproduce the error? I can't seems to get that. 

If it were to throw some errors in the UI on create free pricing, my guess is gonna be from here...
https://github.com/oceanprotocol/market/blob/b5afccbb49028098096fea38a7985768e0e23317/src/hooks/usePricing.ts#L252-L291

**Comment by kremalicious** [comment]
closing as v4 publish is completely different
