### ISSUE TITLE
`checkMaxAvaialableTokens` fails when on other network

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#830]
We need to fetch [this](https://github.com/oceanprotocol/market/blob/b717219592addd15932b8d06acfd7b48a2312814/src/components/organisms/AssetActions/Consume.tsx#L75) from the subgraph, not from ocean. When on another network you get the following error. : 
![image](https://user-images.githubusercontent.com/26000280/131685002-e3d830bd-f056-42ca-bdc1-bf1fbc8e314f.png)

**Comment by kremalicious** [comment]
yes, encountered this over on token approval and fix is quite simple: https://github.com/oceanprotocol/market/pull/640/files#diff-9fb8c5a7542a8d3c882809335fc24d421a8ba66fe7c200bed9d55511be875d51R74-R76

**Comment by mihaisc** [comment]
hmm, i guess it's good enough.
