### ISSUE TITLE
Error when switching network to a network that is not added in Metamask as custom RPC

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#832]
### Steps to reproduce:
1) Make sure metamask is connected to Ethereum Mainnet
2) Delete BSC Mainnet from your metamask RPC if you have that custom RPC.
3) Go to an asset page that is published on BSC Mainnet (https://market.oceanprotocol.com/asset/did:op:2a82D20D65565Be093576Ed9000c4b853D005be3)
4) Click `Switch Network` 
5) Error:
![image](https://user-images.githubusercontent.com/39853992/131794975-e96f3bd3-823a-4b2b-945a-03fd644476db.png)

### Expected behaviour:
Not sure why but code should have added the custom RPC as `wallet_addEthereumChain` below
https://github.com/oceanprotocol/market/blob/4123dae431f67548741b7062ab0bae6fb31d5c2c/src/utils/web3.ts#L99-L141

### Possible cause: 
Correct me if I am wrong but I think is likely the RPC endpoint is not responding to RPC calls of `eth_chainId`?  
See https://docs.metamask.io/guide/rpc-api.html#description-6 for more information.

**Comment by mihaisc** [comment]
Good find, looks like we set a wrong rpc node, we'll investigate.
