### ISSUE TITLE
TVL value is incomplete

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#839]
Checking out [this profile](https://market-git-feature-accountpage-oceanprotocol.vercel.app/profile/0xbbd33AFa85539fa65cc08A2e61a001876D2f13FE) and if you switch to Pool Shares with multiple networks selected in network selector, you will see that numbers don't add up and the TVL display in account header is only accounting for ETH Mainnet in this case:

<img width="1143" alt="Screen Shot 2021-09-06 at 12 38 40" src="https://user-images.githubusercontent.com/90316/132204811-da69e6a6-cf35-4ddc-b2ff-0b5e15e98e19.png">

Expectation is that selecting/deselecting networks also recalculates TVL number. As far as I can see the effects are setup to refetch on `chainIds` changes but seems `getAccountLiquidityInOwnAssets()` helper has a bug

**Comment by bogdanfazakas** [comment]
not sure if this is really a bug, it works as it was described in the original issue #709  (TVL in own assets is basically a sum of all the publishers liquidity in pools of assets that he has published), in the example above the user published only the first asset

**Comment by mihaisc** [comment]
I think that should be liquidity (not tvl), total liquidity the publisher has in its own assets.

**Comment by kremalicious** [comment]
You're right, had the wrong expectation and we would have to rename the value in UI.

But it would be more useful to switch to showing "value this account has put into market" as this then also shows numbers for accounts who are not publishers so usefulness of stats is opened up for bigger set of users

**Comment by mihaisc** [comment]
hmm, yes and no. The purpose of that value is to highlight how much liquidity that user has in its own assets. The higher the value the more "serious" the vendor is. We could add another value that is more generic as you suggest, as long as we don't have too many numbers.
