### ISSUE TITLE
Title out of bounds on asset teaser

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#843]
![image](https://user-images.githubusercontent.com/26000280/132355913-29b2dbf7-7149-4c2b-9291-a1a742d11224.png)
I think the image says it all

**Comment by kremalicious** [comment]
we already try to account for situations like that with:
https://github.com/oceanprotocol/market/blob/main/src/components/molecules/AssetTeaser.module.css#L23-L25

But that's only for the description and it actually produces bad side effects as it breaks in middle of proper words as seen in above screenshot which is just weird. So applying the same `break-word` stuff to the `.title` would make proper titles break in weird places too. This is `word-break: break-all;` causing this.

I think correct way here would be to use only `overflow-wrap: break-word;` and nothing else. Putting the same on the `.title` should in end fix the reported issue. And while we tweak micro-typography, add `hyphens: auto;` into the mix for even nicer text break flow but probably only on `.content`

This was a great resource:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text
