### ISSUE TITLE
explorer link on asset page is leading to a 404

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#844]
<img width="283" alt="Screen Shot 2021-09-07 at 22 00 39" src="https://user-images.githubusercontent.com/2758453/132403742-5ef05ba3-8d38-451c-83cd-499e9708f2c1.png">

https://market.oceanprotocol.com/asset/did:op:5eF1e1D65e058A343e0106065cc3926cf416A1F4

links to: https://market.oceanprotocol.com/asset/undefined/address/0x304fFD0750Fa2D642fd87480D0A1e632DA8bE593 while it probably should lead to etherscan

**Comment by kremalicious** [comment]
nice, this always comes back as it seems: #759

As account profiles were heavily refactored in #774, this issue does not exist there anymore so will definitely be fixed once shipped.
