### ISSUE TITLE
Figure out something better for asset filters

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#855]
For the published list I have commented out the access type filters at the top as current implementation combined with latest filter changes in `main` was just getting too complex and required another refactor to accommodate for both very different use cases.

Goal would be to pick up on this comment:
https://github.com/oceanprotocol/market/pull/774/files#diff-2fd7fca45bccc84bae93cf604acfb3ee47fa57584a37e7c19b3a543869fcdc13R185-R189

Then make the `assets` in the `ProfileProvider` the ones with prices so that in end we populate the whole published list from there and as a bonus we will be able to add filter buttons which on click filter through this data instead of hitting Aquarius again. Another bonus point will be that switching tabs will preserve the published list.

Goal still would be to get the published list rendered as quickly as possible. We get the assets from Aquarius pretty quickly, but then transform this data by hitting subgraph and adding the price. Then we render. Better approach would be to render the asset teasers right after we have DDO list from Aquarius, and only inject the price later or change from initial 0 when we have it

**Comment by mihaisc** [comment]
The best solution here (that will be very useful in v4) is to completely decouple the rendering component from the data (the same thing needs to be done to the asset teaser  ).  We create a model for each item in this component. So the component will have the folowing params  : List of defined model (just one page)  , list of filters to be displayed,  event to handle pagination+ filtering +sorting (maybe a quick search if we want to go crazy) , currentPage, totalPages. The parent component handles the fetching of data, transforming it, filtering and searching.  This way you cand have the search  done on aqua, you can also have the search done in js with filter. 
In this refactor we can also implement the 2 display views that were planed but never implemented : grid , table. 
As a bonus we could also use this for pools but not sure about this tough, we might have different specs for this.

**Comment by mihaisc** [comment]
will be handled here https://github.com/oceanprotocol/market/issues/879
