### ISSUE TITLE
Data tables have too many scrollbars

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#856]
As [described here](https://github.com/oceanprotocol/market/pull/774#issuecomment-918867006) we get scrollbars way too often in our table components. They are supposed to scroll like that when viewport or container does not have enough space for its content, the overflow pattern. This is happening in multiple places throughout app so not just applies to account profiles changes.

1. In linked case we have enough space so there should be no scrollbar. Looks like we need to explore some of the underlying component's options, or our own css styles for it.
2. When there is a scrollbar it should not be so obvious although this highly depends on browser/OS/input used. So we should explore styling the scrollbars within data tables slightly, e.g. making the track & thumb into colors based on our color scheme and minimizing its height

**Comment by KatunaNorbert** [comment]
Does this appear only on specific browsers? I tried to reproduce it on Chrome but the scroll bar seems fin

**Comment by mihaisc** [comment]
Can confirm it in chrome and edge on windows 10

**Comment by kremalicious** [comment]
Just some tinkering thoughts, but it could be caused by us setting kinda fixed padding on the table cells. Because while `rem` is a relative unit it's only relative to root font size. We might have more luck with using % units for the cell padding
