### ISSUE TITLE
profile metric: sales revenue

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#871]
moved over from [#864](https://github.com/oceanprotocol/market/pull/864#issuecomment-925758718):

An interesting metric would be sale revenue, meaning the amount generated by all the sales of an account, converted to fiat which then would be nice meaningful metric to only show on account teaser, and in profile header. We should first investigate and discuss on this issue if that's even possible right now.

**Comment by mihaisc** [comment]
We know how many orders there were, but we don't know the price of that dt at that point. We have 2 options: 
- add in subgraph spot price at the time of the order (not 100% sure if possible, but i'm confident)
- calculate with the current spot price 

Both cases are relevant .

**Comment by mihaisc** [comment]
This can be done now using [this query](https://v4.subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0Aorders%7B%0AlastPriceToken%0AlastPriceValue%7D%0A%7D%0A) , we need to change `lastPriceToken` from string to Token

**Comment by mihaisc** [comment]
Blocked by https://github.com/oceanprotocol/ocean-subgraph/issues/447

**Comment by jamiehewitt15** [comment]
> all the sales of an account, converted to fiat 

Do you mean all of the sales on the current connected network or all of the sales on all networks combined?

**Comment by jamiehewitt15** [comment]
Just checking that I've understood this task correctly... There is already a sales revenue metric on the profile page, so the idea is just to fetch this figure from the subgraph rather than changing the UI?

**Comment by AnaLoznianu** [comment]
Blocked for now by having the pricing information.
If an asset has 100 orders, we need to fetch the pricing of ocean at each order time to better determine the sales revenue.

**Comment by jamiehewitt15** [comment]
The plan is not do do this anytime soon https://github.com/oceanprotocol/market/pull/1807#issuecomment-1386863729, we can reopen if that changes.
