### ISSUE TITLE
No published assets on profile page

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#877]
Getting _No results found_ on every profile, e.g. https://market.oceanprotocol.com/profile/dataunion.eth. Seems something with #867 wasn't right

<img width="577" alt="Screen Shot 2021-09-27 at 10 59 03" src="https://user-images.githubusercontent.com/90316/134877385-78e3f4a1-0b0b-4fd7-9f5f-e92d9accc6a2.png">

**Comment by bogdanfazakas** [comment]
seems that aqua is returning strange results, for eg you get assets on this profile on rinkeby network https://market.oceanprotocol.com/profile/0x968d4670c346275edd5CC1A7535D14b631FFc49C but only the filtering by asset type algorithm works on rinkeby but works well on ropsten

**Comment by bogdanfazakas** [comment]
something similar happens also on the search
