### ISSUE TITLE
Can't buy dataset

### ISSUE THREAD

**Issue by aman-rac** [oceanprotocol/market#885]
Hi, I can't buy the dataset on rinkeby. I am using metamask on https://market.oceanprotocol.com/. I have rinkeby oceans and eth and my accounts are connected to the market dapp. I can stake in the same asset. Pre-thanks for the response guys, great platform.
<img width="613" alt="Screenshot 2021-09-28 at 3 50 07 AM" src="https://user-images.githubusercontent.com/73213717/134993558-f8535cdb-6f45-48b0-872b-394a34c15426.png">

**Comment by kremalicious** [comment]
Which dataset are you referring to?

**Comment by aman-rac** [comment]
@kremalicious  I can't buy any dataset, either mine or someone else's. Browser console error when I connect metamask ->` No config found for given network 'undefined'`. Browser -> Chrome.

**Comment by bogdanfazakas** [comment]
I belive this is the dataset https://market.oceanprotocol.com/asset/did:op:7FBEDfF92F39ae900393B17370E192D508458FDB based on the datatoken name, the issue appeared after we removed one param from a condition https://github.com/oceanprotocol/market/commit/fdac6d8039c9a6188a2ebd5bcd2bd010cae31734#diff-9fb8c5a7542a8d3c882809335fc24d421a8ba66fe7c200bed9d55511be875d51L137 , I'll create a PR for it now

**Comment by aman-rac** [comment]
@bogdanfazakas , thanks. I believe it's a majority of datasets if not all. I can't buy this one also, which I created https://market.oceanprotocol.com/asset/did:op:D917a3B12102f1E4036D8013Cc083e78DB24De99
