### ISSUE TITLE
 Issue: "FRE" hard to understand. Proposal: Rename "fre" as "fixed"

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/market#888]
This is a follow-on from https://github.com/oceanprotocol/docs/issues/717. This issue is that FRE is hard to understand and easily confused with FREE. 

My suggestion here is simply to rename "FRE" to "fixed" in the places where it occurs in our code.

**Comment by kremalicious** [comment]
There is not a single place where we do this. The only place we have this is based on the subgraph typings which we do jot control here https://github.com/oceanprotocol/market/search?q=fre

**Comment by mihaisc** [comment]
will rename in future versions o subgraph to FixedRate  or something similar
