### ISSUE TITLE
Download/compute does not honor infinite approval

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#892]
We use `ocean.pool.buyDt()` and that will always do a specific amount approval leading to the infinite amount user preference introduced with #640 being ignored. 

Example use case when infinite approval is activated:

1. user buys download asset which has a timeout set
2. approves OCEAN once
3. user buys same asset again after expired timeout, and then does NOT have to approve OCEAN again

Most likely needs some changes in ocean.js and over here in market we need to apply same logic as we use for Pool & Trade.

**Comment by mihaisc** [comment]
Does it make sense to do this? Didn't we say we are freezing the market? Why focus on current version of ocean.js and not the next one? And yes this feature should exist in v4

**Comment by mihaisc** [comment]
Is this still an issue? From my memory this works ok. Plus we don't have pools anymore sooo...
