### ISSUE TITLE
Refresh user liquidity after removing liquidity

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#894]
After you remove liquidity you need to do a page refresh so the data in `Your liquidly` updated. It should be done immediately after adding or removing liquidity
![image](https://user-images.githubusercontent.com/26000280/135465213-610f3fc1-6189-4ca5-97da-be8f7d714537.png)

**Comment by kremalicious** [comment]
implemented in #1009 but needs to be tested once add/remove works again which is defined as part of #972, so closing this here
