### ISSUE TITLE
`Switch Network` Button is not functioning properly at times

### ISSUE THREAD

**Issue by krisliew** [oceanprotocol/market#912]
**Describe the bug**
- The `Switch Network` button sometime work properly, and sometime it doesn't. 
![image](https://user-images.githubusercontent.com/39853992/136747545-a8bc4cd3-36da-4b9e-9263-0ce1254a2244.png)

**To Reproduce**
1) prepare a fresh wallet without polygon network added
2) Go to https://market.oceanprotocol.com/asset/did:op:326e6BbFc725b63A7BC3c7C052C48d10d9D3BFCf
3) Click `Switch Network`

**Expected behavior**
- Should add network and switch to the correct network at asset detail page.

**Browser:**
- Firefox Version 92.0.1 (64-bit)

**See Video:** https://www.loom.com/share/ce55b9d93e334312ae3a3f5353c545c1

**Comment by krisliew** [comment]
Tested the same scenario on other site/dapp (https://chainlist.org/), very likely a metamask and firefox issue.

**Comment by kremalicious** [comment]
provided example worked for me on first try with Firefox/MetaMask, please reopen if issue still persists on your end
