### ISSUE TITLE
PoolTransactions table data not updated correctly

### ISSUE THREAD

**Issue by claudiaHash** [oceanprotocol/market#920]
The `PoolTransactions` data is not updated correctly when a network is deselected:

https://user-images.githubusercontent.com/49017601/137155449-800f9a16-65c7-471c-8785-06e78164788a.mp4

**Comment by mihaisc** [comment]
Is this still relevant in v4  @claudiaHash ?

**Comment by claudiaHash** [comment]
We already have an issue opened for pool shares tab https://github.com/oceanprotocol/market/issues/1042 where all rhe functionality will be tested again, so this can be closed i believe.
