### ISSUE TITLE
Publishing a data set requires two transactions but is without guidance for a user

### ISSUE THREAD

**Issue by TimDaub** [oceanprotocol/market#931]
I just published a data set and confirmed the first transaction. This is what I'm seeing:

<img width="893" alt="Screen Shot 2021-10-20 at 14 14 45" src="https://user-images.githubusercontent.com/2758453/138090672-4344b427-0ad5-4ae9-937d-5eebb72e0fb3.png">

After the first transaction is confirmed, I get a notification from my metamask. But suddenly I need to confirm a second transaction too. I'm skeptical and I'm not sure what is going on. Where can I find help? Is this second transaction required? Is someone gonna steal my funds?

I think the UI should give at least an indication that indeed two transactions are required. Ideally, it also guides the user along the way and actively tries to reduce transaction signing anxiety.

**Comment by TimDaub** [comment]
Same is true when trying to publish a FixedExchange rate asset (requires 3 tx):

<img width="666" alt="Screen Shot 2021-10-20 at 14 32 19" src="https://user-images.githubusercontent.com/2758453/138093251-210b7837-c856-4490-8bbc-afc06171f7c4.png">

**Comment by kremalicious** [comment]
Will be solved in `v4` branch, ultimately by #951 which should take over as tracking ticket
