### ISSUE TITLE
supervised learning pipeline for a csv dataset

### ISSUE THREAD

**Issue by aghatpande** [oceanprotocol/market#942]
**Is your feature request related to a problem? Please describe.**
I uploaded a .csv file to the rinkeby testnet called "vital_signs_1", which has ~28000 rows and 5 columns. I want to use compute-to-data on this dataset to create multiple supervised learning models e..g logistic regression, random forest and have the algorithms report the metrics to me. I'm looking for existing compute tools in the marketplace but its hard to locate them?
**Describe the solution you'd like**
One of the variables has five categories and I want to convert it to a two category variable, this is my outcome / dependent variable. I want to use the remaining 4 variables to create the predictive models. I need data clean up steps (e.g. create new variables, remove NAs etc) , split the data into training and testing sets and then run code to create the above mentioned models. 
**Describe alternatives you've considered**
Write my own tools to upload to the Ocean marketplace?
**Additional context**
testing out compute to data for a use case which currently exists.

**Comment by kremalicious** [comment]
not sure what needs to be done to close this issue, it sounds like you are looking for info on how to write algorithms so have you looked here? https://docs.oceanprotocol.com/tutorials/compute-to-data-algorithms/

**Comment by trentmc** [comment]
Yep, agree with @kremalicious.

@aghatpande - what you request is basically already there, as the the ocean.py [Quickstart: Compute-to-Data (C2D) Flow](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md). It a supervised learning flow on a csv-like dataset. 
- It uses the "Gaussian Process Regress" algorithm for learning. 
- It uses arff, which is similar to csv but has someML-specific affordances like specifying input variables. [Here's the file](https://raw.githubusercontent.com/trentmc/branin/main/branin.arff)
- It is all in Python, which is by far the most popular ML environment

**Comment by aghatpande** [comment]
Thanks for looking into this and the links to the resources @kremalicious @trentmc. Have closed the issue since its resolved.
