### ISSUE TITLE
Pricing for dataset cannot be created

### ISSUE THREAD

**Issue by tmanthey** [oceanprotocol/market#945]
**Describe the bug**
A pricing for https://market.oceanprotocol.com/asset/did:op:c865e5E0AAc6B7cE3b75B25317709E9Fa3c14545 cannot be created

**To Reproduce**
1. Go to https://market.oceanprotocol.com/asset/did:op:c865e5E0AAc6B7cE3b75B25317709E9Fa3c14545
2. Click on Create Pricing
3. ERROR: Failed to call create pool

The first transaction to create datatokens ended also with error in the UI while obviously being successful 
https://etherscan.io/tx/0x017a988d807ee6b3f31f0bc1e3e10c3d70e364615dbaedd75855d887779944d8

**Expected behavior**
Create a pricing

**Screenshots**
![image (94)](https://user-images.githubusercontent.com/9221853/142740634-a8492c73-a10a-4eed-8e13-19d96a6aa278.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome
 - 95.0.4638.69

**Additional Informatin**
https://etherscan.io/tx/0xff5cc04f01684504b78271c8919b8f8cb461a2b1512178e4094f45331fcc4d50
https://etherscan.io/tx/0xf68113dc0cf758ed06152e06ec27740801bc8f159da0b408a20d16450f0043d9

**Comment by kremalicious** [comment]
We do not have the bandwidth to investigate this, let alone do changes in v3 market. The v4 market being built in #928 will most likely address this, as the whole publish process is completely changed so closing this for now
