### ISSUE TITLE
Publishing a dataset fails for various reason in the UI while not failing on-chain

### ISSUE THREAD

**Issue by tmanthey** [oceanprotocol/market#946]
**Describe the bug**
Publishing a dataset fails with various errors in the UI while actually being published on-chain and being visible in the Oceanmarket UI.

**To Reproduce**
1. Go to "Publish a dataset"
2. Fill the required information
3. Click on Publish
4. Publish fails in the UI with e.g. "DID cannot be created" error
5. Dataset is published on-chain and is visible in the Oceanmarket UI

**Expected behavior**
A dataset to be published without error

**Screenshots**
![image (95)](https://user-images.githubusercontent.com/9221853/142740803-daf5951c-1d8a-4f99-b82a-f5cd8fd57c6b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Mac
 - MacOS
 - Chrome
 - 95.0.4638.69
 
 **Additional Information**
https://etherscan.io/tx/0xdd1e2b863c8a7d4ee5f9292793714bd55e7be2560c3de35a158857f7e92c2aa5
https://etherscan.io/tx/0x103df2f322d8dfe588c3575844aad2de3b8efb2169993458f5a6d01ec811958c
https://etherscan.io/tx/0x1ef6f112236efcef9bab58fe585b6fff0031cde6e99abbd7c02e3bedf7fd1486
https://etherscan.io/tx/0xb733474242d6204f50fdd3f8e71df538dc2ad88152fa7f68f7626cbdf8f68980
https://etherscan.io/tx/0x360eef2b34b18f4d0ceb0725715a561d16e38500e3ddb1bd378ccac93fbb53c7
https://etherscan.io/tx/0xf68113dc0cf758ed06152e06ec27740801bc8f159da0b408a20d16450f0043d9

**Comment by kremalicious** [comment]
thanks and sorry you ran into this but in terms of priorities it looks like publishing succeeded for you in the end. Nothing will be changed regarding this in current market, but v4 market being built in #928 has completely new publish flow which will address all this, specifically in #951. So closing for now as we do not have any bandwidth to further look into this.
