### ISSUE TITLE
Support 'import' datatokens into Ocean Market

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/market#96]
More generally, anyone should be able to start a marketplace that loads all datasets from the chain.

A q from the community:
[3:56 PM] will we be able to import data tokens onto the Ocean Marketplace, or will it currently only support data tokens created through the GUI

[Thread in slack with answers](https://bigchaindb.slack.com/archives/C012Y7ZFFD4/p1601906252163400)

Matthias: interesting idea, we do not have a UI for it but should technically be possible since lib-js accepts an existing data token. We would need to look into what else is required to get this in market, probably would require a publish flow in UI still
￼￼
Trent: Thanks. I'm thinking this too. It would also need the info that the Provider has. Is that possible to import?
￼￼
Trent: And in general, for V3.0 we're ok, no one will expect 'import' functionality at that point.
￼￼
Alex: we have 3 scenarios:

- Datatoken published without an asset (you can do DT create, mint, createPool).  Question is: should we support that? Because DT has no value attached, just speculative
- Datatoken published with an asset, but aquarius is filtering the dataset (he somehow decided that not the case for our MP). Same questions as above
- Datatoken published with an asset and no filtering . This would work out of the box
￼￼

Trent: Thanks Alex!
￼￼
Trent: Of course there would also need to be simply the Gui support for "import". It's great to know that it might be easy to do post v3.0. But it feels like there will be a hitch or two.
￼￼
Alex: it's easy to build if we want to. we need to detach the pool "options" from the asset and have a separate tab just for pools (edited) 
￼￼
Trent: OK! Let's see when there is actual demand.
￼￼
Alex: yes, agreed, and not for this month
￼￼
Matthias: yeah, “easy”. So the thing is if we want to do a proper UX for the publish part we could spend at least 2 weeks on it. Dissect the publishing into 2-3 big feedback steps (datatoken creation, asset creation, pool creation) and keep track of each step in some unified view. Then users have to be able to restart each failed step and such. This requires a lot of refactoring of react hooks and market. Once we have that, then importing is easy, cause we can plugin whatever is missing into this flow then
￼￼
Alex: easy = doable￼. easy !=  1 day ￼
￼￼
Alex: definitely at least 2-3 weeks for a proper UI, with all the flows (add/remove, swaps, etc)
￼￼
Matthias: And then it is also more clear to users why they have to click 9 damn times in MetaMask although we should get this down somehow too, like all those signatures
￼￼
Alex: yeah, i'm gonna do that

**Comment by mihaisc** [comment]
This is not valid anymore for the flows in v4, maybe at a later date but requires extensive refactoring
