### ISSUE TITLE
Adapt `Aquarius` queries for the new structure

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#968]
Adapt and test the `Aquarius` queries so that the homepage/profile is working properly and we provide the teasers the proper data.

Done : 
- homepage doesn't crash and properly loads latest published list
- profile page loads properly `Published` tab
- search works

**Comment by kremalicious** [comment]
> homepage is has no errors and is loading all the categories

was thinking about that too but from what I see this won't work until we also have #954 solved. But we at least should do some shortcut where as a start for this issue here we only make the latest published list work, as that does not depend on subgraph for the list

**Comment by mihaisc** [comment]
updated

**Comment by kremalicious** [comment]
> search works

so I just tried a bit preview of #986 and while it loads assets on frontpage it then can't find the DID so asset details doesn't even kick in. So without doing scope creep, would be great to at least find individual assets.

**Comment by kremalicious** [comment]
ok, was actually simple but until we reface for new subgraph that's as far as we get for now on asset details, but it renders:

<img width="1397" alt="Screen Shot 2022-01-12 at 18 26 12" src="https://user-images.githubusercontent.com/90316/149199946-252a33e0-3c6f-441f-9902-210b571a4f77.png">
