### ISSUE TITLE
Restore Add/Remove liquidity

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#972]
Not much more to explain.
Also take in consideration https://github.com/oceanprotocol/market/issues/894

Done:
- you can successfully add liquidity and the amount added is reflected in the pool stats without refreshing page
- you can successfully remove liquidity and the amount removed is reflected in the pool stats without refreshing page

**Blocked by #954**

**Comment by kremalicious** [comment]
fyi, I changed the refresh mechanism we had before in #1009 by directly calling the data fetch methods at end of add/remove, so it either works out of the box more reliable now, or I broke it :-) So something to check for when doing this issue
