### ISSUE TITLE
Wallet values

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#974]
Not sure exactly what the problem is, but the wallet doesn't show the correct amount  of  tokens , base token for network (eth, rin, etc)  or ocean tokens

**Comment by kremalicious** [comment]
Reactivated the balance check in `v4` and all working for me against Rinkeby which should be only network working right now:

<img width="431" alt="Screen Shot 2022-01-12 at 12 00 28" src="https://user-images.githubusercontent.com/90316/149136562-28f2ce55-050c-4fbd-a065-5debc94947ba.png">
