### ISSUE TITLE
Publish algorithm

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/market#975]
Didn't test the publish flow for algorithms. This needs to be validated/fixed
This is dependent on this pr ; https://github.com/oceanprotocol/market/pull/967

Done:
- you can properly publish an algorithm and is accurately indexed by `Aquarius`

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Frontend-60acd67b133a660014278212/issues/oceanprotocol/market/975?planning-poker) with ZenHub @bogdanfazakas

**Comment by kremalicious** [comment]
Everything regarding publish testing we should hold off until we stop deploying new contracts. Every time we deploy, the old published assets become useless, and we would have to test all possibilities again. All the changes of the last days are not yet deployed I think https://github.com/oceanprotocol/contracts/commits/v4main_postaudit
