### ISSUE TITLE
Pricing screen tabs

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#990]
As [noted](https://github.com/oceanprotocol/market/issues/862#issuecomment-984393445) misusing the tabs in our pricing screen for a selection state can be confusing:

<img width="537" alt="Screen Shot 2022-01-13 at 12 10 13" src="https://user-images.githubusercontent.com/90316/149327922-fdf920dc-a2b5-44ef-a233-cf0bdddc1ee9.png">

They are exclusive options so semantically they should be `radio` inputs and visually if there would be an element resembling a radio input inside of the tabs, it would make it already way more clear that selecting a tab also selects this as pricing option.

So we need to look into how much we can customize existing tabs of our `Tabs` component, then decide if we might create new custom elements only for this screen.

**Comment by EnzoVezzaro** [comment]
Hi guys,

I wanted to make a brief summary to make sure we're in the same page. 

Based on the description, we need to make more clear the selection of the pricing model on the "Pricing" step of the Publishing wizard. For what I understand is just an UI addition to improve the UX. 

The route that I'd take is the follow: 

- Add prop to "Tabs" component (example: ShowRadio )
- This is an optional param that if passed:
-- Adds a selected Radio input in the correct active tab, while keeping disabled on the rest

This approached makes possible to add the Radio buttons only to the "Pricing" step on the Wizard. 

Looking at the code this could be done as follow: 

- Add prop to "Tabs" component (example: showRadio ): `src/components/Asset/AssetActions/index.tsx`
-- add param `showRadio` to Tabs component
- If the `showRadio` param is passed: `src/components/@shared/atoms/Tabs.tsx`
-- Add optional `showRadio` param to the the component
-- Add Radio Buttons to the `Tab` component inside the `TabList` map loop
-- Add logic to show/hide Radio Buttons

This is preview of the final result if what desired (is not yet styled).

![Screenshot 2022-02-01 at 13.27.34.png](https://images.zenhubusercontent.com/61f7b0225ea40b38a8684622/f56de447-2aa3-4a3c-b362-c18cc901a8d3)
