### ISSUE TITLE
Display NFT metadata somewhere in asset details

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#995]
Output at least the NFT image assuming our current approach in #944, and the NFT address with link to explorer somewhere.

**Comment by moritzkirstein** [comment]
Is this something we can help with implementing? Glad to do so, if it helps. Is there already some preferred way / location on the details page, where this should be shown or would a first proposal be sufficient?

**Comment by mihaisc** [comment]
no ideas, all suggestions are appreciated. If you have something in mind please share here some quick mocks and we can continue the discussion

**Comment by moritzkirstein** [comment]
I quickly put something together displaying the tokenURI on asset details. What do you think?

![grafik](https://user-images.githubusercontent.com/28757404/150414271-8eab8c89-674f-42d0-9522-8822be595e89.png)

Is there already a redesign planned to display (multiple) datatokens related to assets? Another idea could be to use the space where currently the DT name & symbol is displayed. However, the image would need to be rendered rather small to fit there.

**Comment by kremalicious** [comment]
cool, thanks, that is too prominent though and would remove prominence of what we consider most important things for a user to do on this page (download/compute, then providing liquidity).

I think it should be somehow integrated in that first metadata line we have which is supposed to be a collection of the key metadata. Conceptionally, the datatoken belongs to the service/pool, which is already done with another link on the pool tab. So that would be a good place to move the datatoken line to. But this leaves no space for putting them on free/fixed assets which also have datatokens for managing access. That would leave the _Use_ tab where we could find a way to include the datatoken line, which could make it also more clear that datatokens are moved for access.

Once we have moved the datatoken line, it leaves us room for displaying the NFT in a smaller manner compared to above draft. And maybe the name/symbol/description are not needed. And link should then rather go to OpenSea.

And while technically each service for an asset can have its own datatoken, in our v4 launch of market we only allow creating 1 service per asset, and we also only read out the first service if there are multiple services. But this can be kept in mind when moving datatoken line and to me would be a good argument for moving this onto the _Use_ tab, maybe section at very bottom like "access is managed with DT"

**Comment by kremalicious** [comment]
another quick idea as I remember #1010. Maybe extending the publisher line component and display the NFT data along with it, also in. rather minimal way. Cause we might change that line to "Owned by..." as we read out the NFT owner so would totally make sense there.

**Comment by moritzkirstein** [comment]
Do you think the NFT image should be incorporated in the design somehow? Maybe putting it into a tooltip for example?
Or should this be rather minimalistic and only link to OpenSea via text?

Most minimal could be something like
`<a>Data NFT</a> owned by <a>0x</a>, published by <a>0x</a>`

Or as suggested put the information in first metadata line like currently:
`v | DATA SET | Ocean Asset NFT - view on OpenSea`

**Comment by kremalicious** [comment]
tinker, tinker, something like this could make sense, with the image as the grey placeholder. Lots of space to the right cause publisher line & date line can become quite long:

<img width="672" alt="Screen Shot 2022-01-26 at 13 16 39" src="https://user-images.githubusercontent.com/90316/151169722-82885868-d85c-4722-83fe-63b7668000a6.png">

More space for asset access & type also would finally allow to remove that confusing mismatch, and use either text only for all, or icon + text for all.

**Comment by moritzkirstein** [comment]
I started implementing something in `feature/asset-details-nft` branch. For now I worked with the publish preview to validate the design. However, it seems that currently aquarius does not cache the `tokenURI` in nft metadata of DDO:
```json
{
	"nft": {
		"address": "0x9D057712De71F6beA9b094E197b723eb9B453945",
		"name": "Ocean Asset NFT",
		"symbol": "OCEAN-NFT",
		"state": 0,
		"owner": "0x1383C7571FB61127f792B306620c7754CbE30A6b",
		"created": "2022-01-27T13:44:41"
	}
}
```
Do we need something on ocean.js / market layer to fetch this or is this intended to be added to aquarius (or aam I missing something :D)?

**Comment by kremalicious** [comment]
we missed that so far, as when spec was written there was no `tokenURI` yet: https://github.com/oceanprotocol/docs/blob/b1750d01638c8ec249a9157127f7bd57d38b4392/content/concepts/did-ddo.md#nft

So for now it's a web3 call to get the tokenURI from the contract directly

**Comment by mihaisc** [comment]
web3, or get it from subgraph ( [query](https://subgraphv4.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0Anfts%7B%0A%20%20id%0A%20%20tokenUri%0A%0A%7D%0A%7D) )

**Comment by moritzkirstein** [comment]
Thanks for clarifying. I'll add something to get the tokenURI

Here are some screenshots of the current design, would be nice to get some feedback if this is going into the correct direction:
![Screenshot 2022-01-28 at 14 57 32](https://user-images.githubusercontent.com/28757404/151569769-7b360904-5839-4461-a6d8-418cf6cea5e6.png)
---
![Screenshot 2022-01-28 at 14 57 41](https://user-images.githubusercontent.com/28757404/151569779-ab221593-e437-4365-b61d-a8cfc4d7dbc6.png)
