### ISSUE TITLE
Add final DID to NFT metadata

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/market#996]
As defined in #944, we have in the NFT metadata json `external_url`, which should be populated with the full link to the respective asset in the live market. Additionally, the `description` could include the link too.

Both things show up e.g. on opensea within their UI.

Right now we generate the NFT metadata before doing anything else and only in 2nd step we get the DID. So most likely we have to inject the DID at the end of the process when we do `nft.setMetadata`.

**Comment by mihaisc** [comment]
This means another tx though, is it worth it? I get the described use case and it seems cool. We could get away with this with another function in the contract that bundles these 2, setMetadata and setTokenURI.

**Comment by kremalicious** [comment]
definitely not worth it if it requires another transaction. Thought that somehow we can inject it through that final `setMetadata` call but missed that `setMetadata` & `setTokenURI` are separated

**Comment by alexcos20** [comment]
we have a couple of options:
1. have tokenUri as arg to serMetadata -> a lot of code to be changed (aqua,provider,libs,etc)
2. have a helper function setMetadataAndTokenUri ( which calls setMetadata & setTokenUri)

thoughts ?

**Comment by alexcos20** [comment]
will do

**Comment by alexcos20** [comment]
see if https://github.com/oceanprotocol/contracts/pull/456 suits your needs

**Comment by moritzkirstein** [comment]
I saw this is now merged for contract and opened in https://github.com/oceanprotocol/ocean.js/issues/1228
Since we are already working on the NFT publishing flow, we might be able to help implementing this on the market side, once ocean.js is ready.
